### ISSUE TITLE
update application version from the client?

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#10]

**Comment by Thomas101** [comment]
Would be great to have this! Could do with some help getting it working...

**Comment by bertrandmartin01** [comment]
i would love to be able to help, but i've no coding skills whatsoever!

**Comment by Thomas101** [comment]
look at http://sparkle-project.org as suggested in #80

**Comment by brandonb927** [comment]
@Thomas101 have you taken a look at https://www.npmjs.com/package/electron-updater?

**Comment by jacksarick** [comment]
@Thomas101 I'll fork it and try to implement this feature

**Comment by alexweber** [comment]
@Thomas101 I've been looking into this one a bit and it seems like [electron-release-server](https://github.com/ArekSredzki/electron-release-server) might be the best bet.  You could probably host it on a free Heroku instance too.

**Comment by Thomas101** [comment]
A short update on this just to keep all interested parties in the loop! Been looking at using the [auto-updater api](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) that uses squirrel in the back end. This one's preferable as it's cross platform. I can then backbone this off the github releases using [electron-gh-releases](https://github.com/jenslind/electron-gh-releases) which means it should all just work without needing to maintain a server.

One small hurdle is that to use the auto-updating I need to sign the app. Ideally I would like to this anyway for security, however to do this for osx is $99 per annum, then for windows it varies but probably around the $200 per annum fee.

So for the time being I'm going to add this to the future label and pull it off a milestone.

**Comment by alexweber** [comment]
Thanks for the update and too bad about the signing costs... have you considered setting up some form of crowdfunding to sponsor it?  With almost 1000 stars, if each person donated like 25 cents or so it'd be done in a minute :)

**Comment by Thomas101** [comment]
I'm going to close this as I've added an [FAQ about it](https://github.com/Thomas101/wmail/wiki/FAQs)
