### ISSUE TITLE
Nice-to-have: menu item and keyboard shortcut for Settings

### ISSUE THREAD

**Issue by tinymachine** [Thomas101/wmail#100]
This is by no means critical, but it would be nice to be able to pull up the Settings pane using the standard OS X keyboard shortcut, <kbd>⌘</kbd><kbd>,</kbd>. For what it's worth, I think typically on OS X, the equivalent of Wmail's 'Settings' is called Preferences, and it appears as a menu item under the application menu (i.e. the WMail menu in the menu bar), so it might make sense to provide access to Settings/Preferences there, too.

**Comment by paulyoung** [comment]
I've gone looking for this a few times now and was about to file an issue on this.

Keep up the great work :+1:

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!

**Comment by tinymachine** [comment]
Nice - thanks, Thomas! Although the keyboard shortcut is displayed in the menu, I'm not actually able to get the shortcut to work, whether the keyboard focus is in the mailbox pane or the dark grey left-side pane. (This is just a "FWIW" comment; I don't actually need to access Settings that frequently so it's not a problem for me!)

(Also, typically for Mac apps Preferences appears beneath About in the application menu (and usually the "About" menu item includes the application name (e.g. "About Wmail"). Not trying to nitpick -- just thought I'd mention in case you're trying to make this feel as Mac-ish as possible.)

Do keep up the great work!

**Comment by locly** [comment]
They should be easy to fix. I'll open it back up for the next release :)

**Comment by Thomas101** [comment]
They should be easy to fix. I'll open it back up for the next release :)
