### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by chuckhendo** [Thomas101/wmail#101]
What would be needed to get this working on Windows? I've done some preliminary work, and here are the main hold ups I've found:

- The appdirectory.userData() for Windows is `C:\Users\chuck\AppData\Local\wmail\wmail` - node-localstorage attempts to create a folder if it does not exist, however, it doesn't create nested folders. This may be an issue with that package, or it could be fixed directly in wmail by checking for the folder's existence and then using something like https://github.com/substack/node-mkdirp to create it
- An icon in the ico format would need to be created
- packager.js would need to be updated to support building for Windows
- The biggest holdup is that electron-packager has additional requirements to build for Windows on platforms other than Windows (https://github.com/maxogden/electron-packager#user-content-building-windows-apps-from-non-windows-platforms).

After making the changes in steps 1-3, everything seems to be working on my Windows system. Would you be interested in accepting a PR for this? How does your current packaging system work?

**Comment by Thomas101** [comment]
I think those are the main issues that I'd put together in my head, but not looked too much into.  I was thibking most things would be around file paths as I use pretty much standard electron APIs which are cross platform.

As regards pull requests I would love to accept one! I'm just one guy so the more help the better!

To package the app I run packager.js. all this does is runs webpack, packages the app using electron packager then copies the license files into the output directory. There's some shortcuts for running the build scripts in package.json/scripts if that helps!

Thank you!!!

**Comment by Thomas101** [comment]
If you want to submit the pull request with packager.js able to build it I'll happily put it through with the next release :-). I'm hoping to get a prerelease ready next week with the notifications fixed

**Comment by highergroundstudio** [comment]
@chuckhendo Let me know if you need any more help as I was thinking about adding windows support as well.

**Comment by chuckhendo** [comment]
@highergroundstudio Thanks! It shouldn't be too hard; I've got most of it working locally. 

@Thomas101 - I think the only code outside of packager.js/package.json that needs to be changed is the line I was mentioning about creating the config folder if it doesn't exist. Would you be ok with this change, or should I make a PR on node-localstorage?

**Comment by Thomas101** [comment]
I think it's pretty safe to just make the directories if they don't exist :)

**Comment by LouWii** [comment]
@chuckhendo thanks for working on this ! I really miss a google email client on Windows !

**Comment by derfmilo** [comment]
I added it for windows as well pretty simple fix.

**Comment by MarshallOfSound** [comment]
I just put up a Work In Progress PR for windows support, just need to test a few more things and add some more packaging logic :smile:

**Comment by derfmilo** [comment]
const fs = require("fs")fs.mkdir("C:\\Users\\USER\\AppData\\Local\\wmail",function(err){   if (err) {       return console.error(err);   }   console.log("Directory created successfully!");});fs.mkdir("C:\\Users\\USER\\AppData\\Local\\wmail\\wmail",function(err){   if (err) {       return console.error(err);   }   console.log("Directory created successfully!");}); 

    On Thursday, May 5, 2016 12:57 PM, Samuel Attard <notifications@github.com> wrote:
 
 

 I just put up a Work In Progress PR for windows support, just need to test a few more things and add some more packaging logic  —

**Comment by Thomas101** [comment]
Thank you everyone who's been testing, committing code an playing with this! Download 1.3.0 for windows now :)
