### ISSUE TITLE
Spellcheck 

### ISSUE THREAD

**Issue by mykecheckonetwo** [Thomas101/wmail#102]
Love the app but spellcheck (via right click) takes a very long time (more than 30 seconds) and it auto corrects at the location of the cursor not the word. So if in that 30 I move the cursor up or down in the text field it auto corrects there. Once it even autocorrected the "Send" button as that's where the cursor was.

**Comment by ZakStrassberg** [comment]
This happens to me as well.

**Comment by Grathio** [comment]
I have this issue as well on OS X 10.11.3:
Problem: Right-clicking on a misspelled word can take a very long time to show the spelling correction popup. During this time the app is non-responive. WMail shows 100% usage of one CPU, and from roughly 300 MB of memory to 1 GB, though it does fluctuate.

Steps to reproduce: Right-click on a misspelled word longer than a few characters.

The delay is related to the length of the misspelled word, and is non-linear:
3 letters (hte) < 1 second.
7 letters (brosper) 2 seconds.
10 letters (brosperous) 7 seconds.
14 letters (brosperousness) 17 seconds.
18 letters (antibrosperousness) 35 seconds
All times on a 2014 Mackbook Pro

The actual word misspelled doesn't seem to make any difference in the length of the delay.

**Comment by Thomas101** [comment]
Thanks for the detailed analysis on this one. I've profiled some of the code and found that there are two separate issues.

The first one is spellchecking library used, which is `typo-js` takes a long time processing long incorrectly spelt words as you've profiled above. That's where the cpu cycles are going.

Then secondly there appears to be an issue with the context menu in electron which adds around 1.5 seconds of wait time until it appears https://github.com/atom/electron/issues/1854.

The first step is to patch or find a replacement spellchecking lib `typo-js`. Then secondly need to look towards getting the popover menu coming up a bit quicker.

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
