### ISSUE TITLE
Option to disable ding

### ISSUE THREAD

**Issue by bwiggs** [Thomas101/wmail#103]
Can we add a preference toggle for the ding that happens when an email arrives?

**Comment by lid** [comment]
WMail uses Mac OS X system notifications, so you can control sound for the notification in System Preferences->Notifications->WMail->Play Sound For Notifications.

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!

**Comment by bwiggs** [comment]
Thank you!

**Comment by mschwartz** [comment]
Is there a way to change the sound?  On my laptop it plays the same sound as when an app is installed.  I'd like to have it play a different sound.
