### ISSUE TITLE
Request: find/text search

### ISSUE THREAD

**Issue by lid** [Thomas101/wmail#104]
Sometimes I get a really long email and am looking for a specific word or phrase within. For these cases, it would be nice to have a simple text find function.

**Comment by gdsmith** [comment]
+1 this is the number one missing feature for me

**Comment by Thomas101** [comment]
Added in acc33c6c4ead09e76e76b49d3fc9c7069c9b4495

**Comment by gdsmith** [comment]
@Thomas101 Worth a release all on it's own for me 😉 

</impatience>

**Comment by Thomas101** [comment]
Sorry! I managed to break the spell checking in this release -- which I've now fixed, but as a side effect I need to set-up three build boxes, linux, windows and osx. I've been struggling to find the time to get around to this :-(

**Comment by Thomas101** [comment]
I've been testing though and it does work ;-)

![screen shot 2016-06-28 at 09 55 05](https://cloud.githubusercontent.com/assets/103586/16409626/7263c132-3d16-11e6-947e-38c7a465eb01.png)

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!

**Comment by gdsmith** [comment]
@Thomas101 Seems like this or some of the other changes are causing issues with keyboard shortcuts when I have multiple accounts. It doesn't correctly focus the shortcuts to the account you are looking at. So keyboard shortcuts activate in the wrong pane. e.g using / to search I end up searching in the previous account.

**Comment by gdsmith** [comment]
Yes, that's the same issue.
