### ISSUE TITLE
Chrome Extensions

### ISSUE THREAD

**Issue by Thomas101** [Thomas101/wmail#105]
Investigate the feasibility of using chrome extensions. See https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md

Requested extensions include:
* Sidekick by Hubspot
* Gmail offline
* http://markdown-here.com/
* Choosy

**Comment by itamaro** [comment]
+1

+Evernote

**Comment by rkpatel33** [comment]
+1 

+ Streak CRM

**Comment by geekgonecrazy** [comment]
I think you for sure should keep the list of extensions to general functionality vs integration with different services. 

Something like [mailvelope](https://chrome.google.com/webstore/detail/mailvelope/kajibbejlbohfaggdiogboambcijhkke?hl=en) would be amazing.  Would allow pgp encryption.

**Comment by J-Louis** [comment]
+1

- Stylish

**Comment by Thomas101** [comment]
I've been taking a look at this and although there is some support for extensions in electron, there isn't any support for any of the chrome apis which the majority of chrome extensions will use. 

Adding this kind of support would be massive undertaking and not something I think I can feasibly add on my own. However I do think it would be quite easy to add support for specific extensions with the support of their creators. I've added some [FAQs](https://github.com/Thomas101/wmail/wiki/FAQs) with some more information about this and closing this for now.

Thanks everyone!

**Comment by samaphp** [comment]
+1
Streak CRM

**Comment by svetbg** [comment]
+1

**Comment by ankitpati** [comment]
Can [this](https://github.com/koush/electron-chrome "Electron Chrome") help? It is actively maintained, and adds the missing Chrome APIs that are needed for extensions support.
