### ISSUE TITLE
Google Services Integration. Contacts, Calendar, Keep etc

### ISSUE THREAD

**Issue by Thomas101** [Thomas101/wmail#106]
Look at adding other google services to be more like an outlook app
- Calendar 
- Contacts
- Keep

**Comment by itamaro** [comment]
This would be nice indeed, but if anyone is waiting for these integrations, here are viable suggestions in the meantime:

1. For Google Keep - there's a [Chrome App](https://chrome.google.com/webstore/detail/google-keep-notes-and-lis/hmjkmjkepdijhoojdojkdfohbdgmmhki?hl=en) which works great (for me at least) as a desktop app.
2. For Calendar, I use [FluidApp](http://fluidapp.com) to make my Google Calendar for my "main Google account" "look like" a standalone desktop app, and it contains all my secondary-account calendars as well, so I have one view into all of them.

Don't have a suggestion for contacts, as I don't really use it outside of context (in the phone dialer or contacts app, or email compose box).

My small request from Wmail, though, is to be careful from trying to support too many things, and end up not doing the thing it set out to do well enough :-)

**Comment by mykecheckonetwo** [comment]
Would 3rd party productivity be in the mix? Like Trello wunderlist ToDoist etc?


Pardon My Brevity -- Sent From an iPhone,

Mykel Jewell
Mykel.Jewell@Gmail.com

**Comment by xwaver** [comment]
Also Drive support.

**Comment by chadberg** [comment]
Adding my pebble to the pile for Calendar and Contacts, putting them all in one place like Outlook or Thunderbird.

**Comment by coussej** [comment]
Calendar and Contacts would be awesome. As a google-apps users this would allow me to all the 'outlook' stuff in a separate app and not in browser tabs (which you can close by accident and then have to restart and wait for the page to load again)

**Comment by cdysthe** [comment]
I'm all in. WMail has become one of my most used applications so I would like nitty having to leave it for tasks that are very close to email. Especially contacts would be good to have "inhouse".

**Comment by luzpaz** [comment]
:+1: for drive support
On OSX using Mailplane.app you can press ctrl+click(+google-drive-icon) and drive would open as a browser tab within mailplane. Would it be possible to do the same in wmail ?

**Comment by nzoschke** [comment]
Can you offer any guidance on how to add Calendar support?

I'm tinkering around with javascript in the dev console, but not getting anywhere.

**Comment by Thomas101** [comment]
@nzoschke probably the first step is to get WMail building from source on your machine. You're going to be pretty limited as to what you can do from the dev console. There's some instructions on how to do this in the [Readme](https://github.com/Thomas101/wmail/blob/master/README.md).

From there it's either a case of opening a  new [Browser Window](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) or modifying the current UI to add a new [webview](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md) as a tab. If you're interested in taking a look at this I'd be happy to point you help further...

**Comment by abass** [comment]
I think it's an absolute no-brainer to integrate Google Calendar into WMail. Contacts is already accessible by going to email, pressing the dropdown arrow in the top-left, and clicking "contacts".

If this at the very least just had Calendar integration, it would be the one-stop solution for all of my clients. Right now what I do is I pin Gmail + Calendar + Drive to their taskbar to open up as mini standalone apps via the Chrome "Add to Desktop" function. If I could just install this and it would have Gmail + Calendar, it would be SO perfect.

Between that and making gmail chrome extensions accessible in the app, you got yourself a winner!

**Comment by rboccuzzi** [comment]
I also would love this feature, it would make this killer.  Specically, having a single "app" that did mail and calendar would be a big jump in my mind.  Adding drive, keep, and contacts are nice but diminishing returns(in that order) for me.  

One thought, when you start thinking about the UI...it would be nice to be able to switch from email in one google account directly to calendar in the other...rather than have to select the account first, then the view.  Maybe if you have an expanded left pane it gives you the option to have those hanging under the account, but if the left pane isn't expanded, they are tabs across the top (Which would require multiple clicks, one for the account on the left, and one for the view on the top).  Just my $ .02

**Comment by abass** [comment]
Agreed with @rboccuzzi on all points!

**Comment by Thomas101** [comment]
Thanks for commenting everyone. I've added support for Calendar, Contacts, Drive and Keep in the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8). Enjoy!

**Comment by abass** [comment]
Super happy about this! You rock!

Is there any way to do a different icon layout though? It just feels too compressed and busy in it's current form. It went from being a super clean layout to one that's very busy.

I'm assuming I, like many others, are just going to have 2/3 accounts in here total. That leaves so much room on the side. Hitting these new touch-targets are a huge pain as well. This is how it will look for most people:

![IMG](https://d17oy1vhnax1f7.cloudfront.net/items/0U3S3a1Y2u2d0V1I2u0y/Image%202017-01-04%20at%203.42.19%20PM.png?v=136d94c0)

I would much prefer for the calendar, drive, and keep icons to be larger and vertical versus horizontal with more spacing.

**Comment by 0x3333** [comment]
What about:

![screen shot 2017-01-04 at 18 52 52](https://cloud.githubusercontent.com/assets/289289/21658818/34a85dec-d2af-11e6-8c64-6b9288ee8efe.png)

I changed to `flexbox` to `column` and increased icon size to `32px`.

**Comment by 0x3333** [comment]
Just to mention, I have 8 accounts...

This is how it looks with my mod.

![screen shot 2017-01-04 at 18 58 12](https://cloud.githubusercontent.com/assets/289289/21659017/fe638904-d2af-11e6-8905-89eb9208b4ab.png)

**Comment by abass** [comment]
Much, much, much, better! You can still tell they are related to their parent while much better utilizing the space. Where specifically did you make that mod? I would love to do the same - at least until it gets updated.

Also, just as you have a "sleep" setting for each account (calendar/drive/keep), it would be nice to have a "hide" setting as well. e.g. some of my clients never use Google Keep. It would be nice to hide it for some accounts.

Cheers!

**Comment by austinbutler** [comment]
I really like how Shift did it: https://cdn3.tryshift.com/static/images/hero-animation.gif

They forked Wmail and are charging for the feature anyways.

**Comment by rboccuzzi** [comment]
I specifically do not like how shift did it...see my comment above; it
requires two clicks frequently rather than just the one. There is a lot of
space wasted on the left, so I think this is great, especially the vertical
way Tercio did it, even better.

**Comment by abass** [comment]
@austinbutler it's absolutely beautiful from a UI perspective. I like all of their modifications!

From a UX perspective though, @rboccuzzi does have a point.

I do REALLY like that fork though. Even just for organizational sake - You enter the account you want to go to and from there you have email/calendar/drive. One odd bit about it's current form too is that now "selecting the picture" brings you to your mail? While icons bring you to your calendar, drive, and Keep? From a UX perspective that's a tad bit confusing as well. There's no visual queue that clicking your icon is to get to mail.

Hey @austinbutler where can I find that fork?

**Comment by 0x3333** [comment]
@abass  to hide a service you can do it in the settings... there is a remove option:

![screen shot 2017-01-04 at 19 06 22](https://cloud.githubusercontent.com/assets/289289/21659234/f0a39e52-d2b0-11e6-8bfd-f86d4d2072ba.png)

[Change here to `column`](https://github.com/Thomas101/wmail/blob/master/src/scenes/mailboxes/src/ui/Sidelist/SidelistStyles.js#L91)

[Change here to `32px`](https://github.com/Thomas101/wmail/blob/master/src/scenes/mailboxes/src/ui/Sidelist/SidelistStyles.js#L102)

[Change here to `32px`](https://github.com/Thomas101/wmail/blob/master/src/scenes/mailboxes/src/ui/Sidelist/SidelistStyles.js#L108)

I did those changes in the inspector, so I'm not 100% sure it's right.

**Comment by abass** [comment]
Thanks @0x3333 ! Didn't even notice the trash icon or "Add Service" button for some reason. Thanks so much!

@austinbutler interesting that they forked and are charging for it. I'd be curious to see what they are changing aside from just basic modifications. I can't find it anywhere though, they have a website or something?

**Comment by Thomas101** [comment]
Hi,

Thanks for the feedback! I agree it does look a bit cramped. I was thinking more for users with lots of accounts like @0x3333 but it does look like it works with that too. I really struggled with what to best here, but I do like suggestion of adding them vertically below the mailbox.

How about circling them up and using the account colour as well to keep a clear definition between accounts (excuse my mad paint skills....)

![screen shot 2017-01-05 at 08 47 02](https://cloud.githubusercontent.com/assets/103586/21674167/71a2abec-d324-11e6-8d6b-e3e2cb3a55d9.png)

Does anyone think that keeping the current layout under a `compressed` option is something useful? Maybe for accounts that are less frequently used?

**Comment by 0x3333** [comment]
I did something like this:

![screen shot 2017-01-05 at 10 51 21](https://cloud.githubusercontent.com/assets/289289/21681127/f0ada526-d334-11e6-99c9-75ac61eee713.png)

Added the following to [SidelistStyles.js](https://github.com/Thomas101/wmail/blob/master/src/scenes/mailboxes/src/ui/Sidelist/SidelistStyles.js#L100):

```css
background-color: white;
border-radius: 16px;
border: 3px solid rgb(66, 133, 244);
```

Regarding the `compressed` option, I believe it is a good addition, but not a must. In my case, a simple scroll if I'm using a small computer is not a big deal, but would be nice to have this option.

**Comment by rboccuzzi** [comment]
Love that vertical layout  @0x3333 . Agree that the option might be nice
but probably not worth it... Options add complexity and cognitive load..
I'd probably skip... Besides, you can also adjust vertical by trimming
services on less used accounts.

Anyone else notice the calendar does a full refresh way more than email
view? It also seems to reset the view (week to month) frequently.  Seems
there might be a caching problem?

**Comment by Thomas101** [comment]
@rboccuzzi the services go to sleep after a few minutes of inactivity to reduce memory consumption. If you want to a service to stay awake all the time though uncheck the `Sleepable` checkbox under your account settings

**Comment by Thomas101** [comment]
Thanks everyone for the feedback. The [2.0.9 prerelease](https://thomas101.github.io/wmail/download?v=2.0.9) now stacks the services vertically by default. If you did prefer the other way you can enable the `compact` UI on a per-account setting

**Comment by mykecheckonetwo** [comment]
Thanks! For a newb how do I do that?

**Comment by austinbutler** [comment]
Looks like Settings -> Accounts -> Compact Services UI
