### ISSUE TITLE
Menu Bar Icon Vanishes in Dark Mode

### ISSUE THREAD

**Issue by phutnick** [Thomas101/wmail#107]
On MacOS 10.11.3 with the setting _System Preferences->General->Use dark menu bar and Dock_ setting checked the WMail icon appears red when there is unread mail. When there is no unread mail, the icon seems to be black on black and is totally invisible.

Clicking on it highlights it in blue and it becomes visible (along with the message "no unread mail".)

I think that WMail should detect the dark setting and use a white when there is no unread mail. Alternatively, a manual setting would help.

**Comment by Thomas101** [comment]
Hi @phutnick have you tried the 1.2.2 prerelease? It should be white when using the dark theme

**Comment by pibby** [comment]
Can confirm it is white in dark mode in 1.2.2 prerelease 👍
