### ISSUE TITLE
Keep app running after closing the window

### ISSUE THREAD

**Issue by russiancow** [Thomas101/wmail#109]
This might only be relevant for Linux (haven't tested on OS X), but it would be great to keep the app running in the background if you close the window and have the tray icon visible. I don't like to leave superfluous windows open, and I'd really only interact with the app in response to notifications. This is how most apps that have tray icons work, in my experience.

**Comment by Thomas101** [comment]
I think this might be linux only... there are some osx checks in the code to minimize to the dock. Maybe I can roll this up with the tray icon enhancements #75 to allow you to toggle back to the main window etc

**Comment by russiancow** [comment]
I actually successfully got this working on Linux last night. I'll test on OS X later today and do a pull request if everything works.

**Comment by russiancow** [comment]
@Thomas101: So I got this working, but the app stays open even if you have the system tray off, which doesn't make sense because then there's no way to get back into the app. I see you're using Flux to keep track of the settings, but I need to access that setting outside of the React/Flux context (specifically, in WindowManager.js). Any ideas?

**Comment by Thomas101** [comment]
If you need to access the settings these are auto copied across to the main thread on every save. You can grab hold of these in `appSettings.js`

**Comment by russiancow** [comment]
Oh yeah, I don't know how I missed that. I'll check that out later today. Thanks!

**Comment by albahnsen** [comment]
It would be great if there is an option to start minimized in the tray, such that I can start the program on login without showing the first screen.

**Comment by Thomas101** [comment]
Hi @russiancow I've just merged this in. Can you check that master is working as expected?

**Comment by russiancow** [comment]
@Thomas101: Works like a charm! Thanks!
