### ISSUE TITLE
Multiple accounts hotkey

### ISSUE THREAD

**Issue by brandonb927** [Thomas101/wmail#11]
It'd be great if there was a way to have hotkeys for multiple accounts with CMD+1. CMD+2 :) 

I just started using this app and found that it lacked them. I might take a stab at implementing it if nobody is interested and submit a PR.

**Comment by avelis** [comment]
@brandonb927 I also second this feature.

It feels like a natural progression coming from using Slack so much.

**Comment by Thomas101** [comment]
:+1: for slack. I've added it in ;-)

**Comment by brandonb927** [comment]
Thanks @Thomas101! Let me know if there's anything I can help with.

**Comment by avelis** [comment]
@Thomas101That is awesome! I appreciate you doing that and in such a timely manner.
