### ISSUE TITLE
Add ability to change zoom level

### ISSUE THREAD

**Issue by bmurphy1976** [Thomas101/wmail#111]
I'm getting old and my eyesight isn't as good as it used to be.  My eyes get tired staring at a small font all day long.  I usually run my browser at 125% zoom.  Sometimes at 150% and sometimes at 110% but rarely at 100%.

Can you allow zoom?  Even better, allow CTRL/OPTION+ and CTRL/OPTION- to change zoom level on the fly.

**Comment by Thomas101** [comment]
Hey, you can zoom the mailboxes already by going to view>Zoom mailbox in or using shift+cmd+plus

**Comment by bmurphy1976** [comment]
Huh.  How about that, don't know how I missed it.  Sorry to bug you. :)
