### ISSUE TITLE
Priority Inbox support

### ISSUE THREAD

**Issue by swrobel** [Thomas101/wmail#112]
It would be great to have unread count only show "Important & Unread" and to only get notifications for Priority emails.

**Comment by Thomas101** [comment]
Hi, I'm guessing this is with gmail. Are you using the Priority or Important first mailbox setting in gmail? I should be able to add an option in to link into this

**Comment by swrobel** [comment]
You're correct, I'm using gmail. I guess this is perhaps a little more complicated than I thought because of all of the config options for priority inbox - here's a screenshot of my config if it helps:

<img width="637" alt="screenshot 2016-02-23 09 01 15" src="https://cloud.githubusercontent.com/assets/157270/13259402/0afeb7b2-da0c-11e5-9d7b-aafe73af7b0e.png">

**Comment by Thomas101** [comment]
Thanks for the screenshot. I'll see what I can do in version 1.2.2!

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
