### ISSUE TITLE
Request: Option to disable the top menu bar

### ISSUE THREAD

**Issue by jamesbvaughan** [Thomas101/wmail#115]
I really like wmail so far, but I'd love an option to hide the menu bar at the top. I use a tiling wm and menu bars like that generally uglify applications. Also, an option to disable the scrollbar would be great. Thanks!
![2016-02-23-155000_1366x768_scrot](https://cloud.githubusercontent.com/assets/2906913/13270892/ed1be744-da45-11e5-9b9e-4dde19d9c371.png)

**Comment by Thomas101** [comment]
What's the default behaviour on linux? How would you normally hide and show the menu bar?

**Comment by jamesbvaughan** [comment]
I like the way that Atom handles it. In it there's an option in the settings and under the "view" menu. Here's a screenshot:
![2016-02-24-102800_1366x768_scrot](https://cloud.githubusercontent.com/assets/2906913/13296319/f6d05da0-dae1-11e5-8a60-c89d8d3449cd.png)
![2016-02-24-102746_1366x768_scrot](https://cloud.githubusercontent.com/assets/2906913/13296318/f6cab83c-dae1-11e5-9846-b549e00aa374.png)

I've actually been hoping to get started contributing to open source projects like this and I'd love to try to add this feature if you're down to give me some pointers if I need help.

**Comment by Thomas101** [comment]
Hi @jamesbvaughan I've just merged this in and added the option in settings etc, can you confirm it works as expected for you?

**Comment by jamesbvaughan** [comment]
Right now when I try to toggle it, I'm getting an error:
`[TypeError] Cannot read property 'appSettings' of undefined`

It seems that `this` is undefined inside the `updateWindowMenubar` function, and I can't figure out why.

**Comment by Thomas101** [comment]
Hi @jamesbvaughan looks like I was dropping the context. Does that work better now?

**Comment by jamesbvaughan** [comment]
Yep, it works perfectly now. Thanks!
