### ISSUE TITLE
Feature request: Context menu

### ISSUE THREAD

**Issue by JSAcreative** [Thomas101/wmail#116]
I find the lack of a context menu disconcerting. Not in the least, the lack of a copy/cut/paste option.

**Comment by Thomas101** [comment]
Hi @JSAcreative this should be in version 1.2.0 and 1.2.1. Which version are you using at the moment?

**Comment by JSAcreative** [comment]
1.2.1 Linux

**Comment by Thomas101** [comment]
Looks like an issue on linux. I'll take a look into it!
