### ISSUE TITLE
Top bar, not behaving as native apps

### ISSUE THREAD

**Issue by Zakay** [Thomas101/wmail#117]
![screen shot 2016-02-24 at 08 18 12](https://cloud.githubusercontent.com/assets/315159/13278235/49d4aa50-dacf-11e5-91b8-41a873b24baf.png)

The biggest pain of using this app, is that it doesn't behave as a native app.
trying to click and move the window reveals this huge usability issue. The whole top part of the app should be click-movable.

Another web-app-wrapper had this issue and they solved the issue pretty quickly.
https://github.com/stonesam92/ChitChat

**Comment by Thomas101** [comment]
Hi, it should be that the top 40 pixels of the screen or so are moveable. It should really work across the whole blue bar to be honest but that's on the todo list. If you want the default grey bar to return you can re-enable this in the settings

**Comment by Zakay** [comment]
I love the default look without default grey bar, but even when enabling the grey bar, the blue bar invites me to to click on it too much. If the whole blue bar is on the todo list, then the matter will be solved soon. I'll just wait for the fix, until then I'm unfortunately still on Mail.app, which I hope I could leave very soon.

**Comment by Thomas101** [comment]
At the moment I can't propagate the drag events up from the mailbox window. I could try to overlay dom elements over specific parts of the top window but this could prove to be flakey.

**Comment by TimNZ** [comment]
I think you can close this as the window is draggable across the entire width

**Comment by Thomas101** [comment]
I agree @TimNZ and you can enable the titlebar in the settings screen if you want to
