### ISSUE TITLE
Read tray icon looks bad (Unread is fine)

### ISSUE THREAD

**Issue by hernangonzalez** [Thomas101/wmail#118]
Hey Guys,

Seems like this image ended with low quality on *1.2.1*
<img width="30" alt="screen shot 2016-02-24 at 10 01 20 am" src="https://cloud.githubusercontent.com/assets/1162963/13286148/fecc3eba-dadd-11e5-8b85-ccb5258844a9.png">

Cheers,
H.

**Comment by Thomas101** [comment]
Was 1.2.0 okay? It could be the templating that I'm using to get it work on dark menu bars

**Comment by hernangonzalez** [comment]
@Thomas101 yep, 1.20 was good (as is now the Unread)

**Comment by Thomas101** [comment]
I've re-tuned the icn and it should be high quality again :)
