### ISSUE TITLE
Where are the local files stored on OSX?

### ISSUE THREAD

**Issue by tiagofassoni** [Thomas101/wmail#119]
Let me explain why: 

I tried to use google talk from inside Wmail and apparently it goes all nuts when I do that. 

The gmail chat window is no longer accessible and notifications trigger every second. I think it is stuck in a loop stuck in a loop stuck in a loop.

**Comment by tiagofassoni** [comment]
Oh, by the way: thank you so much for the work. Great project, really liked it!

**Comment by Thomas101** [comment]
You should be able to delete everything from `~/Library/Application\ Support/wmail/`. How did you get it to go wrong. Would be great to patch it so it doesn't happen again!

**Comment by tiagofassoni** [comment]
I completely agree with you, it would be great to patch it. But then comes
the question: should we block google talk plugin so it doesn't happen or
allow it? Or is it something else, perhaps?

2016-02-24 12:23 GMT-03:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment]
I suspect I might have to disable it as I think it uses a plugin. I'll take a look though - it might be something simple

**Comment by jimeh** [comment]
I had a similar glitch on one of my machines when I added the first account. I had to wipe out all settings as it kept doing it on every launch.

However it wasn't related to Hangouts for me, cause I had no conversations going. Also I'd prefer to keep Hangouts available, as it's the primary way I use Hangouts on desktop.

Sadly I don't have the config files still that caused it to go haywire :(

**Comment by Thomas101** [comment]
@tiagofassoni does this still happen? I've had a go myself and  it seems to work
