### ISSUE TITLE
Drag and drop does not work

### ISSUE THREAD

**Issue by DerSiedler** [Thomas101/wmail#12]
Adding an attachment via drag and drop is not working. OSX 10.11 dual screen

**Comment by halloalexkern** [comment]
That's also what i'm missing most ... 
:-) AK

**Comment by 1Marc** [comment]
Me too. Would be great to have!

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip). Thanks very much for your help!

**Comment by hanhpho** [comment]
@Thomas101 thank you for the awesome work man :) :+1:

**Comment by 1Marc** [comment]
@Thomas101 win! I'm using Wmail every day now as my main mail experience. Works fantastic.
