### ISSUE TITLE
Use different highlight color for each account on left bar

### ISSUE THREAD

**Issue by karlgrz** [Thomas101/wmail#120]
Greetings! I have been really enjoying using wmail on linux, it's a great app, thanks for building it!

I have 3 Inbox accounts, and they all use the same gravatar, so I have to remember which one is which. It'd be nice if each account had some different hightlighting or something to better distinguish them. I see the hover tooltip with the email (which helps) but it'd be nice to not have to rely on that.

Thanks for the great product!

**Comment by Thomas101** [comment]
Totally agree! In 1.2.1 pre-release you can now upload different avatars separate to your google account if that helps.

**Comment by karlgrz** [comment]
That would help, thanks!

**Comment by Thomas101** [comment]
I'll re-open the issue as it something I'd like to add in! Ideally it would be great to change the border and highlighting colours :-)

**Comment by karlgrz** [comment]
Ahh, oops, I misinterpreted your comment and closed it, heh. Sounds good!

**Comment by Thomas101** [comment]
Hey, this is fixed. You can check it out by [downloading the latest release](https://thomas101.github.io/wmail/download). Thanks! 😊 😊 😊

**Comment by karlgrz** [comment]
:+1: 

Subtle difference, but man is this helpful. Thanks!
