### ISSUE TITLE
OS X: Attempting to use context menu causes app to become unresponsive

### ISSUE THREAD

**Issue by joshrickert** [Thomas101/wmail#121]
When I make a typo, the spell-checker highlights a word in red. When I go to right click on it, the application freezes for a while (10-15 seconds). Eventually the context menu appears (even if I've tabbed out to another window) but it's missing any sort of spell-check options I normally get in Chrome.

**Comment by Thomas101** [comment]
Hi have you tried the 1.2.1 pre-release (http://thomas101.github.io/wmail/download), it turned out it was an issue with the spell checking library. I swapped it out for a different one and it works as you'd expect now!
