### ISSUE TITLE
Unread badge stays active for inbox

### ISSUE THREAD

**Issue by domoritz** [Thomas101/wmail#123]
The unread count stays at 2 although I've read all emails. After a few hours sometimes it seems to correct itself but not very reliably. I'm using version 1.2.1 with 3 accounts. I only see the problem on my personal gmail with inbox.

**Comment by Thomas101** [comment]
Hi I've just taken a look at the request logs on google and there was a batch of errors yesterday. Can you give it another go now? The unread count normally updates a couple of seconds after clicking in the window. If you're still seeing the issue can you go to view > Developer Tools, then click on the console tab to see if there are any errors or warnings there?

**Comment by domoritz** [comment]
Seems to be working now. I'll keep monitoring and report if it happens again. Thank you @Thomas101.

**Comment by domoritz** [comment]
Ha, the issue was actually #90. The unread count shows the number of unread email even if it's hidden by inbox. So it's actually a real bug and wasn't just a glitch.
