### ISSUE TITLE
Multiple inbox support has narrow right pane width

### ISSUE THREAD

**Issue by ffumarola** [Thomas101/wmail#124]
Hey!

I use multiple inboxes and Wmail currently has the width of the right pane squeezed pretty tight. Is there any way to make it responsive like the browser does? Screenshots attached.

Chrome:
![screen shot 2016-02-24 at 4 16 28 pm](https://cloud.githubusercontent.com/assets/671632/13306478/eadbaa72-db18-11e5-8d81-b42ed6e36440.png)
 
Wmail:
<img width="1676" alt="screen shot 2016-02-24 at 4 16 52 pm" src="https://cloud.githubusercontent.com/assets/671632/13306483/f58a3394-db18-11e5-84db-4db28e48a3c1.png">

**Comment by Thomas101** [comment]
This is an interesting one. Could you try downloading version 1.2.1 pre-release (http://thomas101.github.io/wmail/download) then going to view > toggle sidebar to see if that makes your inbox layout correctly?

**Comment by ffumarola** [comment]
Hey Thomas, I'm using the 1.2.1 version. I just toggled the sidebar and
that did not correct the layout... it's still incredibly narrow.
