### ISSUE TITLE
Keyboard shortcut for switching between accounts

### ISSUE THREAD

**Issue by tnguyen14** [Thomas101/wmail#125]
I just downloaded this app today to try on my GMail accounts. Looks great!

I'm happy to see my regular GMail shortcuts are enabled to navigate around the mailbox. However, it seems like there isn't a way to switch between accounts? It would be great to have the tab switch shortcut on OS X (Cmd + Shift + [ or ]) to work here.

**Comment by bertrandmartin01** [comment]
you can do cmd+1, cmd+2, ... to switch between accounts

**Comment by tnguyen14** [comment]
Unfortunately, I have those shortcuts reserved for other key functions on my computer, so they won't work here.
However, from a user experience perspective, I think it's "easier" to go to the next or previous box, without thinking about which number that would be.

**Comment by Thomas101** [comment]
We can support both sets of shortcuts

**Comment by russiancow** [comment]
Common shortcut keys for this kind of thing are `Cmd + Shift + ]` and `Cmd + Shift + [` on OS X, and `Ctrl + PgDn` and `Ctrl + PgUp` everywhere else.

**Comment by alexweber** [comment]
Maybe just let users configure it to whatever they want?

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!

**Comment by tnguyen14** [comment]
@Thomas101 I just downloaded it to try, but it doesn't seem to be working for me. Is there any special switch I need to enable?

**Comment by Thomas101** [comment]
It should work. I had to use `cmd + >` or `cmd + <` as `cmd + [/]` is already used for navigate back and navigate forwards. Which os are you using?

**Comment by tnguyen14** [comment]
Oh, I see that you can go to account with `cmd + 1`, `cmd + 2`. `cmd + >` and `cmd + <` works as well. I't just that I've never used that combo to switch windows. The convention is always `cmd + {` and `cmd + }`, which translates to `cmd + shift + [` and `cmd + shift + ]`. I am on OS X.
