### ISSUE TITLE
Option to turn off all notifications on launch

### ISSUE THREAD

**Issue by karlgrz** [Thomas101/wmail#129]
It would be great to have a toggle that disables all notifications on launch. The only notifications I care about are when I get new mail after I've opened the client. If I have 100 messages unread in a Low Priority bundle I don't care to see those 100 notifications on start.

I'm currently on Ubuntu 64bit v. 1.2.1 (Ubuntu 15.10). 

Thanks for the great app!

**Comment by Thomas101** [comment]
Hey, this is fixed. You can check it out by [downloading the latest release](https://thomas101.github.io/wmail/download). Thanks! 😊 😊 😊
