### ISSUE TITLE
Wmail frequently hangs for a couple seconds

### ISSUE THREAD

**Issue by ffumarola** [Thomas101/wmail#130]
Hey -

I've run into an issue with Wmail where it will frequently hang for 1-2 seconds and not respond to mouse or keyboard input. After 1-2 seconds, it will "catch up"

I'm using Wmail 1.2.1

My system:
- OS X 10.11.3
- 15" Macbook Pro Retina (Mid-2015)
- 2.8Ghz Intel Core i7 processor
- 16Gb 1600Mhz DDR3 Ram

It makes Wmail hard to use because it is frustrating when writing emails or trying to quickly navigate around.

LMK if I can help debug!

Cheers,
Frank

**Comment by stefanjudis** [comment]
Just updated to 1.2.1 and confirm this behavior. 

MacBook Pro (Retina, 15-inch, Mid 2014)
2,2 GHz Intel Core i7
16 GB 1600 MHz DDR3

**Comment by bertrandmartin01** [comment]
same here!

macbook air
v1.2.1

**Comment by ffumarola** [comment]
Glad I'm not the only one :)

I've stopped using Wmail in the meantime, just because it makes working
pretty difficult.

**Comment by Thomas101** [comment]
Hey, does this only happen with 1.2.1? How many unread e-mails does everyone have? If you disable spell checking in the settings and restart the app does it seem any better?

**Comment by ffumarola** [comment]
I have 3 accounts linked, and my unread counts in each are 13, 10, and 2. I
have not tried disabling spell check. I may try that later today, thanks
for the suggestion.

**Comment by stefanjudis** [comment]
> If you disable spell checking in the settings and restart the app does it seem any better?

Nope doesn't solve it. :)

> Hey, does this only happen with 1.2.1? 

Made a big version jump to 1.2.1. Since then I'm having this problem.

Two account : 14 unread & 91 unread.

**Comment by ryanwatkins** [comment]
Not sure if its the same issue or not, but I've seen 1.2.1 balloon up to 2+ GB of memory when left open.

**Comment by Thomas101** [comment]
I'm also seeing the memory go up. I'll do some investigating as to why this is.

@ffumarola @stefanjudis if you try restarting the app does this solve the issue (temporarily)?

Also @stefanjudis if you remove the account with 91 unread do you see an reduction in the hanging?

**Comment by Thomas101** [comment]
I think I've managed to track this down. Can you try the latest pre-release 1.2.2?

**Comment by stefanjudis** [comment]
I'll give it a shot tomorrow. Can you maybe share, what was going on?

**Comment by Thomas101** [comment]
Thanks! There was a bug with the tray icon, which meant that every time it updated it a new click handler was being bound to it. I happened to Come across it by accident while doing some other bits. I left the app to run for a while on my machine and the memory footprint didn't seem to grow, but obviously with some real world use it might be different
