### ISSUE TITLE
Would be nice if "back" and "forward" worked as in browser

### ISSUE THREAD

**Issue by dzg** [Thomas101/wmail#131]
In Gmail website, I can use browser back and forward to flip through history (messages, views, etc.)

Not seeing how to do that in Wmail. Tried Command-[/] but does not work.

Is there a shortcut for back/forward?

**Comment by Thomas101** [comment]
If you try backspace that should work. I think by the amount of conversation around this in other issues it would be good to add a back/forward option.

I'll mark this one for 1.2.3 release and track the issue from here

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
