### ISSUE TITLE
Spell check hangs wmail (v1.2.0) on OS X 10.11.3

### ISSUE THREAD

**Issue by shawnyeager** [Thomas101/wmail#132]
When I right- or ctrl-click to spell check an underlined word in wmail, there is a ~10 second lag in the display of the context-specific menu. During this time, wmail is unresponsive.

This is reproducible every time for me.

**Comment by Thomas101** [comment]
Hi @shawnyeager there are some issues with 1.2.0 and the spell checking. If you try the 1.2.1 pre-release (http://thomas101.github.io/wmail/download) this if fixed.
