### ISSUE TITLE
Linux (1.2.1): Statusbar notifier issues

### ISSUE THREAD

**Issue by act28** [Thomas101/wmail#133]
A couple of issues with the inotify system statusbar for Linux implementation. May be related. 
1. When the statusbar icon is red and has unread messages, the link doesn't work. I would expect that clicking the link refocuses the app. 
2. Similarly, when the notifier pops up alerts with the subject and message summary, the view button doesn't work. I expect it's meant to refocus the app as well.

**Comment by Thomas101** [comment]
Number 1 is related to #75. The app should open when you tap on notifications. I think this might be a linux issue so I'll take a look see what's happening. Which distro are you using?

**Comment by act28** [comment]
Archlinux
