### ISSUE TITLE
Feature request: show link address

### ISSUE THREAD

**Issue by lid** [Thomas101/wmail#135]
It would be great to see the link address when hovering over it, same as you do in regular browsing. This would reduce potential risk for some phishing attacks.

**Comment by Thomas101** [comment]
I've taken a look into this. I could inject some javascript to listen for link hovering and report the url, but this could be spoofed with a targeted attack pretty easily. Ideally I need something in the electron platform to do this and they have an open issue on it here https://github.com/atom/electron/issues/1080.

I could capture navigate events and have it prompt you if you want to continue before actually taking you there, but this would have to be on every click and I imagine pretty annoying - hence most people will turn it off. Going to put this in the electron backlist for now, but still open for suggestions if anyone has any :)

**Comment by Eldaw** [comment]
Looks like the issue in electron has been resolved/closed. Can the functionality be incorporated into WMail now, so that hovering over links in emails will show the URL?

**Comment by Thomas101** [comment]
Nicely spotted! I'll add it in!

**Comment by Thomas101** [comment]
[Event: 'update-target-url'](https://github.com/electron/electron/blob/master/docs/api/web-contents.md) just for my reference

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Comment by Eldaw** [comment]
@Thomas101  thanks for adding this. v1.3.8 is looking great!

However, instead of displaying the URL in the bottom right, is it possible to display it in the bottom left, just like in Chrome? That's where I'm used to looking to see the URL.
