### ISSUE TITLE
Tray Icon is nearly invisible on dark tray

### ISSUE THREAD

**Issue by PaulBGD** [Thomas101/wmail#136]
![Icon](https://i.imgur.com/NQDBWs5.png)
Ubuntu 15.10 if it helps. Maybe add a white border around it?

**Comment by Thomas101** [comment]
This has been fixed in master now and will be fixed in the next release

**Comment by sicofante** [comment]
I'm using 1.3.5 in Ubuntu 16.04.1 and the tray icon is still dark on dark. ???

**Comment by PaulBGD** [comment]
It's pretty hard to detect theme color across different linux distros, I think just having an easy way to change the icon color is good enough.

**Comment by sicofante** [comment]
I don't think it's hard to detect theme colors in Gnome/Unity and KDE, which should cover 90% of use cases. For the rest, you can keep the manual color selection.

**Comment by PaulBGD** [comment]
Then submit a PR! I'd love to see this feature, but I thought it'd be a little hard to retrieve the color schemes in JavaScript.

**Comment by sicofante** [comment]
I don't even know what a PR is...

**Comment by Thomas101** [comment]
Electron doesn't have support for picking out the current color theme on linux or windows. It does on osx though. I think for the time being keeping the color selector is the best thing. I will be adding a background option (#217) so maybe it will be worth adding this as white by default
