### ISSUE TITLE
Feature request: different languages for spell checker

### ISSUE THREAD

**Issue by vitorgalvao** [Thomas101/wmail#139]
Any plans to introduce different languages for the spell checker?

**Comment by Thomas101** [comment]
Yes. I did look into this when I added the spellchecker originally, but didn't have time to do anything about it really.

When I did look I found that most dictionaries are under GPL style licenses which means I can't bundle them into the project without making my project GPL too. However I can provide a link to download them from somewhere else and effectively load them into the app. There's a repository here already (https://github.com/wooorm/dictionaries/tree/master/dictionaries)

Which language are you after?

**Comment by vitorgalvao** [comment]
Pretty ridiculous to put a license on a list of words from a language.

I was looking specifically for Portuguese from Portugal (pt-pt).

Are you thinking about having a place inside the app that will download the dictionaries and load them, ow would we have to download the dictionaries ourselves and include them somewhere where the app can see them?

If it’s the latter, I volunteer to maintain a personal [homebrew-cask](https://github.com/caskroom/homebrew-cask) tap for that. That means people could (if they use `homebrew-cask`) do something like `brew cask install wmail-dictionary-pt-pt wmail-dictionary-en-au` to in one command download and install those two dictionaries wherever wmail needs them.

It’d have to be a personal tap instead of officially supported, since it’s very specific and would require a lot of casks, and we like to avoid such situations.

**Comment by jbmouret** [comment]
If I install these dictionaries, is there a way to easily switch languages? I need French and English and I need to switch very often.

**Comment by mykecheckonetwo** [comment]
Thomas where do I find spell checker dictionaries in English? Trying to build out a subset and I don't know where exactly to begin.

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)
