### ISSUE TITLE
feature: add calendar 

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#14]
would be great to have the google calendar associated with the account as well in the application

maybe a simple icon in the left bar to switch view

amazing work so far by the way!

**Comment by Thomas101** [comment]
Hey, this is an interesting idea. Once the gets a little more stable I'll take a look into this and see what it would look like!

**Comment by AhmedAA** [comment]
Just pitching to in to say I'd love this as well!

Also, thank you SO much for your work! Much needed, and much appreciated <3

**Comment by SirCorion** [comment]
This indeed will be very handy, since you can have different calendars for each gmail/inobx account.

BTW: Awesome job and idea! Wmail is the best mail app!

**Comment by Thomas101** [comment]
Great idea. Going to close this and merge items into one thread #106
