### ISSUE TITLE
[OSX 1.2.3] Canceling a download still shows the "Download completed" notification

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#141]
Wmail still shows a notification "Download completed" if you go to save a file, then press Cancel to cancel the download.

**Comment by Thomas101** [comment]
Ha! That's a handy feature! Fixed this in 9b81f2ea93efe8ff6a7585eaebe2311344b326c9

**Comment by Thomas101** [comment]
Hey, this is fixed. You can check it out by [downloading the latest release](https://thomas101.github.io/wmail/download). Thanks! 😊 😊 😊
