### ISSUE TITLE
Fullscreen broken?

### ISSUE THREAD

**Issue by jbmouret** [Thomas101/wmail#142]
Thanks for this very useful application.

I just updated from 1.2.0 to 1.2.3 and the 'toggle fullscreen' menu item does not anything. There is no 'fullscreen button' on the title window as well. As a consequence, I cannot use wmail in fullscreen anymore. Fullscreen was working fine in 1.2.0.

I am running osx 10.9.5 (which is somewhat old).

**Comment by Thomas101** [comment]
Hey, this is fixed. You can check it out by [downloading the latest release](https://thomas101.github.io/wmail/download). Thanks! 😊 😊 😊
