### ISSUE TITLE
WMail does unresponsive and unusable

### ISSUE THREAD

**Issue by BrandonSmith** [Thomas101/wmail#143]
This morning, upon opening my laptop, WMail takes up an large amount of CPU time. The UI is unresponsive for 5+ minutes. After this time, I can interact with the UI as normal.

New notification count started incrementing. I screen captured at 397, but it built up to 900+ before stopping.

![Screenshot of notifications running amok](https://s3.amazonaws.com/uploads.hipchat.com/42491/448808/5Z9WtT0MGgUvjM4/Screen%20Shot%202016-03-30%20at%2012.32.55%20PM.png)

I noticed the Activity Monitor showing high sustained CPU usage for several minutes:

![Screenshot of CPU usage](https://s3.amazonaws.com/uploads.hipchat.com/42491/448808/je0Tiw33xKTnaP3/Screen%20Shot%202016-03-30%20at%2012.33.06%20PM.png)

For context, I have two accounts, personal and work, through Gmail. Work is managed by IT policies with SSO integration Okta and Google. One policy requires logging in every 24 hours. Since using WMail, this has been working. I open my laptop and when clicking on my work's WMail tab, I'm shown login and go through the process.

**Comment by Thomas101** [comment]
I think I've fixed this, but it might need more investigation if not. Hold out for the version 1.2.4 release

**Comment by Thomas101** [comment]
Hey, this is fixed. You can check it out by [downloading the latest release](https://thomas101.github.io/wmail/download). Thanks! 😊 😊 😊

**Comment by BrandonSmith** [comment]
I don't know how to reproduce. It happened a few times. I think the only correlation was that hours had passed since waking the laptop. I've installed the latest and will make sure to note when I wake it in the morning its behavior. Thanks.

**Comment by Thomas101** [comment]
I think this might have been related to #140 as that was sucking up CPU cycles. Keep an eye on it and let me know if it slows down again!
