### ISSUE TITLE
Reload GMail inbox when new emails arrives by notification

### ISSUE THREAD

**Issue by SpectralKH** [Thomas101/wmail#146]
It's kind of a bad system; You show me a notification, I click it, nothing happens when I click it, I proceed to open WMail and nevermind, no email - Oh wait, reload. Once a notification comes, just automatically reload the inbox :)

**Comment by Thomas101** [comment]
I agree with you. The whole thing is a bit dis-joint at the moment. The chunk of work I need to do is tie in some hooks to the gmail and inbox ui, so when you click on a notification it can open the message for you. There is a library for gmail (https://github.com/KartikTalwar/gmail.js/tree/master) but nothing for inbox yet.

**Comment by SpectralKH** [comment]
Alright, at least you'll be working on it :) Just wanted to say that I love the app

**Comment by dbrodie** [comment]
Also love the app so far.

I think before even opening the correct e-mail when a notification arrives, just raising the WMail window when a notification is clicked, and refreshing the proper gmail tab (though that can also be done when the notification is received from the server) would be a great first step.

**Comment by apoliveira** [comment]
Being able to open the email from a notification seems pretty important for an email client. Has there been any progress on this? Currently can't do it on a fresh install of Ubuntu 16.10 and WMail 2.0
