### ISSUE TITLE
WMail preventing shutdown

### ISSUE THREAD

**Issue by daitarn** [Thomas101/wmail#148]
When shutting down the computer I get the **WMail prevented the shutdown** message, and when I click **Try again** it shutdowns immediately. Just a little annoying, nothing more.
Thank you for all the work that you put here for a free app!

**Comment by alexweber** [comment]
I've had this happen to me with not only WMail but Atom editor a lot and inclined to venture a guess it could be an upstream electron issue...

**Comment by Thomas101** [comment]
I've taken a look into this and there looks to be two issues. Firstly, as @alexweber electron does seem to bring up the `preventing shutdown` dialog, however the dialog usually dismisses quite quickly thereafter. There's a long-standing issue on electron https://github.com/electron/electron/issues/230 tracking this

The second issue is down to the way that I keep wmail open when you close the main window. I was hoping that I could look at the event that was fired to see if the machine was shutting down but unfortunately not. I've open a feature request on electron for this here https://github.com/electron/electron/issues/5874

**Comment by Thomas101** [comment]
Are you still seeing this? I've not seen it for ages

**Comment by alexweber** [comment]
@Thomas101 Nope, use it every day and it's fine!

**Comment by Thomas101** [comment]
Awesome! WIll close this off then
