### ISSUE TITLE
Making everything bigger (feature req.)

### ISSUE THREAD

**Issue by daitarn** [Thomas101/wmail#149]
It would be a nice thing if there were an option to render the whole thing bigger (or smaller), on my display with 2560x1440 everything is pretty small, and there is my age issue (which is not reparable at the moment..)

**Comment by Thomas101** [comment]
Hi,

Is this regard the Gmail/inbox ui or the email ui? If it's making actual Gmail and inbox larger you can do this by using the zoom controls under the window menu, or by using Ctrl/cmd + or Ctrl/cmd -

**Comment by daitarn** [comment]
Oh yes, that's it. Sorry to bother you with this, it seem that's actually just an age issue..
