### ISSUE TITLE
nice to have: zoom/unzoom 

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#15]
it's a personal preference, but on chrome i usually unzoom the window to 75% for gmail because which allows to see more mails and makes the UI much much better if you're using multiple inboxes (otherwise it cuts the inbox you place on the right side)

**Comment by Thomas101** [comment]
Theres an issue with electron that means the shortcut for zoom in is currently cmd+shift+=. This shold be fixed in the next electron release. See https://github.com/atom/electron/issues/1507

**Comment by bertrandmartin01** [comment]
great! thanks

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip). Thanks very much for your help!

**Comment by bertrandmartin01** [comment]
cool!
thanks thomas!
