### ISSUE TITLE
Add Preferences into the native menubar

### ISSUE THREAD

**Issue by LeZuse** [Thomas101/wmail#150]
Right now, there is no Preferences menu item in the native application "WMail" menu. Adding this item would also make the very well established `Command-,` shortcut work.
OS: Mac OSX

**Comment by Thomas101** [comment]
Hi this is in the current pre-release which you can download from http://thomas101.github.io/wmail/download

**Comment by LeZuse** [comment]
Nice, works great! Thanks for this awesome app.
