### ISSUE TITLE
selecting misspelled words is very slow.

### ISSUE THREAD

**Issue by adamki** [Thomas101/wmail#152]
While composing a new message, double clicking on a misspelled word causes wmail to stall and drag.

**Comment by adamki** [comment]
After pulling the project down and setting up some credentials, I was unable to replicate the issue in dev. Problem still persists in production. Will investigate further.

**Comment by asferens** [comment]
Just came here to report the exact same problem. Running MacBook Pro (Retina, Early 2015) OS X EL Captain V 10.11.4. Great software otherwise but it really does grind to a halt with the right click to amend spelling.

**Comment by Thomas101** [comment]
Hi, What version of wmail are you using?

**Comment by asferens** [comment]
Version 1.2.0

**Comment by Thomas101** [comment]
If you give [1.2.4-prerelease](https://github.com/Thomas101/wmail/releases) a spin it should be much much better!
