### ISSUE TITLE
do not show unread badge

### ISSUE THREAD

**Issue by dimmiyjy** [Thomas101/wmail#153]
version 1.2.0 do not show unread badge. i have tried to reinstall Wmail, but till can't show badge. 
and then i tried 1.2.4, the problem remains the same. please help.
![image 2016-05-05 at 9 38 29 am](https://cloud.githubusercontent.com/assets/19179979/15034189/a5f6af46-12a5-11e6-92f8-0d68359edb28.png)

**Comment by Thomas101** [comment]
Hi,

Try deleting `~/Library/Application Support/wmail` and launching the app again. Does the problem persist after this?

**Comment by dimmiyjy** [comment]
@Thomas101 thanks for your reply. I have found that is because of the GFW interference in China, not the program it self. When I launch VPN, everything goes fine.

**Comment by Thomas101** [comment]
Ah okay! You can also set proxy settings under settings>advanced. This might get your around the GFW without needing to use a VPN ;-)
