### ISSUE TITLE
Arch support

### ISSUE THREAD

**Issue by edivad7** [Thomas101/wmail#155]
It will be great if Arch Linux support could be added

**Comment by Thomas101** [comment]
It should support Arch Linux x86-64 out of the box. Can you give me some more details about your setup?

**Comment by edivad7** [comment]
It actually works. My hope is to have an installable package instead of just a folder somewhere on the hard disk. Maybe uploading it to the AUR.

**Comment by tyhawk** [comment]
It has been in AUR since 2016-05-12: https://aur.archlinux.org/packages/wmail-bin/ ;-)

**Comment by Thomas101** [comment]
thanks for finding that @tyhawk !!
