### ISSUE TITLE
wrong unread count 

### ISSUE THREAD

**Issue by inteist** [Thomas101/wmail#157]
When I setup "Unread Primary Messages" I get 251 despite not having any:

![screen shot 2016-05-08 at 10 12 39 pm](https://cloud.githubusercontent.com/assets/53954/15102168/17d5f204-156a-11e6-91fb-24c4c44788ef.png)

**Comment by inteist** [comment]
removed `in:inbox` and I indeed had unread messages. Weird though as they did not show up in the web interface as unread. I suppose some weird mixup with some filters with the "skip inbox" action. TBD...

**Comment by Thomas101** [comment]
the search that the app does in the background is `label:inbox label:unread category:primary`. Not sure what the correct behaviour is here to be honest...

**Comment by inteist** [comment]
I don't know the details but the "correct" behavior I would think should be to use the API that provides this number if there is such an API because in the web interface I had no unread emails while in the app I had 251 unread emails until I did the "trick" above.

**Comment by neutronsalad** [comment]
I have this problem also. Mine is stuck saying 5 even though on the web gmail it shows zero.

So I thought maybe I could delete the app and reinstall it. But when I do, it seems to remember my accounts.

Is there any way to DELETE an account?
How do I delete the app entirely along with all the application data?

**Comment by Thomas101** [comment]
As a short term fix you can find which messages are sticking around by searching for one of (depends on your setting)...

`label:inbox` for inbox/gmail
`label:inbox label:unread` for unread in inbox/gmail
`label:inbox label:unread category:primary` for unread in primary tag on gmail

I'll update the client so you can add custom searches if need be :)

**Comment by panoriega** [comment]
All suggested search strings returns "No Results", I also tried in:unread.  There is not sticking unread emails.

wmail 1.3.1 on Mac OSX

**Comment by AlbertGrimley** [comment]
I've tried all three of those queries in gmail and I get zero messages.  However, wmail always shows 17.  What data can I get you for this issue?

**Comment by Thomas101** [comment]
Have you tried running them in gmail rather than inbox (or are you running them in gmail already?)

**Comment by Thomas101** [comment]
Sorry, spotted you specified gmail before. Give this a try....

Go to View > Developer Tools. In the window that pops up, click on the console tab. Then type the following....

```js
const i = JSON.parse(window.localStorage['Mailbox_index'])
const m = JSON.parse(window.localStorage['Mailbox_' + i[0]]);
const u = Object.keys(m.googleUnreadMessages).map((id) => m.googleUnreadMessages[id]).filter((ms) => ms.unread).map((u) => u.message.snippet)
console.log(u)
```

but replace `const p = 0` for the index of your mailbox. For example if the one with the 17 unread is at the top keep it as `const p = 0`, if it's the second one down use `const p = 1`, third down use `2` etc.

You should see a list of the snippets of the unread messages that wmail believes are in your inbox. If you search gmail for these messages they should come up. Are they unread or have any labels on them etc? How old are the messages, are they quite recent or from years ago?

**Comment by inteist** [comment]
My count is completely messed up all the time.
I decided to give try your suggestion and before I could do anything in the console here's what I got there:

![screen shot 2016-05-30 at 2 51 25 pm](https://cloud.githubusercontent.com/assets/53954/15656510/2459f8f0-2676-11e6-9ccc-bc5d45aa3fbc.png)

**Comment by Thomas101** [comment]
That doesn't look great. Can you try the following...

leave the console open for a while do you see more of those errors or is it just that one?

You see where it has the triangle then `0: Object` can you tap on the triangle and take another screenshot there may be some more error information in there.

If you try again tomorrow do you still see the warning (an error 500 is normally an indication that something went wrong Google's end and might only be temporary)

If you remove your account from the app and re-add it does the error persist?

Finally is this on a work/education Gmail account or a personal one?

Thanks!

**Comment by inteist** [comment]
![screen shot 2016-05-31 at 10 45 59 am](https://cloud.githubusercontent.com/assets/53954/15678618/061e6978-271d-11e6-9896-a4a3e68b3776.png)

**Comment by AlbertGrimley** [comment]
![image](https://cloud.githubusercontent.com/assets/1358475/15679954/cca21d98-2721-11e6-9f8f-44ba03a9cfec.png)

This is a business account.

**Comment by Thomas101** [comment]
what happens if you remove your account and add it again?

**Comment by inteist** [comment]
> what happens if you remove your account and add it again? 
@Thomas101, I did that at least 1 time in the past but I can try again...

**Comment by AlbertGrimley** [comment]
Deleting the account and re-adding just worked for me.

**Comment by inteist** [comment]
>Deleting the account and re-adding just worked for me. 
As I mentioned before I already tried it and tried again and it did not work for me

**Comment by Thomas101** [comment]
@AlbertGrimley great news!

@inteist if you go to `https://security.google.com/settings/security/permissions` do you see `WMail` listed as a connected service? Are you using a vpn or proxy server?

**Comment by inteist** [comment]
Yes and No

![screen shot 2016-05-31 at 12 52 36 pm](https://cloud.githubusercontent.com/assets/53954/15683076/97d4bf00-272e-11e6-9365-f41343b56584.png)

**Comment by Thomas101** [comment]
Okay, lets try deleting everything and starting from scratch on this one.

1.) Quit wmail completely
2.) Open the Terminal app (Applications>Utilities>Terminal.app)
3.) Type `open ~/Library/Application\ Support/wmail` to open the wmail data in finder.
4.) Delete the wmail folder
5.) Relaunch wmail and add your account. Do you see any errors in the console when you go to View > Developer Tools

**Comment by inteist** [comment]
Ok, did that so the problem persists and here's what happens.

I have primary and promotions "sections" enabled


I open the app and add my account. Wmail says there are 343 unread emails while there is none next to my inbox. I go in and switch in the settings to "unread primary messages" . Nothing happens even if I do reload on the mailbox. Then I go to promotions folder and this triggers refresh I suppose and now it shows 8 although the promotions only showed 2.

Running `label:inbox label:unread category:primary` shows no emails... the badge still shows 8

**Comment by inteist** [comment]
Completely removed wmail with appcleaner, reinstalled the 1.3.1 from the website. Same exact thing.

![screen shot 2016-05-31 at 1 14 38 pm](https://cloud.githubusercontent.com/assets/53954/15683788/1244f8b0-2732-11e6-98e7-a4aa6b28970d.png)

**Comment by Thomas101** [comment]
This is turning into quite the mystery. If you go to view > Developer Tools and click on the console tab do you see any errors?

**Comment by inteist** [comment]
No, not now. The app has been open for this whole time with the console open and no errors now... But the count is still definitely wrong.

**Comment by Thomas101** [comment]
Okay, can you paste the following into the console and send me a screenshot of the result. It's a bit of long one, but should log out the parameters it uses for the unread request and the response it gets back

```js
const mIndex = 0
const credentials = require(__dirname + '/shared/credentials')
const google = window.nativeRequire('googleapis')
const mailboxId = JSON.parse(window.localStorage.Mailbox_index)[mIndex]
const mailbox = JSON.parse(window.localStorage['Mailbox_' + mailboxId])
const auth = new google.auth.OAuth2(credentials.GOOGLE_CLIENT_ID, credentials.GOOGLE_CLIENT_SECRET)
console.log(mailbox.googleAuth)
auth.setCredentials({
  access_token: mailbox.googleAuth.access_token,
  refresh_token: mailbox.googleAuth.refresh_token,
  expiry_date: mailbox.googleAuth.date + mailbox.googleAuth.expires_in
})
const UNREAD_MODES = {
  INBOX: 'inbox',
  INBOX_UNREAD: 'inbox_unread',
  PRIMARY_INBOX_UNREAD: 'primary_inbox_unread'
}
const unreadMode = (mailbox.googleConf || {}).unreadMode || UNREAD_MODES.INBOX_UNREAD
let unreadLabel;
switch (unreadMode) {
  case UNREAD_MODES.INBOX: unreadLabel = 'INBOX'; break;
  case UNREAD_MODES.INBOX_UNREAD: unreadLabel = 'INBOX'; break;
  case UNREAD_MODES.PRIMARY_INBOX_UNREAD: unreadLabel = 'CATEGORY_PERSONAL'; break;
}
let unreadLabelField;
switch (unreadMode) {
  case UNREAD_MODES.INBOX: unreadLabelField = 'threadsTotal'; break;
  case UNREAD_MODES.INBOX_UNREAD: unreadLabelField = 'threadsUnread'; break;
  case UNREAD_MODES.PRIMARY_INBOX_UNREAD: unreadLabelField = 'threadsUnread'; break;
}
console.log('unreadMode= ' + unreadMode)
console.log('unreadLabel= ' + unreadLabel)
console.log('unreadLabelField= ' + unreadLabelField)
const req = google.gmail('v1').users.labels.get({
  userId: mailbox.email,
  id: unreadLabel,
  auth: auth
}, (err, response) => {
  if (err) {
    console.log('ERROR->')
    console.log(err)
  } else {
    console.log(response)
    console.log(response[unreadLabelField])
  }
})
```

here's an example of what I get out...
![screen shot 2016-06-02 at 09 19 35](https://cloud.githubusercontent.com/assets/103586/15738442/2f6666f0-28a3-11e6-81a2-2a23eb7c693d.png)

**Comment by Thomas101** [comment]
I think I've managed to fix this in ed7385f085f871c2dc55bc39e84dcf66568dcb04 :-)

**Comment by inteist** [comment]
fingers crossed :–)

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
