### ISSUE TITLE
unread messages in Gmail and Inbox versions of same acct counted as distinct

### ISSUE THREAD

**Issue by olets** [Thomas101/wmail#159]
It's possible to have two WMail accounts for a single Google account, by adding the account as both Gmail and Google Inbox. Don't know if anyone else is using that, but I _love_ it! But there's a bug: if you do that, both WMail accounts are factored into the app's total unread count. Rather than blindly adding the unread count of every WMail account, the total unread count should only factor in each Google account once.

**Comment by Thomas101** [comment]
Hi, you could disable the unread count for one of the accounts. Here's how you do it...

* Go to the settings cog,
* Press the accounts tab
* Select one of the accounts from the dropdown
* Turn off `Add unread messages to app unread count`
* Turn off `Show notifications`

**Comment by olets** [comment]
Nice, that's a good temp fix

**Comment by Thomas101** [comment]
Going forward I think adding the same account as Gmail and Inbox is a fringe case and giving the options to disable notifications and unread messages is the way forward on this. Trying to figure out which account to show the unread emails for will still require the same configuration as what's currently needed.

For example some users may want to keep notifications from gmail and others inbox. Providing the settings and tools to change the way they work gives the best flexibility
