### ISSUE TITLE
mailbox.js:43 Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by wesleydean** [Thomas101/wmail#160]
Version 1.3.1 is giving me a blank screen, after updating and restarting. Tried reloading but no luck. 
![_ 2016-05-11 at 12 31 45 am](https://cloud.githubusercontent.com/assets/6432980/15170032/ec9f3256-170f-11e6-869f-1b54b3943294.jpg)

**Comment by Thomas101** [comment]
That's not good. It seems to work my end. If you re-download it for GitHub and re-extract it do you still get the same error?

**Comment by PaulBGD** [comment]
If you could also give a full stacktrace, it'd be easier to find the issue.

**Comment by Thomas101** [comment]
I'm going to close this issue as it doesn't seem reproducible, but feel free to re-open if you're still having trouble.
