### ISSUE TITLE
Too many notifications

### ISSUE THREAD

**Issue by lukaszbob** [Thomas101/wmail#162]
When I use google Inbox on phone I can set for which categories I want notification. In wmail I have notifications for all messages, even from "Offers" category.
Please add option to disable notifications for some (or all) categories.

**Comment by Thomas101** [comment]
If you go into settings then account, you can update the unread search to look for only message in the primary tab. I'll be adding the option to add custom searches if you want to exclude certain categories etc

**Comment by lukaszbob** [comment]
When I change "Unread mode" to Messages in inbox I have counter with all my messages, even from categories. It isn't solution for my problem, still I have notifications from categories.

**Comment by Thomas101** [comment]
Hi, I'm going to close this and collapse it into #349 as there's a few issues surround some Google Inbox Notifications and unread counts which are all related. Thanks!
