### ISSUE TITLE
Keyboard shortcuts don't work [Ubuntu 16.04 64bit]

### ISSUE THREAD

**Issue by hotice** [Thomas101/wmail#163]
Using WMail 1.3.1 in Ubuntu 16.04 (64bit), keyboard shortcuts don't work at all, I mean both Gmail shortcuts and WMail specific shortcuts (for instance, if I enter fullscreen mode, I can't exit it).

And while we're at it, it I can't seem to right click anywhere in the app (no menu is displayed on right click).

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
