### ISSUE TITLE
"Show Original" support

### ISSUE THREAD

**Issue by lid** [Thomas101/wmail#165]
I noticed that Inbox now has a "Show Original" menu item for each email. In a normal browser, this opens a new tab/pop-up with the unformatted contents of the email. However, in WMail, once this window is opened, there is no obvious way to get back to the normal interface.

**Comment by Thomas101** [comment]
Hi, which version of WMail are you using? There was a bug a while ago that meant you'd end up in the scenario you described, but now it should open up in a new window that you can close etc.

**Comment by lid** [comment]
Hi, I'm using 1.3.1.

**Comment by Thomas101** [comment]
Yep. I see it now! I'll put a patch in for that one. Thanks!

**Comment by Thomas101** [comment]
As a quick fix if you do get stuck like that again, you can right click on your account icon on the left and go to reload. Not ideal, but saves you needing to restart the app ;-)

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
