### ISSUE TITLE
Menu bar icon is low resolution on 4K/retina display

### ISSUE THREAD

**Issue by gnidan** [Thomas101/wmail#166]
<img width="683" alt="screen shot 2016-05-14 at 18 19 52" src="https://cloud.githubusercontent.com/assets/151065/15270962/a3e6a6f4-1a00-11e6-966d-86ed8d6159b2.png">

Looks sadly out of place next to the others!

**Comment by Thomas101** [comment]
This is like the bane of my life! It keeps coming back!!! I think it's after I added the unread count to the tray icon. I'll try and take a look

**Comment by Thomas101** [comment]
Hi @gnidan, do you have more than one monitor? If you open WMail and go to View>Developer Tools, then click on the console tab and type `window.devicePixelRatio` what number do you get?

**Comment by gnidan** [comment]
Yes to more than 1 monitor... `window.devicePixelRatio` returns 2, but now the icon seems fine? Adjusting my resolution scale doesn't seem to change anything and I can't get it to look bad again.

**Comment by Thomas101** [comment]
Is your other monitor the same in terms of resolution? Try dragging WMail onto your other window. Quit it and start it up again. Does that make it look bad again?

**Comment by gnidan** [comment]
Nope, now the icon just looks fine no matter what combinations of scaling/monitor. Weird. Thanks anyway!

**Comment by Thomas101** [comment]
Good to hear! Let's hope it stays fixed :-)

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
