### ISSUE TITLE
Mailboxes not inserted into Window menu when running via 'npm start'

### ISSUE THREAD

**Issue by TimNZ** [Thomas101/wmail#167]
OS X 10.11.5

The ipc message 'mailboxes-changed' is not triggered at startup when running via 'npm start',
so the Windows menu is not populated with the mailboxes.

Works fine when running a built package.

'mailboxes-changed' is triggered when deleting/adding a mailbox when run either way

The mailbox name in Windows menu is 'untitled' when run via 'npm start'

**Comment by Thomas101** [comment]
I'm working on refactoring the data-storage in the version_2 branch so the same data and code is available to both the renderer process and main process. I'll double check this one once I'm done though to make sure it's fixed. Sounds like an edge case that I could have missed when testing!

**Comment by Thomas101** [comment]
This is fixed in master and will be released in the next pre-release. Thanks!

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!

**Comment by TimNZ** [comment]
Thanks mate.

I've squeezed out a lot of learnings from your system.

My only complaint is the use of the shit StorageBucket system, prefer something more robust like Neddb.

Also an ActiveRecord type system combining the model and persistence is something I'm implementing.

Having used Mongoose I'm used to that sort of niceness.

**Comment by Thomas101** [comment]
The `StorageBucket` code is more of an evolution, from originally using localStorage in the renderer thread. As all the validation and business logic is done through altjs using the flux pattern all that was needed was a simple key-store to persist data. Would be happy to take on suggestions though if you think we can improve it!

**Comment by TimNZ** [comment]
Whatever you want to do Thomas, it's your project.  

My comments would purely be personal views on architectural and tech options.  

Thanks again for your work.
