### ISSUE TITLE
Sounds and Colours :D

### ISSUE THREAD

**Issue by YellowLabIT** [Thomas101/wmail#169]
in next releases would be great some implementations:

1 when new email comes, a sound notification play togheter with panel notification in the bottom right corner of the screen.

2 when we click on new email notification (the panel in bottom right corner) nothing happens. we'd like if on click wmail open unread emails.

3 when we set color for inbox account, another great feature would be the top bar change it's color according to the account color

4 when writing new email, it's possible to detach new email windows from the main app? this would be another great implementation if you can do this.

5 Beautiful work, beautiful crossplatform app! we love your great work!

**Comment by vitorgalvao** [comment]
> when we click on new email notification (the panel in bottom right corner) nothing happens. we'd like if on click wmail open unread emails.

That is not exactly right. Clicking the notification does indeed cause WMail to open the new email. What it isn’t doing is bringing the app to the front.

**Comment by Thomas101** [comment]
Going to close this off...

1.) Notifications with sounds are implemented
2.) Keep tracking this one on #171 
3.) Changing the gmail & inbox ui is a nightmare and prone to break. Not sure this is going to work well on a long term basis
4.) I think Google have removed this -- not able to find it anywhere
5.) Thanks :)
