### ISSUE TITLE
add support for openPGP

### ISSUE THREAD

**Issue by CzechJiri** [Thomas101/wmail#170]
This might seem like a stretch, but it should not be too complicated if you use [OpenPGP.js](https://github.com/openpgpjs/openpgpjs) framework, i currently use https://www.mailvelope.com/ in the web browser on top of GMail with no issues

**Comment by tmathmeyer** [comment]
I ported some openPGP functionality to outlook last summer when I was an intern, I'd be willing to give this a shot.

**Comment by Thomas101** [comment]
It should be possible to be add this. I'd be happy to accept a pull request on this :)

**Comment by CzechJiri** [comment]
let's make this a bit more juicy... will donate $50 to EFF the day it goes to non-beta release :-)

**Comment by Thomas101** [comment]
Unfortunately I don't have time to work on adding something like this, but if someone is interested in adding it will happily point them in the right direction and merge the pull request. --  Going to close this off for now
