### ISSUE TITLE
Electron 1.2.0

### ISSUE THREAD

**Issue by TimNZ** [Thomas101/wmail#172]
Heads up that on updating to Electron 1.2.0 the constructor for Tray(image) instance fails in src/mailbox/ui/Tray.js passing null and a NativeImage instance must be passed.
I did a nativeImage.createFromDataURL(loader.src) to get it working.

Also could not get electron-rebuild to work > 1.0.2, issue with **nodehun** compilation.
electron-rebuild should be updated to 1.1.5 as well.

No idea yet if there are other issues.

**Comment by Thomas101** [comment]
Thanks for the heads up! Have you been following the version_2 branch or master? I've updated to 1.0.2 which had some issues over 0.34

**Comment by TimNZ** [comment]
I have branched off and did my own updates to support 1.x.
Thanks for the good work.

**Comment by Thomas101** [comment]
master is now up on 1.2 if it helps you. Still working on getting the spell checking working!
