### ISSUE TITLE
[OS X] Allow WMail to be the default mail client

### ISSUE THREAD

**Issue by SpectralKH** [Thomas101/wmail#177]
I don't think it's possible to have WMail as a default mail client. I might be mistaken, but this is what I think makes it that, inside the OS X Mail app's preferences.
![screen shot 2016-06-03 at 22 00 00](https://cloud.githubusercontent.com/assets/11315492/15791283/aa04e916-29d6-11e6-8c57-e9dba33a9a97.png)
After applying it, it just resets to being Safari. If I'm correct, this is what handles mailto: links too, which would be a super nice thing to have with WMail.

**Comment by SpectralKH** [comment]
Seems to be duplicate of https://github.com/Thomas101/wmail/issues/66, sorry

**Comment by vitorgalvao** [comment]
@SpectralKH Since this is a duplicate, you can just close the issue (bottom right).

**Comment by SpectralKH** [comment]
@vitorgalvao Oh, I didn't realize I could.
