### ISSUE TITLE
OSX: downloading a file - click notification opens /Downloads, not the actual file location

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#178]
On OSX when you download a file, and you get a notification that it downloaded, you click the notification and it opens.. the /Downloads folder, not the actual place I saved the file.

Any way to do that? There must be since Chrome can do it.

As always.. keep up the awesome work!

**Comment by Thomas101** [comment]
I'm not able to get the location when you change it from downloads at the moment. I've opened an issue with electron to see if I can get it added in https://github.com/electron/electron/issues/5877

**Comment by lament** [comment]
Thanks Thomas!

**Comment by Thomas101** [comment]
Looks like this has been added to electron, so I'll take another look at fixing it

**Comment by Thomas101** [comment]
Hi this is fixed in the latest [pre-release](https://github.com/Thomas101/wmail/releases). Thanks!

**Comment by lament** [comment]
Confirmed working for me. Thanks!
