### ISSUE TITLE
feature: add whatsapp web view in the client

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#18]
would be great to have whatsapp web integrated to the client to have a 1 goto place for communication applications

not sure what's the end vision for wmail 
@thomas101 maybe you can share your ideas, as far as i see, gmail client, but maybe planning other communication tools integration?
i really appreciate your work and the application so far! it has already proven very useful managing personal and pro account and it could probably be taken further!

**Comment by parro-it** [comment]
Would be great! This app could integrate [Whatsapp-Desktop](https://github.com/bcalik/Whatsapp-Desktop)
/CC @bcalik

**Comment by Thomas101** [comment]
I should be able to add this in as a different mailbox type -- all be it not a mailbox. Are there any other services that you'd like to see integrated? There is scope here for more than just mail I guess!

**Comment by bertrandmartin01** [comment]
Amazing!

Could be great to add Skype and slack!

**Comment by bertrandmartin01** [comment]
hangout and mightytext.net as well
then you basically have a very large part of communication tools (online+sms)

**Comment by DerSiedler** [comment]
make it a rss reader, too. :P *justkidding*

**Comment by bertrandmartin01** [comment]
and also https://www.messenger.com !

**Comment by vitorgalvao** [comment]
I’m actually against this feature. It’ll make wmail start to become bloated and unfocused, and hence worse in general. Email and chat are different beasts, and should be handled differently. We really don’t want the codebase to start to be divided for chat and email, and for development to be centred around fixing bugs with the quirks of each service.

Tangentially, [an app that integrates multiple chat services](http://meetfranz.com/) recently came out. To me, this is the perfect cue to let wmail focus and excel at email.

**Comment by bertrandmartin01** [comment]
an app that integrates multiple chat services <http://meetfranz.com/> ->
this literally got out today or yesterday. doesn't integrate sms though


I don't mind using 2 apps, but 1 instead would be massively helpful. anyone
is free to add accounts that are not mail related but that would also serve
a need that i don't see fulfiled by any tool.

All depends what Thomas wants to achieve with his app!

**Comment by vitorgalvao** [comment]
> doesn't integrate sms though

You can ask them.

> I don't mind using 2 apps, but 1 instead would be massively helpful.

It would also be bloated, slower, with more bugs, and slower to advance. Lets not forget @Thomas101 is the main person working on this, and a human with limited time and stamina. Focusing and getting a better app with less is better than a worse app with more.

**Comment by russiancow** [comment]
I agree completely with @vitorgalvao—I'd rather wmail stay focused on just being a damn good email client than have a bunch of time spent working on additional services that many won't use. Having separate apps for email and chat isn't a bad thing, especially if it means each one can be great at its own purpose.

**Comment by Thomas101** [comment]
After some thought on this and also taking into account the array of other comms apps out there (e.g. franz) and also whatsapps now native client I think I'll be keeping focus on email for now :). Thanks everyone!
