### ISSUE TITLE
Make application more resizable? [OS X]

### ISSUE THREAD

**Issue by LanderN** [Thomas101/wmail#181]
I can't make the window smaller than around half of the width of my screen (192x1080). Is there a reason for this?

**Comment by Thomas101** [comment]
Have adjusted it to allow as small as 300x770

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
