### ISSUE TITLE
"view original" - no way to close pane

### ISSUE THREAD

**Issue by amossberg** [Thomas101/wmail#183]
If view original is selected to view raw email with headers, the resulting display pane does not have any way of closing and going back to message or inbox view.

**Comment by Thomas101** [comment]
Fixed in master, waiting for release. #165

**Comment by Thomas101** [comment]
Hey this has been added/fixed. You can check it out by downloading the [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!
