### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by Hori873** [Thomas101/wmail#184]
Can you add theme support? I would like there to be a material design theme for GMail.. like the one I can get by using the Ink extension for Chrome.

**Comment by vitorgalvao** [comment]
This app simply loads Gmail and adds features on top of it. Not only would themes be unreasonably hard to make, they’d break with every gmail update.

If you want themes, you need to ask the gmail team.

**Comment by Hori873** [comment]
In this case, is it possible in any way to install chrome extensions in this app?

**Comment by vitorgalvao** [comment]
> is it possible in any way to install chrome extensions in this app?

No, but that isn’t the fault of the app. [It’s the fault of the technology it uses](https://github.com/electron/electron/issues/1498).

**Comment by Thomas101** [comment]
I did have plans of adding support for chrome extensions as electron does have a runtime for extensions, just none of the chrome apis. It's way too much of an undertaking to add enough support to have broad enough coverage though, so as it stands I'm afraid not :-(

**Comment by Hori873** [comment]
It's ok, thanks for your answers.
