### ISSUE TITLE
CopyWebpackPlugin issues

### ISSUE THREAD

**Issue by TimNZ** [Thomas101/wmail#185]
Heads up that I'm having a lot of trouble with this plugin when running webpack, either getting 'ENFILE: file table overflow' or 'EMFILE: Too many open files"

I used Wmail 2 as a starter structure and having ~8000 files in node_modules is not working out well..
I'm changing the structure to flatten node_modules across the project.

Mac and Windows.

**Comment by Thomas101** [comment]
Thanks Tim! Are you using master or one of the releases?

**Comment by TimNZ** [comment]
Master.

**Comment by Thomas101** [comment]
Wow! There's like 95% less in files in master (9878 to 415) since the last release. Which version of npm are you using?

**Comment by TimNZ** [comment]
Ignore me, I've added packages which has blown it out.
