### ISSUE TITLE
Make nice DMG

### ISSUE THREAD

**Issue by MartinDelille** [Thomas101/wmail#188]
This [script](https://github.com/andreyvit/create-dmg) allow to make nice DMG like that:

![image](https://cloud.githubusercontent.com/assets/879889/16275067/b4ebcdfa-38a8-11e6-959b-badb664c4249.png)

It should be easy to use it for this nice project (and it'll remove the need to have a doc like that: https://github.com/Thomas101/wmail/wiki/Installing-on-OSX).

**Comment by MartinDelille** [comment]
Here are the parameters I used: https://github.com/Phonations/Joker/blob/master/common/deploy.pri#L56-L63

**Comment by Thomas101** [comment]
Thanks! I'll take a look at adding this in!

**Comment by stefanjudis** [comment]
@Thomas101 

maybe you wanna consider https://github.com/electron-userland/electron-builder.

It handles all the distribution stuff you to keep the codebase a bit cleaner.

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)

**Comment by MartinDelille** [comment]
Nice! I tip you on Liberapay: https://liberapay.com/on/github/Thomas101/

**Comment by Thomas101** [comment]
@MartinDelille thank you!! :)
