### ISSUE TITLE
Feature request: Open at startup (in the background)

### ISSUE THREAD

**Issue by thorpj** [Thomas101/wmail#189]
Simple and useful feature, that every mail client under the sun has. Wmail should have it too.

**Comment by kiwi46** [comment]
I support this request as well. run at startup. start in tray [linux]

**Comment by SpectralKH** [comment]
Can't you just do it through System Preferences?

**Comment by thorpj** [comment]
Sorry, forgot to mention. Should be a feature on Windows. You can put a shortcut in startup, but the program will open in the foreground, which it shouldn't. It should open minimised.

I'm not sure how thing works on mac.

**Comment by jamgregory** [comment]
As @thorpj mentioned, it's possible to start it on log in, but it'll start in the foreground. Ideally it'd be good if there was a flag or option somewhere that would allow it to open in the background.

**Comment by SpectralKH** [comment]
@jamesbvaughan Good point

**Comment by Thomas101** [comment]
I was hoping this was going to be an easy add thanks to [node-auto-launch](https://github.com/Teamwork/node-auto-launch) but it doesn't work all that well. For example on osx it launches in the foreground etc. I'll keep an eye open for anything else that will let me add this

**Comment by thorpj** [comment]
@Thomas101 Were their any problems with introducing the feature on Windows?

Also i'm not a dev, so i wouldn't know, but does this help? [](http://stackoverflow.com/questions/18463333/how-to-programmatically-launch-an-osx-app-in-minimized-mode)

**Comment by Thomas101** [comment]
I didn't try it on windows, but looking at the open issues on their github repository  other people are reporting the same issues cross platform

**Comment by Thomas101** [comment]
Reinvestigate this [app.setLoginItemSettings](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetloginitemsettingssettings-macos-windows)

**Comment by Thomas101** [comment]
I've been able to get this working on windows and on osx but unfortunately not on linux.

I have however added a command line flag in version 1.3.8 that means you can launch the app with the `--hidden` command. This does mean that if you add a shell script into `/etc/init.d/` to launch wmail you can get it to launch in the background :).

Hold tight for the 1.3.9 release - that will have the option to setup launch configuration in settings

**Comment by kiwi46** [comment]
The start hidden flag works for me. Thanks Regards
Vern Rolton
verdia13@gmail.com Sent from BlueMail

**Comment by Thomas101** [comment]
Hi the next [prerelease](https://github.com/Thomas101/wmail/releases) has just landed with this. Thanks!

**Comment by aurimus** [comment]
Hey!

Could you provide a shor tutorial on how to accomplish this in Linux? 

```
wmail --hidden
The program 'wmail' is currently not installed. You can install it by typing:
sudo apt install wmail
```


Btw, most apps actually just add the script to startup applications when you click the option to start at system startup, so you might just be able to do that quite easily.

**Comment by kiwi46** [comment]
Hi you need to type this exactly including caps
 /opt/wmail-desktop/WMail --hidden

**Comment by aurimus** [comment]
@Thomas101 you don't happen to have "Start at system startup" option in Windows version?
