### ISSUE TITLE
No spelling check when writing/replying email.

### ISSUE THREAD

**Issue by bikmanwei** [Thomas101/wmail#19]
Hihi!
My default language is Chinese, and when I write emails there is no spelling check for English. Can I somehow turn it on? Thanks. Great work!

Great regards,
Bikman

**Comment by pasalot** [comment]
+1 for spell check, slightly concerned how much I rely on it these days!

**Comment by mykecheckonetwo** [comment]
To piggy back on this is there a way to have text expanding supported? Currently it works but is very buggy and only works properly 1/3 of the time.

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.6/WMail_1_1_6_osx_prerelease.zip). Thanks very much for your help!
