### ISSUE TITLE
Not able to copy links

### ISSUE THREAD

**Issue by vighneshpai** [Thomas101/wmail#190]
When I copy links from mail, it just copies the text. There's no way I can copy the link or Am I missing something here?

**Comment by Thomas101** [comment]
Hi, do you still experience this with the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2)?

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, it should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)
