### ISSUE TITLE
Mac's native autocorrect not working

### ISSUE THREAD

**Issue by tinymachine** [Thomas101/wmail#191]
When I use Gmail in Safari, I can take advantage of the Mac's native autocorrect feature (see screenshot). Can this be enabled in Wmail? Now that I've grown accustomed to it, it's hard to go back to correcting my own (frequent) typos!

![screen shot 2016-06-27 at 1 14 19 pm](https://cloud.githubusercontent.com/assets/171986/16394265/2bf3d50a-3c69-11e6-9b74-360be129dca7.png)

**Comment by Thomas101** [comment]
Spell checking has been surprisingly difficult, especially trying to get something that works across platform. At the moment the app uses a 3rd party spell checking library which has proved to be the most reliable way to implement spell checking. Is there a specific feature that's missing?

**Comment by tinymachine** [comment]
Thanks for following up. It's Mac OS's native autocorrect specifically that I'm missing. (I thought that would be pretty straightforward to enable in a native app, but maybe not so for Electron apps?)

**Comment by Thomas101** [comment]
Unfortunately it's not simple to enable. Surprisingly I've been struggling with spell checking for some time. I'm keeping an eye open for anything electron based that can offer native spell checking support but so far nothing that I've found works!

**Comment by tinymachine** [comment]
That’s too bad — thanks for looking into it, though. I found [this electron GitHub issue ('Use system spellchecker')](https://github.com/electron/electron/issues/3189) that looks related, but suggests that right now there’s no easy answer. 

(In typical native Mac apps, text fields would use NSTextView, which get spellcheck features automatically, but I’m gathering electron apps are built using the blink rendering engine, and blink doesn’t use NSTextField for its text fields. Apparently Google has gone to some trouble to get some of the Mac’s native spellcheck features to work in Chrome, but that’s work that the electron team hasn’t gotten to yet.)

**Comment by Thomas101** [comment]
Going to close this for now - electron doesn't have plans to add this into the platform and for me to take this is on is a giant undertaking I'm afraid

**Comment by tinymachine** [comment]
Understood -- thanks for looking into it!
