### ISSUE TITLE
Notifications without notifications

### ISSUE THREAD

**Issue by kopechcr** [Thomas101/wmail#193]
The account pullout shows unread messages, but there are no unread messages (pardon the pixelization) 

<img width="1000" alt="bug" src="https://cloud.githubusercontent.com/assets/20321690/16621408/1e591228-4364-11e6-90e6-905649228bc6.png">

**Comment by Thomas101** [comment]
Hey, this is related to #157. I've just fixed it and released it to the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/1.3.2). Thanks!

**Comment by kopechcr** [comment]
Thanks! I look forward to using it!

On Wed, Jul 6, 2016 at 4:52 PM Thomas Beverley <notifications@github.com>
wrote:

> Closed #193 <https://github.com/Thomas101/wmail/issues/193>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Thomas101/wmail/issues/193#event-714911577>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATYVmh1AtP8QA63EXQ2qtmPytccJQluzks5qTBV4gaJpZM4JGIwI>
> .
>
-- 
-------

Sent from Inbox by Gmail
