### ISSUE TITLE
1.3.2 focus issues on OS X

### ISSUE THREAD

**Issue by bmurphy1976** [Thomas101/wmail#195]
Seems like focus is having trouble on OSX v1.3.2.

If I am focused on tab one (keyboard shortcuts work), then I hit command+2 to focus on tab 2, the window changes to tab 2 but keyboard shortcuts continue to be focused on tab 1.

I.e. if I hit ? after switching to tab 2, the help dialog shows up only when I hit command+1 to go back to tab 1.

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, it should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)

**Comment by bmurphy1976** [comment]
Can confirm, works as expected in new build.  Thanks!!!
