### ISSUE TITLE
OS X Dark Mode not working

### ISSUE THREAD

**Issue by iandrewt** [Thomas101/wmail#196]
Hi,
The issue fixed in version 1.2.2 regarding turning the icon white in OS X dark mode seems to not be working for me. I'm using the latest version (1.3.2), and I've also tried building from source. The icon turns red with unread emails just fine, and displays as black in light mode.

It seems the icon actually doesn't display at all, as the dark menu bar is not actually #000000 for me, its actually #1D1D1D on the active monitor and #1A1A1A on inactive monitors, but I can't see the icon at all. When I click on the icon where it's supposed to be, it shows with the blue background. The icon also gets highlighted blue on all monitors when I click it (doesn't happen with any other apps)

Thanks!

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, it should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)
