### ISSUE TITLE
macOS: App not signed

### ISSUE THREAD

**Issue by joan38** [Thomas101/wmail#198]
Hi,

The app is not signed and require to enable in the security settings the ability to execute unsigned apps, which is not granted to everyone (I am on a company laptop).

Cheers

**Comment by Thomas101** [comment]
Hi, this is basically down to cost (More on this in the [FAQs](https://github.com/Thomas101/wmail/wiki/FAQs)). Have you tried right clicking on the app and selecting open from the dropdown menu?

**Comment by joan38** [comment]
Oh ok, I see.
I managed to make an exception for this app.
