### ISSUE TITLE
[OSX] Command +/- font size bug

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#199]
Command minus (-) decreases the font size, but command 0 won't reset the font size, and command plus (+) doesn't increase the font size as it should.

I had to delete the account and re-add it to get it back to normal size.

Wmail 1.3.1 on 10.11.5 (El Capitan).

**Comment by Thomas101** [comment]
Hi, have you tried the 1.3.2 pre-release? I've just checked and command minus and command plus work my end. Command 0 isn't registered as the reset shortcut at the moment, but I don't see why that can't be added in

**Comment by lament** [comment]
@Thomas101 - that worked, thanks! I figured it was using a Safari shell, and command 0 resets the font size (same as Chrome).

**Comment by Thomas101** [comment]
Added this in 444efbd0f07321a7ad3fa13eb7ce9b7eb6552e2d

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, it should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)

**Comment by lament** [comment]
Thanks, confirmed fixed in 1.3.4!
