### ISSUE TITLE
After successful authorization-no effect

### ISSUE THREAD

**Issue by androidcn** [Thomas101/wmail#2]
After successful authorization-no effect

installed release version

**Comment by Thomas101** [comment]
Hi,

Are you using a @gmail account or google apps for education/work account (might be a @yourcompany.com address). Also which version of osx are you using?

**Comment by xream** [comment]
Same here. 
Normal personal gmail account which end with "@gmail.com".
OS: 10.11.2

**Comment by Thomas101** [comment]
Hi @xream @androidcn 

Do you have google plus enabled? Did you try to sign in to gmail or inbox?

**Comment by Thomas101** [comment]
I think I've found the issue with this. Could you try downloading version 1.1.2? (https://github.com/Thomas101/wmail/releases/download/v1.1.2/WMail_1_1_2.zip)

**Comment by androidcn** [comment]
@Thomas101 also no effect

**Comment by xream** [comment]
@Thomas101 I have google plus enabled. I use inbox. Version 1.1.2 still no luck.

**Comment by xream** [comment]
@Thomas101 After using VPN service, it works ok. I think this's just the Great Firewall's fault.

**Comment by androidcn** [comment]
i using https proxy to Gmail,it may be GreatFirewall's fault.
Check it out 
Youtube
https://youtu.be/rTsQ7FPrVzI

**Comment by Thomas101** [comment]
Thanks for the video. Can you give this a go to give me some more information.

* Download the version 1.1.3 (https://github.com/Thomas101/wmail/releases).
* Launch the app
* Go to View > Developer Tools. Part of the screen should now be taken up by the developer tools
* Add an account like you did before
* You should see a log line appear on the right hand side. Press the little expand triangles to expand the data structure completely
* Take a screenshot
* If you see anything like access_token, refresh_token or id_token cover those up (to prevent anyone getting unauthorised access to your account) in preview and upload the image for me
* You can close the developer tools by pressing the little cross in the top right corner

I've uploaded what I get when I add an account so you've got an idea of what you're looking for.

Thanks

![screen shot 2016-01-16 at 08 30 14](https://cloud.githubusercontent.com/assets/103586/12371448/c0e1eeb8-bc2b-11e5-853c-bae202d67a9a.png)

**Comment by androidcn** [comment]
<img width="1191" alt="screen shot 2016-01-16 at 5 00 49 pm" src="https://cloud.githubusercontent.com/assets/271715/12371563/bef411b6-bc72-11e5-9853-1ad38c8325bd.png">
Check it out

**Comment by androidcn** [comment]
Airmail unibox etc. app is no problem

**Comment by Thomas101** [comment]
Hi, Sorry for the delay. There's a new pre-release available to [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip) can you see if it works in this version and if not repeat the above steps and upload the screenshot again? Thanks very much!

**Comment by androidcn** [comment]
same

Thomas Beverley <notifications@github.com>于2016年1月21日周四 上午5:17写道：

**Comment by androidcn** [comment]
![screen shot 2016-01-21 at 8 48 17 am](https://cloud.githubusercontent.com/assets/271715/12468127/e1b6133c-c01b-11e5-8edd-6ded838616b4.png)
![screen shot 2016-01-21 at 8 48 35 am](https://cloud.githubusercontent.com/assets/271715/12468128/e1bc6890-c01b-11e5-83d8-bccf200acd8b.png)
![screen shot 2016-01-21 at 8 48 52 am](https://cloud.githubusercontent.com/assets/271715/12468129/e1e25a46-c01b-11e5-987c-8754318d2187.png)

**Comment by Thomas101** [comment]
@androidcn could you copy the text in the line that starts with errorStrin?. I think there's more offscreen

**Comment by androidcn** [comment]
"Error: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 216.58.199.13:443"

**Comment by androidcn** [comment]
errorStack 
"Error: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 216.58.199.13:443 at ClientRequest.<anonymous> (/Applications/WMail.app/Contents/Resources/app/node_modules/node-fetch/index.js:117:11) at emitOne (events.js:77:13) at ClientRequest.emit (events.js:169:7) at TLSSocket.socketErrorListener (_http_client.js:265:9) at emitOne (events.js:77:13) at TLSSocket.emit (events.js:169:7) at emitErrorNT (net.js:1253:8) at doNTCallback2 (node.js:465:9) at process._tickCallback (node.js:379:17)"

**Comment by Thomas101** [comment]
If you go to https://accounts.google.com/o/oauth2/token in your web browser do you see something like `{error: "invalid_request"}` or does your browser come up with an error?

**Comment by androidcn** [comment]
browser 

{
error: "invalid_request"
}

**Comment by Thomas101** [comment]
Are you using a proxy or vpn on your machine?

**Comment by androidcn** [comment]
yep 
proxy

**Comment by androidcn** [comment]
![screen shot 2016-01-21 at 4 40 50 pm](https://cloud.githubusercontent.com/assets/271715/12475409/c4d12a94-c05d-11e5-9781-96707876524b.png)
![screen shot 2016-01-21 at 4 40 56 pm](https://cloud.githubusercontent.com/assets/271715/12475408/c4ce5378-c05d-11e5-9ee0-e0d147529ae0.png)

**Comment by Thomas101** [comment]
Awesome thanks, I'll take a look!

**Comment by Thomas101** [comment]
Hi @androidcn I've tried to reproduce this my end, but I'm not having any luck. The error indicates that the connection timed out. I've tried running my own machine across a proxy and also tried conditioning the network to be very bad, but in both cases it still works. Are you able to share any information with me about the proxy server you're using?

**Comment by Thomas101** [comment]
Hi @androidcn, I've put a build together that I've pre-configured for the proxy server you're using `127.0.0.1:6152` and uploaded it here https://drive.google.com/file/d/0B--sEKXlbUTReUV3TUpfRlR0eVE/view?usp=sharing. Could you download this version and see if that works?

**Comment by androidcn** [comment]
![screen shot 2016-01-24 at 11 45 24 pm](https://cloud.githubusercontent.com/assets/271715/12537219/9133a4f2-c2f4-11e5-8f26-0f857c7a783b.png)

Great!!!!!!!!!!!!!!!!

**Comment by Thomas101** [comment]
Awesome! I know what it is. I'll get that rolling into the next release.

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.5/WMail_1_1_5_osx_prerelease.zip). To setup your proxy you need to tap on the cog in the bottom left-hand side then go to the advanced tab. From here enter your proxy settings and it should work.

**Comment by androidcn** [comment]
Thanks for your great work!!!!
and then i want  notification function for new mail.

**Comment by Thomas101** [comment]
It's in the works. Keep an eye on #35
