### ISSUE TITLE
Spell check not quite working on Mac and Windows

### ISSUE THREAD

**Issue by mfoucher** [Thomas101/wmail#200]
Spell check is still not fully working.  It tags misspelled words, shows suggestions, but doesn't replace the misspelled word with the chosen suggested word.

I have attached an animated gif which shows the action
![islrifczof](https://cloud.githubusercontent.com/assets/20408860/16750366/238410f6-4786-11e6-9f85-8193e8a6626a.gif)

**Comment by Thomas101** [comment]
Hi, thanks for reporting this one. It appears to be working on my end. Could you try a few different cases for me to see if the behaviour is the same?

1.) Have a misspelt word mid sentence like "Here is a trest of spelling" and see that works
2.) Delete your signature and try again to see if that makes a difference.
3.) Go to `View > Developer Tools` and then tap on the console tab. Try to re-correct a spelling suggestion and see if any errors pop up
4.) Finally, which version of windows / osx are you using?

**Comment by mfoucher** [comment]
Will do right away.

One questions: on number 2, do you mean delete my email signature or my
account and re-add it?

On 12 July 2016 at 00:15, Thomas Beverley <notifications@github.com> wrote:

> Hi, thanks for reporting this one. It appears to be working on my end.
> Could you try a few different cases for me to see if the behaviour is the
> same?
>
> 1.) Have a misspelt word mid sentence like "Here is a trest of spelling"
> and see that works
> 2.) Delete your signature and try again to see if that makes a difference.
> 3.) Go to View > Developer Tools and then tap on the console tab. Try to
> re-correct a spelling suggestion and see if any errors pop up
> 4.) Finally, which version of windows / osx are you using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Thomas101/wmail/issues/200#issuecomment-231957186>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATdqHA7VBlrvj9tMVx71MM7OeRrDRdRCks5qUz8pgaJpZM4JJ546>
> .
>



-- 
MICHAEL FOUCHER DIRECTOR OF PRODUCTS
 (250) 590-1800
 mjfoucher
 michael.foucher@rdbrck.com
 rdbrck.com
<https://www.facebook.com/rdbrck>  <https://twitter.com/rdbrck>
<https://www.linkedin.com/company/2859057>

**Comment by Thomas101** [comment]
Just your email signature. You don't have to delete it from your inbox settings, just highlight it all in a new compose window and hit delete before trying again. Thanks!

**Comment by TimNZ** [comment]
Did you come across this module for spell check if typo.js is flaky?

https://github.com/atom/node-spellchecker

**Comment by Thomas101** [comment]
That was my first port of call. Unfortunately I've not been able to get it work as `isMispelled()` never returns correctly (https://github.com/atom/node-spellchecker/issues/49), nor does getting spelling suggestions seem to work. I did have a go at patching the library but even then I had absolutely no success on linux and never got around to even trying on windows.

I was originally using [nodehun](https://github.com/nathanjsweet/nodehun) but it's no longer maintained and I haven't really got the time try and maintain it myself, hence the reason I ended up with typo.js

**Comment by TimNZ** [comment]
Fair enough.  It is the module used by the Atom spell-check plugin, though there are reported issues compiling it.  

https://discuss.atom.io/t/solved-trouble-building-an-alternate-spellchecker-for-spell-check-on-an-amd64-windows-10/24851

**Comment by mfoucher** [comment]
1.) Have a misspelt word mid sentence like "Here is a trest of spelling" and see that works
DONE
2.) Delete your signature and try again to see if that makes a difference.
DONE
3.) Go to View > Developer Tools and then tap on the console tab. Try to re-correct a spelling suggestion and see if any errors pop up
DONE - see attached image
4.) Finally, which version of windows / osx are you using?
Mac OS 10.11.5
Windows 10 Version 1511
![fxhmru70gv](https://cloud.githubusercontent.com/assets/20408860/16890800/e4f476fe-4aa6-11e6-89b2-c16ce91bdc03.gif)

**Comment by Thomas101** [comment]
Weird, I can't seem to reproduce this my end which makes life all the more difficult. Thanks for helping out though! Could you try a couple more things for me?

1.) In between typing and right clicking on the misspelt word do you click away anywhere else, or right click on the misspelt word right away?

2.) Can you try the following? (Sorry there's a few steps)
 * Right click on your account icon and choose inspect
 * Click on the console tab
 * Keeping this window open, right click on a misspelt word so that the menu appears (don't try to correct it though)
 * In the window with the console paste `window.getSelection().getRangeAt(0)` and press enter.
 * Send me a screenshot of what you get. I've attached an example of what you should see
 * 
![screen shot 2016-07-16 at 08 58 28](https://cloud.githubusercontent.com/assets/103586/16893552/b6768604-4b33-11e6-9f89-d0324f791169.png)
Now correct the word by clicking on the correct spelling in the menu and see if any errors appear. I don't think any will though
