### ISSUE TITLE
[OSX] [v1.3.2] Adding custom icon turns icon white

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#202]
When I updated from 1.3.1 to 1.3.2 pre-release, it lost my custom icon.

I uploaded a new image, and it turns the icon white.

I removed the account and re-added (thinking maybe it was a cache thing updating from 1.3.1), but still have the same issue.

I tried multiple JPG images with no luck.

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, it should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)

**Comment by lament** [comment]
Thanks, confirmed fixed!
