### ISSUE TITLE
No icon in bottom panel in kde plasma 5

### ISSUE THREAD

**Issue by rezaxdi** [Thomas101/wmail#203]
Hi,

I'm using kubuntu 16.04 and wmail shows an empty icon in bottom panel (system tray) when minimized/closed.

**Comment by Thomas101** [comment]
Which version of WMail are you using? This could be related to https://github.com/electron/electron/issues/6205

**Comment by Thomas101** [comment]
Hi this is fixed in the latest [pre-release](https://github.com/Thomas101/wmail/releases). Thanks!

**Comment by sollidsnake** [comment]
I installed the prerelease version and the icon is still a blank square to me. I'm also using plasma 5.

**Comment by Tunous** [comment]
I'm on version 2.0.7 with plasma 5.8 and I have the same issue as @sollidsnake mentioned. 

I tried changing icon color but it only changes the color of the rectangle. Somehow it appears as a combination of border and background colors.

**Comment by sollidsnake** [comment]
It's strange. It seems to work on my laptop but not on my desktop. I wasn't
able to isolate the issue except the video card. I'm not sure if it could
be it but are you using nvidia with proprietary drivers?

Em dom, 18 de dez de 2016 11:19, Łukasz Rutkowski <notifications@github.com>
escreveu:

**Comment by Tunous** [comment]
Yes, that's right I'm using the proprietary nvidia drivers. I might try switching them later to see if the issue gets fixed.

**Comment by Tunous** [comment]
I tried it with the Nouveau driver and the issue is still present.

**Comment by cribari** [comment]
I have two notebooks that use KDE, one that runs Manjaro Linux and another one that runs Antergos Linux. I have this problem in the latter but not in the former. Both notebooks have Intel GPU.

**Comment by cribari** [comment]
The problem was solved in Antergos + KDE Plasma 5.9.1 by installing ibappindicator-gtk2, libappindicator-gtk3 and libappindicator-sharp. One of them did the trick.

**Comment by Tunous** [comment]
Can confirm. Installing libappindicator-sharp fixed the issue on Arch Linux with Plasma 5.9.1.
