### ISSUE TITLE
WMail app window doesn't respond to input when tray icon flashes (Linux)

### ISSUE THREAD

**Issue by hotice** [Thomas101/wmail#204]
Ubuntu (w/ Unity) 16.04 64bit: when the tray icon flashes, the WMail window doesn't respond to any input: I can't click on any emails, switch accounts... basically I can't click on anything inside the WMail window. This is especially annoying after adding a new account with a large number of unread emails, because then this behavior lasts for quite some time.

Using the latest WMail 1.3.2 binary.

**Comment by Thomas101** [comment]
I think I've fixed this in c2ac426f8e71b214ff96715b628ecfbe479f8cc9. The clause which checks if the tray icon should be updated wasn't all that optimised which meant the tray would update quite often. This doesn't seem to be too much of a problem on osx, however on ubuntu the update seems to take much longer and I think the cumulation of these updates is what's causing the freeze. Have a go with 1.3.3 once it gets released, if you still experience the problem I'll reopen the issue. Thanks!

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, it should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)

**Comment by hotice** [comment]
It looks like it's fixed. Thank you very much!
