### ISSUE TITLE
[OSX 1.3.2 pre-release] Laggy/memory leak?

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#207]
Hi @Thomas101 , 

I noticed in earlier versions there would be a noticeable lag when trying to move around the app. Everything was slow to catch up when typing. It felt very sluggish.. like the app is running out of memory.

This hasn't been an issue for the last few releases, but it's really noticeable on the 1.3.2 pre-release. I've rebooted a couple times but it's still happening.

It's not as bad as earlier releases, but it seems to have reared its ugly head again.

**Comment by Thomas101** [comment]
Hi, would you say it's only when typing or just in general? If you go into settings, disable spell checking and restart the app does it seen any better?

**Comment by lament** [comment]
I did disable spell checking. And it's not just when typing. I'll go to click on a link and it'll freeze for a good 5 seconds sometimes. :/

In Activity Monitor I see the CPU% spike up to 40% sometimes.

**Comment by Thomas101** [comment]
Ah I wonder if this is related to #204 (are you using linux, or osx?). If you disable the tray icon (Preferences > Show Tray Icon) do you still see this behaviour? If you do still see the behaviour, then how many accounts & unread messages do you have?

**Comment by lament** [comment]
It freezes while scrolling as well.

I'm on OSX 10.11.5. I'm not using the tray icon - just the dock icon. I have 1 Inbox and 1 Gmail account.

**Comment by Thomas101** [comment]
I think I know what this is. Also related to #201. I'll keep you updated as regards a fix. Thanks!

**Comment by lament** [comment]
Thanks @Thomas101!

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, it should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)

**Comment by lament** [comment]
@Thomas101 this was not fixed in 1.3.4 pre-release, btw. :(
