### ISSUE TITLE
Right click & copy URL

### ISSUE THREAD

**Issue by icmp15** [Thomas101/wmail#209]
Hi,
Very useful and an amazing app...thanks for taking time to develop this.

Feature request:
Ability to right click on hypertext in an email and copy the 'target' URL.
Slightly different than feature request #135. To clarify my request, I have attached a screenshot from Chrome, with the pop-up menu upon right 'clicking' hypertext in an email. The option I'm referring to is 'Copy  Link Address'.

Reason:
Before clicking any link, I find it useful to see where it is leading to. By copying the URL, it is possible to use wget/curl to follow the link in shell. Directly clicking the link, opens it up in the default browser - to late for any verification.

Also, for various reasons, I use different browsers for different activities - and don't want the URL in the link to open w/ the default browser. I hope there are others who do the same and thus, will find the feature to copy URL and paste in non-default browser useful.

Ability to copy the URL may also help address issue #135.  

Many thanks.

![screenshot002](https://cloud.githubusercontent.com/assets/10064435/17018688/d67158d4-4f30-11e6-90e6-110a65e4727d.png)

**Comment by Thomas101** [comment]
Hi, this just made it out in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/tag/v1.3.4)
