### ISSUE TITLE
Graphic switching is triggered

### ISSUE THREAD

**Issue by Ming-Tang** [Thomas101/wmail#21]
I have a MacBook Pro with dedicated graphics, and I noticed that at startup or shutdown, graphic switching is triggered, causing screen flicker. This might be a problem with Electron, but I'm not sure.

**Comment by Thomas101** [comment]
Thanks! I'll take a look at this. There is a new version of electron out that I'll be moving across to shortly. Maybe that will fix it!

**Comment by Thomas101** [comment]
Hey, there's pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip), do you still the issue with this version?

**Comment by Ming-Tang** [comment]
The issue with graphic switching has disappeared.
