### ISSUE TITLE
Blank form when I try to run

### ISSUE THREAD

**Issue by fblauer** [Thomas101/wmail#210]
I double click on the executable, and I get a wmail window which is blank. I tried 1.3.1 and 1.3.4. I am running the linux 64 bit version.

**Comment by Thomas101** [comment]
Which Linux distro are you running? Do you have the same issue if you try the 32bit version of WMail?

**Comment by jadenPete** [comment]
I have this issue too

**Comment by jadenPete** [comment]
Running Ubuntu 14.04

**Comment by jadenPete** [comment]
This also happens on the 32 bit version (for me)

**Comment by Thomas101** [comment]
When the window launches is it completely white, or do you see the black bar down the left hand side? Are you able to go to `View > Developer Tools` in the menu and tap on the console tab. Are there any errors there?

**Comment by fblauer** [comment]
I am using Ubuntu/mate V 16.04.01. I tried running the 32 bit version, and it won't load at all. Here is a screenshot of what I see:
![image](https://cloud.githubusercontent.com/assets/1015215/17057325/3eea5648-4fe7-11e6-876c-7efb0c353f7b.png)

**Comment by fblauer** [comment]
I see the black bar on the left hand side. As per the screenshot that I sent, I can't see developer tools - no view menu?

**Comment by Thomas101** [comment]
Okay, can you try the keyboard shortcut (`ctrl+alt+j`) to bring it up?

**Comment by fblauer** [comment]
No, the keyboard shortcut doesn't do anything.

**Comment by fblauer** [comment]
I also tried on Linux mint 17.3 (based on ubuntu 14.04), and I get the same issue (Wmail V 1.3.4, 64 bit version)

**Comment by fblauer** [comment]
I also tried on Windows 10, and I have the same issue.

**Comment by Thomas101** [comment]
I think I've solved this. I've done another release, can you try 1.3.5?

**Comment by fblauer** [comment]
Works for me too! Thanks for the very fast response
