### ISSUE TITLE
[OSX 1.3.4] Left sidebar being cut off

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#211]
Just started happening with 1.3.4 pre-release.

I have to quit and restart a couple times. Resizing the window doesn't help.

![screen shot 2016-07-21 at 10 58 00 pm](https://cloud.githubusercontent.com/assets/186014/17047925/b40c21fa-4f96-11e6-98c2-0821506295fe.png)

edit: figured it out.

I have 2 accounts: Inbox on the top, Gmail on the bottom.

I open the app, and immediately click on the bottom (Gmail) account.  App window snaps and cuts off as in the picture. Can reproduce every time.

**Comment by Thomas101** [comment]
I saw this earlier in when I started work on 1.3.4, updated electron and it seemed to disappear. Obviously it's back :-(. How often does it happen for you?

Rather than restarting the app if you hit cmd+r it should just refresh it which is a little quicker :)

**Comment by chuck-talk-sp** [comment]
I am seeing this on Windows and Linux as well. This happens when I click on anything in a secondary Gmail account (or lower). Does not appear to occur with a single account, only multiples, and only moving to the other account.  CTRL+r refreshes to the primary account, but does not return to the same location/view without the issue.
![1fine](https://cloud.githubusercontent.com/assets/5123508/17079733/a84d796a-50de-11e6-889f-d0c1c5645a36.png)
![2uhoh](https://cloud.githubusercontent.com/assets/5123508/17079736/acd61046-50de-11e6-81de-b976cffe2fc4.png)

**Comment by lament** [comment]
Hmm.. now it's worse than before with 1.3.5, and is now this is happening every time I click on my 2nd account, no matter what. CMD+R reloads the browser - cool - but it's the 2nd account I want to access and when I click it, it happens.

**Comment by Thomas101** [comment]
Do you find that it happens only when switching account?

**Comment by semeon** [comment]
This time I restarted the app, it looks fine. Switching account do not cause it.

**Comment by semeon** [comment]
Shite. It broke right after I sent the comment.
Restarting the app and switching the accounts cause it, but it seems to be not stable.

**Comment by karlgrz** [comment]
Confirm seeing this on ubuntu 16.04 as well, on latest pre-release (1.3.5).

**Comment by samaphp** [comment]
I just want to confirm this issue too, the cut off happened after the top menu disappear, I don't remember what I press on the top then the top menu being hide. Defiantly I hide the top menu not from settings because I saw the option on settings after that and I tried to remove the check and check it again with no luck.
I don't know if this relate to the positioning of the page or not.

Many Thanks

**Comment by Thomas101** [comment]
Looks this is fixed with the latest electron. Keep an eye out for the next pre-release. Thanks everyone

**Comment by Thomas101** [comment]
Hi this is fixed in the latest [pre-release](https://github.com/Thomas101/wmail/releases). Thanks!

**Comment by lament** [comment]
Working for me.. thanks!

**Comment by karlgrz** [comment]
+1 agreed, thanks!

**Comment by lament** [comment]
Spoke too soon.. just switched between accounts and it happened again.

**Comment by Thomas101** [comment]
Oh no! Do you think it happens more or less often?

**Comment by lament** [comment]
Less. Before it was every time. Now it's kind of random. I just leave it now. :/

**Comment by Thomas101** [comment]
When I saw it seemed to be when you switch mailbox. Does it happen anytime for you?

**Comment by lament** [comment]
Yes it only happens when switching mailboxes, but it didn't happen right away after opening wmail like it used to. That's why I thought it was fixed. Only did I switch mailboxes minutes later did it get messed up again.

**Comment by Thomas101** [comment]
Next time it happens could you try this to see if it has any effect?

* Go to View > Developer Tools
* Click the console tab and then paste the following....

```js
document.body.style.position = 'absolute'
setTimeout(() => {
  document.body.style.position = 'fixed'
}, 50)
```

**Comment by karlgrz** [comment]
@Thomas101 good suggestion!

It just happened to me on 1.3.6, and I tried your suggestion. It _almost_ works :-)

It looks like it still over the edge by a few pixels, but pretty much solves the problem for me:

![ss](https://cloud.githubusercontent.com/assets/548140/17623050/bbdc7e1a-6063-11e6-93c9-df26531dd477.png)

**Comment by Thomas101** [comment]
Hmmm weird that it's not quite moved across. What about if you try the following, or a combination of both?

```js
document.querySelector('#app').position = 'fixed'
setTimeout(() => {
    document.querySelector('#app').position = 'absolute'
}, 50)
```

Thanks for keep testing on this. It's so annoying that I don't see the issue :-(

**Comment by SpectralKH** [comment]
I definitely got this in 1.3.6 (https://github.com/Thomas101/wmail/issues/211#issuecomment-234734679)

**Comment by karlgrz** [comment]
Just happened again, and I tried the second suggestion with the same result: looks 97% fixed, but there is a slight cutoff on the left side of my avatars still.

**Comment by Thomas101** [comment]
Thanks @karlgrz. Did you do anything when it cut off (e.g. change account, change window size etc?)

**Comment by SpectralKH** [comment]
@Thomas101 Appears from time to time on me. I notice it first when I change accounts, I think it's always been appearing on account #1.

**Comment by karlgrz** [comment]
@Thomas101 this seems to manifest itself when I'm changing from account 1 to either 2 or 3. Seems to happen at different times, but it seems to happen when one of those mailboxes is loading messages.

**Comment by Thomas101** [comment]
Thanks everyone for your feedback. I've had another go at seeing if I can force the window to reposition itself and this will be out in the next release. Thanks!

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)
