### ISSUE TITLE
No icon under Ubuntu 16.04 - Unity

### ISSUE THREAD

**Issue by brunosimioni** [Thomas101/wmail#214]
After decompress the package and run the binary file, no icon shown under Unity bar.
![screenshot from 2016-07-25 10-19-57](https://cloud.githubusercontent.com/assets/1768004/17102761/76e75d5e-5251-11e6-8e29-1e47b56668d3.png)

**Comment by Thomas101** [comment]
This is related to #203. You can continue tracking progress on a fix from there
