### ISSUE TITLE
Disable smooth scrolling

### ISSUE THREAD

**Issue by HanKruiger** [Thomas101/wmail#218]
In Chrome/Chromium or Firefox, I can disable smooth scrolling. I would love to be able to do this in WMail, because I find smooth scrolling incredibly distracting. (Especially when using the scroll-wheel on my mouse.)

**Comment by DaveInKentucky** [comment]
Another vote from me.

**Comment by Thomas101** [comment]
There's some talk around this [in this issue](https://github.com/electron/electron/issues/5460). I'll take a look to see if I can turn it off

**Comment by Thomas101** [comment]
Waiting for support from electron on this. Will keep an eye open and add it to wmail

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!

**Comment by HanKruiger** [comment]
Hi Thomas, thanks a bunch for trying to support this.
However, **it doesn't work for me** on ArchLinux.
I installed the 2.0.3 prerelease, enabled the setting, restarted wmail, but still scrolling was smooth.
Would some log file be helpful? Or output of verbose mode? Let me know.

**Comment by Thomas101** [comment]
I'll take another look to see what's going in. Thanks!

**Comment by Thomas101** [comment]
Hi, would you be able to give this another try in [2.0.4](thomas101.github.io/wmail/download?v=2.0.4)?

**Comment by HanKruiger** [comment]
Sorry, no it's not working in 2.0.4 either.

Just to be clear, I'm referring to this flag: `chrome://flags/#smooth-scrolling`
The default for Chrome/Chromium is to have it enabled, but I would like to be able to _disable_ it.

**Comment by Thomas101** [comment]
Third time luck I'm hoping...

**Comment by Thomas101** [comment]
I think this should be fixed in the latest prerelease which you download [here](https://thomas101.github.io/wmail/download?v=2.0.5). I've checked it on ubuntu and it works so it should be the same for ArchLinux

**Comment by HanKruiger** [comment]
It works. Cheers!

**Comment by Thomas101** [comment]
Yay! Third time lucky then :)
