### ISSUE TITLE
restore left sidebar

### ISSUE THREAD

**Issue by dnlipson** [Thomas101/wmail#219]
I clicked the settings item to hide the left sidebar. But I can't figure out how to restore it. Is there a keyboard shortcut? How else can I restore it? I am using Windows 10 on a laptop.

**Comment by andreiluca** [comment]
Happened to me too, you can access the settings by pressing ctrl+,

**Comment by WUUUUTTT** [comment]
Do you know how to fix this on Linux?  Specifically Arch.  CNTL+  Doesn't seem to work.

**Comment by Thomas101** [comment]
I think you can also use `ctrl+win+s` to toggle it on windows

**Comment by dnlipson** [comment]
Control-Windows-Comma is the combination that finally worked for me. Thanks
for the tips, everyone!

**Comment by semeon** [comment]
My issue might be related, half of the left bar is missing. See the image.

1.3.5 for Mac OS. OS X 10.11.6.

![wmail](https://cloud.githubusercontent.com/assets/4072363/17200435/16fc6976-543a-11e6-8f54-6612b3d6d547.png)

**Comment by massiliattak** [comment]
> semeon commented an hour ago:
My issue might be related, half of the left bar is missing. See the image.
1.3.5 for Mac OS. OS X 10.11.6.

Same here. 1.3.5 on Windows 10.

**Comment by amig** [comment]
I have the same issue (Ubuntu 14.04)

**Comment by Thomas101** [comment]
@semeon this is a separate issue tracking at #211
