### ISSUE TITLE
High energy impact

### ISSUE THREAD

**Issue by Ming-Tang** [Thomas101/wmail#22]
I have two accounts active, and WMail is having 10 energy impact constantly.

WMail has 4 child processes, and two of them have 5 energy impact, another two have 0. In the WMail with 5 energy impact, the memory usage is slowly increasing (about 0.1MB/3 sec), and Unix System Calls and Mach System Calls are also increasing.

Here is the process dump of the process with 5 energy impact: https://gist.github.com/Ming-Tang/f1ebb0ccd2c2d47a7147

**Comment by Thomas101** [comment]
Could be a memory leak with my fetching of the unread count, or could be a leak with inbox itself. I'll fire up a new electron app with just inbox and see if I get the same results.

**Comment by Thomas101** [comment]
this appears to be fixed after using react dom in 1.1.4 Will be fixed in the next release thanks!

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip). Thanks very much for your help!

**Comment by Ming-Tang** [comment]
I downloaded the pre-release version and the problem is still there. The energy impact and increase in memory is still the same.

**Comment by Thomas101** [comment]
Do you mind me asking how many accounts you've added and if they're Inbox or gmail accounts?

**Comment by Ming-Tang** [comment]
I have 2 accounts, and they are both Inbox accounts.

**Comment by Thomas101** [comment]
This looks to be an issue with electron and chromium. I'll keep tracking it
