### ISSUE TITLE
Low Res Windows Tray Icon

### ISSUE THREAD

**Issue by akanimh** [Thomas101/wmail#220]
Is it possible to include a higher resolution Windows (10) version tray icon in the next release? As you can see here it is not very smooth:

![image](https://cloud.githubusercontent.com/assets/3221476/17159167/2ddf7100-5350-11e6-9ae0-87bc248c574e.png)

Thanks!

**Comment by jadenPete** [comment]
I don't think it's an issue with the resolution, I think it needs to be anti-aliased.

**Comment by Thomas101** [comment]
The icon is generated in a html5 canvas. OSX has support for multiple dpi's which means it looks alright there. I'll take a look on windows to see if I can supply a larger image and if that looks any better.

**Comment by clrg** [comment]
The Window icon looks bad as well.

![2016-08-15](https://cloud.githubusercontent.com/assets/68176/17697930/d0125bd0-63af-11e6-9428-891109b090b7.png)

**Comment by clrg** [comment]
Regarding:

> I don't think it's an issue with the resolution, I think it needs to be anti-aliased.

No. It needs to be likely shipped as a .ico file with appropriately downscaled versions of the icon. Believe it or not, the system tray icon is anti-aliased already. It's just the icon doesn't scale down so well due to the width of the lines. Try downscaling the icon in GIMP and you'll get a similar result.

Basically the icon needs redrawing for a tiny resolution (thicker lines etc) which is where the .ico format comes in because it bundles multiple sizes of icon.

**Comment by clrg** [comment]
There is a suitable icon hidden in there somewhere though, as per this screenshot from the task manager:

![2016-08-16 2](https://cloud.githubusercontent.com/assets/68176/17702965/e8e6522a-63c7-11e6-8cfb-19187edf0b4d.png)

**Comment by clrg** [comment]
There is a suitable icon hidden in there somewhere, as per this screenshot from the task manager:

![2016-08-16 3](https://cloud.githubusercontent.com/assets/68176/17703043/305a1bdc-63c8-11e6-9636-9a83b8a6fb2c.png)

Not sure why there is 1 small smudgy icon and 4 better ones amongst 5 processes though.

**Comment by Thomas101** [comment]
I think the packager just "magically" creates the windows icon file... Obviously it needs pointing in the right direction. I'll look into it to see if I can provide an icon file with all the relevant sizes

**Comment by sakshamgoyal01** [comment]
is this fixed in 1.6.3?

**Comment by Thomas101** [comment]
It's fixed, but not yet released. It will be released in the 1.3.7 version

**Comment by sakshamgoyal01** [comment]
when will it be released?

**Comment by Thomas101** [comment]
Once I've completed the remaining items in the [1.3.7](https://github.com/Thomas101/wmail/milestone/18) milestone :-)

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)
