### ISSUE TITLE
System tray icon gets lost with my selected windows 10 theme colour.

### ISSUE THREAD

**Issue by abdulrahimallana** [Thomas101/wmail#223]
<img width="120" alt="wmail_systray" src="https://cloud.githubusercontent.com/assets/247078/17176911/26b0a592-540f-11e6-8b32-92bbcf377482.png">

**Comment by Thomas101** [comment]
Hi, you can change the colour of the icon when read/unread in the settinga screen to make it match more closely with your theme :)

**Comment by abdulrahimallana** [comment]
Didn't realise that. Thanks. Although, I use the "automatic colour" option when it comes to my themes that picks a colour based on the current background image. The indicator may work better with a solid fill as that would provide a constant contrast. Just a thought. Your suggestion definitely helps me solve the problem. Love the app :)

**Comment by Thomas101** [comment]
There's already an issue for adding a background (#217). You can track progress for that there.
