### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by rhansen** [Thomas101/wmail#224]
It would be great if this was packaged as a .deb and made available to Ubuntu users via a [PPA](https://help.launchpad.net/Packaging/PPA).

**Comment by jadenPete** [comment]
Now this is even better than just a deb! I also think there should be separate PPA's for pre-releases and releases.

**Comment by sakshamgoyal01** [comment]
try using wine:
https://www.winehq.org/
it _may_ work, but i'm not sure

**Comment by MarshallOfSound** [comment]
@Thomas101 Once you have working deb files you should check out https://bintray.com/

Free PPA hosting 👍

**Comment by mike-mccormick** [comment]
Just adding another +1 for a PPA, Wmail is pretty much everything I ever wanted in a gmail/inbox client, would be great to have it delivered by a PPA.

**Comment by silvadev** [comment]
The PPA exists in https://launchpad.net/~atareao/+archive/ubuntu/wmail

**Comment by nsrosenqvist** [comment]
Worth reopening since the PPA is not being updated?

**Comment by Thomas101** [comment]
Yeah I think so. I'll try and get around to putting some builds up myself...
