### ISSUE TITLE
Printing PDF not working

### ISSUE THREAD

**Issue by g4challenge** [Thomas101/wmail#23]
when printing a document, it reloads the app, instead of either loading it in a browser or  using the native print dialog.

Relates to issue #16

**Comment by Thomas101** [comment]
Printing a page works using window.print(). I think google might be using some custom api here as printing doesn't work in firefox and crashes safari. Any help would be appreciated

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.6/WMail_1_1_6_osx_prerelease.zip). Thanks very much for your help!

**Comment by lament** [comment]
HiThomas,

I'm on 1.1.7 and can't print PDFs in Inbox. Clicking on the Print icon does nothing. 

Is this working for you?

**Comment by Thomas101** [comment]
Hmmm it was working, but clearly something's gone wrong. I'll take another look

**Comment by Thomas101** [comment]
Looks like gmail opens pdfs differently to other attachments. I've managed to get it to open the pdf in the default browser, which is what pressing print normally does anyway.
