### ISSUE TITLE
no spellcheck on Ubuntu 14.04.4 

### ISSUE THREAD

**Issue by MInner** [Thomas101/wmail#231]
Great app, thank you, Thomas!

I'm using wmail 1.3.1 on Ubuntu 14.04.4.

The only issue I'm facing is that spellcheck doesn't work at all, even though it is turned on (in app settings) and there're no error messages is Developer Tools console :(

What can I do to help you figure out the issue? Right click is not working at all too (just, nothing happens if I do a right click)

(off topic: I accidentally toggled full screen, could you please tell me, how do I leave it? :) )

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest pre-release which you can download from the [releases page](https://github.com/Thomas101/wmail/releases)
