### ISSUE TITLE
Gnome hide top menu when click hide sidebar

### ISSUE THREAD

**Issue by samaphp** [Thomas101/wmail#234]
WMail Version 1.3.5
Ubuntu 16.04
Gnome Flashback Metacity

In Gnome when I click on (toggle side bar) from top view menu it's make the sidebar hide **and also the top hide** :( (in Unity there is no issue because Unity handle the menu on the topbar by default, but Unity top menu just show in full screen mode)

I tried to switch-off and switch-on `Show App Menu` from Settings>General. but it's on by default and after I change it there is no affect.

I checked `~/.local/share/wmail/settings_db.json` manually and I saw there was `showAppMenu` variable with `true` value.

Also I tried to switch-off `Show App Menu` and `Show Show sidebar` and close settings window. Then I checked `~/.local/share/wmail/settings_db.json` manually and I saw there was `showAppMenu` variable with `false` value and `sidebarEnabled` with `false`. I tried to change them manually by typing `true` then I saved the file and Close and kill all WMail app threads and open it again and I saw the sidebar is enabled but the top menu is still hidden :(
Many Thanks.

**Comment by Thomas101** [comment]
6c136c01275b3a78727d9fcd7a9b65494b287acd and d2706b03c4adc29eeec96ab9af39a3255ffeb0b7 fix this

**Comment by Thomas101** [comment]
Hi this is fixed in the latest [pre-release](https://github.com/Thomas101/wmail/releases). Thanks!
