### ISSUE TITLE
Unread badge on Windows taskbar?

### ISSUE THREAD

**Issue by Cantello** [Thomas101/wmail#235]
I was using WMail on OSX and unread badges were working fine but now I had to switch to Windows (10) and there is no unread badge visible on the taskbar, even though the option is enabled and the badge is visible in the app's sidebar.

Is this a limitation within Windows?

**Comment by Thomas101** [comment]
It should be within the taskbar. Sometimes windows hides some of the tray icons to save space. Have you checked here?

**Comment by Cantello** [comment]
Maybe I misunderstood it completely, isn't the unread badge supposed to be **on** the taskbar icon? I do have the traybar icon but an overlaying badge on the **task**bar icon would be terrific.

Maybe I was spoiled by too many years with a Mac... ;-)

====

I do have this badge but obviously only visible when WMail is open:
![2016-08-05 09_31_44-wmail](https://cloud.githubusercontent.com/assets/594700/17429566/9a85b39a-5aef-11e6-8f0c-97efae0b27ae.png)

And I do have this traybar icon (which is very hard to decipher with the default Win10 theme):
![2016-08-05 09_32_17-](https://cloud.githubusercontent.com/assets/594700/17429580/b325591e-5aef-11e6-98ec-dff36653d064.png)

What I was looking for was a badge or some other kind of indication here:
![2016-08-05 09_32_54-](https://cloud.githubusercontent.com/assets/594700/17429592/c59d9430-5aef-11e6-8f8f-d7158fbf5183.png)

**Comment by Thomas101** [comment]
Ahh, I follow you now. Sorry my mistake. WMail doesn't support adding the unread badge in the taskbar at the moment. However a quick google reveals that it is possible (https://github.com/electron/electron/issues/3148) so I'll take a look to see if I can get it working :-)

**Comment by Cantello** [comment]
Great, thanks for considering it!

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)

**Comment by Cantello** [comment]
Thanks, workls great here! :-)
