### ISSUE TITLE
[Windows] Can't get side bar back 

### ISSUE THREAD

**Issue by hebroin** [Thomas101/wmail#238]
WMail version 1.3.1
Windows Client 

I can't find how to get the side bar back after hiding it in the settings.
Also, where is the config file? I tried reinstalling the app, but the side bar is still there. Don't clear local settings on uninstall, maybe?

**Comment by Thomas101** [comment]
Hi you can bring the menu back by using ctrl+s or by going to view > toggle sidemenu

**Comment by hebroin** [comment]
ctrl+s doesn't work, does nothing.
I don't see the top menu so I can't go to view either.

Does alt suppose to bring the top menu as other windows app?

**Comment by Thomas101** [comment]
Yeah I get the same behaviour. To toggle this manually, you could change/delete the settings file. This is under C:\Users\YourName\AppData\Local\wmail\wmail\settings_db.json

**Comment by hebroin** [comment]
Changing the setting in the file worked.
The file is actually named main_proc_db.json thought.

Thank you for your help and for that software. It's nice when people take
the time to do what big corporations don't take the time to!

**Comment by Thomas101** [comment]
Hi this is fixed in the latest [pre-release](https://github.com/Thomas101/wmail/releases). Thanks!

**Comment by Cantello** [comment]
Have the same problem now after upgrading to the latest pre-release. Ctrl-S does not work and enabling the sidebar in both main_proc_db.json or settings_db.json did nothing.
Can I see somewhere which version I am using without having the menu bar available?

**Comment by Thomas101** [comment]
Try `Ctrl+alt+S` to bring it back

**Comment by Cantello** [comment]
Thanks, found this out as well, hence deleted the post. :-)
