### ISSUE TITLE
Support opening email directly from Windows 10 notification

### ISSUE THREAD

**Issue by andrew-dc** [Thomas101/wmail#239]
It'd be great to have to click the Windows 10 notification for an email and go directly to the email, rather than just open Wmail up.

**Comment by aoberoi** [comment]
I'd like to add that this isn't just true for Windows 10 notifications. I'd like the same behavior for OS X notifications too.

**Comment by Thomas101** [comment]
Something I've not quite got around to yet. This is a duplicate of #171. I'm going to close this one up, but you can continue tracking it from there. Thanks!
