### ISSUE TITLE
That icon, can I help make it nicer?

### ISSUE THREAD

**Issue by LightStormVisuals** [Thomas101/wmail#24]
Love the wrapper bruh, but i was thinking maybe the app icon could be a little nicer. I'm a graphic designer so i'm used to doing this kind of thang.

my email is alexander.onabule@gmail.com if you wanna talk about it... no money involved or anything, just want to help a brother out.

**Comment by Thomas101** [comment]
Yes! I'm a programmer and was forced to use keynote (shame, shame) to make the icon. I'll drop you an email!
