### ISSUE TITLE
[OSX 10.11.6; Wmail v1.3.6 pre-release] Inbox counts not syncing up

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#242]
Hi Thomas,

With this new version, the inbox counts aren't syncing up anymore. Gmail shows 6, Wmail left sidebar shows 7 and dock shows 7. Doing a CMD+R doesn't sync them up either.

![screen shot 2016-08-11 at 9 24 03 am](https://cloud.githubusercontent.com/assets/186014/17596300/a196f9cc-5fa5-11e6-8d68-02dcea940b52.png)

**Comment by Thomas101** [comment]
If you mark one as read/get a new email does it change? Is it stuck on 7 or does it change at all?

**Comment by lament** [comment]
It finally changed, but maybe it was just slow to sync? Took more than 10 minutes at least.

**Comment by Thomas101** [comment]
I've just taken a look at the Google developer console and there was a big spike in errors earlier on, so maybe there's something not quite right Google's end. I'm going to close the issue for now, but you notice it continues or it starts doing it again let me know and I'll reopen it
