### ISSUE TITLE
Yubico Security Key two factor authentication issue

### ISSUE THREAD

**Issue by laroucheyouth** [Thomas101/wmail#243]
Windows 10
1.3.6

I use two factor authentication with my google accounts. I have a yubico security key that I use as a second factor. Gave me an error in red when the page loaded to insert the key.

I used the google authenticator app as an alternative second factor. That worked fine.

**Comment by deeplypuzzled** [comment]
Me too. Nice to have. Google Authenticator worked instead.

**Comment by Thomas101** [comment]
WMail uses the standard authentication path that Google provides. Can you give me any information about the error?

**Comment by laroucheyouth** [comment]
this is the issue: https://github.com/electron/electron/issues/3226

-Adam

**Comment by Thomas101** [comment]
Nice find! I think judging by the discussion an inactivity around it, it's probably quite a bit of work. Especially as it will need separate builds for each platform. We're you able to sign in using a different method like @deeplypuzzled?

**Comment by laroucheyouth** [comment]
Yes. You can select any one of the other methods. They should work.

**Comment by Thomas101** [comment]
Thats good. What I'll so is add some information about this into the FAQs as I think it's too much of a big task to add it into WMail then close this off. Thanks

**Comment by laroucheyouth** [comment]
Yeah. This is an electron platform issue.

**Comment by Thomas101** [comment]
Updated docs. Thanks for reporting though!
