### ISSUE TITLE
high dpi monitor issue?

### ISSUE THREAD

**Issue by laroucheyouth** [Thomas101/wmail#244]
windows 10
1.3.6

Please see the edges of the screenshot. When I resize, the right edge doesn't come all the way to the edge, and the left side falls off the screen.

![image](https://cloud.githubusercontent.com/assets/1181112/17611561/787045fa-6016-11e6-937b-be5efc85f44c.png)

I use a 4k high dpi display.

**Comment by Thomas101** [comment]
Hi,

This is definitely related to #211. I haven't seen it happen on resize before though. If you switch accounts does that have any effect?

**Comment by laroucheyouth** [comment]
No. I had to restart the app. Now its back to normal.
