### ISSUE TITLE
Feature Suggestion: Automatic BCC?

### ISSUE THREAD

**Issue by jcappelmann** [Thomas101/wmail#245]
I know there are browser plugins that can do this.  I like to bcc a CRM on my outbound emails.  Just a suggestion.  Thanks.

**Comment by Thomas101** [comment]
Hi, I've added the ability to inject custom CSS and JS into the gmail & inbox window in the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/v1.3.8). This  is probably going to be the best way to achieve this :)
