### ISSUE TITLE
Polishing feature request: A nicer looking icon :)

### ISSUE THREAD

**Issue by laurynas-karvelis** [Thomas101/wmail#246]
OSX El Capitan, most recent WMail.
I would be so cool to see on the Docker a better/nicer looking WMail icon :).

**Comment by Thomas101** [comment]
I'm a software developer by trade and my graphic design skills are... basic.

So if you have any suggestions I'd love to see them :-)

**Comment by clrg** [comment]
It's not just OS X that has polish issues with the icons.

Here's some eye sores on Windows 10:

![2016-08-15 1](https://cloud.githubusercontent.com/assets/68176/17694949/3daa98ae-639e-11e6-8971-344b84898ef4.png)
![2016-08-15](https://cloud.githubusercontent.com/assets/68176/17694950/3de2cc74-639e-11e6-9848-732da628524d.png)

**Comment by Thomas101** [comment]
Ah sorry, I thought you were talking about the app icon. As regards the windows 10 bits there is an  issue already open for this #220.

**Comment by laurynas-karvelis** [comment]
The issue reported by @Thomas101 is indeed another one :).

I asked a colleague of mine whether he'd like to try creating a neat app icon for this app, he showed mild interest, but not sure he'd be actually willing to. I was wondering if guys from dribbble or behance would come to help? Worth exploring this option.
