### ISSUE TITLE
CMD + F (Find)

### ISSUE THREAD

**Issue by solepixel** [Thomas101/wmail#247]
Thank you so much for this integration with Gmail! Wanted to mention something I noticed. There doesn't appear to be a "CMD+F" Find (Find on Page) feature. Pretty standard browser feature, would be nice to still have that in WMail.

* WMail Version: 1.3.1
* Operating System: Mac OSX 10.11.5

Thank you!

**Comment by Thomas101** [comment]
Hi, if you give the latest [prerelease](https://github.com/Thomas101/wmail/releases) a go, cmd+f is there :-)
