### ISSUE TITLE
feature request: changes in 2-pane view

### ISSUE THREAD

**Issue by knireis** [Thomas101/wmail#249]
I use the 'labs' option to display the preview of the mail (2-pane window). There  is some space on the right reserved for 'circles'. Is it possible to hide that and make this space available to the preview of the email?
Second request is an option to hide the email subject in the other pane (the pane with the email list).

See screenshot:
![wmail](https://cloud.githubusercontent.com/assets/2702064/17765384/caa1a832-6525-11e6-91fe-76a305f5d266.png)

**Comment by solepixel** [comment]
For the "Circles" item, I would recommend focusing something more along the lines of this feature request: #273 (Custom CSS). This will allow for much more customization without the need of the developer.

**Comment by Thomas101** [comment]
Hi, I've added the ability to inject custom CSS and JS into the gmail & inbox window in the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/v1.3.8). This  is probably going to be the best way to achieve this :)
