### ISSUE TITLE
Blank account approval popup

### ISSUE THREAD

**Issue by warp4** [Thomas101/wmail#250]
There's no visable text on the accountapproval popup.
Only by moving the mousecursor blindly and clicking somewhere on the lower right side, one can add a mailaccount

WMail 1.3.6
Linux Mint 17.3, Linux Mint 17.2 Cinnamon, and on Linux Mint 17.3 Mate. All 64bit

**Comment by Thomas101** [comment]
Thanks! I'm going to merge this into #259, you can continue to track changes from there
