### ISSUE TITLE
Add a small gap underneath of window buttons in OS X

### ISSUE THREAD

**Issue by honsiorovskyi** [Thomas101/wmail#251]
Currently in both 1.3.1 and 1.3.6 the titlebar of the program in OS X 10.11 looks like this:

![screen shot 2016-08-19 at 14 09 45](https://cloud.githubusercontent.com/assets/2880417/17809538/9e253948-6617-11e6-99b3-8f3faeb1aee6.png)

With the custom logos it's even worse: they overlap. I propose to add a small gap (in terms of CSS pixels — 10-15px) between the window buttons and the logo to make the header look prettier.

**Comment by workcrm** [comment]
Same here. It's a small cosmetic issue, but...

<img width="227" alt="captura de tela 2016-08-19 as 11 49 30" src="https://cloud.githubusercontent.com/assets/16375988/17813766/00a5f4d2-6603-11e6-836e-e344aca5855a.png">

Would be nice to have it fixed!

Anyway... it's an awesome job and made my life a lot easier!

**Comment by trailofdad** [comment]
Has this been fixed? I can't recreate this issue. I'm running OSX 10.11.2 and 1.3.1 of the client

**Comment by workcrm** [comment]
Not really. I'm using 1.3.6 pre

**Comment by solepixel** [comment]
This is a non-issue for those using multiple accounts. Please do not change the window format when multiple accounts are setup. The window controls fit neatly in the sidebar and optimize the maximum space usage for Gmail. See: 

<img width="223" alt="screen shot 2016-08-28 at 9 33 05 pm" src="https://cloud.githubusercontent.com/assets/882391/18039296/229850ec-6d67-11e6-8886-f6be17208b3a.png">

**Comment by Thomas101** [comment]
I will take a look at this. Not sure how resiliently I can patch the gmail UI. Every time Google does a release they normally jiggle their stylesheets around. In the meantime if you fancy having a go yourself the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/v1.3.8) lets you add your own custom CSS and JS into the gmail window.

@solepixel for multiple accounts, it's not moving anywhere ;-)

**Comment by Thomas101** [comment]
I've just added this in 4215f46ab011d268a0c082a476af720fd41bff1f

If you want to try it out early you can with 1.3.8! Here's how
1.) Open Settings
2.) Go to accounts
3.) Click on Custom CSS
4.) Enter the following...
```css
[href="#inbox"][data-ved]>* {
    max-height:33px;
    margin-top: 22px;
}
[jsaction="global.toggle_main_menu"] {
    margin-top: 5px;
}
[jsaction="global.toggle_main_menu"] ~ [data-action-data] {
    margin-top: 21px;
}
```

This wont change when you toggle the sidebar on and off. 1.3.9 will handle all this automatically :)

**Comment by Thomas101** [comment]
Hi this has been added in the latest [prerelease](https://github.com/Thomas101/wmail/releases). Thanks!

**Comment by honsiorovskyi** [comment]
Hi @Thomas101, thanks a lot! Works amazingly with the default logo. But with the custom logos there's still an issue:

![screen shot 2016-09-21 at 13 57 17](https://cloud.githubusercontent.com/assets/2880417/18710972/1f57f140-8008-11e6-87bb-3d6d111348d6.png)

The problem is that Google allows to upload images up to 60px in height. Basically, for our logo I used a small hack in *Custom CSS*  to move it a bit upwards (since our our image could be cropped) but I'm not sure about other logos (for instance, @workcrm's logo might not be fixed like this). Here's the hack I used:

```css
[href="#inbox"][data-ved]>* {
    background-position-y: -13px;
    background-size: cover !important;
    height: 32px;
}
```

Maybe instead there could be a possibility to increase the size of the margin which I marked as **a** on the screenshot (or just the top one)? That will allow people to have full 60px-height images. But as a drawback it will also take some screen space :(

**Comment by Thomas101** [comment]
I was hoping the `max-height:33px;` was going to bring the size down a little bit. I'll take another look

**Comment by honsiorovskyi** [comment]
Maybe you might need to add `!important` to it, because for the `span` which contains the background they have inline styles, without `!important` they wouldn't be overridden, I suppose.

**Comment by Thomas101** [comment]
That would be why. *Hits self*. Thanks, I've added that in!

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!
