### ISSUE TITLE
Zoom function stopping working after hyperlink is added. 

### ISSUE THREAD

**Issue by mjwhaley** [Thomas101/wmail#257]
OS - Linux Ubuntu 16.04 LTS
Version - 1.3.6 prerelease

I'm running Ubuntu on a Ultra HD screen and thus need to zoom the UI etc on wmail to make the text easier to read etc. But when composing a email in full screen mode the zoom stops functioning after I add a hyperlink. It seems to be the case that the pop up dialog of the hyperlink creation tool kills the zoom and then it can't be used until you restart the application again.

**Comment by Thomas101** [comment]
This looks like an upstream issue from electron. I've opened an issue in their repo... (https://github.com/electron/electron/issues/6958). I'll keep tracking this. In the meantime I've found a way around it

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)
