### ISSUE TITLE
Blank pages on Linux (xubuntu 14.04)

### ISSUE THREAD

**Issue by juanminino** [Thomas101/wmail#259]
Thanks for raising an issue / requesting a feature! Make sure you take a quick look at the wiki article before continuing (https://github.com/Thomas101/wmail/wiki/Raising-Issues-&-Features).

Please provide the following info when raising a new issue...

* Which version of WMail are you using? [e.g. 1.3.1]

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

**Comment by juanminino** [comment]
(sorry for my poor english)
1-When click view > reload , window turns in a blank page (need restart wmail)
(Al dar click en view > reload aparece una página en blanco y se hace necesario reiniciar el programa)
2- When add first account (gmail) fist time the approval window turns on blank page
Al agregar la primera cuenta, en la ventana de aprobación aparece página en blanco
3-Wmail freezes when I add a new account (gmail) (need restart wmail)
Al agregar una nueva cuenta el programa se detiene y hay que reiniciarlo

**Comment by axllent** [comment]
I have this same problem on Ubuntu 10.04, Wmail 1.3.6

After any login I simply get a blank page until I restart the application, meaning I cannot get past the 2-step verification (restarting the app brings me back to the login screen). As @juanminino said, if we refresh the view (View -> Reload) the entire screen goes "blank".

**Comment by Thomas101** [comment]
Do you know if you're using a proxy server? If you try version 1.3.1 do you still see it there?

**Comment by juanminino** [comment]
Thanks for reply 
No proxy
I'm using wmail 1.3.1

Today I tried wmail 1.3.6: 
1-wmail 1.3.6 is too slow 
2-view> reload (just blank page with empty gray bar in left side without icons) 
3-when add new account need to restart wmail for enter in the new account 
4-when return to 1.3.1 no accounts (the program resets) "Add your first mailbox" message

¡Gracias por contestar y por desarrollar esta ingeniosa app!, 
-Los puntos mencionados por mi ayer son basados en mi uso de wmail 1.3.1 
-No estoy usando proxy.

Hoy probé el wmail 1.3.6
1-1.3.6 es muy lento (muy pesado) sobre todo al iniciar
2-en 1.3.6 al hacer click en view> reload obtengo una página en blanco con la barra gris derecha vacía (sin íconos)
3- cuando  agrego una nueva cuenta en 1.3.6 las demás cuentas funcionan pero para poder acceder a la nueva cuenta agregada, es necesario reiniciar wmail
4-cuando cerré 1.3.6 y volví a abrir 1.3.1 mis cuentas no estaban.... mensaje: "Add your first mailbox"

Gracias de nuevo

Una sugerencia para un futuro es agregar la opción, de elegir el usuario de chrome con que se abrirán los archivos adjuntos de cada mailbox (por ej al abrir una foto recibida en "cuenta 1"  en wmail, elegir abrir con cuenta chrome "juanminino@gmail.com", mientras al abrir una foto o archivo cualquiera recibido en "cuenta 2" de wmail, esta se abra con chrome pero con el usuario"juanmininowork@gmail.com"....

**Comment by axllent** [comment]
@Thomas101 I can confirm that 1.3.1 (which has the popup authentication window) works fine, including 2-factor authentication. No proxy here.

Sometimes however (after authentication) I still get a grey screen (on 1.3.1) when the app is supposed to load the mailbox (see screenshot). Restarting the app fixes it, but at least it is authenticated.

![screenshot](https://cloud.githubusercontent.com/assets/1463435/17986972/8305846a-6b71-11e6-9e78-4f6bcec9af60.png)

**Comment by Thomas101** [comment]
@juanminino how much RAM does your computer have?

@axllent thanks for checking with 1.3.1. If you re-try with 1.3.6 and when you launch the app go to View>Developer Tools and press on the console tab, do you see any errors?

**Comment by axllent** [comment]
No sorry, no errors (just an info message "Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools") .

I even deleted my settings (`~/.local/share/wmail` & `~/.config/wmail/`) and tried again (with 1.3.6) but I cannot get past the second screen (2-step authentication) because the screen is simply blank. 

![screenshot from 2016-08-27 13-35-13](https://cloud.githubusercontent.com/assets/1463435/18024330/af9061a4-6c5b-11e6-8e2d-4d62f0637ab4.png)

**Comment by Thomas101** [comment]
Could you try the following? I've put a build of the app on Google Drive that opens the developer tools for the authentication window. Could you download it from [here](https://drive.google.com/file/d/0B--sEKXlbUTRQkVtaHdhZ2p5VXM/view?usp=sharing), then

* Open the app
* Add a mailbox
* Wait a few moments until the developer tools open
* Press the `Network` tab
* Press `Ctrl+R` to reload the window
* Send me a screenshot of the output

Here's an example of what I got out

![screen shot 2016-08-27 at 12 50 19](https://cloud.githubusercontent.com/assets/103586/18027178/daed4f3a-6c54-11e6-9f0d-8aaf3d44a171.png)


Thanks!

**Comment by axllent** [comment]
@Thomas101 I'll gladly do that for you, however would you mind please providing a 64-bit linux version?

**Comment by Thomas101** [comment]
Sure, the 64-bit version is [here](https://drive.google.com/open?id=0B--sEKXlbUTRYWxmQ0tEalpjLVU)

**Comment by axllent** [comment]
Thanks. OK, so I get the same output as you for the login screen. 

![screen1](https://cloud.githubusercontent.com/assets/1463435/18032878/460db3ae-6d68-11e6-9015-e4e7b0f2b56c.png)

I then selected "preserve log" and proceeded to log in (so you could see the requests that follow). You'll note the blank code authentication page that appears on the left.

![screen2](https://cloud.githubusercontent.com/assets/1463435/18032886/724bd2b6-6d68-11e6-82c9-30cafb9e1678.png)

The ironic thing is that the first time I tried it was blank, the second I actually got the verification page, and the third, fourth and fifth attempts blank again 9I gave up in case I get locked out of my account).

I'm actually starting to think it's not a Gmail/WMail issue, but rather a window rendering issue in electron(?). If I drag the developer tools left-hand bar I get artefacts above the white space:

![screen3](https://cloud.githubusercontent.com/assets/1463435/18032906/477e867c-6d69-11e6-8a69-2adc4ddc9e04.png)

Not sure what your thoughts are?

**Comment by Thomas101** [comment]
I would agree on the electron rendering bug. It works fine on osx and windows and when I've tried on ubuntu works there for me too. If you move over to the elements tab and start looking through the dom tree does it highlight any elements on screen or is there nothing there?

On a side note there was an issue that might be related https://github.com/electron/electron/issues/6689 about no default font being specified. If you try installing google chrome do you see any issues?

**Comment by juanminino** [comment]
4gb ram

**Comment by axllent** [comment]
@Thomas101 I can confirm that the pages do "render", though not visually (ie: the page does render, I just can't see it). Using the inspector I was able to locate the SMS confirmation code input field and submit it, bringing me to the next page which asks for confirmation for account access (all "hidden" behind the "white screen"). I wasn't able to get past that screen as trying to locate the "Allow access" button with no visual cursor indication is very difficult (I kept clicking the deny access button!). After 3 or 4 attempts I stopped as I don't want to get blocked.

I don't think that particular bug is related however as it does work intermittently (1 out of every 7 or 8 tries maybe?), and the general app works fine (no font/rendering issues there). I already have Chrome installed, and there was no difference when I added that font config.

**Comment by axllent** [comment]
OK, just an update. I found [a mention](https://github.com/ethereum/meteor-dapp-wallet/issues/78) about passing the flags --ignore-gpu-blacklist to the startup command (ie: `./WMail --ignore-gpu-blacklist`). I can only assume this works as it seems to have solved the issue here (2 out of two tries successful). I've given up trying for now but can test later on my laptop which also has the same issue (different graphics card though).

The issue seems related to electron's WebGL rendering I think.

**Comment by Thomas101** [comment]
@axllent nice detective work! I think I can add that flag in by default!

**Comment by Thomas101** [comment]
@axllent I did a little bit of googling on this and according to [this discussion](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/09NnO6jYT6o) in chrome you can find out if and why the gpu has been blacklisted. It would be the same reason as to why it would have been in WMail. Could you go to `chrome://gpu/` in chrome to see if there's anything interesting there? Thanks

**Comment by axllent** [comment]
I can confirm the extra flag (`--ignore-gpu-blacklist`) also fixes it my laptop which had the same issue. Chrome's (Chromium's) output on the laptop is [this](https://gist.github.com/axllent/8d2545b98556ea36e7bfb6355e22da24) (apologies for the raw output). Lots of data there, not really sure what is applicable and what's not.

Adding the flag by default sounds to me like a good idea, though I'm not sure if there are any downsides. I'd assume that it would only impact if WebGL was invoked, so not likely in regular Gmail I guess unless (maybe) inline YouTube videos were viewed (does Gmail still do that?).

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, I've added the option to toggle the command line switch under the advanced settings in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Comment by axllent** [comment]
I can confirm this solves the issue ;-) If you didn't already, it may be worth adding it to a FAQ or docs somewhere, though I suspect it may be very specific to one's OS (Ubuntu Linux being in the minority compared to other OS's).

**Comment by Thomas101** [comment]
I totally agree -- I've added to the FAQ now :-)
