### ISSUE TITLE
Keep Window Size Between Sessions

### ISSUE THREAD

**Issue by MacMhicheil** [Thomas101/wmail#26]
It's nothing major, but I have to maximise the app every time it launches. It would be better if the app remembered it's window size across sessions.

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip). Thanks very much for your help!

**Comment by MacMhicheil** [comment]
Thanks for the update and your hard work. I've been looking for an app like this for ages.

I've updated to the pre-release version, but this still seems to be a problem. If I maximise the window, quit and relaunch it now seems to launch either in full screen mode (as opposed to maximised) or at the same default size it was using in the previous version.

**Comment by Thomas101** [comment]
Ahh yes, I see that too. Just to check if you move and resize the window without maximising does it remember those settings? I'll put a patch in for the maximise issue.

**Comment by MacMhicheil** [comment]
Just checked and yes, it does remember the settings if I move or resize the window without maximising it.

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.5/WMail_1_1_5_osx_prerelease.zip). Thanks very much for your help!
