### ISSUE TITLE
Right clicking on spelling error is slow.

### ISSUE THREAD

**Issue by RajanFernandez** [Thomas101/wmail#261]
When right-clicking on a spelling error to get correction options, the app hangs for several seconds and queues input.
If a correction is selected from the menu, the word is inserted somewhere in the text rather than replacing the incorrectly spelt word.

* Which version 1.2.0
* Mac OSX 10

**Comment by Thomas101** [comment]
Hi, if you try the latest [prerelease](https://github.com/Thomas101/wmail/releases) this has been fixed
