### ISSUE TITLE
app menu and keyboard shourtcuts

### ISSUE THREAD

**Issue by sakshamgoyal01** [Thomas101/wmail#262]
i am unable to use the shortcuts such as hide, show, cycle, minimise

1.3.6 Windows 10

**Comment by Thomas101** [comment]
What are the usual command for these on windows? WMail is setup for the following at the moment...

* hide all Ctrl+H
* hide window Ctrl+W
* show window Ctrl+N
* cycle ctrl+`
*minimise Ctrl+M

**Comment by sakshamgoyal01** [comment]
they dont work

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)
