### ISSUE TITLE
npm failed

### ISSUE THREAD

**Issue by sakshamgoyal01** [Thomas101/wmail#264]
https://gist.github.com/sakshamgoyal01/9d250f5804260a751fe37b6dc9ea96c7

^^^ npm log ^^^

![image](https://cloud.githubusercontent.com/assets/19929553/17974972/4fb28806-6b12-11e6-8b21-63baad847490.png)

1.6.3 source code
Windows 10

**Comment by Thomas101** [comment]
you'll need to install webpack using the -g command. I'll add this to the building from source docs

**Comment by sakshamgoyal01** [comment]
how do we do that? i am new to npm and node.js

**Comment by Thomas101** [comment]
just run `npm install -g webpack`. It will install it globally so that you can run `webpack a b c` from the command line. You might run into some problems trying to run on windows, I've only tested the build environment on linux and osx.

**Comment by sakshamgoyal01** [comment]
got a 'warn' message:


`npm WARN optional dep failed, continuing fsevents@1.0.14`

here is the full thing:
![image](https://cloud.githubusercontent.com/assets/19929553/18000195/1b8df76e-6ba7-11e6-996a-fa7b4e57258f.png)
