### ISSUE TITLE
Use "menu bar" insted of "tray" on OS X

### ISSUE THREAD

**Issue by SpectralKH** [Thomas101/wmail#265]
On OS X there is no "tray," but it's called the menu bar. So if you'd rename all the options to fit that, that'd be great and would save a bit of confusion.

**Comment by Thomas101** [comment]
I agree. I'll add it in...

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)
