### ISSUE TITLE
Refresh button / Detect offline state

### ISSUE THREAD

**Issue by ydyote** [Thomas101/wmail#266]
It would be great if refresh/reload button was added for these kind of situations:
https://i.gyazo.com/39da5094def997183b693d734692322d.png

(and maybe some kind of "about" in app because i was unable to tell version from anything other than my downloaded file)

Using: wmail v1.3.6, Windows 8.1

Keep up the good work!

**Comment by Thomas101** [comment]
I will have a go at detecting online/offline state to see if I can avoid that situation all together :)

**Comment by Thomas101** [comment]
Added in 4a4f06a1adfde8b65d804ee175d70719a0e60ee0

**Comment by Thomas101** [comment]
Hi, thanks for raising this! It's made into the latest prerelease that you can [download from here](https://thomas101.github.io/wmail/download)
