### ISSUE TITLE
cannot scroll

### ISSUE THREAD

**Issue by sakshamgoyal01** [Thomas101/wmail#267]
i am unable to scroll. sorry for putting so many issues and it's a great app, but its is very unfinished. i cannot scroll and i have to use the sidebar, when i click on the text, it automatically scrolls to the top. add option to reset view settings and reset all settings

Windows 10
1.3.6

**Comment by sakshamgoyal01** [comment]
can you add reset view settings? also remove accounts?

**Comment by sakshamgoyal01** [comment]
reset all settings?

**Comment by Thomas101** [comment]
Which OS are you using?

**Comment by sakshamgoyal01** [comment]
windows 10

**Comment by Thomas101** [comment]
Do you still see this issue?

**Comment by sakshamgoyal01** [comment]
64bit win10

**Comment by Thomas101** [comment]
Are you using a mouse / track pad?

**Comment by sakshamgoyal01** [comment]
mouse, problem fixed. idk what happened
