### ISSUE TITLE
cmd+w doesn't close window

### ISSUE THREAD

**Issue by tylertervooren** [Thomas101/wmail#27]
Expected behavior with cmd+w for OSX applications is to close the window, but does not appear to work in wmail.

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip). Thanks very much for your help!

**Comment by tylertervooren** [comment]
Thanks, sir! Great job with this project.

On Wed, Jan 20, 2016 at 1:14 PM Thomas Beverley <notifications@github.com>
wrote:

> Hey, this has made it into a pre-release version which you can download
> here
> <https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip>.
> Thanks very much for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Thomas101/wmail/issues/27#issuecomment-173361237>.
>
-- 
--
Tyler Tervooren
