### ISSUE TITLE
Feature request: Custom CSS

### ISSUE THREAD

**Issue by axllent** [Thomas101/wmail#273]
Would it be possible to add a custom CSS field in the settings to allow the (experienced) user some additional DOM customisation in the Gmail UI (eg: hiding certain page elements)?

Thanks!

**Comment by Thomas101** [comment]
Yes I like this idea. Helps to me to deal with the more bespoke requests. I will also add custom js in to the mix!

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Comment by axllent** [comment]
Thanks! I've just tested (the custom CSS anyway) and confirm it works great. A little frustrating that it needs to be applied separately to each account (rather than one setting applies to all), but I realise that in some cases not all accounts may require the same settings, and it's not that much work to copy and paste anyway.

Good work Thomas, and thank you again!

**Comment by czekaj** [comment]
Here's my dark compact theme if anyone is interested https://gist.github.com/czekaj/fc3f5b7abbfe1b7f6a05f3b1503ad523

**Comment by Thomas101** [comment]
Would anyone be interested in a gallery of snippets to add in and @czekaj would you be interested in adding your sample to a gallery? Just an idea I was having...
