### ISSUE TITLE
Privacy Policy?

### ISSUE THREAD

**Issue by tbyerly52** [Thomas101/wmail#274]
Hi!,

I was curious if there is a privacy policy for Wmail? I am a privacy supporter who likes to know what information is being collected. :D

Thanks, 
-Thomas

**Comment by Thomas101** [comment]
Hi,
I don't have one but I guess I should. Is this something you could help me with? It would be great to set one out and then make sure WMail abides by it.

In terms of information that's being collected, I do collect some anonymous usage stats through Google Analytics. These don't contain anything about your e-mails, email addresses, who you are or anything like that. The code is freely available to check, it's all self contained in this file... https://github.com/Thomas101/wmail/blob/master/src/app/src/app/AppAnalytics.js

The app sends a heartbeat call every 5 minutes when it's open and it sends the following information...

* The size of the WMail window
* Your operating system language (e.g. en_US)
* The type of operating system you're using (e.g. windows, darwin, linux)
* The version of WMail you're using (e.g. 1.3.7)
* Then from the IP address of the collection request you can derive the rough geographical region (e.g. USA, UK etc)

As I said before, this doesn't contain anything identifiable nor does it have any information about your email accounts, behaviour or anything like that. It's something I've added in to satisfy my own ego as the more users I can see using WMail, the more time I'm happy to devote to it :-)

**Comment by tbyery52** [comment]
Thanks Thomas!

If you'd would like, I'll create a great looking and simple privacy policy
page for you. Where should I send it, and what would you like on it?
Thanks! :D

**Comment by Thomas101** [comment]
Thanks @tbyery52! [Fill out my contact form](https://docs.google.com/forms/d/e/1FAIpQLSfbuoJlMKSxHwtJwYY6ZR0KL2dvWfyx5AODqHMEgWVO2wDrGw/viewform) and I'll drop you an email back!

**Comment by tbyery52** [comment]
Done!
