### ISSUE TITLE
spell checker russian not working

### ISSUE THREAD

**Issue by DubininDmitry** [Thomas101/wmail#275]
WMail a1.3.7
Ubuntu 16.04

**Comment by Thomas101** [comment]
Thanks! I'll take a look into this. Did you make sure that you quit WMail completely after changing the language? (Also quitting from the tray icon?)

Could you give me a few words that you expect to be correct and incorrect so I can test my end?

**Comment by DubininDmitry** [comment]
Yes, I also quit app from the tray icon and did it 2 times

**Comment by Thomas101** [comment]
Okay thanks. I'm seeing the same too. I think it might be down to the cyrillic characters. I'll take a look into this! Thanks!

**Comment by DubininDmitry** [comment]
Ok thanks

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Comment by DubininDmitry** [comment]
Ok, good news. Thanks!

**Comment by DubininDmitry** [comment]
i tried again, but spell checker russian not working...
Arch Linux, WMail a1.3.8

**Comment by Thomas101** [comment]
Sorry about that. I'm seeing the same.

Just for when I come around to fix this...

* `my name is thomas` marked incorrect
* `Меня зовут Томас` marked correct
* `Менннннн зовут Томас` marked correct. Hightlighting `Менннннн` does give the `Именно` suggestion

**Comment by Thomas101** [comment]
@DubininDmitry what language have you got ubuntu set to? Is it Russian?

**Comment by DubininDmitry** [comment]
Yes, it is Russian.

**Comment by Thomas101** [comment]
3rd time luck, this should be fixed in the latest [prerelease](https://github.com/Thomas101/wmail/releases). Thanks!
