### ISSUE TITLE
Spell checker Italian freeze app - WMail 1.3.7 64-bit

### ISSUE THREAD

**Issue by DavideVR** [Thomas101/wmail#277]
Set Italian spell checker, after reboot the app freeze.
Reterned english spell checker: app ok.

WMail 1.3.7 64-bit on Win 10 64-bit Anniversary Edition

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Comment by DavideVR** [comment]
Thank's for your Jobs, Thomas! Now it works perfectly.
Davide

2016-09-10 9:38 GMT+02:00 Thomas Beverley <notifications@github.com>:
