### ISSUE TITLE
Compare-version is missing

### ISSUE THREAD

**Issue by Martindelataille** [Thomas101/wmail#278]
I am trying to install new wmail version (1.3.7) on OSX and i have an error with compare-version:

``
ERROR in ./src/scenes/mailboxes/src/ui/UpdateCheckDialog.js
    Module not found: Error: Cannot resolve module 'compare-version' in /Users/martindelataille/Projects/others/wmail/src/scenes/mailboxes/src/ui
     @ ./src/scenes/mailboxes/src/ui/UpdateCheckDialog.js 6:21-47
``

It seem to be required but not installed

**Comment by Thomas101** [comment]
Hi are you building from source for this? If so did you run `npm run-script install-all`

**Comment by Martindelataille** [comment]
Thanks @Thomas101 

I needed to reinstall npm/rebuild/run-script install-all.

But it's working now.
