### ISSUE TITLE
Spell Checker (English) flags some contractions incorrectly

### ISSUE THREAD

**Issue by solepixel** [Thomas101/wmail#279]
Contractions that do not consist of real words get flagged by spell checker:

<img width="82" alt="screen shot 2016-08-29 at 10 10 15 am" src="https://cloud.githubusercontent.com/assets/882391/18056319/08659b84-6dd1-11e6-9476-9e463291ab35.png">

* WMail Version: 1.3.1
* OS: Mac OSX 10.11.6

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)
