### ISSUE TITLE
Header Bar 

### ISSUE THREAD

**Issue by mykecheckonetwo** [Thomas101/wmail#28]
Would like to have header bar allow to move app and resize

**Comment by Thomas101** [comment]
Hi, the top 40 pixels of the screen should allow you to drag and move as if the bar is already there. Are you able to get it to move?

**Comment by DerSiedler** [comment]
I support "mykecheckonetwo". A header bar is a must have for usability. Its pretty hard moving the app around without. Its strange but usally I grab to drak gray row but that is of course not working.

**Comment by mykecheckonetwo** [comment]
Yes basically the size it's set to now seems to be insufficient to move the window around with drag and drop. I have to be very precise with clicking the very top of the window in order to drag the window.

**Comment by DerSiedler** [comment]
Perhaps 40px are not enough or it depends on the screen resolution how much space there is to grab. My 17'' MBP runs with 1920x1200px. And what about Retina Displays?

**Comment by Thomas101** [comment]
It should be the standard size, but I'll test it on a retina display. I'll add an option to enable/disable the old style title bar in 1.1.5

**Comment by Thomas101** [comment]
Also related #13

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.5/WMail_1_1_5_osx_prerelease.zip). Click on the cog in the bottom left-hand side and you turn on the header bar from there. Thanks very much for your help!
