### ISSUE TITLE
Reclaim right space for Gmail

### ISSUE THREAD

**Issue by lowski** [Thomas101/wmail#282]
Hi!
Would it be possible to reclaim the space on the right side of the message for all emails?
<img width="283" alt="screenshot 2016-08-30 19 33 03" src="https://cloud.githubusercontent.com/assets/1379988/18099809/9812dd60-6ee8-11e6-94c1-2385148880de.png">

Some messages use the whole space while others leave empty space on the right.

**Comment by axllent** [comment]
I believe Thomas is going to be adding a new feature I requested which will allow you to add custom CSS & JavaScript to the app ~ which will allow you to fairly easily remove that "wasted space" (provided you have the right CSS). That wasted space you're referring to is probably the advertising space - the same reason I want to get rid of it ;-) I'm guessing you probably block certain advert servers in your network too?

**Comment by Thomas101** [comment]
Hi, I've added the ability to inject custom CSS and JS into the gmail & inbox window in the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/v1.3.8). This  is probably going to be the best way to achieve this :)

**Comment by axllent** [comment]
@lowski Give this a shot, I think it'll do what you want (add it to the custom CSS):

```
/* Hide side ads / wider email screen */
.iY .Bu.y3 {
    display: none;
}

/* messages full width */
.if {
    margin-right: 0;
}
```
