### ISSUE TITLE
zoom levels not working

### ISSUE THREAD

**Issue by bmurphy1976** [Thomas101/wmail#284]
Zoom levels other than 0 are messed up in 1.3.7.  See the image below, the content is not properly sizing itself to the window.

Normal zoom:

![screen shot 2016-08-30 at 3 30 14 pm](https://cloud.githubusercontent.com/assets/270488/18105887/cb82daa0-6ec6-11e6-95d3-154cf5e48a35.png)

Zoom + 1:

![screen shot 2016-08-30 at 3 30 21 pm](https://cloud.githubusercontent.com/assets/270488/18105890/cebef8c0-6ec6-11e6-95d1-bf60ce2aa074.png)

**Comment by Thomas101** [comment]
Hmmm this is down to the fix that I put in for #257. Unfortunately it doesn't look like it's worked. Waiting on electron to fix https://github.com/electron/electron/issues/6958. I'll see if I can get a patch into their next release

**Comment by saifulwebid** [comment]
This is also happening on the Windows x64 version.
