### ISSUE TITLE
Can't move WMail between virtual desktops from the window bar on Ubuntu 16.04

### ISSUE THREAD

**Issue by cdysthe** [Thomas101/wmail#287]
When right clicking on the top application window bar in Ubuntu 16.04 there are options to move the application between virtual desktops in the drop-down menu like "Move to Workspace Right". However, WMail will not move when these options are used so I have to either drag it or close and open on the desktop I want WMail on. All other applications I use that uses the native windows decorations can be moved between virtual desktops, but not WMail. So as a heavy user of both VMail and virtual desktops this is a problem.

* I'm using WMail 1.3.7 

* Running Ubuntu 16.04 x64

**Comment by Thomas101** [comment]
Hi, if you try this with 1.3.8 does it work? I've checked with ubuntu 15 and 16 and it seems to work my end

**Comment by cdysthe** [comment]
Works now with 1.3.8. Great!
