### ISSUE TITLE
Bug: No badges (unread messages) in taskbar icon (Ubuntu Unity)

### ISSUE THREAD

**Issue by byaka** [Thomas101/wmail#289]
* Which version of WMail are you using? **1.3.7**

* Which Operating System are you using? **Ubuntu 14.04**

**Comment by Thomas101** [comment]
Hi, do you see the icon in the taskbar at all?

**Comment by byaka** [comment]
Ofcourse.
![image](https://cloud.githubusercontent.com/assets/1580811/18231805/36fc52ae-72cb-11e6-8448-26ab5793d968.png)

As you can see - 16 unread messages on tray icon, but no badge in taskbar.

**Comment by Thomas101** [comment]
Ah I see - Support for that has been added since checked last. I'll see what I can do

Just for my own reference...
https://github.com/electron/electron/blob/master/docs/api/app.md#appsetbadgecountcount-linux-macos

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Note** that you'll need to use the deb package for this to work.
