### ISSUE TITLE
Blank screen when trying to sign in

### ISSUE THREAD

**Issue by Zylixel** [Thomas101/wmail#29]
Hi, I'm really new to this program, I must've missed something.

Whenever I try to add an inbox I get this screen

![screen shot 2016-01-16 at 10 56 23 pm](https://cloud.githubusercontent.com/assets/11281319/12376015/7287daa6-bca4-11e5-921c-a4fa43187391.png)
![screen shot 2016-01-16 at 10 56 33 pm](https://cloud.githubusercontent.com/assets/11281319/12376016/73fe1bc0-bca4-11e5-8714-bacc26e88bc2.png)

All help is appreciated, Thanks!

WMail 1.1.3

UPDATE: Downloaded 1.1.2, everything worked fine! Must be a problem with the update

**Comment by masoniscool9** [comment]
This is on Wmail 1.1.3

**Comment by masoniscool9** [comment]
UPDATE: Downloaded 1.1.2, everything worked fine! Must be a problem with the update

**Comment by Thomas101** [comment]
There weren't any auth changes between 1.1.2 and 1.1.3 so I wonder what this is. Are you sat behind a firewall or vpn? Could this be related to #2 ?

**Comment by Zylixel** [comment]
I must've had a VPN on by accident, I went back on 1.1.3, pressed add gmail account and everything worked! Sorry for the inconvenience.
