### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by PyGeek03** [Thomas101/wmail#292]
I'm not sure if this is a real issue, but it seems that the latest prerelease (1.3.7) as well as release version (1.3.1) of this app takes up quite a lot of memory (about 600MB with 1 mail account and about 800MB with 2 mail accounts on my Ubuntu 16.04.01), even in background mode.

**Comment by Thomas101** [comment]
That sounds about right. It's because wmail uses chromium under the hood which is quite ram hungry. Unfortunately there's not much that can be done about this apart from waiting for the chrome team to make memory enhancements :-(

**Comment by Ligerx** [comment]
@Thomas101 I'm currently running two other Electron apps: Messenger for Desktop and Discord.
Both of these apps are running with <100mb of ram. I find it odd that WMail is using >400mb ram for me.

I just wanted to confirm that it's not a memory leak or something.

**Comment by Thomas101** [comment]
This is roughly what I'd expect. Gmail and inbox are complete memory hogs. Word has it that the current Dev version of chrome is supposed to be able to reduce memory consumption by 50%. This is due to land by the end of the year, so WMail should be running this early 2017
