### ISSUE TITLE
deb packaging - easy cheat

### ISSUE THREAD

**Issue by philborman** [Thomas101/wmail#294]
Can't help with snap packages, I've no experience of those myself, but deb is quite easy to do using a makefile and checkinstall...

your makefile needs to be something like...
install:
        @mkdir -p /opt/wmail
	@chmod  a+w /opt/wmail
        @cd /opt/wmail
	@wget latest_package.tar.gz
        @gunzip latest_package.tar.gz
        @rm latest_package.tar.gz

then you can  sudo checkinstall  which will run the makefile, track file creation, and make a deb from the resulting output.  You can also give a command line switch to checkinstall to create rpm packages

You could also use the makefile to create a small wrapper script in (say) /usr/bin/
that calls /opt/wmail/WMail    eg...
#!/bin/bash
DIRECTORY=/opt/wmail
if [ -d "$DIRECTORY" ]; then
  cd $DIRECTORY
  ./WMail
fi

Hope this helps

**Comment by Thomas101** [comment]
Thanks 👍
