### ISSUE TITLE
Ability to remove/delete an email account from WMail

### ISSUE THREAD

**Issue by mrachelski** [Thomas101/wmail#296]
Description
I don't see anything in the user interface that allows me to remove an email account from Wmail. People experiment all the time. And most have multiple email accounts. The reason I want to do this is that I wanted to convert over to using INBOX instead of Gmail. So, I expected to delete the account and then re-add it using the Inbox configuration. My use case can easily be solved by providing some sort of 'convert' button, but it still feels to me like not being able to remove an account is a pretty basic function.

* Which version of WMail are you using? 1.3.1

* Which Operating System are you using? Mac OSX El Capitan 10.11.6

**Comment by Thomas101** [comment]
Hi, if you right click on your account in the left had side you can use delete from there
