### ISSUE TITLE
KDE notification system integrate 

### ISSUE THREAD

**Issue by pyrforos** [Thomas101/wmail#297]
Im using  1.3.1 WMail on Kubuntu 16.04 and im very  exited its nearly perfect ! 
Is it possible to integrate the notification  with  the native notification system  so  we can change the sound for the new mail or / and have the option to run  a command?

**Comment by Thomas101** [comment]
Electron implements the notification spec that chrome has. Unfortunately this doesn't provide support for native notifications with kde, nor do any of the browsers support custom sounds at the moment so unfortunately it's not something I'm able to add support for. Sorry!
