### ISSUE TITLE
Restore Default Account Icon

### ISSUE THREAD

**Issue by solepixel** [Thomas101/wmail#299]
I accidentally set the account icon for the wrong account, and there doesn't appear to be a way to remove the custom icon/avatar for the account to just display the one setup in Gmail. I tried to use the same image I used for Gmail, but the icon is all distorted. Here's a screenshot:

<img width="72" alt="screen shot 2016-09-08 at 10 41 08 pm" src="https://cloud.githubusercontent.com/assets/882391/18374811/9be75d2e-7615-11e6-9323-db404999e46a.png">

Top image is distorted, buttom image is what the top one should look like (also the same for my Github avatar)

* WMail 1.3.7 prerelease
* Mac OSX 10.11.6

**Comment by Thomas101** [comment]
I'll add this in! As regards the distorted image, was the image you uploaded square? Could you send me a link to the original image you uploaded because I'm not seeing any distortion :-/

**Comment by solepixel** [comment]
No, the image was not square. Here is the original:

https://www.dropbox.com/s/g4r3a56d5cts4qq/wcus-avatar.jpg?dl=0

I understand it should have probably been square, but it was honestly a mistake to begin with. I just wanted the one from Gmail back.

**Comment by Thomas101** [comment]
Hi this has been added in the latest [prerelease](https://github.com/Thomas101/wmail/releases). Thanks!
