### ISSUE TITLE
Open links in background not working Version: 1.3.7 prerelease on Ubuntu 16.04 xfce

### ISSUE THREAD

**Issue by deepcoder** [Thomas101/wmail#300]
Hello,

I am not able to get the option to launch links in the background to work with version 1.3.7 on Ubuntu 16.04 xfce with Chrome Version 53.0.2785.101 (64-bit). Tried toggling option on and off in preferences, making sure WMmail was fully exited and relaunched.

Thanks for your work!

Dave

Thanks for raising an issue / requesting a feature! Make sure you take a quick look at the wiki article before continuing (https://github.com/Thomas101/wmail/wiki/Raising-Issues-&-Features).

Please provide the following info when raising a new issue...

* Which version of WMail are you using? [e.g. 1.3.1]

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

**Comment by Thomas101** [comment]
If you right click on a link and go to open in background does that work?

**Comment by Thomas101** [comment]
I can confirm this as well. Looks like an electron issue (https://github.com/electron/electron/issues/7174). It does work on osx

**Comment by Thomas101** [comment]
A little more digging has revealed that there's only a standardised way to do this on osx hence the reason it's not working. It doesn't look like there's any cross platform way to do this, so I will remove the options on linux and windows
