### ISSUE TITLE
Dont show URLs

### ISSUE THREAD

**Issue by pojar** [Thomas101/wmail#302]
It does not show the URL when you hover over links.

* WMail  1.3.7
* Xubuntu 16.04

**Comment by Thomas101** [comment]
Hi, you were just 10 hours to early :-). This went out into the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Comment by pojar** [comment]
Super!!
Please help me with CSS to move the URL to the left side, because the right I have Tasks. If it is possible to do with CSS.

**Comment by pojar** [comment]
I need any example Custom CSS. Tnx
