### ISSUE TITLE
Icon missing in deb package 1.3.8

### ISSUE THREAD

**Issue by Matan** [Thomas101/wmail#303]
Icon not packaged into deb.
* Version 1.3.8 deb
* OS: Ubuntu 16.04

Temporary fix:
* Download: https://github.com/Thomas101/wmail/blob/master/assets/icons/app_256.png
* Place at: /opt/wmail-desktop/icon.png - You'll need root privileges.  
* Ensure chmod 755 is set on icon file

**Comment by Thomas101** [comment]
Hi, I don't know why these weren't added in. I've updated the binaries so a re-download should do it :-). Thanks!
