### ISSUE TITLE
🔇 Dont work sound notification 

### ISSUE THREAD

**Issue by pojar** [Thomas101/wmail#304]
* WMail 1.3.8
* Xubuntu 16.04

**Comment by peterLaurence** [comment]
- Wmail 1.3.8 prerelease
- Ubuntu 16.04

No sound notification.
@Thomas101 if you want more details, i am willing to help.

**Comment by Thomas101** [comment]
WMail is sending out to play notifications and it seems to work on osx and windows, so I think this might be an upstream issue. I've raised an issue for this https://github.com/electron/electron/issues/7258

**Comment by Thomas101** [comment]
So the electron team said that the sound effects should be taken from whatever configuration ubuntu has. I had a go at checking the sound as [described here](https://help.ubuntu.com/16.04/ubuntu-help/sound-alert.html) but didn't have any success. If you try the same does it make any difference?

**Comment by peterLaurence** [comment]
I checked and even with setting the alert sound level to the maximum, it doesn't make a difference.
But one thing surprised me. The default sound for alerts is different from the sound i get with other mail apps (like mail-nag).
Maybe throwing a notification and playing a sound are two different things (at least for Ubuntu).

**Comment by Thomas101** [comment]
I'm starting to think they are. The electron team say they're using `libnotify` but documentation on this seems a little scarce. I have found that you can run `notify-send "test" "test2"` from the terminal but this doesn't  bring up a sound. This might have to be something I add in

**Comment by Thomas101** [comment]
It looks like there's a few missing features with the notifications on linux so I've opened a new issue with all of them together. I'm going to close this off but carry on tracking progress on #327. Thanks!
