### ISSUE TITLE
fullscreen/google voice popup

### ISSUE THREAD

**Issue by amossberg** [Thomas101/wmail#305]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.1

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
el capitan

when a google voice call occurs, if WMail is in fullscreen mode, the call keypad popup will not be displayed and the call can not be answered or declined.

if WMail is in windowed mode, the call keypad popup works normally.

**Comment by Thomas101** [comment]
Hi I've checked on 1.3.1 and the latest pre-release and both times when I receive I call it comes up with the popup window with the two options... accept and decline. Pressing accept opens chrome with the hangouts call. Are you still seeing this?
