### ISSUE TITLE
Unity panel integration is not right (no wmail icon)

### ISSUE THREAD

**Issue by luispabon** [Thomas101/wmail#306]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

I'm getting this since I switched from the tarball installation (1.3.7) to the .deb package (1.3.8):

![image](https://cloud.githubusercontent.com/assets/6388823/18433190/2ea9c26c-78de-11e6-9fbc-1dcd77f811b9.png)

Two issues here:
  * Icon is not WMail's (shows unread count just fine though)
  * App name seems undefined

**Comment by Thomas101** [comment]
There was a release that was out in the wild for about hour without the icon. If you go to /opt/wmail-desktop is there an icon.png in that folder?
