### ISSUE TITLE
Deb package released for 1.3.8 prerelease is showing version 1.2.4

### ISSUE THREAD

**Issue by karlgrz** [Thomas101/wmail#307]
I'm on Ubuntu 16.04, and installed the 1.3.8 prerelease deb package (64 bit).

First, this is great you are moving to packaging this in your releases :-) It is hugely appreciated!

Currently, however, the deb package installed appears to be a vastly outdated build (1.2.4) and it doesn't recognize my currently installed inboxes. I'd be happy to help improve the usability of this feature, just let me know what information you need.

**Comment by karlgrz** [comment]
Ya know, I think this might just be an issue with my environment. Will close shortly if that's the case.

**Comment by karlgrz** [comment]
Definitely issue with my environment. I had my old application launcher file still in my unity launcher cache, apparently. That was launching to an older build (1.2.4) that was still in my Downloads folder where I keep the prereleases. Unity must have been caching something funny.

When I checked the launcher that was pinned to my taskbar it was pointing to the old one, strangely.

**Comment by Thomas101** [comment]
Phew I started to panic then!
