### ISSUE TITLE
Unread count not updating

### ISSUE THREAD

**Issue by gotson** [Thomas101/wmail#31]
Just installed WMail, the icon in the dock shows (1) unread mail.
I indeed had one unread mail, but after reading it, the dock icon still shows (1), even after restarting the app.

**Comment by Thomas101** [comment]
Hi, is this still happening? If you receive an email does the count go up to two?

**Comment by gotson** [comment]
i will need to do some more tests, but at startup if i have no email i would expect the count to disappear, which is not the case

**Comment by gotson** [comment]
I managed to reproduce, looks like it's linked to when you pin the icon in the dock.
Have one unread email. Launch WMail. Pin icon in the dock. Delete email => count will not change.

If pinned with 0 unread, it behaves normally.

**Comment by Thomas101** [comment]
If you use the search bar in inbox and type in `label:inbox label:unread` how many results do you see?

**Comment by gotson** [comment]
1 before reading it, 0 after, but icon still showing 1
<img width="1046" alt="screen shot 2016-01-19 at 7 57 02 am" src="https://cloud.githubusercontent.com/assets/2139133/12405819/5e279a08-be82-11e5-8475-315395fae196.png">

**Comment by Thomas101** [comment]
I'm starting to see this too now. If you go to view > developer tools do you [SYNC ERR] notifications?

**Comment by Thomas101** [comment]
@gotson if you try deleting the account by right clicking on it on the left hand side and going to delete, then re-adding it does the unread count start to update again?

**Comment by Thomas101** [comment]
Hey a fix for this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip)
