### ISSUE TITLE
Pressing X on search box after searching keeps words highlighted

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#311]
**Version:** OSX: 1.3.8 prerelease

**Issue:** Using CMD+F to search through email will keep words/phrases highlighted after pressing X. The only way to remove the highlighting is to quit the app or CMD+R to reload the app.

**Expected results:** pressing X after searching should remove the highlighting of the words as it does in Chrome.

**Comment by Thomas101** [comment]
Hi this has been fixed in the latest [prerelease](https://github.com/Thomas101/wmail/releases). Thanks!
