### ISSUE TITLE
Spell check doesn't work on hangouts

### ISSUE THREAD

**Issue by apersonnamedmike** [Thomas101/wmail#312]
Wmail 1.3.8
Windows 10

Not a huge deal, but It'd be nice if the spell check worked in hangouts windows. 
It does  work with the email "compose" parts.

**Comment by Thomas101** [comment]
I've just tried it and it does highlight incorrectly spelt words when I try however it doesn't look like the right click menu works anywhere in the hangouts window. Are you seeing the same?

**Comment by apersonnamedmike** [comment]
yeah, that's what I've got. right click for me just selects the text that I'm typing.

**Comment by Thomas101** [comment]
0df381a adds the context menu with everything working, aside from inserting the spelling suggestion. I've opened an upstream issue for this https://github.com/electron/electron/issues/7245

**Comment by Thomas101** [comment]
Hi this has been added in the latest [prerelease](https://github.com/Thomas101/wmail/releases). Thanks!
