### ISSUE TITLE
Ads blocker

### ISSUE THREAD

**Issue by fedorn** [Thomas101/wmail#313]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Elementary OS Loki

I would love the ability to block Gmail ads. Right now it's the only thing that stops me from using this app.

**Comment by axllent** [comment]
Try this custom css:
```
/* Hide side ads / wider email screen */
.iY .Bu.y3 {
    display: none;
}
/* messages full width */
.if {
     margin-right: 0;
}
```

**Comment by Thomas101** [comment]
@axllent I'm looking at putting a gallery of css&js snippets together. Would you be interested in adding this to the gallery?

**Comment by axllent** [comment]
Sure ;-) What would be even more awesome would be some system like userscripts whereby an update to the gallery would update everyone using it (ie: the gallery is maintained by users logged in), but for starters a gallery would be cool :)

**Comment by Thomas101** [comment]
Agreed on that one. I'm planning on putting 1.3.9pre-release out tonight when I get a chance to build it. I'll shoehorn a link to a gallery into the release for now and probably look into auto-updating once I get the next major release out the door :)

**Comment by axllent** [comment]
Great! If you need help or ideas etc for a scripts repository then just get in touch (I'm a web developer).

**Comment by Thomas101** [comment]
Hi @axllent I hope you don't mind I've added your script to the [user-scripts repo](https://github.com/Thomas101/wmail-user-scripts) as the first one in there :). If there's any more that you can think of I'll happily take as many pull-requests as you can muster!

@fedorn if you add the user script to your custom css when using the app the ads should stop being shown :)

**Comment by fedorn** [comment]
@Thomas101 @axllent Thanks. I also added this to block ads on top of emails list
```
.a2q.a4T.bc1 {
     display: none;
}
```
