### ISSUE TITLE
Contacts open in wmail window

### ISSUE THREAD

**Issue by aldonz** [Thomas101/wmail#314]
* Which version of WMail are you using? 1.3.1

* Which Operating System are you using? Mac OSX 10.11.6

Contacts used to open within wmail window, which was very easy. Today, clicking on Gmail--Contacts opens a login window in my browser. Has this change been done on purpose?

**Comment by Thomas101** [comment]
No change on my end. There are two types of contacts with different behaviours though.
1.) "Old style contacts" these are the ones that launch straight up when pressing the contacts tab in gmail.
2.) "New style contacts" which can be enabled by using Google Inbox or adding them through https://contacts.google.com/preview/. These open up in a new window as they're not part of the gmail ui

Have you enabled new contacts, google inbox or are you using a Google Apps for work/education account?

**Comment by aldonz** [comment]
I'm using a normal gmail account. I tried opening google contacts in the browser, which opened as "new style contacts". Then I selected (on left hand menu) More->Leave Contacts preview, and the ui switched to "old style contacts". Then I logged out of google contacts and shut down wmail overnight. But when I restarted wmail today and selected Gmail->Contacts, the same behavior happens. I get redirected to a browser login window and google loads the "new style contacts". This is really frustrating. I don't like the new style contacts, and can't seem to get things to revert to how they were before, i.e. clicking on Gmail->Contacts in wmail loads my contacts within the wmail ui. It seems to be a google issue. Does anyone else struggle with this?

**Comment by Thomas101** [comment]
According to [this post](http://webapps.stackexchange.com/questions/75625/disable-google-contacts-preview) you can leave the new contacts preview

**Comment by aldonz** [comment]
Yes, that's true. And that's what I had done, as detailed in the post above. However, it makes no difference to wmail. When I select Gmail->Contacts inside wmail, I still get redirected to my browser--and the browser opens the Contacts Preview.
Contacts Preview is causing a great many users untold trouble. But that's another issue.
Is there any way that wmail behavior can be changed so that Gmail->Contacts does not initiate a browser call?

**Comment by Thomas101** [comment]
If you visit gmail in your web browser and click on contacts does it launch contacts preview or the old style contacts?

**Comment by aldonz** [comment]
It opens in Contact preview. I can't find any way of making the change to old contacts permanent.

**Comment by Thomas101** [comment]
I've just had a go and it stuck for me. Is your gmail account a Google Apps for Work or Education account?

On a side note, it doesn't look like you're the only person experiencing this issue with gmail. There's a thread on the official Gmail forum started 6 days ago and closed yesterday about exactly the same thing (https://productforums.google.com/forum/#!topic/gmail/b4aZX0B6eRQ;context-place=forum/gmail). It might be worth trying again as there did seem to be an issue Gmails end.

**Comment by aldonz** [comment]
Finally, Google must have fixed the issue according to your link. This time, when I logged in and changed Contacts Preview to Old Contacts, it stuck! And now, when I click on Gmail-->Contacts within wmail, the old contacts ui opens inside wmail. I'm a very happy camper! Thanks for your help.
