### ISSUE TITLE
Reclaim empty space from disabled chat

### ISSUE THREAD

**Issue by clrg** [Thomas101/wmail#317]
* WMail 1.3.8
* Windows 10 / OpenSUSE Tumbleweed

See attached screenshot with big yellow squiggle. This empty space is vacated by disabling the chat feature.

![2016-09-19 2](https://cloud.githubusercontent.com/assets/68176/18633649/374c663a-7e75-11e6-84ea-4ab7a53b0e66.png)

**Comment by Thomas101** [comment]
Hi, I think you can disable this through gmail. In the gmail UI...

1.) Click on the cog in the top right corner
2.) Click on `settings`
3.) Click on the `labs` tab
4.) Disable the `Right-side chat` lab

That should restore the space on the right for you
