### ISSUE TITLE
Windows Store support

### ISSUE THREAD

**Issue by darren3** [Thomas101/wmail#318]
Do you plan on adding Wmail to the Windows Store? It would make updates easier. There is a tool for developers to convert apps for the Windows Store here.

https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by Thomas101** [comment]
I don't have any plans to add this to the store at the moment I'm afraid. The main reason is down to cost -- which is about 199USD a year. I've got a small section in the [FAQs](https://github.com/Thomas101/wmail/wiki/FAQs#why-is-wmail-not-in-the-apple-app-store--windows-store) if you want more info
