### ISSUE TITLE
Downloading progress bar

### ISSUE THREAD

**Issue by rvillablanca** [Thomas101/wmail#320]
While downloading large files (5 - 10MB aprox) usually I go to the file for open it, but it is not finished yet.
Is possible to add  a progress bar while downloading attachment ? This will show you when you must open the file.

**Comment by Thomas101** [comment]
Looks like [electron supports this](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetprogressbarprogress-options) so I'll take a look at adding it in

**Comment by Thomas101** [comment]
I was originally thinking about adding the progress bar to the app icon but it looks like I've already done that -- that's what I referred to in the docs.

As regards adding the progress to the actual file electron doesn't have any support for this. I did look at downloading the file to a different location in the same way chrome used to do with its `download.crdownload` file but it doesn't look like this is possible with electron reliably as when the user picks the download location that's where it downloads it to.

So I'm afraid at the moment it doesn't look like this is possible, but I'll keep an eye on electron to see if this changes

**Comment by Thomas101** [comment]
Great news on this one. Was doing a bit more digging and I've managed to find a way to do this. The next release will save the partially downloaded file to `myfile.png.wmaildownload` and then on completion move it to `myfile.png` :-)

**Comment by rvillablanca** [comment]
Perfect, I'll be waiting for this!

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!

**Comment by rvillablanca** [comment]
Thanks to you for this useful app!!
