### ISSUE TITLE
Clicking right half of 'Change account icon' button doesn't work

### ISSUE THREAD

**Issue by Eldaw** [Thomas101/wmail#321]
Using v1.3.9 on Windows 10, I notice that clicking on the right half of the 'Change account icon' button doesn't do anything. It is necessary to click on the left half of the button.

**Comment by Thomas101** [comment]
Thanks, I see the same on osx

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!
