### ISSUE TITLE
Click on a notification or the icon from the tray should open wmail

### ISSUE THREAD

**Issue by terencode** [Thomas101/wmail#322]
Clicking on a notification has no effect and you have to right click -> focus to open the app from the tray.

*WMail 1.3.9
Gnome 3.21
Arch Linux 4.7.4*

**Comment by Thomas101** [comment]
Hi, if you click on the tray icon does it bring up the menu or do you have to right click to bring this up?

**Comment by terencode** [comment]
Hey, I do need to right click to bring the menu up.

**Comment by Thomas101** [comment]
I've added the focus click support to the tray icon. As regards the notifications it looks like there's a few missing features on linux so I've opened an issue with all of them in one place #327. You can continue tracking progress from there. Thanks!

**Comment by terencode** [comment]
Thanks!
