### ISSUE TITLE
Latvian dictionary support

### ISSUE THREAD

**Issue by DMGPage** [Thomas101/wmail#323]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.9

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Could you please add Latvian dictionary support? It is available here: http://extensions.openoffice.org/en/project/latviesu-valodas-pareizrakstibas-parbaudes-modulis
And here are download links: http://dict.dv.lv/download.php?prj=lv

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!
