### ISSUE TITLE
Clicking the download notification doesn't open the right folder

### ISSUE THREAD

**Issue by MartinDelille** [Thomas101/wmail#324]
I don't always download my attachment to my user download folder. When I choose another folder, clicking the notification icon open the download folder anyway.

* Which version of WMail are you using? 1.3.1

* Which Operating System are you using? Mac OSX 10.11.6

**Comment by Thomas101** [comment]
Hi, this is fixed in the prerelease channel - it should be going out to the main release channel over the next couple of weeks if you're happy to wait though
