### ISSUE TITLE
Preselect file when opening a downloaded file

### ISSUE THREAD

**Issue by MartinDelille** [Thomas101/wmail#325]
When I download a file and I click the notification, it opens the user download folder. I would enjoy if it could preselect the downloaded file (like when executing the command `open -R path/to/file`

* Which version of WMail are you using? 1.3.1

* Which Operating System are you using? Mac OSX 10.11.6

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!
