### ISSUE TITLE
Disable WMail contextmenu when in Developer Tools

### ISSUE THREAD

**Issue by axllent** [Thomas101/wmail#326]
* WMail 1.3.9
* Ubuntu 16.04

It would be nice to disable the context menu (Select all / WMail settings), assuming of course that right-clicking would enable the regular chrome-like developer debug tools (such as "Inspect" etc). I'm not sure if that is the case, but I thought I'd ask anyway. Trying to find/detect elements in the page for CSS styling is next-to-impossible when trying to work through the DOM manually ;-)

Assuming that is the default context menu, maybe just disable the "WMail contextmenu" when the developer tools are displayed?

**Comment by Thomas101** [comment]
Electron doesn't ship with a native context menu so you have to add your own in. I can add [inspect element](http://electron.atom.io/docs/api/web-contents/#contentsinspectelementx-y) though

**Comment by Thomas101** [comment]
I've added this in. If you're looking at doing more userscripts I'd be happy to do a build from dev for you to make life easier :)

**Comment by axllent** [comment]
Naah that's OK, no need (for me) to do separate builds considering the dev tools are available. I wasn't planning on creating more userscripts than I actually use, but if I do, or need to tweak, then the inspect feature will be awesome! Thanks Thomas!

The client is almost perfect now, you've done a great job. Just the removal of popup blocking now, and maybe icon update for chat notifications ;-)

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!

**Comment by axllent** [comment]
Thanks @Thomas101 - it works perfectly!
