### ISSUE TITLE
Bug: Word document attachments download as 'file' format

### ISSUE THREAD

**Issue by andrew-dc** [Thomas101/wmail#328]
* Which version of WMail are you using? **1.3.1**

* Which Operating System are you using? **Windows 10**

Word document attachments downloaded from Wmail have a bug where they download as a 'file' format, instead of .docx. It's still possible to select this file and 'open file as' using Word however.

**Comment by Thomas101** [comment]
Hi, are you changing the name of the file when downloading? Just noticed I can change the name from `mydocument.docx` to `notmydocument` and it does indeed save without the file extension

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!
