### ISSUE TITLE
Google Contacts in WMail?

### ISSUE THREAD

**Issue by cdysthe** [Thomas101/wmail#329]
Hi,

E-mail and contacts are so tightly integrated in an e-mail client that it would be very nice to have access to Google Contacts in WMail. It would be good to have at least as an option. I have grown totally dependent on WMail by now so it would be great not having to leave the client for something as closely related as my contacts.

**Comment by Thomas101** [comment]
Hi, I completely agree. I have an issue open for this #106 - you can continue tracking progress from there
