### ISSUE TITLE
Suspend app on "X"

### ISSUE THREAD

**Issue by SteffenJahr** [Thomas101/wmail#33]
Most apps on OSX don't close the application if clicking the red button/"X" but rather suspend them or close the current window. If I click on the "X" in the left upper corner WMail closes completely. Please update the behaviour to work like default apps (example TextEdit)

**Comment by DerSiedler** [comment]
I use the latest version 1.1.3 and had 1.1.2 before and the app behaves on my system as expected. "X" closes the window but not the app. The dock symbol has its little bullet.

I use OSX 10.11.2 . Which OSX version are you running?

**Comment by SteffenJahr** [comment]
Works with version 1.1.3 ;)
