### ISSUE TITLE
--hidden flags doesn't work after a while

### ISSUE THREAD

**Issue by peterLaurence** [Thomas101/wmail#330]
Hi, my configuration is :
* WMail 1.3.9 prerelease

* Ubuntu 16.04 (unity)

After a fresh install of WMail, the --hidden flag works as expected. e.g, if i type in the install directory
`WMail --hidden`, the app launches in the "system tray".
But after several app closing/restart, accounts add, ubuntu session logout/login, etc.. the flag doesn't have any effect and WMail starts visible. 

I noticed that removing the configuration files in ~/.local/share/wmail (3 json files), makes the flag work again but then have to reconfigure wmail. I tried to identify which operation triggered the issue but with no success.

@Thomas101 
As a side note, i don't mind launching wmail with flag. But having a checkbox in the settings saying "Start WMail minimized" would be a nice to have.

**Comment by Thomas101** [comment]
I can certainly add a start minimized option. I wonder why the flag stops working. When it stops working, if you check the task manager or use `ps aux | grep WMail` in the terminal are any wmail processes still running?

**Comment by peterLaurence** [comment]
Yes there are several wmail processes running (i could count 7 processes).
I have configured 3 gmail accounts.

**Comment by Thomas101** [comment]
Ah okay. Wmail is only listening out on the hidden flag when it's not already running - hence the reason why it stops working. Have you quit wmail and these processes shouldn't be there, or were you hoping to hide the current wmail window?

**Comment by peterLaurence** [comment]
Ha sorry, i wasn't clear. I thought you asked me if there were several processes running *after* i launch wmail with --hidden flag. But you was asking that after i closed wmail if i understand correctly now.

Unfortunately, even with no wmail process running, e.g. after a fresh os restart, the flag isn't working.

**Comment by Thomas101** [comment]
Ah I get you. I'll take another look then

**Comment by Thomas101** [comment]
Hi do you still see this in the [1.4.0 prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0)?

**Comment by peterLaurence** [comment]
Indeed, still have this with 1.4.0 prerelease. Although the first time it succeeded, subsequent attempts failed (after closing Wmail, no process running).

**Comment by Thomas101** [comment]
The first time you open the window, do you maximise it? Just noticed if I start the app, maximise the window, quit then run `./WMail --hidden` I still get the window coming up

**Comment by Thomas101** [comment]
Found it ;-). Thanks!
