### ISSUE TITLE
Treat Inbox reminders as an unread item

### ISSUE THREAD

**Issue by rfmejia** [Thomas101/wmail#332]
- WMail 1.3.1
- Ubuntu 16.04

Scenario: Whenever a reminder exists on Inbox, count each as an unread item on the tray. If possible, pop up a notification too.

Purpose: Useful for those who snooze emails/reminders to schedule work and keep their inbox clean.

**Comment by Thomas101** [comment]
Hi, I'm going to close this and collapse it into #349 as there's a few issues surround some Google Inbox Notifications and unread counts which are all related. Thanks!
