### ISSUE TITLE
Serious Display Issues - Can't Edit Emails (Selection Bug?)

### ISSUE THREAD

**Issue by transglobalist** [Thomas101/wmail#334]
- Version 1.3.9
- OS Windows 10, 64-bit

**Primary Issue:** Editing emails in composer is virtually impossible. I thought at first I was having an issue with my mouse, because _whenever I would select something, the selection would mysteriously change right before my eyes--usually extending from my cursor (end of the intended selection) to the end of the line or paragraph_. But when I opened gmail in the browser, the problem disappeared. 

**This happens no matter the composer I'm using**: inline (e.g. a reply), new, or new full-screen. In fact, it seems to be worse when I'm replying and there's a lot of text in the thread (because the selection expands even further and the window jumps to the end of the selection).

Another quality of the problem is that it's "jittery," meaning it pops back and forth between the correct selection, and the one it's making up on its own. :)

One possible clue: my laptop has a 4K monitor. Don't know if that can be related, but it's the only thing non-standard about my setup.

Whatever is going on, it's new to this release (the 4th since I began using WMail), and has rendered the app unusable for me except as an email reader.

It's also been hanging semi-regularly (white screen, only window bar and app menu visible), after which I have to kill the process manually via command line or task manager. I can't recreate that one reliably though, so I'm not sure what to tell you other than it's also new to this release.

Thanks,
---jim

**Comment by Thomas101** [comment]
Hi Jim,

Thanks for reporting this. I've just fired 1.3.9 up my end to check this but unfortunately I'm not seeing the same behaviour. I know you mentioned you were running previous versions okay, do you know if you were running the prerelease before this one, 1.3.8? Are you seeing this issue with gmail or inbox or both?

Lame as it may sound, have you tried restarting your machine? Also if you try quitting wmail, deleting your settings and restarting the app does that make any difference? Your settings can be found under...

`C:\Users\<User>\AppData\Roaming\wmail\` e.g. C:\Users\John Doe\AppData\Roaming\wmail\
`C:\Users\<User>\AppData\Local\wmail\` e.g. C:\Users\John Doe\AppData\Local\wmail\

Thanks
Tom

**Comment by Thomas101** [comment]
Also as regards the 4k monitor - have you had any trouble with other apps? If you have one available, would you be able to try wmail connected to a non 4k monitor?

**Comment by transglobalist** [comment]
Hello Tom.

Of *course* you aren't seeing the same behaviour. That would make it too
easy, eh? The life of a software developer 'n all...

To your questions.

*Previous versions:* I'm afraid I don't recall the numbers, but the first
one I downloaded was the one immediately *before *you fixed the menu
shortcuts for fullscreen, show/hide menu, show/hide sidebar, etc. I know
this because I hid the sidebar and could never ever get it back until I
deleted all the settings and reinstalled the app. :)  I was incredibly
happy a day or two later when you pushed a release with those fixes. Since
then, I have installed every version immediately when WMail notified me one
was available. So I presume 1.3.8, yes.

*Gmail, Inbox, or Both*: Both. I wasn't using inbox, but I just added it to
verify. I have the same problem* while making selections* *only*. I can
type all day long with no problem, but if I try to make a selection, it
goes crazy.

*Restart*: I didn't do it for the sake of this bug, but yes. And I have
restarted several times. No change.

*Deleting Settings*: I had not tried that. I did it this morning when I got
your email. No joy.

*4K Monitor: *I haven't had this sort of trouble with any other apps. Only
an occasional issue with incorrect sizing of app components (splash
screens, icon menus, etc). Come to think of it, though, I have to disable
display scaling on Google Chrome or it is unusable: it displays everything
just slightly out of focus
<https://www.quora.com/Can-I-make-Google-Chrome-look-less-blurry-on-my-4K-monitor>...as
though I need glasses. You have to right-click the app icon, and select
Compatibility | Disable display settings on high DPI settings:

[image: Inline image 1]

Since I had forgotten this, I just tried it now with WMail. I even deleted
the settings first, then restarted with "Disable display settings..."
checked. Again, no joy.

As for using another computer without 4K? I don't have any way to do it at
the moment. I live on the road, and am currently in Varanasi, India.
Heading to China for 2 months on October 4th. Because of China, I'd say "so
it doesn't really matter anyway," except I have a VPN to vanquish the Great
Firewall. :)

Sorry I can't help more. I hope someone else sees this or some other "aha!"
moment befalls you, because I really like using your client!

Thanks,
---jim

**Comment by Thomas101** [comment]
Hi Jim,

Of course it's not easy to find ;-). Looking through issues with electron, there are some users reporting issues with touch screens on windows 10. Could be unrelated if you have touch screen? The only other big change that happened between 1.3.8 and 1.3.9 was that chromium got updated under the hood.

If I put a demo app together that shows the issue would you be happy to test that? If I can get a solid failure case I can send this up to the electron guys to get their thoughts on it!

Thanks

**Comment by transglobalist** [comment]
I'm happy to help in any way I can. Your app became a standard part of my
workflow in a very short time, meaning it fills a nice void. I'm already
missing it!

Send me whatever you'd like and I'll put it through its paces. Keep in mind
I'm on India time (GMT + 5:30), so there may be a bit of lag-time in my
replies.

**Comment by oleynikandrey** [comment]
I have the same behavior not only on 4K display, but on laptop display too.

**Comment by transglobalist** [comment]
Tom. 

One other thing that I just noticed. It's not just while composing. It's a general mouse issue. For instance, in the attached screenshot, my mouse is sitting over the word "Circles," and the hover selection is bouncing between Circles and Photography (far below). Rhythmically and repeatedly. It doesn't stop until I move my cursor somewhere else. 

The selection issue is the same: select a few chars and then the selection is actually jumping back and forth. 

I made a 1-minute capture video, but it has some personal info in it. If you have a place I can upload instead of posting publicly, I can do that.

![labels](https://cloud.githubusercontent.com/assets/3701079/18921641/3671b63e-85c3-11e6-8eca-c3d29b83b3ff.jpg)

**Comment by Thomas101** [comment]
@transglobalist fill in my [contact form](https://docs.google.com/forms/d/e/1FAIpQLSfbuoJlMKSxHwtJwYY6ZR0KL2dvWfyx5AODqHMEgWVO2wDrGw/viewform) I'll drop you an email back.

Out of curiosity what laptop make are you both using? Are you able to disable the trackpad using the keyboard (normally pressing one of the `F` keys does this) and does that stop the problem? If you plug in a mouse does that stop alleviate the issue at all?

**Comment by oleynikandrey** [comment]
I'm using Lenovo Yoga 260. Turning off touchpad didn't help.

**Comment by transglobalist** [comment]
I also have a Lenovo. A Y50. My 4K display *is* the laptop display (no
external monitor attached). My touchpad is always disabled, and I have
tried both my usual trackball (USB, wired) and a mouse (USB, wireless).
Makes no difference.

http://transglobalist.com
http://facebook.com/transglobalist
http://instagram.com/transglobalist

**Comment by Thomas101** [comment]
I'm wondering if this is down to some Lenovo mouse software. Do you have like a trackpad app or something that runs in the tray to do with your trackpad. Are you able to disable this / quit it and try with wmail again. I'll put a sample app together to see if there's a clear failure. Hold tight...

**Comment by Thomas101** [comment]
Okay, I've put together a really simple app that has 6 text fields in it. Can you download it, unzip it, run `wmailtest.exe` and see if this has the same problem and if it's in all 6 text fields?

https://drive.google.com/open?id=0B--sEKXlbUTRZ09FYVhYSDlwaTQ

Thanks!

**Comment by oleynikandrey** [comment]
@Thomas101, I've checked your app and there is no problem with selection at all.
But when I resize testarea in webview the field is jumping. 

Look at this video - http://sendvid.com/5bq2ftax

**Comment by transglobalist** [comment]
thomas---

I'm in transit for the next couple of days, so apologies for the delays.
With the test app, I only have issues with webview Textarea and
Contenteditable. I put multiple lines of test copy into both, and the have
the same unpredictable selection-hopping, although not quite as rapidly as
the WMail release. Not 100% reliably, but almost every time, the test app
is jumping to whiltescreen when I'm playing around with this issue in
Textarea, then jumping to Contenteditable. Seems to be when the focus
changes that it happens? Not sure, and sorry I can't make or upload video
until I get to Beijing at this point.

Hope it helps!
Jim

http://transglobalist.com
http://facebook.com/transglobalist
http://instagram.com/transglobalist

**Comment by Thomas101** [comment]
Thanks @oleynikandrey and @transglobalist.

@oleynikandrey I see the same issue when resizing the textbox - does this happen anywhere in wmail. I don't recall seeing a resize handle anywhere.

@transglobalist It would be great to see a video of what you're seeing once you get to Beijing! Thanks!

**Comment by oleynikandrey** [comment]
@Thomas101, I see such behaviour everywhere.  I've made another video, please look here https://sendvid.com/ypnz6acd

**Comment by transglobalist** [comment]
Thomas,

Maybe I can't upload anything while in transit, but I was able to watch
both of Andrey's videos, and that's precisely the same behavior I'm
experiencing. And his videos are better...


http://transglobalist.com
http://facebook.com/transglobalist
http://instagram.com/transglobalist

**Comment by Thomas101** [comment]
Thanks both to of you! This might be something with the flexbox layout so I'll take a look to see if there's anything I can tweak. I might fire a couple of tests across to you again

**Comment by Thomas101** [comment]
I doubt this will be fixed in the latest [pre-release](https://github.com/Thomas101/wmail/releases/tag/v1.4.0) but it might be worth giving it a go. It's got an updated version of electron.

**Comment by transglobalist** [comment]
Installed and tested. Same behavior in every composition view. There is
mourning in the streets of Beijing.

http://transglobalist.com
http://facebook.com/transglobalist
http://instagram.com/transglobalist

**Comment by Thomas101** [comment]
Ignore that commit message, Was meant to be for 344 not 334. Sorry!

**Comment by Thomas101** [comment]
Hi, sorry for the delay in looking into this. There seems to be quite a few issues on electron as regards lost focus, jumping around and pointer issues on windows 10. The general consensus is that this is down to the current version of chromium that's being used.

For the moment I'm going to mark this as an upstream bug, but hopefully once chromium gets updated we'll see an improvement on this

**Comment by Thomas101** [comment]
Looks like there may be a possible solution to this [here](https://github.com/electron/electron/issues/7655#issuecomment-259688853). I'll add an option in the next pre-release to see if makes it any better

```js
app.commandLine.appendSwitch('enable-use-zoom-for-dsf', 'false');
```

**Comment by Thomas101** [comment]
Hi this should be fixed in the latest [prerelease](thomas101.github.io/wmail/download?v=2.0.7). This isn't enabled by default until I know it doesn't have any unwanted side effects. To enable it, go to `Settings > Advanced` then toggle `Use Zoom for DSF` so that it is off and restart WMail. Fingers crossed it should do the trick. Thanks!
