### ISSUE TITLE
Feature:  U2F 2FA Authentication Support

### ISSUE THREAD

**Issue by mrjester888** [Thomas101/wmail#336]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.9
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Please add U2F 2FA support.
https://www.yubico.com/about/background/fido/

**Comment by Thomas101** [comment]
Hi, I would love to add this in, but there's quite a high technical barrier to this at the moment. You can still log in with other 2FA methods though. I've added some more info in the [wiki](https://github.com/Thomas101/wmail/wiki/FAQs#yubico-security-key-support)
