### ISSUE TITLE
Unread badges don't go away

### ISSUE THREAD

**Issue by mschwartz** [Thomas101/wmail#337]
1.3.1 macOS Sierra

![image](https://cloud.githubusercontent.com/assets/329637/18891963/73d42bc2-84bc-11e6-9e02-60a2dc64efa0.png)

It's stuck.  It keeps growing.

I have no unread messages in either of my 2 inboxes.

**Comment by mschwartz** [comment]
Reinstalled 1.3.1 and it did not fix the issue.

Installed 1.3.9 prerelease and that did fix it.

**Comment by Thomas101** [comment]
Hi, sometimes there's a little disparity between the way that the google api reports unread messages and what inbox reports to be unread. If you open the settings in WMail, then click on the accounts tab. Under the `Unread Modes` setting what setting is selected?

You can find out exactly which emails it's found by typing the following the following into the google inbox search bar...

* For `All Unread Messages` it's `label:inbox label:unread`
* For `All Messages in Inbox` it's `label:inbox`

**Comment by mschwartz** [comment]
I understand, but I use wmail on two desktops, my laptop, and a couple of Linux boxes with the same accounts.  This is only happening on some of them, and the only fix was to install 1.3.9.

I saw in the release notes that this bug is supposed to be fixed in 1.3.1.

The wmail notifier in the top toolbar (Mac) shows a list of unread messages.  If I select one of those, it doesn't take me to one of those "unread" messages.  They're not really unread...

I am thankful fot he app.  Thank you for your time on making it.

**Comment by mschwartz** [comment]
Note: the menu only shows "unread" messages, it doesn't take me to the app with the message opened as I expect, even if the message really is unread.

**Comment by Thomas101** [comment]
Ah sorry, I missed that installing 1.3.9 fixed this. I'm hoping to move the prerelease across into the main channel soon -- just waiting for a couple of upstream bug fixes first.

As regards opening the correct message this is still something on the to-do list (#171).

Seeing that the prerelease fixes this and the already open issue for opening messages I'm going to close this off for now. Thanks!

**Comment by almostmavron** [comment]
WMail 1.4.0 prerelease on Kubuntu 16.04
This is happening to me as of today, with a slight variant: the number of unread messages is just stuck to 6, it's not growing when I receive new emails, it's not decreasing when I read them.

"Unread Mode" is set to "All Unread Messages", but using the search term "label:inbox label:unread" on the Inbox search bar gives no results.

I've restarted wmail a few times, nothing changed.
If I play with the settings (Show unread badge, Add unread msgs to app count), the badge disappears and the tray icon count changes accordingly, so it looks like the inner counter itself it's stuck.

![image](https://cloud.githubusercontent.com/assets/21356365/19391179/ae912932-922b-11e6-8885-161a262e3b29.png)
