### ISSUE TITLE
Error message is shown with "Show Original" window

### ISSUE THREAD

**Issue by SlavikZ** [Thomas101/wmail#338]
When I select "Show Original" option, new window with e-mail original is shown in the background and error message saying that "Probably that some popup blocker prevent application to show the window..." is show on the foreground.

* WMail version is 1.3.9 prerelease
* Operating System is Ubuntu 16.04

**Comment by Thomas101** [comment]
Hi, this has just been fixed and is waiting to head out in the next release (#216)
