### ISSUE TITLE
Could the Unread count just show emails in the Primary tab?

### ISSUE THREAD

**Issue by coledaneman** [Thomas101/wmail#34]
This would make the unread count way more useful for me.

**Comment by Thomas101** [comment]
I should be able to do this. At the moment it just searches for unread. I'll add an option in to the settings pane in 1.1.5

**Comment by mykecheckonetwo** [comment]
Could you make this at the least a preference option? I like seeing a unified badge count.


Sent from an iPhone,

Mykel Jewell
Mykel.Jewell@Gmail.com

**Comment by Thomas101** [comment]
hi @mykecheckonetwo I've just done a push with this so it will be out in the next pre-release :)

**Comment by mykecheckonetwo** [comment]
Awesome thanks


Sent from an iPhone,

Mykel Jewell
Mykel.Jewell@Gmail.com

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.6/WMail_1_1_6_osx_prerelease.zip). Thanks very much for your help!
