### ISSUE TITLE
No tray icon for WMail in Ubuntu 16.10 Beta 2

### ISSUE THREAD

**Issue by cdysthe** [Thomas101/wmail#340]
I am running WMail 1.3.9 on Ubuntu 16.10 Beta 2 and there's not tray icon. I have tried to disable and enable the icon and I have tried to resinstall the application. No icon at all.

**Comment by Thomas101** [comment]
Hi, were you using a previous version of wmail or ubuntu and was it working with that combination?

I've just noticed that the very latest version of electron has patched a bug for missing tray icons on elementary - might be related.

**Comment by cdysthe** [comment]
It was working with the current version of WMail until the middle of last week (9/26). So a 16.10 update probably broke the notification icon

**Comment by Thomas101** [comment]
Thanks, that's good to know. I'll take a look into what's changed and see if I can get it back in

**Comment by nemoskapetanos** [comment]
Hi Thomas,

I have the same issue, but I upgraded from Ubuntu 14.04 to 16.04. Whatever update it was, it applies to 16.04 as well.

**Comment by Thomas101** [comment]
Hi, if you open the terminal and type `dpkg -l libappindicator1` what does it print out. Here's what I got on 15.10
![screen shot 2016-10-22 at 18 42 00](https://cloud.githubusercontent.com/assets/103586/19621330/60aa7da6-9887-11e6-93de-e4625c4684c9.png)

**Comment by nemoskapetanos** [comment]
I had to install libappindicator1 as it wasn't installed on my system. Here's the output:
![wmail 1](https://cloud.githubusercontent.com/assets/20514288/19624853/c5a2f81a-9953-11e6-84c6-ea93e6213aeb.png)

Now the wmail icon appears in the system tray but there's no unread count.

**Comment by Thomas101** [comment]
Looks like I might need to add that in as a dependency then.

As regards the lack of updating, what unread count do you currently have across your mailboxes? Is this appearing in the mailboxes on the left hand side? If you go to `Settings`, under the `Menu Bar` section is `Show unread count` toggled? If you try changing the colour of the icon under settings is this reflected in the tray icon?

**Comment by Thomas101** [comment]
@nemoskapetanos you may need to kill all wmail processes by running `killall -9 WMail` or by restarting your machine

**Comment by nemoskapetanos** [comment]
The unread email count appears on the wmail icon in the unity panel but not on the icon in the system tray. Show unread count is toggled on in the settings. Changing the colour of the icon under settings is reflected in the system tray - I changed the colour from blue to green and the icon is now green. Let me know if you need any other info.

**Comment by nemoskapetanos** [comment]
I have some more info. I started cleaning up my mailboxes today and something interesting happened. Once I had pruned my unread emails to 90, the unread email count appeared in the tray icon. My guess is that it doesn't display an unread count in the tray icon if it's over 2 digits.

**Comment by Thomas101** [comment]
Ah yes! *hit head moment*. Once it goes over 99 it defaults back to the mailbox icon. I can't add more than 2 characters as it either overflows the icon and shrinking the text makes it illegible.

What I'll do is add a filled in mail icon for when the count goes over 99 to indicate that state.

**Comment by Thomas101** [comment]
The filled in icon didn't look great scaled down. I've made it show a plus when the count is over 99 instead.

![screen shot 2016-10-26 at 13 36 57](https://cloud.githubusercontent.com/assets/103586/19726155/53ad14ae-9b81-11e6-9ddb-f12ba843536f.png)

Thanks everyone!

**Comment by nemoskapetanos** [comment]
Great idea!

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!

**Comment by nemoskapetanos** [comment]
Thanks for that! I just tested it out and it works fine. In the process, I also found out that the unread counter on the unity panel icon and on the left hand side bar of the app don't go over 100. This doesn't really bother me anymore as the tray icon now works properly. After archiving emails, my unread count is now 15!

**Comment by Thomas101** [comment]
That could be a limitation of unity :-(. Great news the rest is looking good though!

**Comment by nemoskapetanos** [comment]
Interesting point. I've read on forums that the unity DE doesn't have the functionality of say KDE. For a newbie like me, it's adequate and simple to use. I have Docky installed as well, so it does everything I need it to. 2nd day of testing and everything is running great!
