### ISSUE TITLE
Gnome Dark UI - Icon in tray is black and not visible

### ISSUE THREAD

**Issue by cbcoutinho** [Thomas101/wmail#341]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.1

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OpenSUSE Tumbleweed (rolling release), GNOME Shell 3.22.0

![output](https://cloud.githubusercontent.com/assets/12901868/19013451/542af8c4-87d1-11e6-8af3-adc81f020ada.gif)

I use a 'global dark theme' on my laptop, which sets all windows, banner, and system tray to a dark grey/blackish color.  Since the tray icon is also black, this makes it practically invisible. New messages turn the icon red, which works fine.

I recommend using a white icon based on the variable in this gtk-3.0 config file:

```
> cat ~/.config/gtk-3.0/settings.ini 
[Settings]
gtk-application-prefer-dark-theme=1

```

**Comment by Thomas101** [comment]
Hi, you can change the color of the tray icon in the setting in WMail. On version 1.3.1 this is under the tray read color and tray unread color. I'll take a look at some more intelligent theming for the icon too

**Comment by cbcoutinho** [comment]
Thanks for the quick feedback - you're right, I had no idea that was an option. Thanks for the heads up

**Comment by trivigy** [comment]
Hey, anyway to add the ability to set either custom color for that tray or maybe at least add black/white colors? Thanks in advance.

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!
