### ISSUE TITLE
Option to disable update notifications

### ISSUE THREAD

**Issue by mattsluiter** [Thomas101/wmail#342]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.7
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS X 10.11

Add option to disable update notifications in the GUI and make the same option available as a configuration file setting that can be scripted for use with mass deployment of WMail.

**Comment by Thomas101** [comment]
I've added this in, so it will be out in the next release. The settings are stored as JSON in `~/Library/Application\ Support/wmail/settings_db.json` and are separate to the mailboxes so you should be able to just drop in a pre-configured settings or an edited settings for larger deployments.

**Comment by Thomas101** [comment]
I've also added some more info on where data is stored in the [FAQs](https://github.com/Thomas101/wmail/wiki/FAQs#where-does-wmail-store-user-settings-and-data)

**Comment by Thomas101** [comment]
Hi this made it out into the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v1.4.0). Thanks for reporting!
