### ISSUE TITLE
Feature:  Back Mouse Button

### ISSUE THREAD

**Issue by mrjester888** [Thomas101/wmail#346]
Would be swell if the back/forward mouse buttons navigated like they do in webmail.

**Comment by Thomas101** [comment]
I've looked into this before but couldn't find any way to hook into the way the mouse executes the back command. It didn't appear to be anything standardised, certainly nothing I could pick up from JavaScript. If anyone has any other info about how to do this, I'd be happy to re-look into it but at the moment I can't see anyway to do this, sorry!
