### ISSUE TITLE
Feature Request: Offline Mode

### ISSUE THREAD

**Issue by noiseproblem** [Thomas101/wmail#347]
Love the app!!! The best out there for using multiple accounts and hundreds of emails a day. 

I would love a way work offline or even as simple as to hide new incoming emails while still being able send out replies and new ones. Usually going offline and queuing up emails is the only way I can clear out my Inbox and currently have to do that over an iPad or Chromebook. Something similar to Mac Mail's "Take All Accounts Offline".

**Comment by Thomas101** [comment]
Hi, this would be a huge undertaking and isn't something on the roadmap in the foreseeable. I've added a [section in the FAQs](https://github.com/Thomas101/wmail/wiki/FAQs#offline-support) explaining a bit more technically as to why. I hope this helps.

Thanks!
