### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by Thomas101** [Thomas101/wmail#35]

**Comment by dep** [comment]
Is this open case to fix this issue?


![Inaccurate badge count](http://dl.dpeck.net/10Dnn+)

**Comment by Thomas101** [comment]
@dep take a look at #31

**Comment by dep** [comment]
@Thomas101  Thank you!  label:inbox gives me many results.  But they are bundled items and whatnot. I would expect the 'badge' to only show items that are unsnoozed and actively *in* the inbox at that moment.

**Comment by dep** [comment]
Honestly I'd just love the ability to disable unread badging if possible.

**Comment by Thomas101** [comment]
I'll be adding this in 1.1.5 ;-)

**Comment by tylertervooren** [comment]
I'm on 1.1.5 and don't see an option to disable notifications. Did this get pushed back or do I misunderstand the context of the request?

**Comment by Thomas101** [comment]
@tylertervooren if you're talking about the notifications that come up from gmail then you can disable these in gmail settings at the moment. In v1.1.5 you can now disable the number that appears on the app in the dock. Click on the cog in the bottom-left corner, then toggle the `Show app unread` setting. This will stop the count appearing in the dock

**Comment by nateabele** [comment]
@Thomas101 Anything I can do to help with this?

**Comment by Thomas101** [comment]
Hi @nateabele if you want to take a stab at it, you're more than welcome to! I'll happily take any merges! The email feed is already pulled from google, we just need to store the last notification and bubble up new emails as notification. Might need a bit of work to show the right e-mail too!

**Comment by Thomas101** [comment]
Added this in 1aef58c835960ce9383b0ab2b921562f4bc65426

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.7/WMail_1_1_7_osx_prerelease.zip).

**Comment by nateabele** [comment]
Woohoo! Thanks. Looks like you beat me to it. :smile:
