### ISSUE TITLE
Is the application called WMail or Wmail?

### ISSUE THREAD

**Issue by Eldaw** [Thomas101/wmail#351]
There are some inconsistencies in the naming of the application in various places. In some places, like in the Readme.md here on GitHub, the application is referred to as Wmail. In other places, like in the Programs and Features list in Windows, the application is called WMail.

**Comment by Thomas101** [comment]
Truth be told I wasn't sure when I started the project. Lets stick to WMail though as the W is an abbreviation for Web. Thanks!

**Comment by Eldaw** [comment]
Don't forget
<title>Wmail</title>
for the page at http://thomas101.github.io/wmail/

Maybe there are others in the website, source code, etc. I haven't looked for every instance. I recommend doing a Search-and-Replace.
