### ISSUE TITLE
WMail slowed down by animated Google avatars.

### ISSUE THREAD

**Issue by cdysthe** [Thomas101/wmail#353]
When I am in e-mail with someone who has an animated Google avatar WMail gets very sluggish and eats an extra chunk of memory. As soon as I am done with the conversation WMail most often returns to normal, or I simply restart. This does not happen when I use Inbox in Vivaldi. 

WMail 1.4.0
OS: Ubuntu 16.04 and 16.10 x64

**Comment by Thomas101** [comment]
Thanks, I'll take a look into this

**Comment by Thomas101** [comment]
Does this happen if you attach a gif in a message? Are you seeing this with gmail or inbox?

**Comment by Thomas101** [comment]
Hi are you still seeing this behaviour in the latest [prerelease](https://thomas101.github.io/wmail/download?v=2.0.8)?

**Comment by Thomas101** [comment]
Hi, I'm going to close this off for now due to inactivity. If you're still having the issue feel free to re-comment or open a new issue and I'll look back into it.
