### ISSUE TITLE
Not Showing Custom Company Logo

### ISSUE THREAD

**Issue by solepixel** [Thomas101/wmail#354]
How do I refresh the logo for my G Suite account? I recently uploaded a custom logo for my company and tried many ways to clear cache and refresh, but I'm still not seeing the logo. I'm not sure if there's much you can do, but when I visit my mail in the browser, I can see my logo.

Here's a screenshot: http://3cd.co/3P1w0g1z3U3u
![missing-company-logo](https://d3vv6lp55qjaqc.cloudfront.net/items/020k3i0N3z0A3Z0w0n3e/Screen%20Shot%202016-10-06%20at%209.42.36%20AM.png?X-CloudApp-Visitor-Id=590902&v=91328f6f)

* Which version of WMail are you using? 1.4.0 prerelease
* Which Operating System are you using? Mac OSX 10.12 (Sierra)

**Comment by Thomas101** [comment]
WMail doesn't really touch the logo besides shifting it down a little bit when you don't have the sidebar.

I suspect if you wait long enough it will update itself or if you re-add the mailbox it will update. I've seen that Google can be quite slow at updating things like this and is quite heavy on caching assets in the browser too.

**Comment by Thomas101** [comment]
I've just taken a quick look at my account in chrome and the expiry time on the default icon is set for a year so you may have to re-add your account.

**Comment by solepixel** [comment]
That did the trick! I removed it and added it back and there it is! Thank you!

**Comment by Thomas101** [comment]
Awesome! Nice logo btw ;-)

**Comment by solepixel** [comment]
Thank you! Glad you like it. Super excited about it, but slowly "getting it out there". Glad to have some good feedback :)
