### ISSUE TITLE
[Clarification] Difference between x64 and x86 ? 

### ISSUE THREAD

**Issue by funilrys** [Thomas101/wmail#355]
Hello world ! 
I'm working on the package on [AUR](https://aur.archlinux.org/packages/wmail-bin/) for archlinux
I think a clarification is needed cause for other apps it's clear:

32bits == i686/ia32
64bits == x86_64

Hava nice day !

**Comment by Thomas101** [comment]
Awesome! Thanks for adding it on AUR! Where were you thinking about the clarification? On the download page?

**Comment by funilrys** [comment]
It's official this app is available on AUR [here](https://aur.archlinux.org/packages/wmail-bin/#news) + I'm gonna add it to wiki asap !

It's in your release page :)

**Comment by funilrys** [comment]
*Arch user can install it with `yaourt -S wmail-bin`

**Comment by Thomas101** [comment]
Ah you mean with the filenames? Would changing them to...

WMail_1_4_0_prerelease_linux_x86_64.deb
WMail_1_4_0_prerelease_linux_x86_64.tar.gz
WMail_1_4_0_prerelease_linux_ia32.deb
WMail_1_4_0_prerelease_linux_ia32.tar.gz

... be clearer?

**Comment by funilrys** [comment]
Yeah ! :) I lost time on downloading to check that x)

**Comment by Thomas101** [comment]
I'll keep this open for now as I'll need to run an update to the site when I publish the binaries next :)

**Comment by funilrys** [comment]
All right :) Gonna add your app to arch wiki :)

**Comment by Thomas101** [comment]
Thanks! Packaging script is updated ready for the next release. Thanks again!

**Comment by funilrys** [comment]
Link added to List Of Application of Archlinux Wiki : [Link](https://wiki.archlinux.org/index.php/List_of_applications/Internet#Graphical_2) 

Good night !
