### ISSUE TITLE
CMD-A doesn't appear to 'select all text' anymore

### ISSUE THREAD

**Issue by dep** [Thomas101/wmail#357]
* Which version of WMail are you using? [e.g. 1.3.1]
v1.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX

When I press CMD-A to select all text in any input (chat windows, subject, body, etc), nothing happens. Expect OSX to 'select all text'

**Comment by lament** [comment]
Can confirm.

We also lost CMD+SHIFT+V to paste formatting. :(

**Comment by Thomas101** [comment]
Thanks, I think this must have been introduced in be6bb0f5d3ca6968b91ceda0b3f3a90b06a7e0e8
