### ISSUE TITLE
[UI] [Inbox] page slider through blue header

### ISSUE THREAD

**Issue by damiongans** [Thomas101/wmail#358]
------------
**Q1:** Which version of WMail are you using? 
**A1:** 1.4.0

**Q2:** Which Operating System are you using? 
**A2:** Windows 10 64bit

----------

I would like to see that the header of Google Inbox is full width. Right now the right slider to browse the inbox breaks the header. I think it looks better when the slider is below the header.
![image](https://cloud.githubusercontent.com/assets/20154922/19191169/803a96d4-8ca1-11e6-99b8-a609fdc3ed64.png)

**Comment by Thomas101** [comment]
Hi, it looks like this is a styling issue with Inbox itself. They've chosen to keep the scrollbar over the top of the header. I don't know why though, it does look better without!

You can hide the scrollbar by adding a userscript. If you open settings and go to the accounts tab, then press the Custom CSS button. In the screen that appears if you enter...
```css
body::-webkit-scrollbar { display:none; }
```
... and hit save it will hide the scrollbar. (It may take a few seconds to take effect after the mailbox reloads).

I've added this userscript to the [userscripts repository](https://github.com/Thomas101/wmail-user-scripts) for other users too.

Thanks!
