### ISSUE TITLE
Keyboard shortcuts don't work

### ISSUE THREAD

**Issue by gotson** [Thomas101/wmail#36]
For instance pressing 'c' should open the compose dialog.

**Comment by jonsolove** [comment]
It looks like you have to enable the shortcuts.  Go to the Settings within Inbox >> Other, then check the "Keyboard shortcuts" checkbox.

**Comment by Thomas101** [comment]
@jonsolove is correct. Are you happy for me to close this one?

**Comment by gotson** [comment]
Weird, they were enabled before, but didn't work. Now they work.
