### ISSUE TITLE
Opening inline links in browser not working

### ISSUE THREAD

**Issue by nlenkowski** [Thomas101/wmail#360]
* Which version of WMail are you using? [e.g. 1.3.1]
1.4.0 Prerelease

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.12

**Possible bug:** 
In 1.3.9 clicking on the URL in the add/edit link dialogue would open it in my browser. As of 1.4.0 nothing happens when clicking the URL.

![image](https://cloud.githubusercontent.com/assets/1290235/19243421/f0f30988-8f17-11e6-9416-7b7fcbb06f0e.png)

I've tried restarting WMail as well as changing my default browser to no affect. Other apps can still open links as normal.

**Comment by Thomas101** [comment]
Thanks! Looks like the parsing is going alright but wmail isn't handling the `js-new-window` call properly

**Comment by nlenkowski** [comment]
Thanks a ton for looking into this. And thanks for all the hard work on WMail, I love it and use it daily 👍

**Comment by Thomas101** [comment]
No probs :). Glad you're enjoying it! :-)
