### ISSUE TITLE
Mail Doesn't Show up at all

### ISSUE THREAD

**Issue by Razorfin8** [Thomas101/wmail#362]
- Which version of WMail are you using? 1.4.0
- Which Operating System are you using? Ubuntu 16.04

![screenshot from 2016-10-14 17-15-05](https://cloud.githubusercontent.com/assets/2932987/19405888/cdfc2d20-9231-11e6-89d9-b568078ff123.png)

I'm using a gmail account, when I signed in this is what displayed.

**Comment by Thomas101** [comment]
Hi, if you go to settings then advanced and toggle `Ignore GPU Blacklist` and restart WMail, does this make any difference?

**Comment by jaylenw** [comment]
@Thomas101 , thank you. It appears by toggling the `Ignore GPU Blacklist` worked for me.

I am running the open source drivers for my AMD APU on Ubuntu 16.04. 

----------------------------
Processor: AMD A10-5745M APU with Radeon(tm) HD Graphics × 4 
Graphics: Gallium 0.4 on AMD ARUBA (DRM 2.43.0, LLVM 3.8.0)
