### ISSUE TITLE
Build fails on Arch Linux (EMFILE: too many open files)

### ISSUE THREAD

**Issue by iandrewt** [Thomas101/wmail#364]
* Which version of WMail are you using? [e.g. 1.3.1]

Using HEAD, 5ae2ea29e2ee32a57203414de40db33db68b2517

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Arch Linux, everything up to date with Testing repos enabled, and NodeJS v6.8.0

This is the error I get
```bash
$ npm start
> wmail@1.4.0 prestart /home/andrew/Documents/wmail
> webpack

[DEVELOPMENT BUILD]
[FULL SOURCEMAPS]
[TASK=all]
clean-webpack-plugin: /home/andrew/Documents/wmail/bin/fonts has been removed.
clean-webpack-plugin: /home/andrew/Documents/wmail/bin/icons has been removed.
clean-webpack-plugin: /home/andrew/Documents/wmail/bin/app has been removed.
clean-webpack-plugin: /home/andrew/Documents/wmail/bin/scenes/mailboxes has been removed.
clean-webpack-plugin: /home/andrew/Documents/wmail/bin/scenes/platform has been removed.
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/home/andrew/Documents/wmail/src/app/node_modules/jquery/src/core.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.source (/home/andrew/Documents/wmail/node_modules/copy-webpack-plugin/dist/writeFileToAssets.js:45:31)
    at Compiler.writeOut (/home/andrew/Documents/wmail/node_modules/webpack/lib/Compiler.js:256:26)
    at /home/andrew/Documents/wmail/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by Thomas101** [comment]
Hi, I think this is down to the os limiting the maximum amount of open file handles. Webpack and other task runners can be very heavy on the files they have open when running. Other posts on google suggest increasing the file limit. You can check the upper limit by running `ulimit -n` (on osx I got 256) and increase it running `ulimit -n 10480` for example. Did that fix it?

**Comment by iandrewt** [comment]
Turns out it was a bug with `gnome-terminal`, which doesn't get the `ulimit` correctly. Found a workaround to increase it beyond 4096 and everything is working now. Thanks!
