### ISSUE TITLE
Google Apps account not staying logged in on restart

### ISSUE THREAD

**Issue by Ligerx** [Thomas101/wmail#366]
* Which version of WMail are you using? [e.g. 1.3.1]
v1.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I have one Google Apps account (with my college). Every time WMail restarts, I have to log back in. The rest of my normal accounts are fine.

**Comment by Thomas101** [comment]
Hi, this can sometimes happen if your provider uses SAML to log you in. There's some instructions in the [FAQ about how to force WMail to stay signed in](https://github.com/Thomas101/wmail/wiki/FAQs#i-have-to-sign-in-everytime-i-launch-wmail)

**Comment by Ligerx** [comment]
I tried using the artificially persisted cookies and it didn't seem to help.
That said I usually have a smooth time logging in on my browser. A large part of that is because it saves my username/password for the non-gmail single sign on I have to do.
Having that feature would definitely make my life a lot easier!

**Comment by Thomas101** [comment]
Hmmm, that's interesting. When you login do you get the "Signed into a new computer" email? Sometimes you have to open that email and wait 5 - 10 minutes for google to keep you logged in next time

**Comment by Ligerx** [comment]
This is what I see when I first open the app. This happens every time, no exception, even with persistent cookies turned on.

![Initial Page](https://cloud.githubusercontent.com/assets/6577974/19462951/084d06fa-94be-11e6-85dd-37bdddc9b846.PNG)

That redirects me to my SSO page, which then redirects me back to gmail.
![SSO Page](https://cloud.githubusercontent.com/assets/6577974/19462953/0b70e4be-94be-11e6-8665-2ea50d094793.PNG)

I don't get any signed into a new computer email.
So what I'm suggesting is the first screen could just be skipped, and the second page would be autofilled, similar to how it's happening in my browser.

**Comment by GalawynRM** [comment]
To me is working in 1.3.9 and not working in 1.40, I was forced to downgrade to 1.3.9.

**Comment by Thomas101** [comment]
Ah! I wonder if this is to do with this commit (6f782d62d524d821cc9a66ca900ac85b6b2a8239). @Ligerx does it work for you in version 1.3.9 with the cookie persistence turned on?

**Comment by GalawynRM** [comment]
Not sure, it's the same problem, but me too with an educational google account, it's working well with cookie persistence of 1.3.9, but not way i'm able to make it work in 1.4.0.
For all the rest, one of the best mail account ever!

**Comment by Thomas101** [comment]
on 1.3.9 if you add your education account afresh (so you have two versions of the same account) and restart WMail do you stay logged in? As regards the cookie persistence once you've logged in with the persistence turned on, you wont see the effects of turning it off or on for another 30 days or so.

**Comment by Thomas101** [comment]
This should be fixed in 2.0.0
