### ISSUE TITLE
Login autostart minimized

### ISSUE THREAD

**Issue by DominicBarnard** [Thomas101/wmail#367]
I'm looking to have WMail open as minimized when user logs into Ubuntu for all users on the system. 

I can easily autostart WMail for all users with a WMail.desktop file in /etc/xdg/autostart. But i can't access the users settings to set the start minimized option which means WMail will pop on screen the first time user logs in and then leave to the user to change settings inside WMail to set to start minimized.

An answer be to add a command line arg to WMail giving option to open minimized. Then I can set the .desktop file to exec WMail with the arg to start minimized.

Any other solution/workaround would be appreciated.

Using Version 1.4.0 on Ubuntu 16.04

**Comment by Thomas101** [comment]
Hi, when you start WMail you can add the `--hidden` or `--hide` flag, this will start it with the main window hidden

**Comment by DominicBarnard** [comment]
Awesome, thanks very much!

**Comment by Gibbz** [comment]
what is the command line arg to start WMail? I cant find it anywhere!

**Comment by Thomas101** [comment]
@Gibbz if you're using linux and installed using the deb package you should be able to do `/opt/wmail-desktop/WMail` to start
