### ISSUE TITLE
Unread Email Counter

### ISSUE THREAD

**Issue by webchun** [Thomas101/wmail#368]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.1
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS Sierra

The count number doesn't looks good when we have a lot of unread items

<img width="259" alt="wmail" src="https://cloud.githubusercontent.com/assets/4277547/19422226/5a7f0938-943b-11e6-9fa1-c3e2f5f0f7e8.png">

**Comment by webchun** [comment]
Hi thomas, It looks much better now, but once you have more than 100 unread emails then it's starting to look boring and less informative with the '100' number. 
I'd like to suggest to make the counter support up to 999 and rounding thousand with K.  
<img width="264" alt="counter" src="https://cloud.githubusercontent.com/assets/4277547/19672164/60ce2634-9a9e-11e6-89da-ecf7bc8964e3.png">

**Comment by Thomas101** [comment]
Yeah I agree with you - have updated. Thanks

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!
