### ISSUE TITLE
Memory Comsumption

### ISSUE THREAD

**Issue by webchun** [Thomas101/wmail#369]
* Which version of WMail are you using? [e.g. 1.3.1]
1.3.1
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS Sierra

I'm using wmail with 4 gmail accounts and it consume about 2.4 GB of RAM. Is it something that  can be improved?

<img width="498" alt="wmail2" src="https://cloud.githubusercontent.com/assets/4277547/19422587/c937be38-9440-11e6-810e-25b0840fa903.png">

**Comment by Thomas101** [comment]
Hi, 2.4GB does seem very high. On my machine I'm currently seeing 420mb with two accounts). Is this on the same machine with all the unread messages (#368)? If so what's the total unread count? 

If you try the latest pre-release do you see the same issue? **Before installing** the you may want to back up your settings as the Prerelease channel has backwards-incompatible changes. [Full instructions here](https://github.com/Thomas101/wmail/wiki/Installing-Prereleases) just in case you want to go back and don't want to re-setup your accounts

**Comment by webchun** [comment]
Yes, it's the same machine as the #368 but with 4 accounts. The total unread count is 40 K emails ^_^

**Comment by Thomas101** [comment]
Wow... 40k! How do you sleep at night? lol. Did you try it with the pre-release to see if that was any better. There's lots of code updates in the current pre release branch

**Comment by ffumarola** [comment]
Here is my memory footprint with 1.4.0 on macOS Sierra 10.12. I have ~50 unread emails across 2 accounts.

<img width="795" alt="screen shot 2016-10-18 at 12 43 59 pm" src="https://cloud.githubusercontent.com/assets/671632/19493715/adc39dc0-9530-11e6-9d0f-edca556f078f.png">

**Comment by Thomas101** [comment]
@ffumarola if you restart wmail is the memory consumption that high straight away or does it take time to get up to that level?

**Comment by ffumarola** [comment]
Just restarted wmail and here's mem usage

<img width="800" alt="screen shot 2016-10-19 at 12 57 15 am" src="https://cloud.githubusercontent.com/assets/671632/19510283/624194d0-9597-11e6-82e7-7858c153857e.png">

**Comment by Thomas101** [comment]
Thanks. I could really do with some more information about what's going on across all processes. Would you able to do the following for me?

1.) Start up WMail and take another snapshot of your activity monitor

2.) In WMail go to `View > Developer Tools` and make sure the `console` tab is selected

3.) Paste in the following `process.getProcessMemoryInfo()`. You should get something like...
```js
Object {workingSetSize: 99436, peakWorkingSetSize: 0, privateBytes: 56776, sharedBytes: 80432}
```
Can you copy and paste what that outputted for me?

4.) Go through each mailbox in turn, right clicking on the account icon and choosing `Inspect`. A new window will open, repeat selecting `console` and pasting `process.getProcessMemoryInfo()`. Then copy and paste the output for each mailbox.

5.) Finally for the last step can you completely quit google chrome, relaunch it and sign in to one of your accounts then take a snapshot of what Chrome is using in the activity monitor?

Thank you!

**Comment by ffumarola** [comment]
1) New snapshot after restarting Wmail
<img width="801" alt="screen shot 2016-10-22 at 10 48 22 am" src="https://cloud.githubusercontent.com/assets/671632/19621408/249212e8-9846-11e6-9c5e-67ff347cb6d9.png">

2+3) View > Developer Tools
Object {workingSetSize: 176772, peakWorkingSetSize: 0, privateBytes: 119092, sharedBytes: 90940}

4) Inspect+console for each mailbox
VM651:1 Uncaught ReferenceError: process is not defined

5) Chrome snapshot after restarting w/ extensions turned off
<img width="803" alt="screen shot 2016-10-22 at 10 53 55 am" src="https://cloud.githubusercontent.com/assets/671632/19621411/2c9eadac-9846-11e6-841a-385e00c867a6.png">

**Comment by Thomas101** [comment]
Thanks for that @ffumarola . Looking at it those latest numbers that's what I'd expect and consumption is still lower than chrome. As regards the near gig of memory consumed in your original post I'll add a button in to grab some debug information to see if this a memory leak in Inbox or a memory leak in something WMail is doing.

@webchun if you've got 4 accounts you should be seeing 6 processes rather than 8. 1 for each mailbox, one for the WMail UI and one for the WMail app so it's strange that you're seeing 8 helpers. If you try restarting the app afresh what's the memory consumption and process count?

**Comment by webchun** [comment]
Hi @Thomas101 sorry for no response since the last time. Things were a bit hectic last week and I didn't get chance to make some tests. I'll make some test to day with 4-5 emails and let you know the results

> Wow... 40k! How do you sleep at night?
lol 
well one account have arround 35k emails actually. Most of them are just transactional emails from one of my website and I never opened them

**Comment by Thomas101** [comment]
I've added a button into the next release which gives some more detailed information about the memory consumed by each item. Will move this issue into the next pre-release and then revisit it when we can grab a bit more info about what's going on. Thanks everyone

**Comment by webchun** [comment]
Here's the current memory footprint of wmail prerelease 2.0.1 with 4 accounts.  
It's much improved now!

<img width="666" alt="memory_footprint" src="https://cloud.githubusercontent.com/assets/4277547/19672313/896d1220-9a9f-11e6-996e-9a813995f248.png">

**Comment by Thomas101** [comment]
Hi, I've added a button into the settings screen which gives information on what element is consuming memory. If you open settings then look for a blue link which says `Memory Info`. Click this and it will give you brief overview of the memory used by each mailbox and the main processes etc

**Comment by webchun** [comment]
ok nice. Here's the memory footprint

<img width="418" alt="wmail" src="https://cloud.githubusercontent.com/assets/4277547/19776828/ddec7528-9c9f-11e6-8c45-8bd8c84ef82d.png">

**Comment by Thomas101** [comment]
These numbers seem to be approximately what I'd expect to see. It would be great if you could keep an eye on the numbers though and if you notice the memory consumption has jumped or climbed slowly re-send information about what the OS reports and also what WMail reports. I can then look to see if this is a memory leak with Gmail & Inbox or with WMail itself.

As a side note though, Google have announced that chrome 55 ships with an updated JavaScript engine ([link](https://www.engadget.com/2016/10/09/chrome-55-reduces-memory-use/)). This is meant to reduce memory consumption by up to 50%. This should hit mainstream chrome around the end of the year and I suspect will hit electron and WMail early in 2017 :-)
