### ISSUE TITLE
bug: when clicking on notification, popup with error then app crashes

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#37]
when i click on a notification, it tells me that it can't open the message because of a pop-up blocker (which might or might not be the case, i have to check but not sure how since it's the application itself that blocks it as far as i understand).

Then when clicking on ok, the message closes down but when going to wmail it window is all blank and i can't do anything. need to restart the whole application 

version: 1.1.3 on gmail (not inbox)

**Comment by Thomas101** [comment]
We should disable the the in-browser notifications and put out our own when we check for the unread counts

**Comment by Thomas101** [comment]
We should be able to disable the default gmail notifications once https://github.com/atom/electron/issues/4174 makes it into the next release. This should stop the crashing. Our own implementation in #35 will be able to take over from this then
