### ISSUE TITLE
Notifications and proxy

### ISSUE THREAD

**Issue by J-Louis** [Thomas101/wmail#370]
- Which version of WMail are you using? 1.4.0
- Which Operating System are you using? Windows7

Sounds like the notifications (popup and systray icon) don't work in a proxy context.
note: my windows configuration uses a proxy .pac (a script to calculate the proxy @)

**Comment by Thomas101** [comment]
Hi, have you setup the proxy server in WMail under settings > advanced?

**Comment by J-Louis** [comment]
Yes. And WMail works well for connecting to GMail and reading mails just the notifications and systray state don't work.

**Comment by Thomas101** [comment]
The webview which provides the window into gmail and inbox automatically gets the proxy details from the OS however the http calls don't which is why it has to be configured separately.

I'll take a look into it to see why it's failing

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!

**Comment by J-Louis** [comment]
Still the same problem with the 2.0.5

**Comment by Thomas101** [comment]
If you go to View > Developer Tools then click on the console tab do you see any errors or warnings coming up?

**Comment by Thomas101** [comment]
Hi, version 2.2.0 and 2.2.1 should handle proxies much better. They're available to [download here](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!
