### ISSUE TITLE
cmd + a doesn't select all

### ISSUE THREAD

**Issue by ffumarola** [Thomas101/wmail#372]
* Which version of WMail are you using? [e.g. 1.3.1]
1.4.0 prerelease

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS Sierra (10.12)

cmd (apple) + a doesn't work for select all

**Comment by Thomas101** [comment]
Hi, this is waiting in the queue to go out in the next release (#357) so should be with you soon!
