### ISSUE TITLE
Unread count only shows for one inbox

### ISSUE THREAD

**Issue by ffumarola** [Thomas101/wmail#373]
* Which version of WMail are you using? [e.g. 1.3.1]
1.4.0 prerelease

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS Sierra (10.12)

I have a personal gmail inbox and a work/google apps inbox, and the unread count only shows on my personal inbox.

<img width="242" alt="screen shot 2016-10-18 at 12 39 34 pm" src="https://cloud.githubusercontent.com/assets/671632/19493582/28bbf712-9530-11e6-8bc8-c5b8a61dfab9.png">

<img width="240" alt="screen shot 2016-10-18 at 12 39 54 pm" src="https://cloud.githubusercontent.com/assets/671632/19493583/28c004ec-9530-11e6-9570-ce8ec25b354b.png">

edit: sorry the numbers are one off... I deleted an email between taking screenshots :)

**Comment by Thomas101** [comment]
Hi, if you go to `View>Developer Tools` do you see any errors appearing in the console? Sounds like somethings failing on one of your accounts

**Comment by ffumarola** [comment]
This is all that shows in console:

<img width="553" alt="screen shot 2016-10-20 at 10 28 33 pm" src="https://cloud.githubusercontent.com/assets/671632/19587615/9717516c-9714-11e6-9f36-2bb952d44bfb.png">

**Comment by Thomas101** [comment]
Looks like something's gone wrong authenticating with google. If you re-add the account does it work after that?

**Comment by ffumarola** [comment]
@Thomas101  I don't think that's the issue, because it's adding the unread notifications across both accounts to my unread label on my personal account. Also, is there any way to reauthenticate without deleting the inbox and then re-adding it?

**Comment by Thomas101** [comment]
Ah, I see. Wow, that is weird. Which version of WMail did you update from? Was it the 1.3.9 pre release or 1.3.1 main release?

**Comment by ffumarola** [comment]
1.4.0 pre release fresh install and I have now upgraded to 2.0.0 release channel.

I'll uninstall and do a clean install.

**Comment by ffumarola** [comment]
Actually, looks like I had upgraded from 1.2.1. But, doing a clean install didn't do the trick. Deleting the account and re-adding the accounts DID. 

Now to debug why the unread counts are different than gmail on the web.

Account #1 
<img width="178" alt="screen shot 2016-10-22 at 11 22 39 am" src="https://cloud.githubusercontent.com/assets/671632/19621598/06e30f78-984a-11e6-8e09-d3db18a94b16.png">

<img width="83" alt="screen shot 2016-10-22 at 11 22 46 am" src="https://cloud.githubusercontent.com/assets/671632/19621599/0c7b6ebc-984a-11e6-8169-3e9bbf9c4a80.png">


Account #2 
<img width="191" alt="screen shot 2016-10-22 at 11 23 01 am" src="https://cloud.githubusercontent.com/assets/671632/19621596/00379c98-984a-11e6-9620-b329be31915c.png">

<img width="76" alt="screen shot 2016-10-22 at 11 23 06 am" src="https://cloud.githubusercontent.com/assets/671632/19621597/03e14a10-984a-11e6-9ead-22a72a0d9182.png">

Want me to create another ticket?

**Comment by Thomas101** [comment]
No, we can continue tracking that from here. What kind of gmail inbox are you using? You may need to change the unread mount in WMail by going to Settings > Accounts and picking from the unread mode dropdown

**Comment by ffumarola** [comment]
I just rotated wmail through all of the different unread count types and none matched.

Example for one account:
Gmail says: 28
Wmail All Unread: 55
Wmail Unread in Primary: 38
Wmail Unread Important: 46
Wmail All in Inbox: 100

**Comment by Thomas101** [comment]
Thanks I've managed to narrow this down and it will be out in the next pre-release

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!

**Comment by ffumarola** [comment]
Just upgraded and it reintroduced the issue where only one of my accounts shows the unread count now. Will delete + readd, but FYI.

<img width="97" alt="screen shot 2016-10-26 at 2 43 26 pm" src="https://cloud.githubusercontent.com/assets/671632/19746290/95a50c32-9b8a-11e6-8968-fa3b568ffd83.png">

**Comment by ffumarola** [comment]
Once I deleted + re-added the accounts, unread counts are now accurate!

**Comment by Thomas101** [comment]
Awesome. Weird that you keep seeing that sync issue though. If it happens again can you raise another issue/recomment with the output of the console
