### ISSUE TITLE
Changing icon

### ISSUE THREAD

**Issue by brighthero** [Thomas101/wmail#374]
That may sound trivial, but I'd love to have a way to change the icon of the app (not tray icon) to something looking more like the actual Google Inbox icon. 
I understand that may be difficult due to copyright reasons, but I think it would be possible if you would let the user choose a custom icon.

**Comment by Thomas101** [comment]
Which operating system are you trying to do this on?

**Comment by brighthero** [comment]
Windows 10

**Comment by Thomas101** [comment]
I'm afraid not on windows, it would require the binary to be rebuilt to change the icon. Sorry!
