### ISSUE TITLE
Windows E-Mail-notification sound

### ISSUE THREAD

**Issue by VOOM108** [Thomas101/wmail#376]
- Which version of WMail are you using? [e.g. 1.4.0]
- Which Operating System are you using? [Windows 10]

Could WMail trigger the Windows E-Mail-notification sound instead of the standard notification? Or alternatively have a custom sound-setting in the settings?

**Comment by Thomas101** [comment]
Hi, I've opened a new issue as regards notifications (#452) to collapse a few issues which are all related. I'm going to close this but you can continue tracking it here #452. Thanks!
