### ISSUE TITLE
Feature Suggestion: Ability to pick browser to open link

### ISSUE THREAD

**Issue by avaorac** [Thomas101/wmail#377]
* Version 1.3.2

* I'm using MacOS Sierra

If possible, I would like a way to configure which browser the link will open it.  By default I use another browser at my work, but for personal sites I use Chrome.   If there's a setting to pick which browser is the default only when using WMail, that would be perfect.

**Comment by Thomas101** [comment]
There's no way to do this from within electron at the moment and support for opening urls from the command line can be patchy depending on browsers and versions.

Someone did suggest using something like [Choosy](https://www.choosyosx.com/) a while ago to pick opened links. I've got no personal experience with this, but it might be worth looking into it.
