### ISSUE TITLE
Dictionary language

### ISSUE THREAD

**Issue by tgrrr** [Thomas101/wmail#379]
Hi,

I've got my mac set to Australian/British English. The spell checker only works in US English, without the ability to add words to dictionary/ignore.

It keeps want to autocorrect 'How yer goin' maaaate' to 'Hi, how are you?'...

* Which version of WMail are you using? [e.g. 1.3.1]
1.3.1

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac 10.6.1

**Comment by Thomas101** [comment]
There's a bunch of improvements coming in 2.0.0 for spell checking including different english variations. The release should be going out in the next few hours :)
