### ISSUE TITLE
downloaded filename has temp.extenttion like ".download....

### ISSUE THREAD

**Issue by lcc40** [Thomas101/wmail#380]
- Which version of WMail are you using? [e.g. 1.3.1]
  2.0.1
- Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
  MacOs 10.12.1

---> downloaded filename has temp.extenttion like ".download....

**Comment by Thomas101** [comment]
Hi, it should be that it has the extension `.wmaildownload` whilst downloading but once the download is complete it should return to the proper filename (e.g. `image.png.wmaildownload` -> `image.png`). Did the file get stuck with `.wmaildownload` forever?

**Comment by slashjs** [comment]
I've noticed something which may help.

When downloading an attachment through WMail, the `.wmaildownload` file doesn't go away if viewing through a folder shortcut on the dock, as shown here:
![Docked folder](http://i.imgur.com/FCIGAUD.png)

However if you open the folder, there is nothing there:
![Finder/terminal](http://i.imgur.com/0QuLf6n.png)

You can resolve this issue by removing the folder shortcut from the dock, and then adding it again. The `.wmaildownload` file is then no longer visible.

**Comment by Thomas101** [comment]
@slashjs I've seen this a couple of times on osx. Possibly some incompatibility with node and the osx dock. I wonder if I move the file into `/tmp` and then delete it if that will work around the issue

**Comment by Thomas101** [comment]
I've taken a look into this and it seems to be that the dock is not refreshing the downloads folder. Looks like an issue with osx or maybe an issue with osx and nodejs together. Going to close this off for now as I don't see any clear way to resolve this. Thanks for reporting though!
