### ISSUE TITLE
Idea: Email tracking

### ISSUE THREAD

**Issue by ffumarola** [Thomas101/wmail#381]
- Which version of WMail are you using? [e.g. 1.3.1]
  2.0
- Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
  Sierra

Allow for email tracking on a per user level, similar to https://polymail.io/features

**Comment by Thomas101** [comment]
I've opened a new issue covering re-looking at chrome extensions as there's a few sub-issues as regards extensions. You can follow progress/info here #451
