### ISSUE TITLE
Idea: Send later

### ISSUE THREAD

**Issue by ffumarola** [Thomas101/wmail#382]
- Which version of WMail are you using? [e.g. 1.3.1]
  2.0
- Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
  Sierra

Allow for "send later" feature (similar to http://www.boomeranggmail.com/l/send-later.html or https://polymail.io/features)

**Comment by Thomas101** [comment]
I've opened a new issue covering re-looking at chrome extensions as there's a few sub-issues as regards extensions. You can follow progress/info here #451
