### ISSUE TITLE
Unreaded counter in window title

### ISSUE THREAD

**Issue by szebrowski** [Thomas101/wmail#383]
* Which version of WMail are you using? 2.0.1 prerelease

* Which Operating System are you using? Linux Arch

Hey, it would be greate to have option for unreaded messages in window title.

**Comment by Thomas101** [comment]
This should be an easy one to add in :)

**Comment by Thomas101** [comment]
Added this in 9c61c42acf93cc4c2ab050944cb893edbf57d2fe

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!

**Comment by szebrowski** [comment]
It works. Thanks. :)
