### ISSUE TITLE
RESOLVED: White Screen on 2fA

### ISSUE THREAD

**Issue by davidmcdougal** [Thomas101/wmail#384]
* Which version of WMail are you using? [e.g. 1.3.1] = 2.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] = Solus 1.2.1 with Budgie Desktop, 2.8.2 Kernel

So, here is the strange part.  I have Solus running on my desktop and laptop same versions, same packages etc only the desktop goes to a white screen and never gives me the 2FA verification so I cannot setup the email.  

Here are my desktop details if that helps.   I really love WMail on my laptop (System 76 machine) with Solus so would love to use on the desktop also.   I am using the raw tar, extracting it and running it from my home directory in a subfolder called WMail.
```
System:    Host: REMOVED Kernel: 4.8.2 x86_64 (64 bit)
           Desktop: Budgie 10.2.8  Distro: Solus 1.2.1
Machine:   Mobo: ASRock model: 970 Extreme3
           BIOS: American Megatrends v: P1.70 date: 10/12/2012
CPU:       Hexa core AMD Phenom II X6 1100T (-MCP-) cache: 3072 KB 
           clock speeds: max: 3300 MHz 1: 1700 MHz 2: 2500 MHz 3: 800 MHz
           4: 800 MHz 5: 800 MHz 6: 800 MHz
Graphics:  Card: Advanced Micro Devices [AMD] ATI Barts XT [Radeon HD 6800 Series]
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on AMD BARTS (DRM 2.46.0 / 4.8.2, LLVM 3.9.0)
           GLX Version: 3.0 Mesa 13.1.0-devel
Audio:     Card-1 Advanced Micro Devices [AMD] ATI Barts HDMI Audio [Radeon HD 6800 Series]
           driver: snd_hda_intel
           Card-2 Logitech driver: USB Audio
           Sound: Advanced Linux Sound Architecture v: k4.8.2
Network:   Card: Intel 82574L Gigabit Network Connection driver: e1000e
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full
           mac: 68:05:ca:0d:32:74
Drives:    HDD Total Size: 2496.5GB (13.5% used)
           ID-1: /dev/sdb model: ADATA_SP900 size: 256.1GB
           ID-2: /dev/sda model: Corsair_Force_GT size: 240.1GB
           ID-3: /dev/sdd model: WDC_WD1002FAEX size: 1000.2GB
           ID-4: /dev/sdc model: SAMSUNG_HD103SJ size: 1000.2GB
Sensors:   System Temperatures: cpu: 21.5C mobo: N/A gpu: 55.0
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 262 Uptime: 1 day Memory: 5075.2/16025.1MB
           Client: Shell (bash) inxi: 2.3.1 
```
Happy to supply any logs that may help.  I realize this is probably a one off, just weird that it is working well on another machine with the same OS version, and packages only a few hardware differences.   Both units are on the same network also, desktop and laptop are wired for the most part.

Thanks in advance.
David

**Comment by davidmcdougal** [comment]
I know I had done this on the 1.3 and 1.4 versions and it did not matter, but I turned on the GPU ignore and rebooted and it is working now.  So, must be a Radeon issue with my older GPU.

**Comment by Thomas101** [comment]
That was going to be my suggestion! I'm not too sure what the underlying issue is here or what combination of gpu/driver/os causes it.
