### ISSUE TITLE
Unread message mode suggestion

### ISSUE THREAD

**Issue by Braccae** [Thomas101/wmail#385]
There's an option for inbox to set the unread mode as all unread messages and all messages in the inbox but no option to set unread mode as unread emails in inbox. As someone that bundles emails from low priority once a week and leaves read emails in my inbox for when I can get to them, it's kind of annoying because I either constantly have unread emails in the app indicator or get notifications from all my low priority semi-junk mail all the time. I suggest an option to only show unread emails in the main inbox as 'unread' by the app indicator/full app.

* Wmail 2.0.1
* Ubuntu GNOME 16.10

**Comment by Thomas101** [comment]
Hi, this is down to the lack of inbox api's provided by Google. Unread counts are currently backboned through what Gmail provides. I'm looking at ways that I can grab this information to provide more information for inbox users and have an issue open for it here (#349). You can continue tracking progress there.

Thanks!
