### ISSUE TITLE
Disable Notifications for Bundled Emails

### ISSUE THREAD

**Issue by drewthatgamer** [Thomas101/wmail#387]
* Which version of WMail are you using? [e.g. 1.3.1] 2.0.1

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Mac OSX El Capitan

For certain email bundles, such as Promos, I don't want to see notifications for them. I was wondering if there was a way to get rid of only notifications for those emails, or if this can be a implemented feature?

**Comment by Thomas101** [comment]
Dupliate of #349
