### ISSUE TITLE
Notifications always showing 1 more email than is actually unread.

### ISSUE THREAD

**Issue by g105b** [Thomas101/wmail#388]
* Version 2.0.0.

* Ubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/358014/19663518/2f2c15ec-9a34-11e6-90b3-f23210757744.png)

**Comment by Thomas101** [comment]
Thanks for reporting! I've managed to narrow this down and it will be out in the next pre-release

**Comment by g105b** [comment]
Nice one, thanks dude!

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!
