### ISSUE TITLE
Wrong max count number in the menu bar

### ISSUE THREAD

**Issue by webchun** [Thomas101/wmail#389]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.1 prerelease
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS Sierra

In the pre-release 2.0.1 the max counter value in the menubar is 100. It works properly before it (version 2.0.0)
Please see the screenshot.

<img width="369" alt="wrong-counter" src="https://cloud.githubusercontent.com/assets/4277547/19672408/66efc76e-9aa0-11e6-848a-ff83bdd56ce0.png">

**Comment by Thomas101** [comment]
I think I'm hitting some quota limits on this. Would explain why it's hitting 100 on the dot too. I'll take a look into this to see what I can do

**Comment by Thomas101** [comment]
I think I've managed to fix this. Will be out in the next release

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!

**Comment by TomStaveley** [comment]
Hi @Thomas101 
I'm now seeing a very different number... 62! Previously it was stuck on 100, but my account actually has 200 unread emails now.

When moving from 2.0.0 to 2.0.3 pre release, I simply replaced the application file. Is this okay or should I be deleting any/all files within the Application Support directory when changing versions?

**Comment by webchun** [comment]
Same as @TomStaveley I see different numbers now. It says that I have 96 unread emails while I actually have 2027.

**Comment by Thomas101** [comment]
@TomStaveley @webchun  you may need to change the unread mode that's being used for the notifications. If you go to Settings > Accounts there's a dropdown which by default is `All Unread Messages`.

You can check if the searches are working correctly by pasting the different queries into the gmail search bar. The searches that the different modes run on are...

* **All Unread Messages** `label:inbox label:unread`
* **Unread Messages in Primary Category** `label:inbox label:unread category:primary`
* **Unread Important Messages** `label:inbox label:unread label:important`
* **All Messages in Inbox** `label:inbox`

Do one of these searches match the correct count?

**Comment by TomStaveley** [comment]
Afraid not @Thomas101. Here's some digits:

### Work account
All Unread Messages | Badge: 63 | Actual: 203
Unread Messages in Primary Category | Badge: 0 | Actual: 0
Unread Important Messages | Badge: 60 | Actual: 90
All Messages in Inbox | Badge: 100 | Actual: 10,600

### Personal account
All Unread Messages | Badge: 4 | Actual: 4
Unread Messages in Primary Category | Badge: 0 | Actual: 0
Unread Important Messages | Badge: 2 | Actual: 2
All Messages in Inbox | Badge: 100 | Actual: 32,673

**Comment by Thomas101** [comment]
@TomStaveley in gmail, if you go to the cog in the top right hand corner, and then settings. Under the Account tab there is a dropdown which says "Inbox Type". What's picked in that dropdown?

**Comment by TomStaveley** [comment]
@Thomas101 Settings > Inbox > Inbox type is set to Default on both.

**Comment by Thomas101** [comment]
Thanks, if you paste `label:inbox label:unread category:primary` into the gmail search bar how many messages do you get out? For me I get 7 search results which correlates to the number of unread messages displayed in my inbox on the left hand side

![screen shot 2016-10-29 at 12 22 08](https://cloud.githubusercontent.com/assets/103586/19829201/96289d5a-9dd2-11e6-8d1b-35f9afa95156.png)

**Comment by TomStaveley** [comment]
Doesn't return anything for either account. Maybe because I'm not making use of categories for either of them? They are both set as follows:
<img width="450" alt="screen shot 2016-10-29 at 13 01 15" src="https://cloud.githubusercontent.com/assets/4049079/19829393/d16f89b4-9dd7-11e6-8990-ca1f9b7558e2.png">

**Comment by Thomas101** [comment]
Okay I see the same with that. Looks like it kills off the primary inbox when you untick them all. What happens if you search for `label:inbox label:unread`?

**Comment by TomStaveley** [comment]
I get the expected number of unread results, 204 and 4 for work and personal respectively.

**Comment by Thomas101** [comment]
Okay, if you go to the WMail preferences and set the unread mode to be `All Unread Messages` then wait 60 secs or click anywhere in the gmail window and wait a few seconds does that update to be the right number?

**Comment by TomStaveley** [comment]
So that's the default setting, right? Which used to work for me up to and including V1.3.2.

Currently, that setting is still reporting incorrectly for my work account:
> All Unread Messages | Badge: 63 | Actual: 203

...but for my personal account, it's fine:
> All Unread Messages | Badge: 4 | Actual: 4

**Comment by Thomas101** [comment]
Thanks! I've just noticed there's an error case that doesn't get logged so it could be that your sync is running in error. I've uploaded a [copy of master with some extra logging](https://drive.google.com/file/d/0B--sEKXlbUTRcm9fZ21oQXhOZk0/view?usp=sharing). Could you try downloading it, then once open go to View > Developer tools and click on the console tab. From there can you send me a screenshot. Here's what I had...

![screen shot 2016-10-29 at 16 52 29](https://cloud.githubusercontent.com/assets/103586/19831017/1de7a11c-9df8-11e6-9ca9-b1cb334a80a2.png)

**Comment by TomStaveley** [comment]
<img width="1680" alt="screen shot 2016-10-29 at 17 09 54" src="https://cloud.githubusercontent.com/assets/4049079/19831138/9d495782-9dfa-11e6-97af-581bc687c7d5.png">

**Comment by Thomas101** [comment]
Brill thanks!  I see the same now :)

**Comment by Thomas101** [comment]
Fingers crossed this should be fixed in 2.0.4 if you want to [test it out](thomas101.github.io/wmail/download?v=2.0.4)

**Comment by TomStaveley** [comment]
Happy to report all is working perfectly now :)

**Comment by Thomas101** [comment]
Awesome! Thanks for your help!
