### ISSUE TITLE
Wrong count in unread badge 

### ISSUE THREAD

**Issue by TomStaveley** [Thomas101/wmail#391]
WMail v2.0.0
Mac OSX 10.10.5

I have two accounts, work and personal. Currently, my work account has 197 unread emails, and my personal has 6.

I added both accounts (both Gmail, not Inbox) to WMail, and my work account is reporting as 100 in the unread badge. Personal is working correctly with 6.

<img width="237" alt="screen shot 2016-10-25 at 11 51 13" src="https://cloud.githubusercontent.com/assets/4049079/19683235/66400d48-9aa9-11e6-81e8-9efd56d81184.png">

I believe this problem has existed in all previous releases as far back as V1.3.2, which was the version I was 'pegged back' to because of this issue existing.

Any ideas?

**Comment by BradipoEremita** [comment]
I have the same problem, the icon on the unity bar shows 12 unread mail that do not exist

**Comment by Thomas101** [comment]
@TomStaveley this looks like some quota limits have been hit. This is the same issue as #389 so I'll close this and you can continue tracking from there.

@BradipoEremita I think this is the same as #388 which is fixed and waiting to go out in the next release.

Thanks both for reporting!
