### ISSUE TITLE
Account removal is non-obvious

### ISSUE THREAD

**Issue by singerb** [Thomas101/wmail#393]
WMail 2.0.0, OS X

Removing an account requires a right click on the account icon in the sidebar, which is non-obvious (even after that's fixed to use the standard Mac right click mechanisms). The account list in the preferences should give an option to remove the account (and the dropdown to change accounts should be more obviously a dropdown; I initially thought it was a text field for the name of the account).

**Comment by Thomas101** [comment]
Thanks! Added title to dropdown to make it more obvious. Added delete button
