### ISSUE TITLE
Feature request: textual sidebar

### ISSUE THREAD

**Issue by singerb** [Thomas101/wmail#394]
Some people would rather have text labels than icons in the sidebar to distinguish their accounts; this might require the sidebar to be a little wider. Looking more like a traditional mail client (i.e. Mail.app) in this regard is both an upside for user familiarity, and a downside in terms of a unique look, but if configurable it could be useful.

**Comment by Thomas101** [comment]
The trouble with this is that the amount of horizontal screen real estate required is at least double what is currently used for the sidebar and the amount of vertical real estate used is vastly reduced. I really want WMail to get out of the way of the Gmail UI as it's nothing more than a little fluff around switching accounts.

I think Mail.app places the folders & labels under the heading to preserve the used space but in WMail this would require hacking the Gmail and Inbox UI which is tempremental to say the least.

A good compromise could be to add instant tooltips like what the settings and add button use. This isn't supported by the ui library that I'm using at the moment, but it is on their todo list (https://github.com/callemall/material-ui/issues/2230). So once that's been added I'll look into adding those in.
