### ISSUE TITLE
credentials.js when using binaries

### ISSUE THREAD

**Issue by skydiver** [Thomas101/wmail#395]
(WMail 2.0.0, Linux)

It's possible to use own **GOOGLE_CLIENT_ID** and **GOOGLE_CLIENT_SECRET** from the compiled builds (deb) ?

Maybe use credentials.js or just a new advanced option.

**Comment by Thomas101** [comment]
At the moment there's no way to customise this. I was thinking that if you're happy enough to set yourself up with google you're probably looking to build the from source. Do you have a specific use case for this?

**Comment by skydiver** [comment]
I was thinking to use on a corporate environment and personalize the "content screen"

**Comment by Thomas101** [comment]
Which content screen are you looking at? The one when you add an account or something different?

**Comment by skydiver** [comment]
sorry for my misspelling, "consent screen" 
![screenshot from 2016-10-28 20-48-16](https://cloud.githubusercontent.com/assets/578784/19826096/90697b7e-9d59-11e6-9f4b-b56ad06e6f17.png)

**Comment by Thomas101** [comment]
Ah okay I see. I would be reluctant to add this in to the compiled version as there's a high potential for this to break in the future. If I need to add extra permissions or update the auth settings for new features then I also need to communicate these out to anyone using their own credentials before the auto-update gets pushed out.

If you really do want to add your own consent screen though WMail does compile from source pretty easily. Once you've gone to the effort of setting up your [Google Identity](https://github.com/Thomas101/wmail/#building-from-source) you just need to run

```sh
npm install webpack -g
cd /your_wmail_directory/
npm run-script install-all

# if you want to test everything's working before packaging
npm start

# if you're happy to copy the binaries into /opt/wmail or somewhere else yourself
node packager --platform=linux

# if you want the deb file and a tar file generated for you
node packager --platform=linux --distribution
```
