### ISSUE TITLE
Non-graceful halt loses accounts

### ISSUE THREAD

**Issue by jonnixs** [Thomas101/wmail#396]
Whenever the system falls over or needs forcefully rebooted, on restart of Wmail, no accounts are available and you have to set them all up again.

Wmail 1.3.9 but has been happening for the last few point releases and at least one minor version. Upgraded to version 2.0.1 in case of fix

Ubuntu 16.04 x64.

Thanks.

**Comment by Thomas101** [comment]
Is this when wmail falls over or when the os falls over? I'm guessing that node is crashing/being killed mid write. It might be worth me using something to ensure atomic writes. (maybe [write-file-atomic](https://github.com/npm/write-file-atomic))

**Comment by jonnixs** [comment]
It's when the OS falls over and you need to manually power cycle (as an example).

**Comment by Thomas101** [comment]
Thanks, I've switched it across to `write-file-atomic`. Hopefully this should provide enough to protection and only result in changes being lost. Feel free to re-open or comment if you still see the issue after the next release. Thanks!

**Comment by jonnixs** [comment]
Will do.

Thanks for all the good work :).

**Comment by Thomas101** [comment]
Hi, this has made it out into the latest [pre-release](https://thomas101.github.io/wmail/download). It would be awesome if you could give it a go to see if it's been fixed. Thanks!

**Comment by jonnixs** [comment]
Have installed, will report back if it happens again.

Thanks for the quick work.
