### ISSUE TITLE
How to use the core of wmail to build desktop app for other web apps like messenger

### ISSUE THREAD

**Issue by jvalenciag** [Thomas101/wmail#397]
Hi,
I would like to use the of wmail to build a desktop app for ex. messenger, whatsapp.. or include support for those web apps in wmail. There is an app for chrome that do it but google is deprecating chrome apps.

[https://chrome.google.com/webstore/detail/all-in-one-messenger/lainlkmlgipednloilifbppmhdocjbda](https://chrome.google.com/webstore/detail/all-in-one-messenger/lainlkmlgipednloilifbppmhdocjbda)

Thank you.

**Comment by Thomas101** [comment]
Hi, if you're looking for an all-in-one solution I would recommend [Franz](http://meetfranz.com/). They've got a lot of support for different messaging apps. WMail is more focused on providing enhanced support for Gmail and Google Inbox.

**Comment by jvalenciag** [comment]
It is possible to use the core of wmail to not start building from scratch?

**Comment by Thomas101** [comment]
If you're happy to get your hands dirty and write some code then definitely! It's not something I've been able to invest any time into at the moment, but if you'd like to add it in I would definitely be happy to help and accept pull requests!
