### ISSUE TITLE
Missing shortcut CMD+H

### ISSUE THREAD

**Issue by DerSiedler** [Thomas101/wmail#4]
Hi, great work so far. Last time I saw such a super easy way to change my multiple accounts is years ago as a firefox plugin. But as many plugins it died due to FF worst decision ever to start the version battle with Chrome.

One tiny issue is the missing CMD+H shortcut. I use it a lot to minimize apps to the dock.

**Comment by parro-it** [comment]
@Thomas101 could I suggest you to use (electron-localshortcut)[https://github.com/parro-it/electron-localshortcut] module to implement shortcuts? (I'm the author)

**Comment by Thomas101** [comment]
Thanks for the heads up on your library @parro-it :+1:

**Comment by DerSiedler** [comment]
perfect

**Comment by parro-it** [comment]
@Thomas101 your welcome, glad you're using it!
