### ISSUE TITLE
Choose and enforce a code style

### ISSUE THREAD

**Issue by parro-it** [Thomas101/wmail#40]
To improve source code, it would be great if you choose a formal code style and enforce it using a tool like eslint or similar. I see you're using something similar to [standard](https://github.com/feross/standard).

If you want, I'll can help setting up the process and correcting code style errors.

**Comment by Thomas101** [comment]
Yeah this looks good! Looks pretty much what I try and code to already so lets give it a shot!

**Comment by parro-it** [comment]
Ok, I'll prepare a PR for this. I probably require your help to complete it...

**Comment by Thomas101** [comment]
Thanks @parro-it merged the PR in. Looking good!
