### ISSUE TITLE
Quit behaviour incorrect osx

### ISSUE THREAD

**Issue by DasBlatz** [Thomas101/wmail#400]
* Which version of WMail are you using? 2.0.3

* Which Operating System are you using? Mac OSX 10.12.1

get always silent crashes, open the app read mails, minimise or move it in background. after a while the app is completly closed?!

**Comment by Thomas101** [comment]
Does OSX come up with an application has crashed dialog? Once it has crashed if you open the activity monitor and search for WMail do you see any running processes?

**Comment by DasBlatz** [comment]
no crash dialog or message at all. I will keep an eye on console, next time the app is gone

**Comment by DasBlatz** [comment]
**update** 
found the bug 

the **red „x“** on the top left _sometimes_ closes the app completely, this is an unexpected behaviour for the red button in OSX. Only **CMD+Q** closes the app! 

Clicking the „x“ only should hide the window. Please fix this @Thomas101

**Comment by Thomas101** [comment]
Hmmm it's a bit of an art to figuring this out. I'll take a look to see where the hole is

**Comment by Thomas101** [comment]
This has been fixed in [2.0.4](thomas101.github.io/wmail/download?v=2.0.4). Thanks!
