### ISSUE TITLE
Enhancement request: Allow to add/modify the account icon at the side bar

### ISSUE THREAD

**Issue by hexion** [Thomas101/wmail#406]
A new menu option for the right click menu over an account icon in the side bar could allow to select a new image for the account icon. This change would be local to wmail, and would take preference over gmail's profile image.

* Which version of WMail are you using? [e.g. 1.3.1]
2.0.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 14.04

**Comment by Thomas101** [comment]
Hi, you can already change the icon by going into settings, then clicking the accounts tab and using the `Change Account Icon` button. This as you said is local to WMail.

Version 2.0.3 also has an `Account Settings` option when you right click to take you straight through to the settings for the account too.

**Comment by hexion** [comment]
My bad, did not see the option although it is quite visible!
Thanks
