### ISSUE TITLE
Enhancement request: Left click on the status bar icon hides the main window when it is visible

### ISSUE THREAD

**Issue by hexion** [Thomas101/wmail#407]
At the moment, if the main window is hidden clicking on the status bar icon displays the main window, but doing the same when the window is shown does not hide the window.

This behaviour could be made more consistent by implementing this suggestion.
- Which version of WMail are you using? [e.g. 1.3.1]
  2.0.0
- Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
  Ubuntu 14.04

**Comment by Thomas101** [comment]
Great idea! I think linux and windows will support this. For osx I can add a hide option to the dropdown

**Comment by hexion** [comment]
Thanks for considering it!

**Comment by Thomas101** [comment]
Hi, this has just been released in the 2.0.6 prerelease which you can download [here](https://thomas101.github.io/wmail/download?v=2.0.6). Thanks!

**Comment by hexion** [comment]
Works like a charm! Thanks for implementing it.
I'll buy you a beer as soon as paypal.me is available over here.

2016-11-08 19:52 GMT+00:00 Thomas Beverley <notifications@github.com>:
