### ISSUE TITLE
Linux file size

### ISSUE THREAD

**Issue by Frikki** [Thomas101/wmail#408]
* WMail 2.0.3 64-bit
* Linux Mint 17.3 Cinnamon

First, I’d like to thank you for a wonderful piece of software.

This isn’t really an issue, but I wonder why the `.deb` package file size is 52 MB. It seems incredibly big. In comparison, VSCode is nearly half the size, 32 MB.

**Comment by Thomas101** [comment]
I think microsoft must be doing a custom build of electron or something where as I'm using the prebuilt binaries which might include some extra stuff that microsoft have taken out. Electron itself comes in at 40-50mb compressed according to this [issue](https://github.com/electron-userland/electron-prebuilt/issues/187) and theres about 15mb of WMail stuff on top of that.

In terms of wastage I know the spellchecking module has some duplicate code in it for different platforms which could shave off a few megs but I need to update the build process to do that. The Google APIs library is quite heavy coming in at 1.4 megs. There's definitely stuff that could be pulled out of that but it becomes an extra support task as they seem to do a release once a week.

Realistically I could probably bring the distributed files down to the 45-50 meg mark but to get something close to 32 means they're doing something clever
