### ISSUE TITLE
The unread counter isn't working and i'm not receiving notifications

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Thomas101/wmail#409]
- Which version of WMail are you using? [e.g. 1.3.1]
  2.0.0
- Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
  macOS Sierra

As stated in the title, the unread counter always shows 'No unread mail' and when I receive mail it doesn't give a notification.

**Comment by Thomas101** [comment]
Hi are you using a proxy server?

**Comment by GijsGoudzwaard** [comment]
@Thomas101 No.

**Comment by Thomas101** [comment]
Do you see any message counts at all or is it always stuck at 0? Are you using inbox or Gmail? If you go to View > Developer Tools and click on the console tab do you see any errors in the window?

**Comment by GijsGoudzwaard** [comment]
It is always stuck at 0, I am using Inbox.
There are no errors but I do have 1000+ warnings:

![screen shot 2016-10-30 at 19 03 01](https://cloud.githubusercontent.com/assets/5947260/19838610/869aab92-9ed3-11e6-905b-25ac5929b49d.png)

**Comment by Thomas101** [comment]
By the look of it there's some kind of error communicating with the Google servers.

If you restart WMail, or click the plus on icon in the bottom left corner and re-add your same account do you start to see any counts?

**Comment by GijsGoudzwaard** [comment]
@Thomas101 Re-adding my account worked, thanks!

**Comment by Thomas101** [comment]
That's good to hear. Not sure why it went haywire. Could well be something on Googles end. Thanks!

**Comment by aurimus** [comment]
@Thomas101  I have the same issue with Gmail inbox. Here's a screenshot, Primary has 2 unread emails (I only want to see the unread count from primary) and the notification icon says nothing.

![screenshot from 2016-11-03 11-38-23](https://cloud.githubusercontent.com/assets/1052992/19961287/738d0a38-a1ba-11e6-9d7c-eed619663361.png)

**Comment by Thomas101** [comment]
@aurimus, if you go to the accounts tab what's selected under `Unread Mode`?

**Comment by aurimus** [comment]
@Thomas101 I had forgotten the option "Add unread count to app unread messages count". It's working, thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released in the 2.0.6 prerelease which you can download [here](https://thomas101.github.io/wmail/download?v=2.0.6). Thanks!
