### ISSUE TITLE
Taskbar shortcut gets invalidated after every upgrade to new version

### ISSUE THREAD

**Issue by Eldaw** [Thomas101/wmail#410]
There's still something not quite right with the installation. After upgrading to each new release or pre-release, the shortcut for WMail that is pinned to my taskbar gets invalidated -- the icon changes to a blank page icon and when I click on it I get an error that the shortcut's destination could not be found and am then given the option to delete the shortcut.

Furthermore, if I use the start menu to search for WMail and then right-click on it, there is no option to 'Pin to Taskbar' like there should be. See screenshot:
http://imgur.com/a/SstYO

**Comment by Thomas101** [comment]
Thanks which version did you go from to when upgrading?

**Comment by Eldaw** [comment]
I upgraded from 1.4.0 to 2.0.0, and from 2.0.0 to 2.0.4.

**Comment by Thomas101** [comment]
Okay, thanks I'll take a look into this

**Comment by Thomas101** [comment]
When you first clicked on WMail after install did you get the "Please wait while Windows configures WMail" box like in #350 or did it just launch as normal?

**Comment by Eldaw** [comment]
It appeared to launch as normal. But it's only after launching WMail for the first time after install that I even get the option to 'Pin to taskbar'. So something is happening/changing after launching for the first time each time.

**Comment by Thomas101** [comment]
It certainly looks that way :-(

**Comment by Thomas101** [comment]
I've changed the library I use for generating the installer in 2.0.6 which I'm hoping will fix the right click pin to taskbar issue, however I do see that after installing the taskbar icon continues to be invalidated every time.

**Comment by Thomas101** [comment]
Hi, this has just been released in the 2.0.6 prerelease which you can download [here](https://thomas101.github.io/wmail/download?v=2.0.6). Thanks!
