### ISSUE TITLE
Don't notify for Low Priority on Inbox account

### ISSUE THREAD

**Issue by karlgrz** [Thomas101/wmail#415]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

Thanks for awesome client, as usual :-)

On my phone, I don't get notifications for mail that goes to Low Priority on my Inbox accounts. This is excellent!

However, on wmail, I get a notification for each of these messages. It would be great to not get these notifications, or, at the very least, have a configuration setting to turn them off.

**Comment by Thomas101** [comment]
Hi, glad you're enjoying it :). Is this something that's started in the last couple of pre-releases?

When you talk about low priority do you mean items that fall into `Everything else` on Gmail, or items that are bundled together in Google Inbox?

**Comment by karlgrz** [comment]
I am referring specifically to the Low Priority bundle in Inbox. I'm not sure if that's a default or something that I configured, although I don't remember configuring anything specific. From Inbox UI:

![ss](https://cloud.githubusercontent.com/assets/548140/19905597/86ba802a-a045-11e6-9a17-08eb607299e7.png)

You know, I think I've always gotten these notifications on wmail, just now I am starting to get a ton of emails that fall there from work and I've noticed it more lately due to that larger volume.

Hope this helps, let me know if I can add any more details.

**Comment by Thomas101** [comment]
Ah okay, just wanted to check it wasn't one of the changes I've made since 2.0.0. At the moment the unread counts and notifications all come off gmail (even if you're using inbox) as Google doesn't provide an api for Inbox just yet. I've not quite figured out how I'm going to add it in yet but I've opened up an issue here (#349). You can continue tracking from there :)

**Comment by karlgrz** [comment]
:+1: sounds good to me! Thanks!
