### ISSUE TITLE
Notifications don't parse lower case subject

### ISSUE THREAD

**Issue by lilHermit** [Thomas101/wmail#416]
* Which version of WMail are you using? 2.0.5

* Which Operating System are you using? Ubuntu 16:10

-----
Any email with the header "subject: test" shows as "no subject" in notification. It parses ok in the message list within the app

**Comment by Thomas101** [comment]
Hi, I've sent myself a couple of emails with "test" as the subject and also "subject: test" but both of these get the subject okay. Do you still see this problem?

**Comment by lilHermit** [comment]
My bad I wasn't clear enough it the initial report (Must have got distracted). The issue is when the header is "subject: test" rather than "Subject: test" (notice lower case S). The issue title is mislead too. Apologies!

**Comment by Thomas101** [comment]
Ah I'm with you now. Just out of curiosity do you know which client sends lowercase headers?

**Comment by lilHermit** [comment]
Excellent prompt fix! It's not a mail client, it's a company back-end payment system

**Comment by Thomas101** [comment]
Hi, this has just been released in the 2.0.6 prerelease which you can download [here](https://thomas101.github.io/wmail/download?v=2.0.6). Thanks!
