### ISSUE TITLE
Notification actions

### ISSUE THREAD

**Issue by Nxt3** [Thomas101/wmail#419]
The ability to customize some notification actions for the notification would be awesome. For example, being able to delete an email from the notification or marking it as done.

**Comment by markmckenna** [comment]
For Inbox, I'd love to see 'snooze' and 'done' options, with a dropdown for the snooze time.

**Comment by Thomas101** [comment]
Hi, I've opened a new issue as regards notifications (#452) to collapse a few issues which are all related. I'm going to close this but you can continue tracking it here #452. Thanks!
