### ISSUE TITLE
When clicking any link on an email it opens two tabs at the same time instead of one as expected.

### ISSUE THREAD

**Issue by lautarorb** [Thomas101/wmail#42]
Im with OSX 10.11.2 and WMail 1.0.0 and Chrome 47.0.2526.106 (64-bit) as default browser.

**Comment by bertrandmartin01** [comment]
You should try to download the latest wmail version it's been solved as far
as I remember

**Comment by lautarorb** [comment]
Sory, my bad! Great app by the way, thanks!!!
