### ISSUE TITLE
New version not picking up unread emails

### ISSUE THREAD

**Issue by nemoskapetanos** [Thomas101/wmail#427]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.6
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

Hi again Thomas,
Version 2.0.6 is not picking up unread emails and consequently they are not showing up on the tray icon or the left hand side account icon. This was working fine in ver 2.0.5. So it's something that was changed from 2.0.5 to 2.0.6

**Comment by Thomas101** [comment]
Hi are you using Gmail or Google Inbox? Is the count stuck on a certain number or just fixed at zero? If you go to `View > Developer Tools` and click on the console tab is anything logged out?

**Comment by nemoskapetanos** [comment]
The console tab is blank. I made a small breakthrough though. It's only picking up the unread emails in the primary account even though I've selected "All unread messages" in the unread mode option. Is there anything else I should look at?

**Comment by Thomas101** [comment]
In Gmail are you using the Categories Inbox with Primary, Promotions etc?

**Comment by nemoskapetanos** [comment]
Yes, exactly.

**Comment by Thomas101** [comment]
Ah sorry, this is down to cec15454b48069ae2608f5d2c59cba89e0a50383 and is the same issue as #425. There's a problem on Googles end which means the unread counts aren't entirely accurate all the time and I've been trying to pull the count out of the gmail ui instead. I hadn't really considered users using one type of inbox and unread counts from another.

I'll fix this in the next pre-release. If it's becoming a big issue in your daily workflow, 2.0.6 remains entirely compatible with 2.0.5 and 2.0.0 if you need to downgrade in the short-term

**Comment by nemoskapetanos** [comment]
It's not a critical issue for me, as I receive all my important emails in the primary inbox. I'll just upgrade when the next pre-release comes out.

**Comment by Thomas101** [comment]
Hi this should be fixed in the latest [prerelease](thomas101.github.io/wmail/download?v=2.0.7). Thanks!

**Comment by nemoskapetanos** [comment]
Fantastic! Installed the new pre-release and the unread count works exactly as it should.
