### ISSUE TITLE
On Mac, Cmd-H doesn't behave like other apps

### ISSUE THREAD

**Issue by thillerson** [Thomas101/wmail#43]
Most Mac apps simply hide and pass focus to the next app in the stack when you press Command-H. Wmail closes the key window and remains focused. If you press command-h to hide the app, you have to click the app in the dock to get the key window back.

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip). Thanks very much for your help!

**Comment by thillerson** [comment]
Great thanks!
