### ISSUE TITLE
Deluge of notifications of new emails

### ISSUE THREAD

**Issue by sjennison** [Thomas101/wmail#430]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.6
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Upon logging back in to my computer, wmail sends a massive number of notifications for emails, even in my Updates, Purchases, Promos, Social, and Forums folders (using Google Inbox). These do not normally generate notifications (Inbox for Android, for example, does not notify about emails in these categories). Additionally, the huge number of notifications renders the bottom-right part of my screen unusable until they all clear. As background information, I recieve approximately 20-25 low-priority emails a day, which get sorted into these folders. Clicking through 20-25 notifications is not fun! I'd like a way to
- Configure which folders I get notifications for (or only show them for emails not sorted into a folder).
- Clear all notifications without having to click through or wait for each one.

**Comment by Thomas101** [comment]
Hi, do you still see the notifications if you leave your machine on or are there extra ones/outdated ones when you log back in?

You can configure which emails you get notifications and unread counts for by going to settings> accounts and changing the setting under `Unread modes`.

**Comment by sjennison** [comment]
I believe they happen when I log back in.

I'm aware of the unread counts feature, the problem is that it turns off notifications for *anything* sent to that email address. I'd like to have only notifications for emails that the Google inbox client sends notifications for - which I believe is just emails sent directly to me (IE not autofiled in a folder).

**Comment by Thomas101** [comment]
Hi, this is fixed in the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8). Thanks!
