### ISSUE TITLE
It is not possible to add WMail as a default email program in windwos 10.

### ISSUE THREAD

**Issue by stomms** [Thomas101/wmail#431]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

It is not possible to add WMail as a default email prohram in windwos 10.
So it will not open email links from browser and so on. Please fix:)
Adding "Create New Mail" possibility from the task bar shortcut contects menu would be also very good.

**Comment by Thomas101** [comment]
Duplicate #66
