### ISSUE TITLE
Unable to click and drag to select text in Inbox emails

### ISSUE THREAD

**Issue by benvddriessche** [Thomas101/wmail#437]
This behavior is non-consistent. When trying to select text in an email (Inbox account), the initial click sometimes closes the email instead of allowing the text to be selected. As a result, the focus shifts to the list of emails and selects those while the left mouse button is held. Changing focus away from WMail or selecting another account sometimes resolves the issue temporarily. I have not found a consistent way to reproduce this behavior.

* Which version of WMail are you using? 2.0.7 (but also happens on stable 2.0.x) release
* Which Operating System are you using? Windows 10 (AU)

**Comment by Thomas101** [comment]
Hi I wonder if this is down to some mouse & highlighted bugs that have been reported in electron. Using 2.0.7 if you go to settings > advanced and toggle `Use Zoom for DSF` so it's off does this fix the issue?

**Comment by benvddriessche** [comment]
That seems to have fixed the issue, thanks!

**Comment by Thomas101** [comment]
Awesome! I'm thinking I might toggle that off by default
