### ISSUE TITLE
Is it possible to just change the default font sizes

### ISSUE THREAD

**Issue by tuhlmann** [Thomas101/wmail#438]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 14.04

Is there a way to get to change the default font size that is used to render the content? Rather than zooming everything I would like to be able to just increase the used font sizes the way I could do through Chrome's settings.

Thanks!

**Comment by MichaelTunnell** [comment]
Yes, this is possible. This can be done on a Per Account basis.

WMail Settings -> Accounts (tab) -> Choose the account you want to affect -> click the "Custom CSS" button (on the right side of the settings) and enter the following CSS.

`body { font-size:20px; }`

You can choose a different font size if you want, that is just an example.

![](http://i.imgur.com/JFOeth4.jpg)

**Comment by Thomas101** [comment]
Does what @MichaelTunnell suggested work? I'm thinking that might be the best way about it as I don't see any support for this in electron

**Comment by tuhlmann** [comment]
@MichaelTunnell @Thomas101 Thans for the suggestion. Yes, that works.

**Comment by Thomas101** [comment]
Awesome! @MichaelTunnell if you're interested this would go great in the [wmail-userscripts](https://github.com/Thomas101/wmail-user-scripts) ;-)
