### ISSUE TITLE
Expand trimmed mail

### ISSUE THREAD

**Issue by ICDeadPpl** [Thomas101/wmail#442]
I'd like to see an option to automatically show trimmed mail fully expanded, just as the "Trimless for Goole Mail" extension for Chrome does:  https://chrome.google.com/webstore/detail/trimless-for-google-mail/niepjjjfafhadmfdminbckmciijcaagc 
The extansion mentioned above makes all mails show in full in Chrome, without trimming.
As WMail works now, when I click on "Show the full mail" link at the bottom of a trimmed mail, it opens the mail in a pop-up window. Which is fine in itself, but aestehetically it would be nicer to have all mails shown in full.

My setup:
* WMail 2.0.7 (Google Inbox mode)
* Windows 10 Home 64-bit

**Comment by Thomas101** [comment]
I've opened a new issue covering re-looking at chrome extensions as there's a few sub-issues as regards extensions. You can follow progress/info here #451
