### ISSUE TITLE
Spam mail moved to inbox

### ISSUE THREAD

**Issue by ICDeadPpl** [Thomas101/wmail#443]
When I move a mail wrongly classified as spam back to my inbox, the links in the mail are not clickable.
I have to quit WMail and start it again, for the be able to click on the links in the mail in question.

My setup:
* WMail 2.0.7
* Windows 10 Home 64-bit

**Comment by Thomas101** [comment]
Hi, I'm assuming you're seeing this with Google Inbox rather than Gmail? I've just tried it in Chrome and I see the same behaviour, so it looks like this is an issue on Googles end. If you try it in chrome do you see the same?

**Comment by ICDeadPpl** [comment]
Yes, you are right. Google inbox in Chrome has the same behaviour.
I'll send a bug report their way!
