### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by armaldio** [Thomas101/wmail#444]
Hello :)
A support for markdown would be awesome ?

(like http://markdown-here.com/)

Thanks

**Comment by MichaelTunnell** [comment]
I don't understand where you want the Markdown to be available. If you are asking for composing emails then that doesn't work since this is just loading the webapp of Gmail and therefore Google has control over that not WMail.

**Comment by Thomas101** [comment]
I've opened a new issue covering re-looking at chrome extensions as there's a few sub-issues as regards extensions. You can follow progress/info here #451
