### ISSUE TITLE
Sound Notification Customization

### ISSUE THREAD

**Issue by hexplor** [Thomas101/wmail#447]
* Which version of WMail are you using? 2.0.7
* Which Operating System are you using? [Mac OSX ]

Would be super awesome if WMail would allow user to customize notification sound per account. Something what mailplane already does.
Besides I would like to congratulate great mail program. It's really fast comparing to competitiors.

**Comment by Thomas101** [comment]
Hi, I've opened a new issue as regards notifications (#452) to collapse a few issues which are all related. I'm going to close this but you can continue tracking it here #452. Thanks!
