### ISSUE TITLE
Use system proxy settings. Environment variables.

### ISSUE THREAD

**Issue by jmtvms** [Thomas101/wmail#448]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

You cloud make your app use the http_proxy and https_proxy from the environments variables. As far as i know it works on windows and linux.

Scripts that set all the configurations when i'm on the office to use proxy and other script to use my note at home removing all the environment variables.

At your advanced screen add the third proxy options called use system settings.

**Comment by Thomas101** [comment]
I could take it out from environment variables. I didn't know there was a standard set that os's use. Do you have an example script I can use for testing? (Feel free to point it at any old proxy server/proxy server that doesn't exist).

**Comment by jmtvms** [comment]
Most of the linux softwares use these environment variables:

http_proxy=http://10.203.0.1:5187/
https_proxy=$http_proxy
ftp_proxy=$http_proxy
rsync_proxy=$http_proxy
no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"

https://wiki.archlinux.org/index.php/proxy_settings

But in windows most of the software doesn't use those environment variables. they got these settings from the proxy settings inside Internet Explorer

For windows you have two ways:

**Windows Registry**
To access the windows registry on node use
https://www.npmjs.com/package/windows-registry
The windows registry path for the proxy settings is:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings

**Windows API**
On Windows API you can call WinHttpGetIEProxyConfigForCurrentUser method
In node there's a library to access the windows API https://github.com/node-ffi/node-ffi
API DOC: https://msdn.microsoft.com/en-us/library/windows/desktop/aa384096(v=vs.85).aspx

I think since macos is based on unix is may use the same settings as linux.

**Comment by jmtvms** [comment]
Other think i noticed.
After the authentication process using the proxy settings inside the app the app works regardless the proxy settings. probably the component you are using to open the inbox page uses the OS proxy settings.

**Comment by Thomas101** [comment]
Awesome that's a great help! The reason the mailboxes still work is chromium under the hood auto detects the system proxy but the http calls made in the main thread don't. 

There is a repo that tries to crawl the proxy settings that chromium uses, but I didn't have much success with this. In an ideal world the whole thing should just work and using those environment variables might be a way to get to that point

Thanks

**Comment by Thomas101** [comment]
Hi, version 2.2.0 and 2.2.1 should handle proxies much better. They're available to [download here](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!
