### ISSUE TITLE
can't add G-account

### ISSUE THREAD

**Issue by yz-huang** [Thomas101/wmail#454]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.12.1

Problem description:
1. Click "add inbox mailbox" or "add gmail mailbox"
2. Sign in google account in a new window
3. 2-step verification
4. Request for permission: click "allow", and the google window close, and back to the initial window "add your first mailbox". But no account added.

**Comment by Thomas101** [comment]
Hi, if you go to View > Developer Tools and click on the console tab do you see any errors when trying to sign in?

**Comment by yz-huang** [comment]
<img width="793" alt="screen shot 2016-12-03 at 10 20 17 am" src="https://cloud.githubusercontent.com/assets/24309913/20856103/4012fe02-b942-11e6-9895-1e1a2b0c4b42.png">

**Comment by Thomas101** [comment]
Are you using a proxy server by any chance? If you are you'll need to set the proxy settings under Settings > Advanced

**Comment by yz-huang** [comment]
Thanks. Problem solved.
