### ISSUE TITLE
Trackpad scrolling not working

### ISSUE THREAD

**Issue by angoodkind** [Thomas101/wmail#455]
* Which version of WMail are you using? [e.g. 1.3.1]
Both 2.0.0 and 2.0.7
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Cannot scroll using touchpad. Need to either use arrow keys or finger on screen.

**Comment by Thomas101** [comment]
Hi, have you tried toggling `Use Zoom for DSF` to be off under settings>advanced?

**Comment by angoodkind** [comment]
Thanks. That solved the issue.
