### ISSUE TITLE
GUI goes all white when "dragging" accidentally with mouse / pen

### ISSUE THREAD

**Issue by VOOM108** [Thomas101/wmail#456]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.7 (issue has been there before)
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Win 10 64bit

When accidentally dragging with the mouse or in my case Wacom pen anywhere on the Wmail surface the content of the window goes alle white. Have to close Wmail and reopen to fix. 

This probably happens more often with a pen than with a mouse so has not been experienced widely by users...

**Comment by Thomas101** [comment]
Hi, have you tried toggling `Use Zoom for DSF` to be off under settings>advanced in 2.0.7?

**Comment by VOOM108** [comment]
Nope, did that now, that helped :)

**Comment by Thomas101** [comment]
I think I see this too. I got it when dragging images to the desktop. Thanks

**Comment by Thomas101** [comment]
Hi, this is fixed in the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8). Thanks!
