### ISSUE TITLE
Downloaded attachment not visible in Finder or regular Chrome-based Gmail

### ISSUE THREAD

**Issue by deeplypuzzled** [Thomas101/wmail#46]
Many thanks for a very useful piece of software that uses 1-2GB less RAM than Gmail in Chrome.

When I download an attachment in wmail, I cannot see it in the Finder. E.g. a Word attachment cannot be opened in Word.

When I want to upload an attachment in wmail, the only files that I can see in wmail are ones that I downloaded in wmail. Drag and drop from Finder to wmail doesn't work.

This looks like a permissions problem. 
The wmail.app permissions (from Get Info) are:
xxxx (Me) Read & Write
staff Read only
everyone Read only
The Google Chome.app permissions are:
system Read & Write
wheel Read only
everyone Read only

I am an administrator. Adding the "Administrators" group to wmail.app's permissions does not help.

I am using wmail 1.1.3 for two Google Apps accounts on OSX 10.10.5.

**Comment by Thomas101** [comment]
Hey, I think this should be fixed in the latest pre-release which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.4/WMail_1_1_4_prerelease.zip)

**Comment by deeplypuzzled** [comment]
Thanks very much for the rapid response, Thomas. 1.1.4 does fix that problem.
