### ISSUE TITLE
Arch linux, cannot uninstall. error: target not found wmail

### ISSUE THREAD

**Issue by cj59** [Thomas101/wmail#460]
Arch linux, cannot uninstall. error: target not found wmail  WMail ver 2.0.7-1
I have tried updating the system, as well as packer. Still get the error target not found wmail.
Arch Linux kernel ver. 4.8.13-1

**Comment by funilrys** [comment]
I'm the maintainer of the Arch package, Is this still actual ?

**Comment by cj59** [comment]
No longer relevant. This was an oversight on my part. Your package was perfectly fine. I am sorry I forgot to close this out. Thank you for sending me a reminder.
