### ISSUE TITLE
Notifications appears even if they are disabled

### ISSUE THREAD

**Issue by pawelantczak** [Thomas101/wmail#461]
* Which version of WMail are you using? 2.0.7

* Which Operating System are you using? macOS Sierra

Hello.
I have one account added twice. As GMail and as Inbox.
On GMail account settings all checkboxes are disabled.
On Inbox I have "Show notification" enabled + "Unread mode" = "All messages in inbox".

My understanding was, that I will be notified only when new email appears in my Inbox inbox.
Meanwhile, notifications appears for all emails. Even for those "Offers" etc. GMail category.

BTW. Same thing with unread counts.

Regards.

**Comment by Thomas101** [comment]
Hi, this is because inbox handles the categories differently. For this setup you might have some more success by disabling all notifications in the Google Inbox mailbox and having them show up on the Gmail version instead. Here you can set the unread mode to be `Unread Messages in Primary Category`
