### ISSUE TITLE
All mail inbox?  

### ISSUE THREAD

**Issue by sambolee** [Thomas101/wmail#462]
2.0.7
Mac OSX 10

Hi,

Thanks again for this amazing program!  I am grateful for your work and for making it free.  One feature I thought would be great is to have an all mail inbox where I can see all my emails in one view?

**Comment by Thomas101** [comment]
Hi. This is a real tricky one to do. WMail works more like the browser embedding Gmail and Google Inbox in browser tabs. Adding a combined mailbox would require writing an entire Gmail and/or Google Inbox UI, which is achievable but is also a huge undertaking. At the moment this isn't something that I'm looking towards working on I'm afraid.

There is more of a merged view in the tray icon context menu. It only provides a brief snippet of the unread items in the accounts, but might be helpful in your workflow.

Thanks for raising the issue!

**Comment by sambolee** [comment]
Thanks Thomas!  How about a way to add contacts?
