### ISSUE TITLE
update to chrome 55 ?

### ISSUE THREAD

**Issue by julestruong** [Thomas101/wmail#463]
* Which version of WMail are you using? [e.g. 1.3.1]

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

**Comment by Thomas101** [comment]
I will be doing this (I've been waiting for the memory optimisations from this release), just waiting for electron to upgrade and I'll filter this through

**Comment by Thomas101** [comment]
I'm going to close this off for now, but I will be updating to the latest chrome once it filters down through the stack. I try to keep all the WMail dependencies up to date as much as I can.

Thanks!
