### ISSUE TITLE
Option to display only primary unread count

### ISSUE THREAD

**Issue by ugachmaaz** [Thomas101/wmail#466]
* Using v2.0.0 on Windows 10 x64. 
Feature suggestion -- 

This feature exists in Shift, the paid fork of Wmail, but would be really nice to have in Wmail. Currently, Wmail can only display the total unread count. My primary Inbox unread count is currently 16, but the unread count in Wmail just says "100" because of the large number of unread messages in the Social, Promotions and Updates categories. 

Thanks!
Maaz

**Comment by jlabonski** [comment]
When labels are bundled and set for a particular time of day, this gets annoying rather quickly. I have to hunt for which label the new mail happens to fall in, or resort to "in:inbox is:unread" to find the offending item.

**Comment by Thomas101** [comment]
@ugachmaaz you can change the unread mode that WMail uses by going to Settings and then picking `Unread Messages in Primary Category`. This should use just the items in the primary category. Alternatively in the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8) you can also select `Scrape unread count directly from UI` which will take the unread count that you see in the UI and use that

@jlabonski In the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8) you can also select `Scrape unread count directly from UI` which will stop showing unread counts for individual bundled items and snoozed items
