### ISSUE TITLE
App sometimes closes while closing the window

### ISSUE THREAD

**Issue by Nemo64** [Thomas101/wmail#467]
* Which version of WMail are you using? [e.g. 1.3.1]
Versino 2.0.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
maxOS 10.12.2 (16C67)

So normally, when i close the WMail window, the App stays aktive so I can receive notifications etc. 
But I had it now a few times that closing the window actually closes the entire app.
I haven't found a way to reproduce it consistently yet.

**Comment by Thomas101** [comment]
Hi, this has been fixed in the pre-release channel which you get from the [downloads](https://thomas101.github.io/wmail/download?v=2.0.8) page. Thanks!

**Comment by Nemo64** [comment]
Thanks. I have looked though the guidlines and downloaded the pre-release version but since this issue isn't always reproducable i wasn't sure that the issue is fixed there. But yes, it did not happen the past few days so I guess it is fixed.

Thanks again ;)

**Comment by Thomas101** [comment]
Awesome! Let me know if it does come back up!
