### ISSUE TITLE
Account images can be dragged and dropped into the inbox area

### ISSUE THREAD

**Issue by luispabon** [Thomas101/wmail#468]
I accidentally dragged and dropped the profile picture into the inbox area and this is the result:

![image](https://cloud.githubusercontent.com/assets/6388823/21455951/4f929c18-c91c-11e6-9e4c-d058a1f966e5.png)

wmail 2.0.7 on Ubuntu 16.10. Google inbox accounts.

**Comment by Thomas101** [comment]
Thanks, fixed this!

**Comment by luispabon** [comment]
:muscle:

**Comment by Thomas101** [comment]
Hi, this is fixed in the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8). Thanks!
