### ISSUE TITLE
Feature Request: disable hangouts chat when Google Chrome extension is active

### ISSUE THREAD

**Issue by twoelevenjay** [Thomas101/wmail#47]
I know when viewing inbox in the browser the Google Hangouts conversations do not appear when the Chrome extension is installed that displays them independently on the desktop.

Is is possible to have WMail detect the same thing? Right now I have the conversation pop up in two places.

**Comment by Thomas101** [comment]
I'm not sure that I could detect if you have it open, but I could look at disabling hangouts when I add the settings screen?

**Comment by twoelevenjay** [comment]
That sounds like a great idea. This app is exactly what I was wanting when I switched from Mailbox by Dropbox to Inbox recently. Thank you. I am a PHP guy but have been digging hard into JS recently, maybe I will be able to contribute to the settings page.

**Comment by Thomas101** [comment]
All help is appreciated! Feel free to clone the repo and submit a pull request :)

**Comment by CyanJDroid** [comment]
Came here to suggest the ability to disable hangouts in the app, glad I checked to see if someone had suggested it yet! Buy yeah, getting double hangouts notifications is kinda annoying, any updates on when we might be seeing this feature added (if at all)?

**Comment by Thomas101** [comment]
I don't think this is something I'll be adding to wmail at the moment - trying to detect if hangouts is open within the browser is pretty much a no-go I'm afraid

**Comment by CyanJDroid** [comment]
Then perhaps simply adding a setting for disabling/blocking Hangouts in wmail? Wouldn't that be significantly simpler to implement, and would probably suffice for most users (I know it would for me)?

**Comment by Thomas101** [comment]
Trying to patch through to whatever Google has added for hangouts is extremely difficult and every time they push a new version of their client out the patches to change this will need updating too. To be honest it will probably spend more time not-working than working :-(
