### ISSUE TITLE
The proprietary software "shift" appears to be a copy of this project

### ISSUE THREAD

**Issue by Fingel** [Thomas101/wmail#471]
* Which version of WMail are you using? [e.g. 1.3.1]
Git

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Arch Linux

Thanks for the awesome software! This is not exactly an issue per say, but I thought you might be interested in this:

https://tryshift.com/

"Tired of Switching between Gmail Accounts? Get Shift."

Looks like a direct copy of this project, right down to the UI. 

Indeed, after unpacking "app.asar" is does look like they used the code from this repo. Grepping "wmail" results in the following:

```
bin/app/shared/constants.js:  DB_EXTENSION: 'wmaildb',
bin/app/app/windows/MailboxesWindow.js:const WMailWindow = require('./WMailWindow')
bin/app/app/windows/MailboxesWindow.js:class MailboxesWindow extends WMailWindow {
bin/app/app/windows/MailboxesSessionManager.js:    const downloadPath = unusedFilename.sync(savePath + '.wmaildownload') // just-in-case
bin/app/app/windows/WMailWindow.js:class WMailWindow extends EventEmitter {
bin/app/app/windows/WMailWindow.js:module.exports = WMailWindow
bin/app/app/windows/ContentWindow.js:const WMailWindow = require('./WMailWindow')
bin/app/app/windows/ContentWindow.js:class ContentWindow extends WMailWindow {
bin/app/app/stores/mailboxStore.js:  createNewMailbox (data) {
bin/scenes/mailboxes/mailboxes.js:	  DB_EXTENSION: 'wmaildb',
bin/scenes/mailboxes/mailboxes.js:	  * https://github.com/Thomas101/wmail/issues/211
bin/scenes/mailboxes/mailboxes.js:	              'Wmail'
bin/scenes/platform/webviewInjection/WMail/WMail.js:class WMail {
bin/scenes/platform/webviewInjection/WMail/WMail.js:module.exports = WMail
bin/scenes/platform/webviewInjection/Browser/Spellchecker.js:  Nodehun = require('../../../../app/node_modules/wmail-spellchecker')
bin/scenes/platform/webviewInjection/Google/Google.js:const WMail = require('../WMail/WMail')
bin/scenes/platform/webviewInjection/Google/Google.js:    this.wmail = new WMail()
```
They are definitely not in compliance with the Mozilla Public License, as far as I can tell. 

Anyways, I think this is kinda wrong, and I wanted to bring it to your attention.

**Comment by ShantanuJoshi** [comment]
Super sketchy... check out their "pricing" https://tryshift.com/pricing such bs

**Comment by Thomas101** [comment]
Hi, thanks for the heads up on this!

@Fingel WMail was licensed under MIT until 7a167e45724614e94f3166839c32ea3e4e69294f and I believe they took a fork before that point

**Comment by 0x3333** [comment]
Even if it was licensed under MIT they should include the copyright to you. This is at least unfair use.

```
Redistributions in binary form must reproduce the above copyright notice,
 -  this list of conditions and the following disclaimer in the documentation
 -  and/or other materials provided with the distribution.
```
