### ISSUE TITLE
Delay between new letter notification and its appearance in the window

### ISSUE THREAD

**Issue by ckald** [Thomas101/wmail#475]
New letter notification appears seconds before I can see the letter in the window. Sometimes delay is relatively short, but sometimes it takes 10-15 seconds.

* Which version of WMail are you using? [e.g. 1.3.1] 
2.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS X 10.12.1

**Comment by Thomas101** [comment]
Hi, I've updated the app to be more intelligent about when it re-checks for updates. This should be out in the next prerelease. Thanks
