### ISSUE TITLE
Stuck in "View entire message"

### ISSUE THREAD

**Issue by deeplypuzzled** [Thomas101/wmail#48]
When I receive a large message, Gmail truncates message display with the note: "[Message clipped] View entire message".

If I click the link to "View entire message", the full message appears in wmail, entirely replacing the wmail interface (except the left-hand column). There is no way to escape from this window, except closing and restarting wmail. Gmail shortcut keys are no escape from the trap.

In Chrome/Gmail, the full message appears in a new window/tab. 

A possible solution might be to display the full message in the browser, i.e. treat the "View entire message" link like any other web link in a message?

**Comment by Thomas101** [comment]
Thanks for this one.

Subtasks:
* Open new messages (and possibly contacts #16) in new window
* Ensure inbox, or gmail link opens in same window
* Handle cmd+w and cmd+h shortcuts for multiple windows
* Handle quit behaviour for multiple windows

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.5/WMail_1_1_5_osx_prerelease.zip). Thanks very much for your help!

**Comment by deeplypuzzled** [comment]
Thank you Thomas. Fixed. This is a really impressive piece of software and the memory use benefits have speeded up my MB Air.
