### ISSUE TITLE
Notifications not appearing

### ISSUE THREAD

**Issue by dhackamack** [Thomas101/wmail#480]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS X 10.12

Notifications do not appear (icon badge or notification center) nor does WMail appear as an option in the system preference for notifications. Unable to receive any notification of new mail.

**Comment by MarkaPola** [comment]
Same problem for me (WMail 2.0.7 and MacOS 10.12.2).
Moreover, icon badge is displaying always the same number of mails (for instance 4) regardless the real number of unread mails.

**Comment by Thomas101** [comment]
Hi, are you using a proxy server? If you are you'll need to enter your settings under `settings > advanced`. If not could you go to `View > Developer Tools` and click on the `console` tab and see if there are any errors?

@MarkaPola there is a bug on Googles end with some sticky unread messages. You can grab the unread count directly from the UI by toggling `Scrape unread count directly from UI` setting in your account in version [2.0.8](https://thomas101.github.io/wmail/download?v=2.0.8)

**Comment by MarkaPola** [comment]
Good news.

All my problems seems solved using 2.0.8 on MacOS 10.12.2.
Thanks for pointing proxy because, for unknown reason, my proxy settings was no longer correct. After this fixed, unread count is OK (without using 'Scrape unread count' option).
And notifications go back to live as well (is it linked to proxy problem?).

Thanks for your help.

**Comment by Thomas101** [comment]
Sounds like it was down to proxy then. I am planning on trying to grab the proxy settings automatically in a future version #448
