### ISSUE TITLE
UI mostly black

### ISSUE THREAD

**Issue by dasizeman** [Thomas101/wmail#482]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
VirtualBox Ubuntu 16.04 guest OS on Windows 10 host

When I open WMail in my Ubuntu VM, the UI is mostly black, with a few white or blue boxes.  I have a feeling this is a problem with the OpenGL implementation in VirtualBox, since I saw a similar issue on my VM with the Spotify Linux client.  I solved that by disabling hardware rendering.

Is there a way to set the "Ignore GPU Blacklist" option through the command line?  I can't see enough of the interface to set it normally, and I have a feeling this would solve the problem.

**Comment by Thomas101** [comment]
Hi,

Probably the best way at the moment is to write directly into the settings file. Make sure WMail is fully quit and then overwrite the contents of the file at `~/.local/share/wmail/settings_db.json` with...

```js
{"app":"{\"ignoreGPUBlacklist\":true}"}
```

**Comment by WoodyWoodsta** [comment]
Was having a similar issue on linux and enabling "Ignore GPU blacklist" solved it for me.

**Comment by Thomas101** [comment]
Hi, I'm going to close this off for now due to inactivity. If you're still having the issue feel free to re-comment or open a new issue and I'll look back into it.
