### ISSUE TITLE
Notif. executable

### ISSUE THREAD

**Issue by AravK** [Thomas101/wmail#484]
Debian 8.6:
Please make a separate executable which shows up on the notification to use as a start-up app
Perhaps named WMail-notif?

**Comment by Thomas101** [comment]
Hi, is this to launch WMail from a notification it has generated, or to launch WMail on startup?

**Comment by AravK** [comment]
To just show up on the notification bar at startup

**Comment by Thomas101** [comment]
Ah I'm with you. There's no push button way to do this, but you can configure WMail to run at startup. According to [serverfault](https://serverfault.com/questions/735621/debian-how-to-run-a-script-on-startup-without-having-to-write-30-lines-of-shell) you can run commands on startup by editing `/etc/rc.local` (You may use a different location for this though, depending on your setup). In here you can start WMail in hidden mode (the ui will be closed off to the notification bar) by running `./WMail --hidden`

**Comment by Thomas101** [comment]
Hi, I'm going to close this off for now due to inactivity. If you're still having the issue feel free to re-comment or open a new issue and I'll look back into it.
