### ISSUE TITLE
Suddenly Work Gmail getting Cookie Error 

### ISSUE THREAD

**Issue by trueschool** [Thomas101/wmail#488]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.10.5

All of a sudden I get an error screen when I login to my work Gmail. Artificially persisting my cookie no longer helps. They must be wise to me. What do I do?

**Comment by Thomas101** [comment]
When I persist the cookie I set the expiry date for 30 days ahead which matches with what most providers also set it to. However if they've set it to a different time you can end up in this situation.

If you right click on your account icon in the left hand side and click on `Re-Authenticate` it will clear all the data from your session and should be able to re-login.
