### ISSUE TITLE
Google Services - Can't Open Google Drive Content

### ISSUE THREAD

**Issue by Niomar** [Thomas101/wmail#489]
* Which version of WMail are you using? 2.0.8

* Which Operating System are you using? Windows 10

Love the new Google services support, but you can only view the titles of the entries in Google Drive.  Once you try to open any of the items, it opens a new tab in your default browser, which won't work if you're logged into another Google account.  Specifically, Google Drive doesn't allow users to switch between accounts.  You have to sign out of one account before you can sign into another with Google Drive to view or edit actual content.

With the new Google services, it will show your Google Drive content within WMail, but when you double click to open any item, it opens in your default browser, which isn't possible if you're signed into another Google account already.  Is it possible to have Google Drive content open in a new tab within WMail itself to prevent this from happening?

**Comment by abass** [comment]
oooohhh, interesting. Yes, this!

**Comment by Thomas101** [comment]
Hi, thanks for reporting. The [2.0.9 prerelease](https://thomas101.github.io/wmail/download?v=2.0.9) open docs files in new WMail windows rather than going out to the browser

**Comment by abass** [comment]
Great work! You are killing it!

**Comment by abass** [comment]
UPDATE: Any way to make it so the new window respects the zoom ratio WMail has? the docs/sheets/etc. that I open are super small (4K monitor)

**Comment by Thomas101** [comment]
It should try to match the parents size. Are you using WMail maximised? If you un-maximimise WMail and open a doc does this match more closely?
