### ISSUE TITLE
Desktop notifications on new mail

### ISSUE THREAD

**Issue by mrcasals** [Thomas101/wmail#49]
Hi!

Do you have any plans to add desktop notifications on incoming email? I'm using v1.1.3 and haven't checked the pre-release version, so I might have missed this.

Thanks for the work! :)

**Comment by Thomas101** [comment]
I'm planning on adding these soon :)

**Comment by mrcasals** [comment]
Awesome, thank you!

On Fri, Jan 22, 2016 at 9:36 AM Thomas Beverley <notifications@github.com>
wrote:

> I'm planning on adding these soon :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Thomas101/wmail/issues/49#issuecomment-173844595>.
>
-- 
Marc Riera

**Comment by DerSiedler** [comment]
will it work with the notification center?

**Comment by Thomas101** [comment]
It will work with notification center. I'm going to close this issue as it is a duplicate of #35. Feel free to follow this issue for updates!
