### ISSUE TITLE
Scrolling down by touchscreen not working in Inbox

### ISSUE THREAD

**Issue by andrushka80** [Thomas101/wmail#490]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I am using Google Inbox for my personal gmail.com address. In tablet mode, using the touch screen, I cannot scroll down on the list of categories (Inbox, Updates, Social, Promos etc.), in the left tab. If I try to scroll down by swiping my finger up&down on them, it will only scroll down on the emails (the main window). This basically means that in tablet mode, I cannot get down to Promos category, for instance because it is out of reach. This works ok with scrolling by touchpad or by mouse in non-tablet mode.

**Comment by Thomas101** [comment]
Hi, do you see this issue when using inbox in Google Chrome?

**Comment by andrushka80** [comment]
Hi,

As a matter of fact, it does not work with Chrome either. I just tried it.

Andrei

**Comment by Thomas101** [comment]
This looks like something is google is doing their end then. I've had a quick look through what it's doing but can't spot anything obvious. If it's not working in chrome, it might be worth reporting this on the [Google Product Forums](https://productforums.google.com/forum/#!forum/inbox) as someone at Google may pick it up. I'm going to close this issue off for now though as it's not specific to WMail
