### ISSUE TITLE
mailto: from mac calendar garbles the email addresses

### ISSUE THREAD

**Issue by dchersey** [Thomas101/wmail#492]
* Using 2.0.8 prerelease on Mac OSX 10

Really glad to see support for system-level email hooks! However there is an issue invoking this from Mac Calendar. 
When I right click on an event with invitees, then select "Email all participants" WMail is correctly invoked but the resulting message is addressed to recipients with escaped characters, i.e. `David%20Hersey%20%3Cdavid@leapforward.us%3E` instead of David Hersey <david@leapforward.us>.

Probably a 1-line fix!

Cheers,

David

**Comment by Thomas101** [comment]
Thanks! It was a 3 line fix, but should be working now ;-). It's in the [2.0.9 prerelease](https://thomas101.github.io/wmail/download?v=2.0.9)

**Comment by dchersey** [comment]
Thanks!
