### ISSUE TITLE
No Desktop Icon

### ISSUE THREAD

**Issue by WilliXL** [Thomas101/wmail#493]
* Which version of WMail are you using? [e.g. 1.3.1]
v2.0.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 64-bit

The icon is just the picture file stand-in.

**Comment by Thomas101** [comment]
Hi, this is fixed with in the current set of pre-releases which you can [download from here](https://thomas101.github.io/wmail/download?v=2.0.8). Thanks!
