### ISSUE TITLE
Unread count is stuck at a minimum of 2

### ISSUE THREAD

**Issue by jemmyw** [Thomas101/wmail#494]
* Which version of WMail are you using?

2.0.8 but the problem has been persistent through versions

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Mac OSX

<img width="78" alt="screen shot 2017-01-06 at 5 17 13 pm" src="https://cloud.githubusercontent.com/assets/8016/21707440/05668b40-d434-11e6-871b-a26b99c478ee.png">

The unread count for my inbox stays at 2 even though there are no unread messages. When there are unread messages then the number goes up only once there are more than 2 unread. So if there's 1 unread it'll say 2, if there are 3 unread then it'll say 3. If I then mark all 3 as read it'll go back to 2 and stay there.

I have other inbox accounts in WMail and it doesn't have the same issue with them. I've also switched laptop and installed everything from scratch and the problem returned, so it does appear to be an issue interacting with that particular account.

If I search the account for in:unread then nothing comes up, and other mail clients don't show unread mail.

**Comment by Thomas101** [comment]
Hi, this is probably down to either snoozed items, bundled items or a known bug on Googles end. 2.0.8 has added enhanced support for unread counts in Inbox though. If you right click on your account in the left hand side and go to `Account Settings`. You'll find a toggle box called `Scrape unread count directly from UI`. Give this a go, it may work better for you

**Comment by jemmyw** [comment]
Thanks, that worked!
