### ISSUE TITLE
Release zip should not be included in git repo

### ISSUE THREAD

**Issue by forivall** [Thomas101/wmail#5]
Instead, you should use github's release feature. You can remove the release zip from history with https://rtyley.github.io/bfg-repo-cleaner/ (or `git filter-branch`, if you're an old-schooler)

**Comment by Thomas101** [comment]
I completely agree. `98f70765a8375371fd6be02f3c926737e23ebca1` fixes this and the tree has been pruned. Thanks for the advice!
