### ISSUE TITLE
Is there a way to integrate adblocking of some kind?

### ISSUE THREAD

**Issue by live4truths** [Thomas101/wmail#500]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Win7

Would be amazing to somehow block the tab-like promotions. Using Ublock in the chrome browser itself, is there a way I am missing to get rid of these pesky things?

Thank you!

**Comment by Thomas101** [comment]
Hi, I'm still looking at way of integrating some or all chrome extensions (#451) which is what ad-blocking will probably fall under. In mean time though if you're using gmail, one of the [wmail-user-scripts](https://github.com/Thomas101/wmail-user-scripts) might fit your needs. One user has already added a script to hide the ads in Gmail
