### ISSUE TITLE
Are there any plans on porting wmail to iOS? Please say yes.

### ISSUE THREAD

**Issue by bsarrazin** [Thomas101/wmail#501]
Please? Please say yes.
I can help. :)

**Comment by Thomas101** [comment]
Hi, I haven't done anything about porting to iOS or mobile devices yet. I've been using Inbox, Drive, Calendar etc with multiple accounts on Android for a while and although they're not all in one app I felt they're easy enough to switch between for my use. I was wondering how you would see WMail better that? Is it just ease of switching between accounts or do you have a different use case in mind?

**Comment by bensarz** [comment]
Features I can think on top of my head:
1. Switching accounts is just horrible on iOS
1. Syncing accounts across devices
1. iCloud support so I can avoid using the Apple app

Surely, we could come up with more features but as you said, perhaps the friction between Inbox/Drive/Calendar/Hangouts isn't worth porting over.
I am simply a fan of using the same app on iOS as I do on macOS.
