### ISSUE TITLE
Add external IMAP/POP3 accounts

### ISSUE THREAD

**Issue by jgh001a** [Thomas101/wmail#508]
* Which version of WMail are you using?
2
* Which Operating System are you using?
Mac

I wish I could bring in my other email accounts. Gmail retrieves external account emails every hour, where I'd rather have them pushed as I get them.

**Comment by Thomas101** [comment]
Hi, there's an issue open for this #145. Going to close this off and you continue tracking from there. Out of curiosity which type of email is it? Does it have a web mail UI?

**Comment by jgh001a** [comment]
It's just your standard private email account that I have set up with my
web host. I don't want to forward my messages to gmail.

Reason being, I'd like to see a separate account appear, instead of having
it feed into Inbox.

That would also mean there would be no webmail interface.

On Tue, Jan 10, 2017 at 9:59 AM Thomas Beverley <notifications@github.com>
wrote:

Hi, there's an issue open for this #145
<https://github.com/Thomas101/wmail/issues/145>. Going to close this off
and you continue tracking from there. Out of curiosity which type of email
is it? Does it have a web mail UI?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Thomas101/wmail/issues/508#issuecomment-271648972>, or mute
the thread
