### ISSUE TITLE
Mailto not focusing WMail window correctly (Workspaces)

### ISSUE THREAD

**Issue by Dazzel** [Thomas101/wmail#509]
* Which version of WMail are you using? 2.0.9

* Which Operating System are you using? macOS Sierra 10.12.1 

I have the WMail windows always open on an different workspace as the browser. Now if I click on an mailto link in the browser, a new tab opens with the link in the address bar an WMail is selected as the active application but the correct workspace is not selected.

Also the newly opened tab should be closed automatically I guess.

**Comment by Thomas101** [comment]
Yep, I see the same. Thanks!

**Comment by Thomas101** [comment]
Hi, version 2.2.0 and 2.2.1 should refocus the window when opening mailto links. They're available to [download here](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!
