### ISSUE TITLE
Clearing out the inbox

### ISSUE THREAD

**Issue by fmay** [Thomas101/wmail#512]
* Which version of WMail are you using? 2.0.0
* Which Operating System are you using? Mac OS X

I am a recent convert to WMail and very happy with it indeed. I really want the Inbox screen to be empty but each time I mark a load of emails as done, they do disappear but are replaced (of course) by older and older ones. This account is years old so I do not have the time or patience to laboriously makr them all as done.

Is there a way I am missing to simply mark every single as done and thus have a nice clean Inbox page? Sorry if this is not an ideal forum for asking this question.

**Comment by Thomas101** [comment]
Hi

I had this problem when I first switched to inbox. In "Gmail land" when you mark a message as done it simply moves  it into the archives folder. You can login to Gmail and do this as a bulk action. The [instructions here](https://productforums.google.com/forum/#!topic/inbox/wmquBApcLKk) explain the process pretty well.

I hope that helps!

**Comment by fmay** [comment]
Many thanks!
