### ISSUE TITLE
Wmail to remember when opening Google Calendar to do so in 'month' view

### ISSUE THREAD

**Issue by luzpaz** [Thomas101/wmail#517]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.9
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Manjaro Linux 16.10

Is there a way to have wmail remember that whenever I open Calendar to do so in Monthly view? The current behaviour is to open in 'Week' view. 

BTW, thanks for all the awesome work!

**Comment by BenJetson** [comment]
Not sure if this solves your problem (maybe it's more specific to WMail), but you can already do this with Google Calendar.

Just click the cog in the top-right, followed by settings. Then, scroll down until you see "default view" and change the setting to match your needs. Don't forget to scroll to the very bottom and press the save button  before you go back to the calendar view.

Here's a screenshot walkthrough:
![help](https://cloud.githubusercontent.com/assets/10427974/21816165/27fc7c40-d72d-11e6-8de3-64db35a26b20.png)

Cheers! :smiley:

**Comment by luzpaz** [comment]
@BenJetson Thanks for the great visual step-by-step! I think this solved my issue. Cheers!

**Comment by Thomas101** [comment]
Thanks @BenJetson :)
