### ISSUE TITLE
Google Drive Preview / Copy Disabled

### ISSUE THREAD

**Issue by omarkassim** [Thomas101/wmail#518]
* Which version of WMail are you using? [e.g. 1.3.1]

2.0.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS 10.12.2

When an attachment is received (in this case it was a PDF), Gmail will pop up a preview window from which you can typically copy text and paste elsewhere. In Wmail I attempted to do this via the menu, using OS shortcuts (CMD + C) and via right click, unfortunately none of the methods worked.

When you attempt to copy something via right click in Wmail, this is what I see:

![screen shot 2017-01-10 at 07 59 13](https://cloud.githubusercontent.com/assets/544282/21793491/4e7bfade-d70b-11e6-8cc8-42650f823106.png)

When you attempt to copy something when the preview window is showing, this is what I see:

![screen shot 2017-01-10 at 07 59 23](https://cloud.githubusercontent.com/assets/544282/21793497/5b47252c-d70b-11e6-8eb4-593feec8f086.png)

The Copy function is missing and I assume that it is not available at all when the preview window shows.

**Comment by Thomas101** [comment]
Hi, this has been reported before (#356 and #428) and the conclusion that we came to was that the same behaviour was evident in chrome & firefox and it appears to be something that google's doing their end. You can highlight the text but copy keyboard shortcuts fail and copy isn't in the context menus. I've re-checked an attachment my end in chrome to see if anything had changed but it looks like the same behaviour is still there. If you try it in your web browser are you able to copy text?

**Comment by omarkassim** [comment]
@Thomas101 My apologies, I had a quick look around but wasn't able to find any similarly reported issues. I've tested in Chrome and while there isn't a copy action via right click and copying via the Edit menu in Chrome OS X fails, weirdly the keyboard shortcut actually works. I've tested with a few different PDFs and wherever I can highlight text (i.e. a text layer exists for that given PDF) I'm able to copy it using a keyboard shortcut!

**Comment by juanfurmie** [comment]
Hi Guys,

I can concur that the same behaviour *used to* take place in browser, but it seems Google have since fixed it. The shortcut keys do indeed work.

Thanks @Thomas101 for your amazing work on this!!! Will buy you some beer after payday ;-)

**Comment by Thomas101** [comment]
Hi, I'm going to close this off for now as it appears to have been solved from Googles end. If you're still having the issue feel free to re-comment or open a new issue and I'll look back into it.
