### ISSUE TITLE
Add actions to macOS notifications

### ISSUE THREAD

**Issue by Undo1** [Thomas101/wmail#519]
* Which version of WMail are you using? 2.0.0

* Which Operating System are you using?  macOS 10.12.2

In the native Mail.app, notifications can be dismissed with an action:

![screen shot 2017-01-10 at 9 04 02 am](https://cloud.githubusercontent.com/assets/5162342/21814010/313d5d8c-d715-11e6-9d0f-f7e8e734814e.png)

It'd be really nice if notifications from Inbox through WMail did the same - at least a 'done' button would be awesome

**Comment by Thomas101** [comment]
Hi, I totally agree with you! Issue #452 is open for this already, so will close this off and you continue to track progress from there. Thanks!
