### ISSUE TITLE
Update Chromium

### ISSUE THREAD

**Issue by AGonLen** [Thomas101/wmail#524]
Correct me if I'm wrong, currently WMail is running Chromium 53, and the latest stable release is 55.0.2883.87 (423768) - Friday, 9 Dec 2016.
Also, it might be some good info to add the version of Chromium you are using on WMail somewhere visible in the application.

I'm using WMail 2.0.9-pre-release

**Comment by SpectralKH** [comment]
I think it is dependant on Electron. I cannot say for sure, but I think so.

**Comment by Thomas101** [comment]
@SpectralKH is correct. Still waiting on electron to update this. They've just pushed out their beta version that uses Chromium 54, so 55 will most likely be available around April time.
