### ISSUE TITLE
Memory info not accurate

### ISSUE THREAD

**Issue by AGonLen** [Thomas101/wmail#525]
See below the screenshot of the "Memory Info" link in WMail where shows the Main Process memory (which already defers from the Windows 10 Task Manager information); and then each of the mailboxes where not entirely sure where the information comes from...

I'm using WMail 2.0.9-pre-release on Windows 10 Pro

![screen1](https://cloud.githubusercontent.com/assets/24992203/21829623/8474305c-d797-11e6-9446-e13a32e27e94.PNG)
![screen2](https://cloud.githubusercontent.com/assets/24992203/21829625/8ba46ae0-d797-11e6-93a1-849f5ec4cd72.PNG)

**Comment by Thomas101** [comment]
Hi, the memory info is only a snapshot and doesn't continue updating in WMail so I would expect it to be slightly different, but not that far out.

WMail should also have a number of background processes in a similar way that Google Chrome does. If you head down to the background processes section do you see any more WMail processes?

**Comment by AGonLen** [comment]
Hi @Thomas101, Not a big deal this one, sure you have more important ones to look at, but thought about reporting it as it's pretty different. I'm using WMail 2.0.9 on Windows 10 Pro.

In case you have some time and want to have a look also to this one, see below more info:
![1](https://cloud.githubusercontent.com/assets/24992203/22521323/f9b415e0-e8b7-11e6-861d-dc7198d13801.PNG)
![2](https://cloud.githubusercontent.com/assets/24992203/22521338/007dbc96-e8b8-11e6-943f-ad83f78878a0.PNG)
![3](https://cloud.githubusercontent.com/assets/24992203/22521344/02639f08-e8b8-11e6-9daf-fb38745763df.PNG)

**Comment by Thomas101** [comment]
Thanks for the extra info. The numbers windows reports do seem consistently lower. I wonder if the task manager shows compressed memory where as what I'm getting is uncompressed. It's definately weird. On osx they do seem to align up pretty closely. I've not checked on Linux.

I've had a quick look around but can't find anything that would explain the discrepancy. As this is using the built in [electron calls](https://github.com/electron/electron/blob/master/docs/api/process.md#processgetprocessmemoryinfo) to grab the memory info this would probably come down as an upstream bug if it isn't the desired behaviour. I'm going to close this off for now as I don't think there is a simple fix and the memory dialog is really only good for giving an indication if one of the frames has run away with a bunch of memory.

I guess the only other thing to try would be to see if the task manager in chrome gives consistently higher numbers than the windows task manager. If so then I'd definitely put this down to one showing compressed and the other not.

Thanks for raising this and looking into this a bit more though!

**Comment by AGonLen** [comment]
Ok, your call.
Thank you! WMail is great and very useful; I'm just reporting bugs and issues to make it even better :)

**Comment by Thomas101** [comment]
Thanks! Always useful to know about these things :)
