### ISSUE TITLE
Paste and Match Style

### ISSUE THREAD

**Issue by brianlenz** [Thomas101/wmail#527]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.9

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS Sierra (10.12.2)

When pasting data into Wmail, there is no ability to Paste and Match Style as there is in the browser (e.g. cmd-shift-V in Google Chrome). This is a very useful option when you want to strip rich text formatting from pasted text into an email. The current paste option in Wmail forces you to retain the styling of the pasted text, which isn't always desirable.

It would be great if Wmail could support this, as well.

Thanks for providing a great app!

**Comment by Thomas101** [comment]
Hi, Paste and Match style is available in the right click context menu, edit menu and also as cmd+shift+V. Where are you trying to paste? Maybe the text field you're using doesn't support it.

**Comment by brianlenz** [comment]
Hmmm. Sorry about that. Not sure how I missed it? Anyway, feel free to cancel/close this 👍

**Comment by Thomas101** [comment]
No worries 👍
