### ISSUE TITLE
Account credentials periodically lost.

### ISSUE THREAD

**Issue by thomasmichaelwallace** [Thomas101/wmail#528]
Once every month or so (I haven't yet identified the trigger), wmail forgets all (three) of the Google Inbox accounts I've configured, and instead just shows me the 'Add your first mailbox' screen.

Wmail 2.0.0 / macOS Sierra

I'm going to try moving up to the pre-release edition (which I use on my Linux desktop and doesn't seem to do this.

Let me know if there's anything I can do to help diagnose this vague but irritating issue!

also: cheers for making this amazing app.

**Comment by Thomas101** [comment]
Hi, this is an issue where if the OS kills wmail as it's writing an account it can corrupt the database. It was fixed in the 2.0.2 pre-release, so upgrading should stop this happening
