### ISSUE TITLE
switching release channels

### ISSUE THREAD

**Issue by gkatsev** [Thomas101/wmail#529]
I tried looking to see if such an issue exists but not sure.

I believe auto updates are available. On the website, there's the stable and pre-release channels. There's also an option to disable updates checking. Would be cool if there was an advanced option to opt into/out of pre-releases.
So, if you download the stable channel but want to move to pre-releases, you could just toggle an option but then if you don't like testing the pre-releases anymore you could uncheck it and it'll drop you down to the latest stable.

Not sure how easy or hard to add it but would be nice to have.

**Comment by Thomas101** [comment]
Hi, WMail doesn't support auto-updating at the moment [more info](https://github.com/Thomas101/wmail/wiki/FAQs#why-doesnt-wmail-support-auto-updating), but that is something that will be coming soon ;-)

As regards switching between channels, WMail only listens out for updates on the channel it's currently on. So for example the release channel only listens for release updates and the pre-release only for pre-releases. When I push a new release out I normally push a pre-release at the same time so if you want to stay on a channel just keep downloading the pre-releases.

Adding the option to switch between release channels through a toggle option probably isn't something I'm going to add in to be honest. Sometimes when releasing a new version data structures which are stored on disk are changed which is normally okay as I'll write some code to migrate them but to maintain compatibility between release and pre-release versions on the same major number is just another headache to cope with.

With the release & prerelease I was going along with the same model that Google have implemented for Chrome in that you have to explicitly download the other channels etc

**Comment by gkatsev** [comment]
Sounds good. Thanks for making wmail!
