### ISSUE TITLE
Global shortcuts

### ISSUE THREAD

**Issue by Forever-Young** [Thomas101/wmail#536]
Electron seems to have this function: https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md

Desired shortcut is 'Show/Hide ("to tray icon") window'

**Comment by nsrosenqvist** [comment]
Same here. I was looking for an option to set the Esc key to close the window but keep it running in the background.

**Comment by etrnljg** [comment]
There's actually the shortcut Ctrl+M working as you expect @nsrosenqvist 
(if the application closes, make sure the checkbox "Show icon" under "General/Tray" is checked)

I was also expecting to use Esc, as other Electron app I use do. Maybe add a setting for that?

**Comment by Thomas101** [comment]
Hi, I agree this would be a good thing to add! There's already an issue for this #144 you can continue tracking it from there
