### ISSUE TITLE
Signature not adding to reply emails

### ISSUE THREAD

**Issue by rangerrick337** [Thomas101/wmail#537]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.9
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.12.2

The signature is added in the quoted text block instead of above so it doesn't show up when replying to a message. I tested it thoroughly. It works in the gmail interface as it should and does not work in WMail.

I have ticked the box in gmail for "Insert this signature before quoted text in replies and remove the "--" line that precedes it."

I am using Gmail and not Inbox.

This would help me out if fixed as I have business accounts that I'd like to include the signature correctly. Thanks for your work on this Thomas, it's awesome you've added so much including the other google services.  This is my first email client since Sparrow!

**Comment by Thomas101** [comment]
Hi,

WMail doesn't really touch the Gmail UI and just shows it in the same way your web browser does so it's weird that you're seeing a different behaviour in your browser vs WMail. Are you using any extensions in your browser to add in this behaviour?

**Comment by Thomas101** [comment]
Hi, I'm going to close this off for now due to inactivity. If you're still having the issue feel free to re-comment or open a new issue and I'll look back into it.
