### ISSUE TITLE
REQUEST: expand/collapse services under account icon

### ISSUE THREAD

**Issue by ronenrozner** [Thomas101/wmail#539]
I have several Gmail accounts configured, and with all the service icons underneath the main account icon, it is hard to switch between account views. Can the service icons underneath each main icon be expanded and collapsed somehow ?  thanks

* Which version of WMail are you using? 2.0.9

* Which Operating System are you using? Windows 8, openSuse 42.2

**Comment by Thomas101** [comment]
Hi, do you use all the services for each account (as the ones you don't use can be disabled in settings) or are you just looking to tidy up the left hand panel? There is some discussion around how best to show services in #503 already

**Comment by Thomas101** [comment]
Hi, I'm going to close this off for now due to inactivity. If you're still having the issue feel free to re-comment or open a new issue and I'll look back into it.
