### ISSUE TITLE
Add ability to reorder the accounts

### ISSUE THREAD

**Issue by alexg0** [Thomas101/wmail#54]
Add ability to reorder the items in the sidelist.  With enough accounts, need to be able to keep items in predictable order.

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.5/WMail_1_1_5_osx_prerelease.zip). Just right click on the account on the left hand side to re-order it. Thanks very much for your help!
