### ISSUE TITLE
Feature Request: Mark as read from menu bar.

### ISSUE THREAD

**Issue by alanontheweb** [Thomas101/wmail#540]
Love Wmail on OSX. It's almost perfect.

I was hoping you could add a "mark as read" option from the top Menu Bar underneath "Compose New Message". Or maybe it can be per account. Many messages I know to ignore or mark as read without needing to open the client. Just less clicks.

Thank you!

**Comment by Thomas101** [comment]
Hi, I agree this would be useful. There's already an issue open for this #215 you can continue tracking from there
