### ISSUE TITLE
Account Names

### ISSUE THREAD

**Issue by tarekadam** [Thomas101/wmail#542]
* Which version of WMail are you using? - 2.0
* Which Operating System are you using? - MacOS

Only one good picture of me exists, so I use it on all my profiles.
So I can't tell my mailboxes apart.  All I see is 5 photos identical photos of me on the left.
It would help if I could label each account.

Otherwise, you're app has kinda changed my life.  For years, I've wanted to outsource more, but hated email.  Now I don't mind it ~ and I'm on top of it.  Thank you so much.

**Comment by Thomas101** [comment]
Hi, the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v2.0.9) has some more information when you hover over your account - for example your email address and unread messages. Would that help?

**Comment by tarekadam** [comment]
Ya, that sounds great.  I'll just hold tight and wait for your release.
Thanks!!  - Tarek

**Comment by Thomas101** [comment]
Awesome. I'll close this off for now then. Thanks!
