### ISSUE TITLE
Download folder

### ISSUE THREAD

**Issue by AGonLen** [Thomas101/wmail#544]
Would it be possible to remember the Download folder? I have the settings as "Always ask download location", but it always goes to "Downloads" folder, although the last folder was a different one. Would it be possible to remember the last folder where files were downloaded and use that as 'starting point' for new downloads?

(Using WMail v2.0.9 on Win10)

Thanks

**Comment by Thomas101** [comment]
Hi, this is on my todo list, there's already an issue open for this (#434)  you can continue tracking progress from there. Thanks!

**Comment by AGonLen** [comment]
Perfect. Many thanks!
