### ISSUE TITLE
Zoom flickering

### ISSUE THREAD

**Issue by aurimus** [Thomas101/wmail#545]
Ubuntu 16.10, v2.0

The zoom flickers back and fort on some occasions. Explained in video.

https://drive.google.com/open?id=0B6hpw3kYc6qXdzhTamRoZUFYUzg

**Comment by Thomas101** [comment]
Hi, this was the best way I could fix an upstream issue with electron not keeping the zoom level for a while, but I've managed to find an even better way to do this which doesn't have the flickering side effect. I fixed this in 2ddca0a631c2cf068abc39927a39018da78cc9c9 but it's still waiting to go out into the next release/prerelease
