### ISSUE TITLE
Oops, something went wrong

### ISSUE THREAD

**Issue by dpo** [Thomas101/wmail#548]
* Which version of WMail are you using? [e.g. 1.3.1]

2.0.0. My issue may have been fixed in a pre-release?!

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

OSX 10.9.5.

After updating to 2.0.0, I've been getting this popup periodically:

![screen shot 2017-01-29 at 11 01 25](https://cloud.githubusercontent.com/assets/38760/22405601/47cba632-e613-11e6-8ee5-c2012cfc4377.png)

Thanks!

**Comment by dpo** [comment]
ps: still happens after the last update.

**Comment by Thomas101** [comment]
Is this appearing in a Gmail or Google Inbox account? If you restart WMail do you still see the same issue?

**Comment by stefanjudis** [comment]
☝️ I see it in Inbox. But I doesn't seem to affect any functionality. And it only appears occasionally. Haven't figured out yet, what's causing it.

**Comment by Thomas101** [comment]
I have to be honest I suspect this is something to do with Inbox itself and it's not an error that comes out of the WMail codebase. Could be something to do with account configuration/http connections dropping etc. Have you ever seen this in Inbox in Google Chrome for example?

**Comment by stefanjudis** [comment]
Yeah - I was thinking that it's in their codebase too. :) 

> Have you ever seen this in Inbox in Google Chrome for example?
Not using Inbox in a browser anymore. ;) I've got the excellent WMail! :P 

Thanks for that!

**Comment by dpo** [comment]
Yes it's in Inbox. For me, it happens almost every time I delete a message. It doesn't happen in the iOS app. It doesn't seem to affect functionality; it's just annoying.

**Comment by Thomas101** [comment]
@dpo could you try it in a desktop browser on your mac? See if it comes up there

**Comment by dpo** [comment]
I've just used it in the browser (Safari) for a couple of hours without any such popup. I'll try enabling the dev tools in WMail to see if anything shows up in the console.

**Comment by Thomas101** [comment]
That's interesting. It would be good to know if anything does come up in the Dev tools. Thanks!

**Comment by dpo** [comment]
All I see in the console is messages of this sort (but they don't seem to coincide with the "oops" popups):

![screen shot 2017-02-01 at 20 50 48](https://cloud.githubusercontent.com/assets/38760/22534230/a1e637ae-e8c0-11e6-8045-7b033a43fe81.png)

**Comment by Thomas101** [comment]
Thanks for that. That's error is WMail failing to reach google to sync the unread count & notifications. It shouldn't have any impact on the something went wrong error.

Was it just one of these or do more come up after a short while? If it was just the one I would think this is probably just WMail failing to connect out whilst your mac re-connects to the network after sleep etc. If there are repeated ones do you use a proxy server?

**Comment by dpo** [comment]
Those are only occasional. I'm not behind a proxy. It seems unrelated to the "oops". I'll post here if I find out more. Thanks!

**Comment by Thomas101** [comment]
Thanks. The `ENOTFOUND` error basically means that it couldn't connect to `googleapis.com` which suggests that your machine has come offline briefly for some reason. Maybe it's reconnecting to a network or switching network? Would be good to know if there is any correlation between that behaviour and these coming up

**Comment by Thomas101** [comment]
Hi, I'm going to close this off for now due to inactivity. If you're still having the issue feel free to re-comment or open a new issue and I'll look back into it.
