### ISSUE TITLE
Support for Google Drive offline files?

### ISSUE THREAD

**Issue by nsrosenqvist** [Thomas101/wmail#550]
* Which version of WMail are you using? **2.0.9 pre-release**

* Which Operating System are you using? **Ubuntu Gnome 16.10 x64**

It would be awesome if support could be added for Google Drive offline files, there's an option for it in the Google Drive settings view but it requires a Google Chrome extension. Is it possible to have this shipped with the app or download it after installation (if there's license issues)?

**Comment by Thomas101** [comment]
This would be awesome to add in. I've added the Google Docs offline to the `Re-look at extension support` issue #451. Probably best to continue tracking from there as that's where I'll be posting updated. Thanks!
