### ISSUE TITLE
BUG: Unread count stuck at 2273

### ISSUE THREAD

**Issue by braykov** [Thomas101/wmail#558]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.9
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.10

**Comment by Thomas101** [comment]
Hi, is this with Gmail or Google Inbox? If you toggle the `Scrape Unread Count directly from UI` option to on for your account does this reset it to the correct number?

**Comment by braykov** [comment]
This is the Gmail. I use it with the tabs Primary, Social, Promotions, Updates and Forums.
Turned on Scrape. Restarted WMail - result 2273.
Turned off Scrape. Resterded again - result 2273. And it's like this on two machines. Both Ubuntu.

**Comment by Thomas101** [comment]
Which Unread mode do you have selected under your account settings?

**Comment by braykov** [comment]
"All unread messages".
But all but the last option show the same number :-)
Only with "All messages in inbox" it changes to 4566. But this number is also fixed: deleting emails does not change it.

**Comment by Thomas101** [comment]
If you're using the categories inbox you're probably best to use the `Unread Messages in Primary Category` mode. You might need to wait a few minutes/restart WMail for the counts to update

**Comment by braykov** [comment]
Nope, I like it like this. It worked in 2.0.8 properly.

**Comment by Thomas101** [comment]
That's weird. I've looked through the commits between 2.0.8 and 2.0.9 and there's no changes to this. When you turned on the scrape did you try restarting WMail? What's the unread count that Gmail displays under the compose button?

**Comment by braykov** [comment]
Ok, first, I did what you wanted - switched to `Unread Messages in Primary`, waited and restarted. No change.
Now, under `Compose`, I see the unread which are only in the `Primary` group, which is 7.

**Comment by braykov** [comment]
OK, I think I have something. At some point I enabled 2-factor authentication for my Google account.
Maybe that is the point where the unread count stopped updating.
Just now, on one of the machines I purged the app and deleted all settings and cache. Installed again. Google asked me for confirmation. And now it is working (however updating unread count takes like half a minute).

Perhaps WMail did not realize it needed account confirmation or whatever. 
If you think of debugging steps, I still have the old setup in place with another machine.

**Comment by Thomas101** [comment]
Okay thanks. I'm not sure why the authentication would have been failing as it should have carried over when 2FA was enabled. If it's working now am I okay to close this off?

**Comment by braykov** [comment]
I personally don't have a problem with it anymore. And I know how to fix it on the other machine.
But I also think WMail should have sensed the need to reconfirm authentication. Instead it works fine, but does not update the unread count.
It is up to you :)

**Comment by Thomas101** [comment]
I'll close it for now then. I've got some updates coming to the auth stuff that should hopefully make it more stable. Thanks!
