### ISSUE TITLE
Request: I want to use backward and forward buttons on mouse

### ISSUE THREAD

**Issue by TYKim7** [Thomas101/wmail#56]
Hi.

First, thank you very much making this awesome app!!
I always looking forward to use this light and super fast mail client. 

I've been using this app for a few days. And I want to request a small improvement.

I've been using Mac with 5 button mouse, and the forward and backward buttons don't work in Wmail app. 

If possible, please make a improvement in next release~

Thank you again.

**Comment by Thomas101** [comment]
Hi @TYKim7 what make is your mouse?

**Comment by TYKim7** [comment]
Hi

Minr is razr mouse. Death edder 2000

2016년 2월 6일 토요일, Thomas Beverley<notifications@github.com>님이 작성한 메시지:

> Hi @TYKim7 <https://github.com/TYKim7> what make is your mouse?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Thomas101/wmail/issues/56#issuecomment-180562083>.
>


-- 
Tae-Young Kim
Ph.D Candidate

Molecular Nanoelectronics Lab
Dept. of Physics & Astronomy
Seoul National Univeristy, SEOUL, KOREA
Office: +82-2-880-6608
Mobile: +82-10-2652-4673
Lab Webpage: http://mnelab.com

**Comment by russiancow** [comment]
Is there any update on this? I looked into implementing it myself, but it seems Electron doesn't capture mouse events for those buttons at all, for some reason. I found [this](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-app-command-windows), but it's only supported on Windows apparently.

**Comment by Thomas101** [comment]
@russiancow not as yet. I've had a quick look at it but couldn't see anything obvious

**Comment by Thomas101** [comment]
I've taken another look at this and don't seem to be able to pick out any events on osx. This might be something that needs to be added to electron-core for osx, or it might just be the case that I'm looking in the wrong place.

I'm going to keep an eye out for any potential solutions to this and also add it to the help-wanted flag in case anyone else has any ideas

**Comment by lid** [comment]
Doesn't it depend on what those mouse buttons are actually bound to? I'm using a Logitech mouse with "back" and "forward" buttons bound to "Left Cmd + Left" and "Left Cmd + Right", respectively. This works  in Chrome, and works in Wmail as well.

**Comment by russiancow** [comment]
@lid: In your case, yes, since you mapped it yourself. But the issue here is a different one, namely that Electron doesn't seem to expose click events for mouse4 and mouse5 for some reason.

**Comment by trueschool** [comment]
I'm not sure if it's appropriate to piggyback on this request, but it would also be cool to be able to use the Cmd+← arrow to page back like I would in a browser.

**Comment by Thomas101** [comment]
@trueschool I've opened a new issue for this #260

**Comment by Thomas101** [comment]
I'm going to close this off now. Mice generally use non-standard controls which I'm not able to pick out. WMail does support backspace and Cmd+←. It's probably best to try and map your mouse controls to those keybindings.
