### ISSUE TITLE
Restoring WMail from minimised icon

### ISSUE THREAD

**Issue by james-clark-5** [Thomas101/wmail#565]
* Which version of WMail are you using? [e.g. 2.0.9]

* Which Operating System are you using? [Windows 10 64-bit]

Have to double click (or quadruple click!) the icon to restore the app - is it possible to have an option for just a single click to be required?

Here's what I see: WMail is active in the taskbar. Double clicking the minimised icon (near the clock) minimises the app. Double clicking again restores it. 
If the app isn't in the foreground/visible, I would only click this to try and make it visible.

**Comment by Thomas101** [comment]
Thanks, I'll take a look as to why this doesn't work with single click

**Comment by Thomas101** [comment]
Hi, version 2.2.0 and 2.2.1 should allow you to show re-focus the window with a click. They're available to [download here](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!
