### ISSUE TITLE
wmail error: no mailbox specified

### ISSUE THREAD

**Issue by igorbarkowsky** [Thomas101/wmail#569]
* WMail 2.0-3.1 (from ppa:atareao/wmail for Ubuntu)
* Ubuntu 16.04.1

Try to run application from terminal at first time:
```
$ wmail
wmail error: no mailbox specified - please define at least your $MAIL environment-variable!
```

**Comment by Thomas101** [comment]
Hi, I'm not 100% sure if the error is coming from something to do with the packaging or WMail itself. I can't find any record of the error string in the source code.

When running WMail if you go to about under the main menu which version does it come out with? I suspect it might be version 2.0.0. If you try the latest [prerelease](https://github.com/Thomas101/wmail/releases/tag/v2.0.9) that may help. There's a deb build which should just install right off.

**Comment by igorbarkowsky** [comment]
Just install from deb-package from your site, and launch program through unity lense. It solves the problem.

**Comment by Thomas101** [comment]
Awesome, I'll close this off then. Thanks
