### ISSUE TITLE
Suggestion: simplify Gatekeeper instructions in README

### ISSUE THREAD

**Issue by tinymachine** [Thomas101/wmail#57]
Loving WMail. Thanks so much for your work on this! Just a thought: you could simplify the README directions for launching the app for the first time with Gatekeeper enabled by instructing users to right-click or Control-click on the app icon and then click "Open" in the contextual menu: 

![contextual menu](https://cloud.githubusercontent.com/assets/171986/12565302/cc6b9ef2-c368-11e5-85d0-98f46fce0c1e.png)

Then they'll see this prompt:

![Gatekeeper dialog](https://cloud.githubusercontent.com/assets/171986/12565213/5878ff26-c368-11e5-923a-641a3312a254.png)

They'll just need to click "Open", then they're set.

**Comment by Thomas101** [comment]
Well you learn something new every day. I've been going the long way around for ages! Thanks for this! :)

**Comment by tinymachine** [comment]
You're welcome -- thanks for Wmail!
