### ISSUE TITLE
Possible Memory Leak on macOS

### ISSUE THREAD

**Issue by gdsmith** [Thomas101/wmail#570]
Recently I've noticed leaving WMail open it ends up using massive amounts of memory. Not sure when it started, but it wasn't with the latest macOS software update. Quitting and restarting fixes it temporarily but it does end up happening again.

* Which version of WMail are you using? [e.g. 1.3.1]

2.0.9 (now checking 2.0.8)

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS Sierra 10.12.3

**Comment by gdsmith** [comment]
Okay, still happening with 2.0.8

![image](https://cloud.githubusercontent.com/assets/908695/22642477/41840ad2-ec74-11e6-851e-a07bbad2b1a7.png)

**Comment by Thomas101** [comment]
Hi,

In WMail if you open up the settings there's a small link that says `Memory Info` at the bottom of the dialog. Can you drop me a screenshot of what that comes up with? That will give me some more detailed information about what's using what.

Thanks

**Comment by gdsmith** [comment]
Seems to have settled down, may have been related to large number of unread emails, have cleared my inboxes…

**Comment by Thomas101** [comment]
From what I've seen it's normally down to inbox to be honest. I've just uploaded the [2.1.1 release](https://thomas101.github.io/wmail/download?v=2.1.*) which uses chrome 56. You might get better mileage with this :)
