### ISSUE TITLE
[2.0.9/2.1.0] Installation problem 

### ISSUE THREAD

**Issue by keypey** [Thomas101/wmail#573]
* Which version of WMail are you using? [e.g. 1.3.1]
- 2.0.9, 2.1.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
- Debian GNU/Linux 9.0 (stretch)

Problem during installation:
- Require WMail libappindicator1 >= 12.10.1

> dpkg --info WMail_2_0_9_prerelease_linux_x86_64.deb 
nowy pakiet Debiana, wersja 2.0.
rozmiar 51982864 bajtów: archiwum kontrolne=2505 bajtów.
     431 bajtów,    12 linii      control              
    5027 bajtów,    73 linii      md5sums              
     188 bajtów,     4 linii   *  postinst             
 Package: wmail-desktop
 Version: 2.0.9-1
 Installed-Size: 147026
 Section: misc
 Priority: optional
 Architecture: amd64
 Depends: lsb-base (>= 3.2),libappindicator1 (>= **12.10.1)**
 Maintainer: Thomas Beverley <tom.beverley.wmail@gmail.com>
 License: MPL-2.0

But debian has version 
- 0.4.92-4

>aptitude show libappindicator1
Pakiet: libappindicator1                     
Wersja: **0.4.92-4**
Stan: zainstalowany
Zainstalowany automatycznie: nie
Wieloarchitekturowość: taka sama
Priorytet: opcjonalny
Sekcja: libs
Opiekun: Debian QA Group <packages@qa.debian.org>
Architektura: amd64
Rozmiar rozpakowanego: 102 k
Wymaga: libatk1.0-0 (>= 1.12.4), libc6 (>= 2.2.5), libcairo2 (>= 1.2.4),
        libdbusmenu-glib4 (>= 0.4.2), libdbusmenu-gtk4 (>= 0.4.2),
        libfontconfig1 (>= 2.11), libfreetype6 (>= 2.2.1), libgdk-pixbuf2.0-0
        (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk2.0-0 (>= 2.20.0),
        libindicator7 (>= 0.4.90), libpango-1.0-0 (>= 1.14.0),
        libpangocairo-1.0-0 (>= 1.14.0), libpangoft2-1.0-0 (>= 1.14.0)
--
kp.,

**Comment by nipnull** [comment]
Hi! Yeah, its not good.

I fix it by upgrading libappindicator1 from https://pkgs.org/download/libappindicator1 (i use ubuntu trusty updates main).

Apt takes it good.

**Comment by Thomas101** [comment]
Awesome! I was going to suggest using one of the ubuntu repositories

**Comment by keypey** [comment]
I tried to install libappindicator1_12.10.1+13.10.20130920-0ubuntu4_amd64.deb, but without success. 
@nipnull:
I can not install from the Ubuntu repository (Trusty) - because it breaks the other depending on other Debian packages Stretch that use libappindicator1 (ex. python-appindicator requires: = 0.4.92-4).

**Comment by keypey** [comment]
@nipnull: I found another solution that works for me. It is not elegant, but keeps the debian stretch (9.0) package dependencies (change in control file .deb)
1. Download WMail_2_1_0_linux_x86_64.deb
2. Next:
$ cd <download-directory>
$ cp WMail_2_1_0_linux_x86_64.deb WMail_2_1_0_linux_x86_64-repack-control.deb 
$ mkdir tmp
$ cd tmp
$ ar p ../WMail_2_1_0_linux_x86_64.deb control.tar.gz | tar -xz
$ nano control
```
in file: "control", 
change line: Depends: lsb-base (>= 3.2),libappindicator1 (>= **12.10.1)**
to: Depends: lsb-base (>= 3.2),libappindicator1 (>= **0.4.92-4**) 
```
$ tar czf control.tar.gz *[!z]
$ ar r ../WMail_2_1_0_linux_x86_64-repack-control.deb control.tar.gz

3. We can now install WMail_2_1_0_linux_x86_64-repack-control.deb  on Debian 9.0 Stretch. I am using 11 email accounts - and version 2.1 works correctly (libappindicator1, version: 0.4.92-4).

**Thomas101**, Thanks for a great job! Thanks and keep up the good work!
--
kp.

**Comment by Thomas101** [comment]
@keypey Glad you managed to get it working. The other thing I was going to suggest was downloading the tar version, changing the dep to 0.4.* and installing it manually.

Do desktop notifications continue to work with `0.4.92-4`? If they do I might reduce the dependency version to reflect this

**Comment by keypey** [comment]
@Thomas101: 

Desktop notification test:
![wmnotify](https://cloud.githubusercontent.com/assets/3405185/22821403/2e636024-ef7b-11e6-9d62-59512746d56a.png)

works fine!

**Comment by nipnull** [comment]
@keypey: It's really interesting solution, thanks for experience. And it's really better to save original repositories connection without conflicts with versions of dependent packages.

About notifications: i used 2.0.0 version and update to 2.1.0. On each of them notifications works fine throw dunst.

**Comment by nipnull** [comment]
If it'll be really big problem, its possible to write .sh to work with new tar installation to create .deb with replacing versions of dependent packages from ubuntu repos to debian stable.

@Thomas101: write if it'll be actual

**Comment by Thomas101** [comment]
I've just updated the deb builds with the `0.4.92-4` dependency. Same release version. Thanks!

**Comment by nipnull** [comment]
@Thomas101: 0.4.92-4 is stable version on Debian 9, which is not released yet. At Debian 8 stable version of libappindicator1 is 0.4.92-3.1. Is it possible to change dependency version one more time? Thanks a lot

**Comment by keypey** [comment]
Thomas101: My primary workstation has a version 0.4.92-3.1. I can also test WMail version libappindicator1 0.4.92-3.1.

**Comment by Thomas101** [comment]
@keypey it would be great if you could! I'll relax the requirement a little more if it all looks good

**Comment by nipnull** [comment]
I'm testing right now too. As example, your last stable build as .deb with replacing dependency by keypey method notify me about this messages.

**Comment by keypey** [comment]
nipnull ,  Thomas101 :
0. repack for libappindicator1 0.4.92-3.1
1. Install on: LMDE Betsy/(Debian Jessie -8 repo) - ok.
2. Add account - ok.
3. Try icon - ok.
4. Notify - ok.
Later (at night) I try to check all my accounts.

**Comment by nipnull** [comment]
@keypey, @Thomas101:

0. Repack - ok;
1. Install on Debian 8.1 with i3wm - ok;
2. Using old settings like its upgrade - ok.

I'm using only 1 account as inbox.

**Comment by Thomas101** [comment]
It's looking good my end. I'm just prepping the updated deb files...

**Comment by Thomas101** [comment]
that's those updated! Thanks :)

**Comment by nipnull** [comment]
This issue is going to be a chat;) @Thomas101, thanks you again for really responsive development so useful soft)
