### ISSUE TITLE
This version of Chrome is no longer supported. Please upgrade to a supported browser.

### ISSUE THREAD

**Issue by ivancevich** [Thomas101/wmail#574]
Which version of WMail are you using? 2.0.0

Which Operating System are you using? macOS Sierra 10.12.3

Hi, I use Wmail every day. It's awesome! Thank you creating it!
Today, when I opened it, I got this message from Gmail on the top: "This version of Chrome is no longer supported. Please upgrade to a supported browser."
I guess Electron will need to be updated.
Thanks again.
JC

**Comment by alexforster** [comment]
Just came here to say the same. Can't live without WMail – thanks for all the work!

**Comment by Thomas101** [comment]
I'm working on upgrading chromium to 56 - will post new releases later on today

**Comment by chuck-talk-sp** [comment]
Thanks Thomas101, this is an awesome application and I use it every day as well. :)

**Comment by ochoadavid** [comment]
Same here, using Linux 64.
Thanks Thomas101, great app! =)

**Comment by missebet** [comment]
Just verified I'm using the latest version of chrome, and still have the error. Completely closed and re-started WMail.  Ant thoughts?

**Comment by ivancevich** [comment]
@missebet it doesn't matter which version of Google Chrome you have. WMail uses its own version of Chromium.

**Comment by Thomas101** [comment]
2.1.0 and 2.1.1 pre-release have just hit the [download page](https://thomas101.github.io/wmail/download?v=2.1.*). A bit of a rush to get electron updated quickly, but it looks like it's all working :)

Thanks everyone for reporting!
