### ISSUE TITLE
Black Bar on the left doesn't have to be there all the time.

### ISSUE THREAD

**Issue by shahin365** [Thomas101/wmail#58]
Hi,

this black barn the left takes space and it doesn't do anything other than switching/adding account. can you add an option to hide it?

Thanks :)

**Comment by shahin365** [comment]
Closed? what it means? already done?

On Sat, Feb 20, 2016 at 2:43 AM, Thomas Beverley <notifications@github.com>
wrote:
Closed #58 [https://github.com/Thomas101/wmail/issues/58] .

—
Reply to this email directly or view it on GitHub
[https://github.com/Thomas101/wmail/issues/58#event-557444089] .[https://github.com/notifications/beacon/AP-Uu4rZMfmftxdgHC_AivEDRMBQprmWks5pmBCvgaJpZM4HMDxN.gif]

**Comment by shahin365** [comment]
How Can I hide the sidebar?

On Sat, Feb 20, 2016 at 2:43 AM, Thomas Beverley <notifications@github.com>
wrote:
Closed #58 [https://github.com/Thomas101/wmail/issues/58] .

—
Reply to this email directly or view it on GitHub
[https://github.com/Thomas101/wmail/issues/58#event-557444089] .[https://github.com/notifications/beacon/AP-Uu4rZMfmftxdgHC_AivEDRMBQprmWks5pmBCvgaJpZM4HMDxN.gif]

**Comment by shahin365** [comment]
What I meant was the Black side bar which shows accounts.

On Sat, Feb 20, 2016 at 2:43 AM, Thomas Beverley <notifications@github.com>
wrote:
Closed #58 [https://github.com/Thomas101/wmail/issues/58] .

—
Reply to this email directly or view it on GitHub
[https://github.com/Thomas101/wmail/issues/58#event-557444089] .[https://github.com/notifications/beacon/AP-Uu4rZMfmftxdgHC_AivEDRMBQprmWks5pmBCvgaJpZM4HMDxN.gif]

**Comment by mykecheckonetwo** [comment]
Shahin give them some time. When it's "closed" that means they have addressed the issue and upon a future update you will see this feature roll out. I'm assuming they are in final testing of an upcoming release.

**Comment by shahin365** [comment]
I’m sorry I didn’t mean to disrespect. Since there is no word from Developer, I
just was curious what closing a topic means.
Cheers to all. Have a nice weekend :)

On Sat, Feb 20, 2016 at 11:34 AM, mykecheckonetwo <notifications@github.com>
wrote:
Shahin give them some time. When it's "closed" that means they have addressed
the issue and upon a future update you will see this feature roll out. I'm
assuming they are in final testing of an upcoming release.



On Feb 20, 2016, 10:33 AM -0600, shahin365<notifications@github.com>, wrote:
> How Can I hide the sidebar?
>
> On Sat, Feb 20, 2016 at 2:43 AM, Thomas Beverley<notifications@github.com>
> wrote:
> Closed #58 [https://github.com/Thomas101/wmail/issues/58] .
>
> —
> Reply to this email directly or view it on GitHub
> [https://github.com/Thomas101/wmail/issues/58#event-557444089]
.[https://github.com/notifications/beacon/AP-Uu4rZMfmftxdgHC_AivEDRMBQprmWks5pmBCvgaJpZM4HMDxN.gif]
>
> —
> Reply to this email directly orview it on
GitHub(https://github.com/Thomas101/wmail/issues/58#issuecomment-186642434).
>
>
>


—
Reply to this email directly or view it on GitHub
[https://github.com/Thomas101/wmail/issues/58#issuecomment-186642914] .[https://github.com/notifications/beacon/AP-Uu4MVViXbBg33CD_q3zz8u73JoEs3ks5pmI0tgaJpZM4HMDxN.gif]

**Comment by Thomas101** [comment]
hi @shahin365 no worries. I've closed it because I've fixed it, but I've added the `waiting-release` tag which means it's not yet been added into a build and released. Once I've finished, put the final finishes to the build I'll make a release and post it as a pre-release which you can download. I normally try to post message on all the closed issues at this point.

Once there have been a few pre-releases and some external testing I'll build a full release which gets pushed out to all the active users :). Keep an eye on the thread and I'll post when you can download it :+1:

**Comment by shahin365** [comment]
Awesome! Thank you so much :)
Great work. Nice app. It’s still Alpha & Already better than some other similar apps out there in App Store.

Have a good weekend.

------------
My Best,
Shahin

       

On February 20, 2016 at 11:40:44 AM, Thomas Beverley (notifications@github.com) wrote:

hi @shahin365 no worries. I've closed it because I've fixed it, but I've added the waiting-release tag which means it's not yet been added into a build and released. Once I've finished, put the final finishes to the build I'll make a release and post it as a pre-release which you can download. I normally try to post message on all the closed issues at this point.

Once there have been a few pre-releases and some external testing I'll build a full release which gets pushed out to all the active users :). Keep an eye on the thread and I'll post when you can download it

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!

**Comment by shahin365** [comment]
That was fast! Wonderful! It looks much cleaner now! :)

On Sat, Feb 20, 2016 at 12:43 PM, Thomas Beverley <notifications@github.com>
wrote:
Hello! I've added this into the latest pre-release (1.2.1) which is available on
the downloads page [http://thomas101.github.io/wmail/download] or from the direct link
[https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip] .

Thanks for your help!

—
Reply to this email directly or view it on GitHub
[https://github.com/Thomas101/wmail/issues/58#issuecomment-186657964] .[https://github.com/notifications/beacon/AP-Uu-eYBq7e4JXr3_U4ehO3Zwc7d8_sks5pmJ1XgaJpZM4HMDxN.gif]
