### ISSUE TITLE
Warning: version of Chrome is no longer supported

### ISSUE THREAD

**Issue by cribari** [Thomas101/wmail#580]
* Which version of WMail are you using? [e.g. 1.3.1]

2.0.9

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Arch Linux 

I see the following warning message in a yellow top bar: "This version of Chrome is no longer supported. Please upgrade to a supported web browser."

**Comment by Thomas101** [comment]
Hi, if you [download 2.1.0 or 2.1.1 prerelease](https://thomas101.github.io/wmail/download) this no longer appears

**Comment by luzpaz** [comment]
Looks like the arch maintainer hasn't updated to 2.1.0

**Comment by funilrys** [comment]
Thanks for the ping I'm on it now !

**Comment by funilrys** [comment]
@cribari @luzpaz Arch Update come in the next 15/30 minutes :)

**Comment by funilrys** [comment]
@Thomas101 @cribari @luzpaz Updated. Do you prefer to have the pre-release (2.1.1) or the release version (2.1.0) ? 

Your choice gonna be mine!

**Comment by luzpaz** [comment]
@funilrys I vote for 2.1.1

**Comment by funilrys** [comment]
Thanks for answer @luzpaz . As active user around wmail for Arch (thanks for all those pings) your choice is important. 

And you @cribari ?

**Comment by cribari** [comment]
@funilrys Many thanks for updating the Arch package! 

@funilrys @Thomas101 I have just upgraded wmail to version 2.1.0 (Arch Linux). I noticed an important difference from the previous version: I no longer have the Services options in Preferences -> Accounts. Is that gone?

**Comment by Thomas101** [comment]
@funilrys thank you! :-)

@cribari @funilrys the services are still only in the prerelease channel 2.1.1. I've got some work to do on them before they go mainstream but had to rush out this update with newer version of chrome.

**Comment by funilrys** [comment]
so @cribari please wait a bit gonna publish update to 2.1.1 :)

**Comment by cribari** [comment]
@funilrys Thank you!!!!

**Comment by funilrys** [comment]
@luzpaz @cribari @Thomas101 Archlinux version is now updated to 2.1.1

**Comment by cribari** [comment]
@funilrys Services are back! Many, many thanks.

**Comment by luzpaz** [comment]
@funilrys 👍 
@cribari please close the issue. Thx
