### ISSUE TITLE
Quitting v2.1.0 app prompts "quit unexpectedly" window every time

### ISSUE THREAD

**Issue by chuckreynolds** [Thomas101/wmail#582]
* Which version of WMail are you using? [e.g. 1.3.1]
2.1.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.12.3 (16D32)

Every single time since updating to 2.1

<img width="956" alt="problem_report_for_wmail" src="https://cloud.githubusercontent.com/assets/46185/22801740/f2490dfe-eec2-11e6-81c6-bf80d733ed21.png">

**Comment by borgo** [comment]
Same here, 2.1.0 / OSX 10.12.3
[bugreport.txt](https://github.com/Thomas101/wmail/files/764925/bugreport.txt)

**Comment by Eworm** [comment]
Same here! 2.1.0 / Mac OS 10.12.3

**Comment by chuckreynolds** [comment]
> happens on Quitting (Cmd+Q)
And I tested with File > Quit too. both; same thing.

**Comment by Thomas101** [comment]
Thanks I'm seeing the same. Only appears to affect Mac OS. There's a couple of bug reports on this in electron so it looks like an upstream bug...

https://github.com/electron/electron/issues/8644
https://github.com/electron/electron/issues/8563#issuecomment-277227964

**Comment by thomasmichaelwallace** [comment]
This also happens on 2.1.1.

**Comment by nlenkowski** [comment]
Getting this on 2.1.0 on macOS 10.12.3 as well.
[wmail-crash-report.txt](https://github.com/Thomas101/wmail/files/787436/wmail-crash-report.txt)

**Comment by rosamaglione** [comment]
Same here. Version 2.1.1

On macOS 10.12.3.

![image](https://cloud.githubusercontent.com/assets/25934006/23174917/e009c918-f82b-11e6-9846-28eec06644cf.png)

**Comment by ieatfood** [comment]
Has been fixed upstream and released in electron@1.6.1. Just need to bump wmail.

**Comment by Thomas101** [comment]
Hi, version 2.2.0 and 2.2.1 should quit gracefully now. They're available to [download here](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!
