### ISSUE TITLE
What happen to Services?  I.e. google drive, etc

### ISSUE THREAD

**Issue by rccolata** [Thomas101/wmail#583]
* Which version of WMail are you using? [e.g. 1.3.1] 2.1.0.  
I 

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I was using ver 2.0.9 and there were google drive, etc services below the icon for my gmail account.  When I installed 2.1, they disappeared and I see no way to enable them.  When I uninstalled 2.1 and reinstalled 2.09, then they reappeared as well as the settings for them.  installing 2.1 removes them.  I see no changes on the change log for this.

**Comment by pawelantczak** [comment]
Try `2.1.1`

**Comment by Thomas101** [comment]
Yeah you need to stick with the prerelease channel. Have updated the release notes to reflect this more clearly
