### ISSUE TITLE
Can't run Wmail 2.1.0 on OSX because it is from an unidentified developer

### ISSUE THREAD

**Issue by Jofsey** [Thomas101/wmail#586]
Sorry, I can't provide a screenshot because it's in Russian.

Mac OSX 10

**Comment by Thomas101** [comment]
Hi, the first time you run it you need to use right click and open because you have Gatekeeper enabled. Theres' further [instructions here](https://github.com/Thomas101/wmail/wiki/Gatekeeper-&-OSX)
