### ISSUE TITLE
Clicking on Desktop Notification does not open email if you have Adblock plugin. 

### ISSUE THREAD

**Issue by wdziemia** [Thomas101/wmail#59]
When I click on a notification, the window shifts to WMail but WMail fails to open the email. A popup comes up telling me to disable Adblock, and once hit "Ok" then the page never loads anything (only shows a blank screen). There is no way to reload the page to display the inbox again unless I restart the client. Im not sure how green-list WMail within adblock either. 

System OS: OSX 10.11
Chrome Version: V 48.0.2564.82 (64 Bit)

**Comment by bertrandmartin01** [comment]
dupliate with issue #37 

https://github.com/Thomas101/wmail/issues/37

**Comment by wdziemia** [comment]
Dupe of #37
