### ISSUE TITLE
Calendar notifications would great!

### ISSUE THREAD

**Issue by bsarrazin** [Thomas101/wmail#590]
* Which version of WMail are you using? 2.1.1
* Which Operating System are you using? macOS 10.12.3

It would be great if we could get calendar notifications. :)

**Comment by Thomas101** [comment]
Thanks! I'll take a look!

**Comment by bauerp** [comment]
That would be great! I could then fully use this for work.

**Comment by evantahler** [comment]
I'm using mailplane, and if WMAIL added a view for google calendar, this would be a total replacement :D

**Comment by SVilgelm** [comment]
👍

**Comment by pkajaba** [comment]
Please add it :) Anyway great app!
