### ISSUE TITLE
Left Alt + Shift shortcut open the Toggle Menu Application

### ISSUE THREAD

**Issue by SMed79** [Thomas101/wmail#592]
Hi,

to switch [between languages](http://i.imgur.com/6jkkz0N.png) the default shortcut is **Left Alt** + **Shift** but this change the keyboard layouts and at the same times open the [Toggle Menu Application](http://i.imgur.com/3wyDfaX.png).

I have to click **Esc** or any where to hide the menu application and continue writing.

I don't know what wrong, any idea is welcome. 

* wmail v2.0 (C) 2000~2002 Sven Geisenhainer <sveng @ informatik.uni-jena.de>

* Ubuntu 16.04.1 LTS (xenial) / 4.4.0-62-generic

**Comment by nipnull** [comment]
Hi!

I repeat this bug on Debian 8 with wmail 2.1.0 by using left alt with left shift to switch languages.

**Comment by Thomas101** [comment]
Thanks, I'll take a look at what's toggling the application menu
