### ISSUE TITLE
libappindicator1 dependency

### ISSUE THREAD

**Issue by ZachCuipylo** [Thomas101/wmail#593]
* Which version of WMail are you using? [e.g. 1.3.1]
Attempting to install latest x64 .deb file, have also tried with tarball

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Kali Linux (Sana) Rolling 64-bit

*WMail repeatedly returns errors of missing dependency (libappindicator1 (>= 12.10.1) when trying to install

I have attempted to solve using apt-get -f install (both with an without package argument), and installing all related libappindicator1 packages from the sid repos on debian's site.  I have i386 architecture enabled, but am using the 64 bit .deb/tar.

Where is this missing dependency?

(I love WMail and have been using, but something went wrong when I tried to upgrade)

P.S. Is there a specific repo that includes wmail?  (note that there is already a packaged named "wmail" but it is a different program)

```
user@kali:~$ sudo dpkg -i WMail_2_1_0_linux_x86_64.deb
     Selecting previously unselected package wmail-desktop.
     (Reading database ... 531254 files and directories currently installed.)
     Preparing to unpack WMail_2_1_0_linux_x86_64.deb ...
     Unpacking wmail-desktop (2.1.0-1) ...
     dpkg: dependency problems prevent configuration of wmail-desktop:
     wmail-desktop depends on libappindicator1 (>= 12.10.1); however:
     Version of libappindicator1:amd64 on system is 0.4.92-4.

     dpkg: error processing package wmail-desktop (--install):
     dependency problems - leaving unconfigured
     Errors were encountered while processing:
     wmail-desktop
```

```
user@kali:/opt$ gdebi WMail_2_1_0_linux_x86_64.deb
      Reading package lists... Done
      Building dependency tree        
      Reading state information... Done
      Reading state information... Done
      This package is uninstallable
      Dependency is not satisfiable: libappindicator1 (>= 12.10.1)
```

**Comment by nipnull** [comment]
Hi! There's a solution https://github.com/Thomas101/wmail/issues/581

**Comment by Thomas101** [comment]
I've also re-uploaded the 2.1.0 and 2.1.1 releases with the libappindicator1 dependency relaxed down to 0.4.92-4 so if you try re-downloading those you should be good :)
