### ISSUE TITLE
Can't access options menu

### ISSUE THREAD

**Issue by felipeGdlO** [Thomas101/wmail#595]
Hello, I just downloaded the current stable build of WMail for Windows 10. I set up my two email accounts and then opened the options menu, I removed the side bar where I can chose which account to view. I want to get the sidebar back but now I can't reopen the options menu since the button is in that side bar. I tried uninstalling and reinstalling but that didn't solve the issue.

How can I open the options menu to re-enable the sidebar?

SOLVED IT: by trial and error found that by pressing shift+fn+F10 I can access the WMail settings

**Comment by Thomas101** [comment]
Hi you can also bring them up by right clicking anywhere in the window and picking `WMail Settings`
