### ISSUE TITLE
2.1.1 Goes to default zoom sometimes after exiting mail view

### ISSUE THREAD

**Issue by braykov** [Thomas101/wmail#597]
* Which version of WMail are you using? [e.g. 1.3.1]
2.1.1
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.10
* Which application? [Inbox, Gmail]
GMail

My default zoom is 5 times IN (where do you show the %???).
Sometimes after I delete a mail or click "Return to Inbox" after reading a mail, the zoom resets to default. It is as if I have clicked CTRL+0. And when I try zoom in again, just after the first CTRL+Shift+=, it is restored. And the same happens if I zoom out once, too. So it seems my setting is remembered but the view does not correspond.

**Comment by Thomas101** [comment]
Hi, did this happen on the previous version you were using?

**Comment by Thomas101** [comment]
There's also some fixes upstream in electron around this although they've not made it out into a release yet https://github.com/electron/electron/pull/8537

**Comment by braykov** [comment]
This problem is new for me on 2.1.1. It didn't happen on 2.0.9. Not sure about 2.1.0.

**Comment by fsdias** [comment]
I confirm this behaviour with 2.2.1 .

**Comment by bmurphy1976** [comment]
Same here.  New behavior in v2.2.1, was not in v2.2.0.  Ubuntu 16.04 installed 64-bit deb.

**Comment by Thomas101** [comment]
Hi, this should be fixed in [2.3.0 and 2.3.1 prereleases](https://thomas101.github.io/wmail/download?v=2.3.all). Thanks for reporting!

**Comment by fsdias** [comment]
Thanks, fix confirmed!

**Comment by braykov** [comment]
Great many thanks!
Not only this is fixed, but also the initial zoom flicker that used to happen right after starting the app is now gone with 2.3.1.
