### ISSUE TITLE
Notification don't work behind proxy

### ISSUE THREAD

**Issue by movitch** [Thomas101/wmail#601]
* Which version of WMail are you using? [e.g. 1.3.1]
2.1.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX Sierra

Hi,
Notification and number of undread emails in status bar icon are not refreshed behind proxy server (set on the OSX system, it's a proxy server with authentication for information). However i can use app normaly, the issue is just on notification and unread email number.

**Comment by Thomas101** [comment]
Hi, version 2.2.0 and 2.2.1 should handle proxies much better. They're available to [download here](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!
