### ISSUE TITLE
Change description to simply WMail

### ISSUE THREAD

**Issue by Dainius14** [Thomas101/wmail#602]
On Windows 10 this applications are displayed by description. Only by expanding the list it is possible to see the actual title. IMO just plain title should be used as description.

![](http://i.imgur.com/vtNT3mN.png)
![](https://i.imgur.com/jxpDtik.png)

**Comment by Thomas101** [comment]
Thanks, I've changed this in the packager

**Comment by Thomas101** [comment]
Hi, the latest versions 2.2.0 and 2.2.1 have just WMail as the descriptions and they're available to [download here](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!
