### ISSUE TITLE
Can't Open Email in New Window

### ISSUE THREAD

**Issue by Niomar** [Thomas101/wmail#603]
* Which version of WMail are you using? [e.g. 1.3.1] 2.1.1 Prerelease
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Windows 10

When viewing an email, there is an icon in the top right corner of the email to open it in a new window (built-in gmail function).  It doesn't work in WMail.

![image](https://cloud.githubusercontent.com/assets/9040032/23028484/174ccd92-f42d-11e6-9d28-48b06344be8b.png)

**Comment by Thomas101** [comment]
Hi, thanks for reporting. There's already an issue open for this (#363). You can continue following progress updates from there
