### ISSUE TITLE
Open links in the background, and right click functionality

### ISSUE THREAD

**Issue by ToyinB** [Thomas101/wmail#605]
* Which version of WMail are you using? [e.g. 1.3.1]
2.1.1 pre release

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I noticed that there's no option to open links in the background, unlike the Mac version of this software. This could be a technical issue, however, it would be great to see the functionality maintained between OSs as much as possible.

Right click options would be a welcome addition. Simple commands such as 'move to folder,' or 'snooze until,' without having to click the individual Google icons etc.

**Comment by Thomas101** [comment]
Hi, this is down to the support that electron has given for [opening urls](http://electron.atom.io/docs/api/shell/#shellopenexternalurl-options-callback). The activate option is only available for osx hence why I haven't added it in on the other platforms. There may be a way to do add this feature in for windows and maybe linux too.

As for adding commands into the right click menu, it's certainly possible although a bit messy as you have to try and scrape the command actions out of gmail/inbox user interface which means it can be quite brittle. Do you use any browser extensions that already add this type of functionality? This might be something that would be better suited to adding into an extension when I add support

**Comment by ToyinB** [comment]
I had a quick dig around for an addon for Inbox to enable right click options. Doesn't seem to exist. However, in a broader sense enabling addons would be a fantastic addition. Gmelius for Inbox by Gmail would improve the flexibility of your product a lot (https://chrome.google.com/webstore/detail/gmelius-for-inbox-by-gmai/dlbjhjnahgmigifoggidegpakbcjomgg?hl=en).

**Comment by Thomas101** [comment]
Extensions are something that's in the pipeline and I think this is probably going to the best way to add these kind of additional features in. I've got an issue up for tracking those already (#451) so probably best to keep an eye on that one.

Will close this off for now as the extension issue is already open. Thanks!
