### ISSUE TITLE
Option to disable hotkeys

### ISSUE THREAD

**Issue by dantof** [Thomas101/wmail#607]
* Which version of WMail are you using? [e.g. 1.3.1]
2.10
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Win10 64

Alt+Ctrl+S conflicts with Right Alt+S which is used in several languages (keyboard layouts) to input national characters. I think that Alt+Ctrl+Letter is the same as RightAlt+Letter so Alt+Ctrl hotkeys potentialy confict with keyboard layouts that use right Alt to enter additional characters.

Easiest fix would be to change hotkey or to create an option to disable hotkeys.

**Comment by Thomas101** [comment]
Hi, is it only this keyboard shortcut that conflicts? It might be a case of just changing the bindings for windows to be a different combination

**Comment by dantof** [comment]
Hi, 
Only CTRL+Alt+S is a problem for me but using CTRL+ALR is generally not recommended on windows:

"_The right Alt key is usually an equivalent of the AltGr key because both the right Alt key and the AltGr key share the same scancode and are indistinguishable by software. However, on some keyboards it may not be the case, i.e. the keyboard has two Alt keys, each of which acts as the left Alt key. On compact keyboards like those of netbooks, the right Alt key may be missing altogether. To allow the specific functionality of AltGr when typing non-English text on such keyboards, Windows allows it to be emulated by pressing the Alt key together with the Control key:
Ctrl+Alt ≈ AltGr
Therefore, it is recommended that this combination not be used as a modifier in Windows keyboard shortcuts as, depending on the keyboard layout and configuration, someone trying to type a special character with it may accidentally trigger the shortcut,[5] or the keypresses for the shortcut may be inadvertently interpreted as the user trying to input a special character._"

It is from https://en.wikipedia.org/wiki/AltGr_key

**Comment by Thomas101** [comment]
I think that's the only one that uses ctrl+alt. I'll change it in the next release :). Thanks!

**Comment by Thomas101** [comment]
Hi, I've changed the keybindings in 2.2.0 and 2.2.1 and this is now available to [download](https://thomas101.github.io/wmail/download?v=2.2.*). Thanks!

**Comment by dantof** [comment]
Works perfect, many thanks!
