### ISSUE TITLE
[Feature Request] Add "Mark as read" and "Delete" buttons to native Windows 10 notifications

### ISSUE THREAD

**Issue by BabyPuncher** [Thomas101/wmail#608]
Windows 10.

See [MSDN blog entry on Windows 10 toast notifications](https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/07/08/toast-notification-and-action-center-overview-for-windows-10/) for more details on what the notifications are capable of.

**Comment by Thomas101** [comment]
Hi, electron doesn't provide support for the extra windows 10 notification actions (nor on osx for that fact) but I am looking at re-implementing some of the notification stack to include this as well as some other enhancements.

I've already got an issue open for this (#452), you can continue to track progress from there.

Thanks!
