### ISSUE TITLE
bug: after saving an attachment to drive, clicking again on the drive icon goes to inbox instead of going to drive

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#61]

**Comment by Thomas101** [comment]
this is probably related to #16 and #23.

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.6/WMail_1_1_6_osx_prerelease.zip). Thanks very much for your help!
