### ISSUE TITLE
Unread Count Doesn't Show

### ISSUE THREAD

**Issue by davidtaylorjr** [Thomas101/wmail#616]
* Which version of WMail are you using? 2.2.0

* Which Operating System are you using? Windows 10

The app had unread messages but the tray icon doesn't show any unread messages.

**Comment by Thomas101** [comment]
Hi,

Is this just the tray icon that's not showing unread messages? Are you seeing unread counts in the WMail sidebar?

**Comment by davidtaylorjr** [comment]
No I don't see an unread count anywhere.

**Comment by Thomas101** [comment]
Are you using inbox or gmail? What settings are you using if you got Settings > Accounts?

**Comment by Thomas101** [comment]
Also if you go to View > Developer Tools and click on the console tab do you see any errors or warnings coming out?

**Comment by davidtaylorjr** [comment]
None at all.

**Comment by Thomas101** [comment]
Are you using inbox or gmail? What settings are you using if you got Settings > Accounts? Are you behind a proxy server?

**Comment by davidtaylorjr** [comment]
I'm using Inbox, not behind a proxy, and I have it set to show unread
messages.

**Comment by Thomas101** [comment]
If you change the unread mode in settings does that have any effect?

**Comment by davidtaylorjr** [comment]
Ok this is interesting, it is now showing a "5" for unread messages but the
real count is about 9. Now I'm really confused.

**Comment by ElCampeon** [comment]
I am having the same issue. The badge counters seemed to stop working after I added a second email account. I turned off all counters and notifications for the 2nd account and that seemed to turn off both accounts. Then I deleted the 2nd account, restarted and turned on the badge counters for the 1st account, but nothing seems to work to get the functionality back.

Mac OSX 10.12.2 (16C67)

Wmail 
Version: 2.2.1 prerelease

![wmail 2017-02-24 19-46-32](https://cloud.githubusercontent.com/assets/26015813/23326389/cc53684a-fadb-11e6-804a-eb3d54ad3b77.png)

**Comment by Thomas101** [comment]
@ElCampeon the invalid grant error normally means that the token WMail is using to talk to Gmail has become invalid. Some users have reported this happening if you change 2 factor authentication settings with Google. 

If you try removing the last account, restarting wmail and add it again does that work and does anything come out in the console?

**Comment by ElCampeon** [comment]
OK. So, I deleted my main account, and then registered it again. Now, I have new message notifications in badge icons, but they have been wrong in terms of the amount of new emails, and they are delayed in updating.

**Comment by BechirZalila** [comment]
Hi,

I have the same problem here.

WMail version: 2.2.1 (same problem with 2.2.0)
OS: Max OS X 10.11.6

Attached an expanded error message I noticed on the developer tools console

![capture d ecran 2017-02-27 a 10 33 15](https://cloud.githubusercontent.com/assets/4518482/23355967/66dc5108-fcd8-11e6-9d0a-58e663854132.png)

**Comment by Thomas101** [comment]
@ElCampeon there can be a delay of a minute or so in updating the unread counts in WMail. If you go to settings and account I'm guessing your account is using the `Unread Unbundled messages` setting. If you change this to `Unread messages` is this more like what you'd expect?

@BechirZalila Apparently there's [been some issues](https://productforums.google.com/forum/#!msg/gmail/Kfsx8YjqAS4/nELRaCAkAAAJ) over at Google with users getting signed out of their accounts. You will probably need to re-add your account. I'll add something into WMail to handle this a bit more gracefully if it ever happens again

**Comment by BechirZalila** [comment]
@Thomas101 I did a fresh installation and readded all my accounts, same result.

**Comment by JBPlinn** [comment]
I got the same problem. No unread mail count whatsoever.

Wmail 2.2.0
Linux Ubuntu 16.04 - Xfce

I have errors in console: 
![image](https://cloud.githubusercontent.com/assets/26065072/23366403/de1f1042-fd06-11e6-918b-fb573aff0b67.png)

Worked like a charm in previous version.

**Comment by Thomas101** [comment]
After you re-added your account did you account icon appear in the left hand side or is it a solid color/number?

Could you give the following a try to see if it makes any difference...

1.) Download the previous version of WMail [2.1.0 if you were on the release channel](https://github.com/Thomas101/wmail/releases/tag/2.1.0) or [2.1.1 if you were on the prerelease channel](https://github.com/Thomas101/wmail/releases/tag/v2.1.1) and see it works out the box. If it doesn't, try re-adding one of your accounts. Does that start syncing the unread count?

2.) If 1 doesn't work, go to your [google account permissions](https://myaccount.google.com/permissions) in your browser, locate WMail in the list of authorized apps, click on it and then click remove. You'll need to re-add your account after this, does that make any difference?

**Comment by JBPlinn** [comment]
The account icon appear and the unread count is handled properly: erased when read, in the sidebar and in the tray.
No problem now.

**Comment by amig** [comment]
I also have an issue with the unread count tag. It's showing but it is stuck on a number that has nothing to do with the real count. I tested with version 2.2. and 2.2.1 and had the same issue. I downgraded to version 2.1.0 and unread count was back to function normally. I'm using Ubuntu 16.04 64b and gmail.

**Comment by BechirZalila** [comment]
I also downgraded to version 2.1.0 and everything seems to work fine now...

OS: Max OS X 10.11.6

**Comment by Thomas101** [comment]
Hi,

I've put together some debug builds that I've [uploaded here](https://drive.google.com/drive/folders/0B--sEKXlbUTRYjVhMnoxLUNMMmc?usp=sharing) (osx & linux only this time). Would anybody be able to download this and then give the following a try?

The debug build will work independently of the WMail you currently have setup so you'll find that when you launch it you wont have any accounts and your settings will be reset to default.

1.) Quit WMail and Launch the debug build
2.) Add an account
3.) If the developer tools aren't open, open them by going to `View > Developer Tools`, then click the `Console` tab and type/paste`window.test()` and wait a few moments for everything to come out and take a screenshot. You should get something like this...

![screen shot 2017-02-28 at 12 25 32](https://cloud.githubusercontent.com/assets/103586/23405214/211d9652-fdb1-11e6-9613-1ac6427e3056.png)
*I've auto-obfuscated the tokens that are logged out and these are shown as `<CLIPPED|length>first_10_chars`*



If you've done that can I have the following info...

* Account Type [Gmail/Inbox]
* Did your account icon appear when you first added the account [yes/no]
* Did you see any notifications or unread counts appear after adding the account [yes/no]
* Can you attach the screenshot that you took

Thanks!

**Comment by amig** [comment]
I tested the update and unread count was correct. Gmail/Ubuntu 16.04/64. Account icon was ok.

![wmail](https://cloud.githubusercontent.com/assets/203434/23412481/57e21ac8-fdde-11e6-8386-ec173dd541ce.jpg)

**Comment by BechirZalila** [comment]
I tested the debug version and the mail count does not work properly: for the main google account, it is never displayed. For secondary google accounts it is correctly displayed. Here is the screen shot you asked.

Account Type [Inbox]
Did your account icon appear when you first added the account [no for main account (first)/yes for other accounts]
Did you see any notifications or unread counts appear after adding the account [same as above]
![capture d ecran 2017-02-28 a 17 08 46](https://cloud.githubusercontent.com/assets/4518482/23413661/991102d4-fdd9-11e6-8f9d-f716b2128bbe.png)

**Comment by Thomas101** [comment]
Thanks for doing that. I think there's a couple of different issues here.

@amig I think this might be related to a [problem on Googles](https://productforums.google.com/forum/#!msg/gmail/Kfsx8YjqAS4/nELRaCAkAAAJ) end with auth tokens. Unfortunately WMail isn't handling the reauthentication problems all that gracefully right now which is why your counts etc have stopped working. In your WMail install, if you remove the affected accounts and re-add them does this make any difference?

@BechirZalila What kind of count are you expecting to see in WMail? Are any or all of the messages in bundles in Inbox (e.g. in the promotions category, or in bundles you've created yourself?).

Can you try the following for me please?
* In Inbox if you enter the following search do you get any results `label:inbox label:unread -has:userlabels -category:promotions -category:forums -category:social`?
* Can you right click on the account in the left hand side and go to settings can you send me a screenshot of your account settings?

Thanks!

**Comment by BechirZalila** [comment]
@Thomas101 The pattern you asked me to search led me to the possible cause of this problem. In the account setting of debug version, by default, the unread mode set to "All unboundled unread". I changed it to "all unread" and now I see the count I expect.

This setting ("All unboundled unread") was not present in the old 2.1.0.

Thanks for your help :-)

**Comment by Thomas101** [comment]
Good to hear! The new setting is similar to what the Google Inbox iOS and Android apps use

**Comment by amig** [comment]
Ok. I reinstalled the 2.2.1 version, removed my email account and added it again and now all is looking good. Unread count is updating correctly.

**Comment by BechirZalila** [comment]
I also reinstalled version 2.2.0, changed all my accounts settings as shown in the attached screenshot. Now I have the good old behavior I expect.

![capture d ecran 2017-03-01 a 08 51 39](https://cloud.githubusercontent.com/assets/4518482/23450694/d5590556-fe5c-11e6-948d-61b8a153fa5d.png)

**Comment by Thomas101** [comment]
Thanks! Got a new release with some fixes uploading at the moment...

@BechirZalila I've re-added the configuration screen for when you create an Inbox account so you should be able to set this up when first adding your account. This will be in the next release.

@amig good news! The next release will tell you if this happens again and give you the option to re-authenticate the account without needing to delete and re-add.

**Comment by davidtaylorjr** [comment]
@Thomas101 updated to the new release but it doesn't seem to fix this bug.  See the screenshot:

![image](https://cloud.githubusercontent.com/assets/10404733/23483200/fac378f6-fe9f-11e6-872d-df023408f3c1.png)

**Comment by davidtaylorjr** [comment]
There are also no errors in the console.

**Comment by amig** [comment]
Installed 2.3.1 and so far all is ok.

**Comment by Thomas101** [comment]
@davidtaylorjr under your account settings try setting the unread mode to be `All Unread Messages`

**Comment by davidtaylorjr** [comment]
That worked, but I can't imagine that anyone would not want bundled
messages to always be included in that count....

**Comment by Thomas101** [comment]
Great to hear. I stuck with the bundled messages as the default as this is what the iOS and Android apps do. The latest version does present the option in the account setup screens so hopefully that should help everyone get setup the way they want to use it :)
