### ISSUE TITLE
Bug: keyboard focus not in the main app pane by default

### ISSUE THREAD

**Issue by tinymachine** [Thomas101/wmail#62]
I thought keyboard shortcuts weren't working for me in Gmail, but it turns out the keyboard focus just isn't in the main app pane (where the Gmail UI appears) by default. If I click my mouse into the app pane then I can use the keyboard again.

Keyboard focus again is lost when switching away from the app and back again, and when switching between accounts in the dark account pane on the left.

**Comment by LBRapid** [comment]
@Thomas101 Your timing is uncanny. I just installed 1.1.5 an hour ago, had this one complaint about the focus and 1.1.6 had been uploaded and fixed the issue. Thanks!

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.6/WMail_1_1_6_osx_prerelease.zip). Thanks very much for your help!

**Comment by tinymachine** [comment]
My pleasure, Thomas! Thank you for implementing the fix so quickly, and for
your excellent work in general on Wmail. Do you have a virtual tip jar?

**Comment by tinymachine** [comment]
Just a follow-up (with a minor remaining bug): this is now working perfectly in almost every use-case except when you use keyboard shortcuts to toggle between accounts. It would be great if the mailbox could remain in focus even when using keyboard shortcuts to toggle between accounts. Thanks!

**Comment by Thomas101** [comment]
Hi @tinymachine if you want to buy me a beer you can by dropping a tip into my [paypal account](https://paypal.me/ThomasBeverley).

I've had a look at the account switching and it looks like the focus remains on the previous mailbox. I'll put a patch in for this in 1.1.7 :)

**Comment by Thomas101** [comment]
Managed to track that one down!

**Comment by tinymachine** [comment]
Wow -- that was incredibly fast! Thanks, Thomas. Looking forward to checking out 1.1.7!

**Comment by Thomas101** [comment]
Thanks for the tip! :-)

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.7/WMail_1_1_7_osx_prerelease.zip).

**Comment by tinymachine** [comment]
Works great -- thanks, Thomas!
