### ISSUE TITLE
"Categories" is a list and does not have a semicolon as trailing character

### ISSUE THREAD

**Issue by Yeedle** [Thomas101/wmail#621]
I just installed the new stable version  2.2.0 on Elementary OS 0.4 (based on Ubuntu 16.04) using the 64 bit deb for Linux. I installed it from the command line using `sudo apt install ./WMail_2_2_0_linux_x86_64.deb` . 

The last line after finishing installation informed me that
```
/usr/share/applications/wmail.desktop: warning: key "Categories" is a list and does not have a semicolon as trailing character, fixing
```

**Comment by Thomas101** [comment]
Thanks! I've changed it so the next release will have the trailing semicolon
