### ISSUE TITLE
Upgrading from 2.1.1 prerelease to 2.2.0 release loses calendar, drive, etc.

### ISSUE THREAD

**Issue by tomi** [Thomas101/wmail#622]
After I upgraded from 2.1.1 prerelease to 2.2.0 release version both of my accounts lost the calendar and drive from the sidebar. I couldn't find any way to get them back. I resolved this by downgrading back to 2.1.1

* Which version of WMail are you using? [e.g. 1.3.1]
2.1.1 prerelease

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.11.6 (15G1217)

**Comment by Thomas101** [comment]
Hi, if you want to continue using services you need to stick with the prerelease channel and use 2.2.1. They haven't yet made it into the release channel
