### ISSUE TITLE
After installing the latest prelease of wmail it doesn't start.

### ISSUE THREAD

**Issue by houwdb** [Thomas101/wmail#623]
* Which version of WMail are you using? v2.2.1

* Which Operating System are you using? Windows 10

**Comment by Thomas101** [comment]
Hi, if you try uninstalling WMail from the control panel and re-installing it again does this make any difference?

**Comment by houwdb** [comment]
Yes thanks. . Now it works.

Dirk-Bart

Op 28 feb. 2017 6:41 p.m. schreef "Thomas Beverley" <
notifications@github.com>:

**Comment by Thomas101** [comment]
Thanks for giving it a go! Once I get some time I'm hoping to move across to a different installer which should be a bit more resilient :)
