### ISSUE TITLE
Bug in Version 2.2

### ISSUE THREAD

**Issue by ppsphil** [Thomas101/wmail#627]
* Which version of WMail are you using? [e.g. 1.3.1]
   Attempting to use version 2.2
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.11
[WMail Bug.pdf](https://github.com/Thomas101/wmail/files/807513/WMail.Bug.pdf)

**Comment by Thomas101** [comment]
Hi Philip, sorry to hear you've been having trouble. There are some fixes to the zooming in the latest 2.3 version which you can [download from here](https://thomas101.github.io/wmail/download?v=2.3.all). Additionally if you don't want to be notified about new releases you can toggle the `Check for updates` option in settings.
