### ISSUE TITLE
Where are the Calendar and Contact icons gone??

### ISSUE THREAD

**Issue by craige111** [Thomas101/wmail#628]
* Which version of WMail are you using? [e.g. 1.3.1]
2.2.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu16.04

I had enjoyed using these handy icons under the main account icon on the top left.  With v2.2.0 these have disappeared and there is no setting to bring them back. Why are they gone?

Thanks

**Comment by Thomas101** [comment]
Hi, you need to stick with the [prerelease channel 2.2.1](https://thomas101.github.io/wmail/download) to continue using services. There's still a few kinks that need working out on these...

**Comment by craige111** [comment]
Hi Thomas

Maybe I forgot that I installed the pre-release build. 

Regards,
Craig
