### ISSUE TITLE
Cannot select my work Gmail account, stuck on personal Gmail

### ISSUE THREAD

**Issue by ubercool** [Thomas101/wmail#629]
* Which version of WMail are you using? [2.2.1]
* Which Operating System are you using? [Mac OSX 10.12.3]

It shows the icon in the tool bar with 4 unread messages, but when I click on it I can't get it to switch to that account. The Wmail window stays stuck on my personal Gmail account.

I even revoked access to the app from my personal Gmail account but still loads that inbox.
 
Also in "Accounts" it only lists my work email as an account. Clicking on "Pick your account" does nothing.

**Comment by Thomas101** [comment]
Hi, it sounds like something's gone wrong with the data structures on disk. You might need to kill them completely and re-try adding your accounts.

If you quit WMail, are you able to delete `~/Library/Application Support/wmail/` e.g. `/Users/ubercool/Library/Application Support/wmail/`. If you re-add your accounts does that work correctly?

On a side note, do you remember if you did anything in particular before it stopped working? E.g. moved an account, deleted one or something like that? Knowing that might help me resolve the root of the issue

As regards revoking access this will only revoke access to the API calls which are used to grab the unread counts and notifications. The gmail/inbox ui that you see if authenticated in the same way that a browser session is.

**Comment by ubercool** [comment]
Hi Thomas:

Thanks for the email. Removing that folder works. I only recall adding my personal Gmail to the account, after which I could no longer access the previous account. Don’t recall anything else.

Thanks again,
Michael

**Comment by Thomas101** [comment]
Okay, thanks for the info. I'll do some testing and keep an eye open to see if anything else comes up. I'm going to close this off for now but feel free to re-comment if it happens again. Thanks!
