### ISSUE TITLE
default folder for saving attachments

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#63]
i can't seem to find a setting to have a default folder to save attachments. It always asks me to select the destination.

Did i miss something? if not, it would be great to add it!

thakns!

**Comment by parro-it** [comment]
You may want to use [electron-dl](https://github.com/sindresorhus/electron-dl) for this

**Comment by Thomas101** [comment]
I've updated the app by setting the progress on the app icon. There's a bug with electron which means I can't auto-set the download directory at the moment. I'll keep tracking this though and hopefully patch it soon. (https://github.com/atom/electron/issues/4352)

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
