### ISSUE TITLE
ER: Replace the blue background with the account color

### ISSUE THREAD

**Issue by gabriel-r** [Thomas101/wmail#631]
1. Set your account color to some green.
2. Empty your inbox. 
3. Notice the blue background with the sun+clouds 

_Enhancement request: change the account background color. It's one CSS rule, and it looks great._

[See this example, where I also set the header to dark green for an even nicer effect.](https://www.evernote.com/l/AAK_1VbdRLdOAYAO_tQUPMe02P5tSLAGFKkB/image.png)

**Comment by Thomas101** [comment]
Hi, this is something you could use the custom CSS or custom JS for under the account settings. You could add this into the [wmail-userscripts](https://github.com/Thomas101/wmail-user-scripts) repository. Happy to take a Pull Request :)
