### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by Martindelataille** [Thomas101/wmail#633]
Where is the build from source page gone ?

I notice that there is no scripts to build from source too.
Does it sound like a paid version coming ?

**Comment by xhocquet** [comment]
No response to this: https://github.com/Thomas101/wmail/issues/617 either, would prevent compiling yourself anyway.

**Comment by Thomas101** [comment]
Hey, there is some exciting stuff coming soon to WMail. It's going to remain open-source and will be coming with build instructions :).

I've got a local branch that I'm prepping with some awesome stuff that improves notifications, but requires some server support to subscribe/unsubscribe to google so it can tell the client to re-check for new messages (This is done without exposing your emails to a 3rd party. The server only gets told that something has changed).

This changes the build-from-source procedure for generating credentials etc. I was hoping to have the new website up and running by now with the build instructions but I've been a bit bogged down with the last two releases. You'll need the credentials file to get up and running - I've put a [Google form up](https://goo.gl/forms/JAUOQAbWANP1saOD3) for now if you want to get building

**Comment by Martindelataille** [comment]
Thanks to stay us in touch @Thomas101 

Great project and best works (clean and nice code) 👍
