### ISSUE TITLE
Extensions or add-ons

### ISSUE THREAD

**Issue by javifelices** [Thomas101/wmail#634]
Have you considered the possibility of extensions or add-ons for Gmail? I use a lot of mail and it would be interesting compatibility with the Chrome Store in the extensions of Gmail, and added that is going to make the problem. 

Greetings and thank you.

**Comment by ontherunvaro** [comment]
https://github.com/Thomas101/wmail/wiki/FAQs#chrome-extensions

**Comment by javifelices** [comment]
Thanks and sorry. I read everything not to repeat, but it happened to me, again thank you

**Comment by Thomas101** [comment]
I am planning on re-looking at this (#451) if you want to keep an eye on that issue :)
