### ISSUE TITLE
How to update in Linux

### ISSUE THREAD

**Issue by Manzanit0** [Thomas101/wmail#639]
* Which version of WMail are you using? 2.2.0
* Which Operating System are you using? Ubuntu MATE 16.04 LTS

Hi!

I was wondering how to update WMail to 2.2.0 in Ubuntu rather than uninstall/install again. This might be more of a SysAdm question tho :grin:

Thanks in advance for any support :smiley:

**Comment by almostmavron** [comment]
Hi.
I'm using  Kubuntu 16.04 LTS and I've been updating WMail by downloading the .deb from the site and just double clicking it (or you could dpkg -i debpackage && apt-get -f install).
WMail itself advertise new versions and offers the link to the download page.

**Comment by Thomas101** [comment]
@almostmavron is right, if you're using the deb packages you should just be able to double click and  follow the steps in the software center to upgrade. Ideally I should be distributing WMail through the support distribution channels (#208, #224, #485), but this isn't something I've managed to get around to yet. Hope this helps!
