### ISSUE TITLE
MacOS: Indicator on Menu bar

### ISSUE THREAD

**Issue by hernangonzalez** [Thomas101/wmail#64]
Hi,

It would be nice to be able to see an indicator of WMail with the unread count on my menu bar. I normally keep my dock hidden, so kinda need something to figure out my unread count when I return to my laptop.

Thank you!
H.

**Comment by parro-it** [comment]
It's actually enabled only for linux platform, as a replacement for the docker notification.
I could enable it on every platform if @Thomas101 agree.

**Comment by hernangonzalez** [comment]
I could test it if you like.

**Comment by ivancevich** [comment]
@hernangonzalez @parro-it @Thomas101 It would be nice if we could toggle it on and off from the setting menu. Such as the "Show titlebar" option.

**Comment by Thomas101** [comment]
I agree would be handy! I'm just about to add a couple of bits into settings, so I'll add an option in. @parro-it if memory serves me correctly you need to supply the correct sized image for osx -- any idea what this is?

**Comment by mykecheckonetwo** [comment]
As long as this is an option this would be amazing.

**Comment by Thomas101** [comment]
I've added the option into the settings screen but not implemented the functionality yet :) See commit a953206edd90f470cb8e8dc606d38c5fb6e4e25a

**Comment by parro-it** [comment]
@Thomas101 regarding the icon size I really don't know for sure, but I think Electron take care of resize it. 
I will give it a shot, but at the moment I could not check it on OSX.

**Comment by parro-it** [comment]
Just published a PR.

**Comment by parro-it** [comment]
@hernangonzalez, could you give it a try?

**Comment by Thomas101** [comment]
thanks @parro-it. I'll see how it works!

**Comment by hernangonzalez** [comment]
@parro-it Yep.

**Comment by parro-it** [comment]
It could be useful to add some action in the context menu. For now it contains a clone of the tooltip text...

**Comment by parro-it** [comment]
E.g. exit app or show/hide window

**Comment by Thomas101** [comment]
The icon needed to be 22px :(. Updated that, and also changed it so it shows a red icon when there is unread mail and a black icon when there is no unread mail. The menu should probably have a compose button or something too. I'll look at adding that later on though.

**Comment by Thomas101** [comment]
@hernangonzalez I'll do a build and release 1.1.6 later on this week. Want to get a couple more bug fixes and features in :)

**Comment by parro-it** [comment]
I saw you used the icons only on OSX. Since they work also on Linux, I've removed the platform check. The change color trick is nice!

**Comment by hernangonzalez** [comment]
@Thomas101 great.. ping me and i'll give it a try.

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.6/WMail_1_1_6_osx_prerelease.zip). Thanks very much for your help!

**Comment by hernangonzalez** [comment]
Awesome guys, thanks!
