### ISSUE TITLE
installing WMail on Elementary Loki OS using WMail_2_3_0_linux_x86_64.tar.gz

### ISSUE THREAD

**Issue by fmaster007** [Thomas101/wmail#643]
* Which version of WMail are you using? [e.g. 1.3.1] Downloaded WMail version 2.3.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Using OS elementary OS 0.4 Loki (64-bit) Built on Ubuntu 16.04.2 LTS

I am a newbie in Linux so any step by step would help. Thanks!!

**Comment by JostCrow** [comment]
you should download the deb file. That is installable with the software center.

**Comment by Thomas101** [comment]
As @JostCrow said, use the deb file, it should just be a double click install :)
