### ISSUE TITLE
Persistent 10-12% CPU even when not in focus [1.3.1 pre release] on Mac OS X 10.12.3

### ISSUE THREAD

**Issue by arooni** [Thomas101/wmail#645]
* Which version of WMail are you using? 1.3.1

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]: 10.12.3

CPU hovers around  10-13% cpu even when it's not in focus.  

I'd like to ditch Boxy so I can use the same app on my Ubuntu laptop.  

Wondering if there's a setting change I'm missing, I already have 'sleep when not in use' across both my google inbox and gmail account (should I not have both of these set up at the same time)?  

Thanks!

**Comment by Thomas101** [comment]
Hmmm, that's not good. How many mailboxes have you added to WMail?

**Comment by arooni** [comment]
I have two.  One google inbox and one gmail. 

BTW: your app is fantastic; want to emphasize that.

**Comment by Thomas101** [comment]
Thanks :). I see that you're still using the 1.3.1 pre-release. Have you tried upgrading? The 2.3.1. release landed recently. This has chromium 56 with a bunch of memory improvements

**Comment by arooni** [comment]
Thanks!  Memory usage looks a lot better.  Main process is hovering around
2% cpu and helper at .1% (when not in use).  Also I learned about the \
feature in htop; so bonus!

I was going to ask you how to upgrade to latest prerelease; but looks like
auto update (at least on prerelease version), is baked in.

Also I could probably enjoy some more cpu savings if I didn't use *both*
gmail and inbox in the same account.


may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - brofist.com
twitter - @brofist <https://twitter.com/brofist>

**Comment by Thomas101** [comment]
Awesome glad that's looking a lot better for you :)
