### ISSUE TITLE
Bug: Clicking notifications takes me to mailbox but shows error, then white screen

### ISSUE THREAD

**Issue by brandonb927** [Thomas101/wmail#65]
Whenever I receive an email on my GMail inbox I get an OS X notification, click on it, then get an error in the app and the page goes blank forcing me to CMD+R in the window to reload it. Below is a GIF demonstrating the behaviour. (also, don't mind the screenflick watermark :stuck_out_tongue:)

![wmail_issue](https://cloud.githubusercontent.com/assets/1509352/12757397/ba5b9a44-c98c-11e5-98ed-cba4381f07a8.gif)

**Comment by Thomas101** [comment]
Hi, there's an open issue for this already #37. Hoping to get it fixed soon :). I'll close this for now, but you can continue to follow progress on #37

**Comment by brandonb927** [comment]
Gah, totally sorry for not checking first! :cry:
