### ISSUE TITLE
Feature Request: Add 'Trimless' support into WMail

### ISSUE THREAD

**Issue by geoking** [Thomas101/wmail#650]
* Which version of WMail are you using? [e.g. 1.3.1]
2.3.1

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Hi, 
I've been using your app for a while now and it's fantastic. I would however love it if you could add support for a Google Chrome extension known as 'trimless,' which automatically removes the 'message trimmed' link and expands the message within the app. The source code for this app can be found here: http://bit.ly/YDmt1z

Thanks for the app and taking the time to read!

**Comment by Thomas101** [comment]
Hi, I've added trimless into the extension support issue (#451). Thanks!
