### ISSUE TITLE
Preload Google Drive (or make wdrive)

### ISSUE THREAD

**Issue by aurimus** [Thomas101/wmail#652]
I would find it convenient if wmail preloaded google drive so it's available instantly (since it's there). Or otherwise would be even better to have Wdrive as a separate app also ;)

**Comment by Thomas101** [comment]
Hi, you can turn this on in the settings. Right click on your account on the left hand side and go to Account settings. For Google Drive, Keep etc there's a checkbox next to it with `Sleep when not in use`. Make sure this is unchecked.
<img width="979" alt="screen shot 2017-03-14 at 17 58 40" src="https://cloud.githubusercontent.com/assets/103586/23915128/0adee816-08e0-11e7-8bce-a359065f7f3b.png">

**Comment by aurimus** [comment]
Thanks @Thomas101 , that did it. The checkbox should be the opposite, it feels unintuitive (checkbox checked should preload the service).

Another Question: Is there a way to switch between services with shortcut or through menu? I don't like the sidebar being open, it takes space.

**Comment by Thomas101** [comment]
Not at the moment, but I have some bits in the works to add this ;-)
