### ISSUE TITLE
Handle mailto links. Become default mail client

### ISSUE THREAD

**Issue by brandonb927** [Thomas101/wmail#66]
If I set the default Mail app in OS X to WMail, it looks like Mail.app resets it back to Mail.app when you click on a `mailto:` link somewhere on a webpage. I don't know if this is a bug in OS X or in how WMail handles `mailto:`links, if at all.

**Comment by Thomas101** [comment]
Not sure we're doing anything with mailto at the moment. This should really be added in though!

**Comment by drreen** [comment]
+1 for that!
desparately looking for an inbox client which handles mailto smoothly :)

**Comment by dnap941** [comment]
Hello, 

Is there no Windows 10 Mailto support for WMail? 

At the moment, I am unable to select WMail for mail client.  No options are given to me for choosing Wmail. 

Thanks in advance.

**Comment by knireis** [comment]
Same issue here on linux, mailto links open in thunderbird and i am unable to change it to wmail in the settings. Using Mint 18 Cinnamon edition.

**Comment by byaka** [comment]
@Thomas101, can you please explain, what help needed with this task and what problem with it?

**Comment by Thomas101** [comment]
Yeah sure there's two main areas I need help with...

1.) **Compose dialog in Gmail & Inbox**. Gmail has some [pretty well documented url queries](https://stackoverflow.com/questions/6548570/url-to-compose-a-message-in-gmail-with-full-gmail-interface-and-specified-to-b) you can use to bring up the compose dialog along with to:, subject: etc all prefilled in, however Inbox doesn't support anything like this. So we need to sniff the content of the page and manipulate the dom to effectively bring up a new message and pre-fill fields in the most resilient way possible.

2.) **Handling mailto links**. Doing this cross platform is a real pain.
 * Windows it requires editing the registry I think
 * OSX probably something like [this](https://superuser.com/questions/548119/how-do-i-configure-custom-url-handlers-on-os-x) to update the services.
 * Linux, I'm not sure about to be honest

The good news is though that I'm segueing towards this with some of the work I've already been doing. For example, there would have been a number 3 in terms of getting cross platform native libraries to compile (as undoubtedly we will need to use some), but I think I've cracked that in last few commits to get the spellchecker working. See [nodehun](https://github.com/Thomas101/nodehun) for travis and appveyor autobuilding then [wmail-spellchecker](https://github.com/Thomas101/wmail-spellchecker) for the prebuilt versions

**Comment by Thomas101** [comment]
This looks promising for osx & windows https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-path-args-macos-windows

**Comment by aurimus** [comment]
+1, any progress?

**Comment by cdes** [comment]
+1

**Comment by Cantello** [comment]
Any ideas on how to do this on Windows 7?

**Comment by byaka** [comment]
@Cantello, look at [this](https://stackoverflow.com/questions/7105258/how-to-register-custom-program-to-handle-mailto-protocol-on-windows-7)

**Comment by simonbcn** [comment]
Same problem on Arch Linux 64 bits. 😞

**Comment by Thomas101** [comment]
Long overdue but I've added this in :-). Will be out in 2.0.8 over the next week. Thanks everyone!

**Comment by brandonb927** [comment]
Thank you for the incredible work @Thomas101  💃

**Comment by simonbcn** [comment]
I'm testing the git version on Arch Linux with Gnome Shell but it doesn't work. Where is the `.desktop` file? The solution only works for Linux distros based on `.deb` packages.

**Comment by Thomas101** [comment]
@simonbcn The desktop file is created when running the package script `packager/Distribution.js:distributeLinuxDeb()`. If you've installed using the deb package it should have been placed in `/usr/share/applications/wmail.desktop`. I've added...

```
Exec=/opt/wmail-desktop/WMail --mailto=%u
MimeType=x-scheme-handler/mailto;
```

as per what [google suggested](https://unix.stackexchange.com/questions/204419/mailto-not-working-with-custom-desktop-file) but I'm not all that familiar with how linux ties in protocol handlers etc, so if you've got any advice I'd happily take it!

**Comment by simonbcn** [comment]
Arch Linux, and derivatives, don't use `.deb` packages.
In any case, I have modified the desktop file and I just added the line: `MimeType=x-scheme-handler/mailto;`. The `--mailto=` in `Exec` wasn't necessary. Now this works.

**Comment by Thomas101** [comment]
Hi, this has been added in the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8). Thanks everyone for reporting!

**Comment by Dazzel** [comment]
Hm. I am not able to set WMail as the default mailto-handler in windows. The UI marks this as done but windows does not recognize this. Already tried to reinstall. 

Version 2.0.9

**Comment by Thomas101** [comment]
@Dazzel If you click on a mailto link does it try to open it, or does it open with another email client?

**Comment by Dazzel** [comment]
It does open with another mail client. As I said I am not able to select
WMail in the list for mail handling.

Thomas Beverley <notifications@github.com> schrieb am Di., 10. Jan. 2017,
19:00:

**Comment by Thomas101** [comment]
Ah okay. I might need to do some more work to get it to work from the windows control panel etc.

If you do it from the WMail UI by going to settings and then toggle `Handle mailto links` and then try to open a mailto link does that work?

**Comment by Dazzel** [comment]
Nope. Hadn't had any luck with this. The switch is on but it is not
registered properly in the system.

Thomas Beverley <notifications@github.com> schrieb am Di., 10. Jan. 2017,
19:56:

**Comment by Thomas101** [comment]
I've just opened a new issue #520 for this, we'll track it from there.
