### ISSUE TITLE
Support spotlight finding WMail - easy fix

### ISSUE THREAD

**Issue by JorySchossau** [Thomas101/wmail#660]
* Which version of WMail are you using? [e.g. 1.3.1]
2.3.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.11.3

I'm not familiar with your build system at a glance, so can't submit a pull request, but here's an easy fix to support spotlight if you can modify how the Info.plist file is constructed.

Add to Info.plist:
`<key>CFBundleSignature</key>`
`<string>????</string>`

The "????" Is the default coming from a standard OSX project, and it's fine to leave it as is, or you can go register your own signature with Apple, but it's not necessary. The Key/Value pair simply needs to exist for spotlight to work (at least on my system).

**Comment by Thomas101** [comment]
Hi, I would have thought it should just work from `CFBundleDisplayName`, but I can add this in. Do you have any specific spotlight configuration that you know of that might filter results?

**Comment by JorySchossau** [comment]
I would have thought so as well, especially since this is not documented
very well, pretty much anywhere. However, I don't have any modifying apps
installed or running and my only filter is that I explicitly only let
spotlight operate on Applications and Calculator. This is the first app
I've downloaded that I've needed to modify like this. I first learned of
this when I made my first app and wanted it to show up in spotlight. Does
it "just work" in your test environment?.. I'm curious.

**Comment by Thomas101** [comment]
That is weird! I've got it running on my own mac and my work mac without any problem `cmd+space` then `wmail` works. In fact just typing `w` brings it up.

Someone [here](https://discuss.atom.io/t/spotlighting-indexing-of-an-atom-shell-app/14935/2) reported a similar issue and your patch fixed it for them. I'll add it for the next build, I don't think it will do any harm

**Comment by Thomas101** [comment]
I've added this into the packager so will be out in the next release. Thanks!

**Comment by TimNZ** [comment]
You no longer have a package.js or any package scripts in package.json - how are you packaging now?
