### ISSUE TITLE
Calendar not displaying properly in "Day" view; no way to reset back to "Weekly"

### ISSUE THREAD

**Issue by fcrvenkovic** [Thomas101/wmail#661]
* Which version of WMail are you using? [e.g. 1.3.1]

2.3.1

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

mac OS Sierra 10.12.4 Beta (16E189a)
<img width="1280" alt="screen shot 2017-03-14 at 12 29 12 pm" src="https://cloud.githubusercontent.com/assets/3732983/23918894/fa9dba46-08b1-11e7-9bb9-64d28d9f4821.png">

**Comment by Thomas101** [comment]
That looks like a stylesheet failing to load. If you restart WMail and try again does it still come out like that?

**Comment by fcrvenkovic** [comment]
@Thomas101 thanks for the response! Restarting didn't do anything, I had to remove the account and re-add it again for it to display properly.

**Comment by Thomas101** [comment]
That's really odd. I wonder if there was an issue at Google's end and it cached the response or something. I'll close this off for now, but if it comes again re-comment and I'll dig a bit deeper. Thanks!
