### ISSUE TITLE
Additional Google services disappeared

### ISSUE THREAD

**Issue by NikolaZornic** [Thomas101/wmail#662]
Hi,

I updated WMail today (from 2.1) and my additional Google services disappeared (Drive and Calendar). I tried with reinstalling (uninstalled with Revo Uninstaller and installed again), but wasn't able to add those additional services again. Only Inbox/Gmail is available.

Am I doing something wrong?

Regards,

Nikola

* Which version of WMail are you using? [2.3]

* Which Operating System are you using? [Windows 10 x64]

**Comment by Thomas101** [comment]
Hi, services are still in beta and are currently only in the prerelease channel, if you download 2.3.1 prerelease they should be all back :)
