### ISSUE TITLE
No tray icon on Linux KDE

### ISSUE THREAD

**Issue by thesbros** [Thomas101/wmail#665]
* Which version of WMail are you using? 2.3.1

* Which Operating System are you using? Arch Linux with KDE Plasma

On Linux with the KDE desktop environment, the tray icon does not show - instead popping up as it's own transparent window: ![screenshot](https://i.imgur.com/Z8oQ2mg.png)

On the contrary, other Electron apps such as Discord and GPMDP tray icons work fine.

**Comment by Thomas101** [comment]
I haven't seen it do that before! Do you know if you have libappindicator1 installed?

**Comment by thesbros** [comment]
So sorry for the delayed response! I installed `libappindicator-gtk2` and it works now. I'll tell the AUR package maintainer about this.
