### ISSUE TITLE
Electron.io Apps List

### ISSUE THREAD

**Issue by MggMuggins** [Thomas101/wmail#679]
Not really an issue, sorry about that, but a support question. If found Wmail because I liked the way Shift looked (proprietary fork of this project, grr), and tried that out, and came across wmail somewhere in that app. Needless to say, I uninstalled shift and moved to wmail right away. In any case, I might have found wmail instead of shift in the first place if wmail had been on the list of electron apps ([here](electron.atom.io/apps/)). Basically wondering if Thomas would mind getting Wmail put on that list (info on how to do that [here](https://github.com/electron/electron.atom.io/blob/gh-pages/CONTRIBUTING.md#adding-an-app-or-project-to-the-site)).
Thanks, ~Samwise

**Comment by kristofferjalen** [comment]
WMail is on the list now.

**Comment by MggMuggins** [comment]
Cool, thanks.
