### ISSUE TITLE
RANT: Wmail - is it dead?

### ISSUE THREAD

**Issue by ronenrozner** [Thomas101/wmail#689]
With the announcement of Wavebox, does that mean that further development of Wmail is dead ? For me, Wavebox is an attempt to shove bloatware down my throat and make me pay for it: "But what happens when you start adding things that aren't mail?" - Don't know, Don't care ! ; "Outlook & Office 365" support ? F*@K Microsoft! Long Live FOSS ! ; "We love Slack and we use it every day" - Slack Who ? ; "Trello" ? Thanks had breakfast already; "Docs & Office editing"- Really ? Another one ?

So yes, I may be in a minority here, but I like my applications simple and light. I don't have an issue paying for it (although FOSS still rocks) as long as i'm getting what I want, NOT features I don't need.

**Comment by SMed79** [comment]
> I like my applications simple and light.

I'm here because of the concept of [DOTADIW](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well) but unfortunately no longer.

**Comment by chaoscreater** [comment]
I knew I should have kept a copy of the latest WMail installer. Does anyone else still have it and can they share it please? I don't use any of the features in Wavebox and was fine with using Wmail, now I have to pay for using the same thing???? No thanks.

**Comment by JBPlinn** [comment]
Well, people you want the same functionalities as Wavebox for free?

get Rambox [http://rambox.pro/]

It struck me that Wavebox is a direct copy of Rambox.

**Comment by geekgonecrazy** [comment]
Seems even the wiki documentation on how to build wmail was removed also.  Anyone have a link to it?

**Comment by chaoscreater** [comment]
The only problem I have with this is that it's just a crappy monetizing attempt by the developer. Wmail allows you pretty much unlimited Gmail accounts (I had 5 setup). With Wavebox, you're limited to 2. Why turn something that was absolutely fine into utter crap? I hate it when developers do this nowadays. And really? Yearly annual subscription fee? What a rip off, it's not even resource optimized properly.

All download links and documentations to Wmail were removed, so it's clearly an attempt to try to push people into paying unnecessarily.

Luckily, you can still find the latest Wmail stable on Softpedia. Get it while you still can.

**Comment by geekgonecrazy** [comment]
@chaoscreater I forked and rolled back before all the non-sense to 2.1.1 also added the instructions back to the readme.  https://github.com/geekgonecrazy/wmail/#building-from-source

I also created a snap for it installable via: `sudo snap install wmail-snap`

**Comment by SMed79** [comment]
The most recent fork **2.3.1** before the monetization :moneybag: was made by @WillPresley 22 days ago.
* https://github.com/WillPresley/wmail-fork

**Comment by geekgonecrazy** [comment]
@SMed79 been making my way slowly through.  Looked like they were working on preparing for it for a while.  Will take a look at the fork.  Thanks for sharing :+1:

**Comment by WillPresley** [comment]
@geekgonecrazy You are absolutely correct. The same packager can be forward-ported to 2.3.1 as well. I personally really enjoyed the (Google only) additional services that were introduced in 2.2.x-2.3.x, so I prefered to fork from that location. I have been extremely busy with a new business, but I plan on doing similar to you, and re-including the build directions, as well as the proper packager, I just haven't had time yet.

Maybe one day soon some of us can get together and talk bug-fixes/performance increases for this "community fork", I'm sure there's some easy things we can do.

**Comment by samaphp** [comment]
I liked the way of WMail since the beginning but the main issue that it's eating a lot of memory.

And since this issue talking about WMail alternatives, please allow me to wonder if anyone interested in paying for mail client, I will suggest Newton App for Mac it's the best app ever .. well optimized and will make you in love with your inbox.
https://newtonhq.com/

I'm daily Newton user and it has all my Gmail and Mail Exchange emails. Go and read about the supercharger features it deserves every penny.

**Comment by WillPresley** [comment]
@samaphp Trying to get openWMail to use less memory will be one of my first real goals as a contributor to that Org. I agree with you that things bloat quickly. Seems like Wavebox iterated upon the 'Sleepable services' aspect of wmail, something I am going to take a closer look at soon. Getting things in the background to behave properly is obviously an issue right now.

https://github.com/openWMail/openWMail

**Comment by SMed79** [comment]
The King is dead; long live the King.
