### ISSUE TITLE
Menu Item "Hide Others" not available

### ISSUE THREAD

**Issue by AndrewSwift** [Thomas101/wmail#72]
EVERY Mac app has a File menu item "hide others" that can be used to get rid of the clutter on the screen. Wmail is awesome and I really appreciate its existence.

It would be nice if this were available for Wmail.

**Comment by mykecheckonetwo** [comment]
I've never looked at that before what would the hide others functionality do?


Sent from an iPhone,

Mykel Jewell
Mykel.Jewell@Gmail.com

**Comment by AndrewSwift** [comment]
It hides any applications that are visible EXCEPT the frontmost.

For example if you have Photoshop, Text Edit, Notes and Safari open all at once and you alt-tab between them, you see all of their windows.

To reduce clutter (in Notes) for example, I choose "Hide Others". It hides all but the Notes app, including Photoshop, Text Edit and Safari.

I don't know if this is clear, but I use it constantly (via cmd-alt-H) to reduce my screen clutter.

I guess the most important time I use it is alt-tab to finder, then use it to get rid of all the open applications.

Perhaps I am the only one!

**Comment by mykecheckonetwo** [comment]
No I'm sure you're not and it makes sense now. Thanks.

On Thu, Feb 4, 2016 at 8:37 AM AndrewSwift <notifications@github.com> wrote:

> It hides any applications that are visible EXCEPT the frontmost.
>
> For example if you have Photoshop, Text Edit, Notes and Safari open all at
> once and you alt-tab between them, you see all of their windows.
>
> To reduce clutter (in Notes) for example, I choose "Hide Others". It hides
> all but the Notes app, including Photoshop, Text Edit and Safari.
>
> I don't know if this is clear, but I use it constantly (via cmd-alt-H) to
> reduce my screen clutter.
>
> I guess the most important time I use it is alt-tab to finder, then use it
> to get rid of all the open applications.
>
> Perhaps I am the only one!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Thomas101/wmail/issues/72#issuecomment-179934864>.
>
-- 
Regards,

Mykel Jewell
Mykel.Jewell@Gmail.com

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.7/WMail_1_1_7_osx_prerelease.zip).

**Comment by AndrewSwift** [comment]
I am amazed at your rapidity. Thanks so much!
