### ISSUE TITLE
OSX: Menu icon looks odd

### ISSUE THREAD

**Issue by hernangonzalez** [Thomas101/wmail#73]
Hey Guys,

Maybe the size of it is wrong, i can clearly see the pixels here.
<img width="287" alt="screen shot 2016-02-04 at 10 04 00 am" src="https://cloud.githubusercontent.com/assets/1162963/12815758/0bd05fb8-cb27-11e5-800a-3819a68f64eb.png">

Thanks,
H.

**Comment by hernangonzalez** [comment]
Any chance we could also have:
1) Bring App to front on tap.
2) Show unread count in place, instead as a menu option

**Comment by Thomas101** [comment]
I've added some higher dpi images, which will go out in the next release. We really should utilise the menu more though as you suggested!

**Comment by Thomas101** [comment]
I've copied the enhancements across to issue #75 where I'll keep track of the updates. I'll close this issue now though as I've fixed the images :)

**Comment by Thomas101** [comment]
Hey, this has made it into a pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.7/WMail_1_1_7_osx_prerelease.zip).

**Comment by MacMhicheil** [comment]
When I turn the menubar icon off it goes invisible, but is still there and clickable.

![screen shot 2016-02-05 at 07 48 17](https://cloud.githubusercontent.com/assets/16734687/12840687/3f3d4b52-cbdd-11e5-9661-38515202cff0.png)
![screen shot 2016-02-05 at 07 48 59](https://cloud.githubusercontent.com/assets/16734687/12840688/3f4284be-cbdd-11e5-9c2b-4db352d46711.png)

**Comment by hernangonzalez** [comment]
Great guys, will try, thx!

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.8/WMail_1_1_8_osx_prerelease.zip). Thanks very much for your help!
