### ISSUE TITLE
UI/UX improvement - selected account better visible

### ISSUE THREAD

**Issue by fane89** [Thomas101/wmail#74]
Hello,

first, great idea and project - loving it!

I've got only one thing bugging me, i don't know fast enough which account i'm watching.
This happens only when two accounts are added to the app.

I know after some time that the blue circle means its selected but at first look its weird.
<img width="276" alt="zrzut ekranu 2016-02-04 o 19 59 57" src="https://cloud.githubusercontent.com/assets/9295830/12826154/f16512a6-cb79-11e5-8923-d221b56194f3.png">

One is blue, one is white - it's not intuitive IMO.

Workaround for this is to user CMD + number of account.

It's trivial and it happens only with two accounts attached.

**Comment by fane89** [comment]
My suggestion:

<img width="276" alt="suggestion" src="https://cloud.githubusercontent.com/assets/9295830/12826429/45593af8-cb7b-11e5-896b-d862643bbf69.png">

The dot should be on the outer side always - when You introduce the possibility to change location of the side panel (accounts panel) maybe...

**Comment by Thomas101** [comment]
that's a good idea. I'll take a look!

**Comment by fane89** [comment]
Cool, thanks. Now just have to wait for the release :)

**Comment by Thomas101** [comment]
You don't have to wait long! [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.7/WMail_1_1_7_osx_prerelease.zip).

**Comment by fane89** [comment]
i just built it from source.

There is a little bug.

<img width="146" alt="zrzut ekranu 2016-02-04 o 23 20 57" src="https://cloud.githubusercontent.com/assets/9295830/12831706/fcf833de-cb95-11e5-980f-4a8ca273f13b.png">

**Comment by Thomas101** [comment]
Fixed this in 14e9923f513aedf8cb00c3a8a79c42502e6c44f6

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.8/WMail_1_1_8_osx_prerelease.zip). Thanks very much for your help!

**Comment by fane89** [comment]
great!
Already using it! Keep up the good work :)
