### ISSUE TITLE
Tray Icon Enhancements

### ISSUE THREAD

**Issue by Thomas101** [Thomas101/wmail#75]
Accumulation of items plus #73 

1) Bring App to front on tap.
2) Show unread count in place, instead as a menu option
3) Show account switcher
4) Show unread e-mail by account

**Comment by alexweber** [comment]
For OSX it would be cool it enable "dark mode" support, the current colored icon sticks out like a sore thumb :)

**Comment by Thomas101** [comment]
dark mode support added and number 2 completed

**Comment by Thomas101** [comment]
Hey, this is fixed. You can check it out by [downloading the latest release](https://thomas101.github.io/wmail/download). Thanks! 😊 😊 😊
