### ISSUE TITLE
Show inbox count instead of unread count

### ISSUE THREAD

**Issue by paulyoung** [Thomas101/wmail#77]
I'd much rather know how many items are still in my inbox as opposed to how many I've read.

I think this is much more in line with how Inbox is intended to be used.

I've tried a few different solutions for native Inbox, and this looks really great so far. Keep up the great work!

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.8/WMail_1_1_8_osx_prerelease.zip). Thanks very much for your help! You can select the unread count search in settings

**Comment by paulyoung** [comment]
Thanks! I just upgraded to 1.2.0 and it's working great.
