### ISSUE TITLE
Keyboard based navigation please

### ISSUE THREAD

**Issue by ashwinmt** [Thomas101/wmail#79]
can we have keyboard navigation when shuttling between multiple inboxes? Currently, the only way to enable keyboard navigation inside an inbox is by manually clicking inside and then pressing a key... While Cmd + 1-n works to shift between inboxes, a ctrl + tab / something equivalent would be great to move focus inside the tab...

**Comment by Thomas101** [comment]
Hi @ashwinmt if you're using the version 1.1.2+ you should be able to cycle between account by doing cmd+1, cmd+2 etc. I've added backspace support in gmail, but this hasn't made it out into a release yet
