### ISSUE TITLE
when reading a mail, delete key doesn't go back to previous page/inbox

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#8]
would be great if the delete key could have the same behavior as in browser and go back to the previous page when reading a mail 

basically a shortcut for the "Back to Inbox" button

**Comment by Thomas101** [comment]
I agree this would be helpful. I've not managed to figure out how to do this yet, but I'll keep on it!

**Comment by Thomas101** [comment]
Hey, this has made it into the latest pre-release version which you can [download here](https://github.com/Thomas101/wmail/releases/download/v1.1.8/WMail_1_1_8_osx_prerelease.zip). Thanks very much for your help!
