### ISSUE TITLE
Add autoupdate support (Maybe using Sparkle?)

### ISSUE THREAD

**Issue by ztomer** [Thomas101/wmail#80]
I think that adding autoupdate support will be beneficial to the user experience.

Sparkle is an Autoupdate framework which is used in multiple projects (for example - Hammerspoon).
https://sparkle-project.org/

Will you consider adding autoupdate support?

**Comment by Thomas101** [comment]
I really need to add this in, especially after this week of update madness. It's now the oldest open issue on #10 so I'll bump it into a release soon. Going to close this as it's a duplicate
