### ISSUE TITLE
Request: open links in background

### ISSUE THREAD

**Issue by vitorgalvao** [Thomas101/wmail#81]
As the title says. Usually apps that can open links in the user’s browser have an option to make the browser not steal focus.

**Comment by Thomas101** [comment]
Good idea!

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!

**Comment by vitorgalvao** [comment]
Thank you. Will be trying it now.

**Comment by vitorgalvao** [comment]
While I do appreciate the addition, testing it I just found that it doesn’t work like what I had in mind (should’ve been more specific). What I meant was an option to *always* open links in the background.

Usually a user has a preference for one or the other. Having to right-click to open a window in the background is more work than not using the option:

* If we do not use the option, we click, ⌘⇥, and we’re back where we were.
* If we use the option, we click, move the mouse down, click again.

Again, I do very much appreciate the addition, but for this to be actually useful and in line with other applications do, it needs to have a global option we can set to always do one or the other by default when left-clicking once.

**Comment by vitorgalvao** [comment]
While I do appreciate the addition, testing it I just found that it doesn’t work like what I had in mind (should’ve been more specific). What I meant was an option to *always* open links in the background.

Usually a user has a preference for one or the other. Having to right-click to open a window in the background is more work than not using the option:

* If we do not use the option, we click, ⌘⇥, and we’re back where we were.
* If we use the option, we click, move the mouse down, click again.

Again, I do very much appreciate the addition, but for this to be actually useful and in line with what other applications do, it needs to have a global option we can set to always do one or the other by default when left-clicking once.

To make the use-case/problem clearer, right-click doesn’t even work to show the option when clicking the `View Pull Request` (or `View Issue`) links that appear without having to open the email.
![image](https://cloud.githubusercontent.com/assets/1699443/13198374/2b342c88-d7ff-11e5-9ef4-0909e6e5d5c1.png)

In this case, I’d usually click, click, click, click, click, select and delete all, and then switch to the browser

**Comment by Thomas101** [comment]
Ahhh okay. That should be easy to add in. I'll reopen it and attach to 1.2.2

**Comment by vitorgalvao** [comment]
Thank you (for this and for all the work on the app).

**Comment by tinymachine** [comment]
An additional thought on opening links in the background: several email apps I've used allow Cmd+click (on a link) to open the link in the background, instead of first opening the contextual menu and then selecting the option. This would be a nice addition!

**Comment by vitorgalvao** [comment]
I see this has just landed in the latest (pre-)release. Thank you.
