### ISSUE TITLE
Request: Allow custom avatar image

### ISSUE THREAD

**Issue by vitorgalvao** [Thomas101/wmail#82]
Currently, `wmail` grabs whatever image is in the _My Picture_ area of the _General_ Settings section. It also requires that we set visibility to “Visible to everyone”, as “Visible only to people I can chat with” doesn’t work. Even then, it seems Gmail outright butchers the image quality (quite noticeably on a retina screen).

With that in mind, would it be feasible to let us set our own images?

**Comment by Thomas101** [comment]
This is a good idea. Might be worth looking at custom colours for the item on the left. I can use this to segue into supporting other platforms other than gmail and inbox

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
