### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ivancevich** [Thomas101/wmail#83]
Hey @Thomas101 and collaborators,

Thanks a lot for the great effort making WMail happen, it's awesome!

I'd like to recommend creating a change log, so we can keep track of what each version adds and fixes.

Best,

JC

**Comment by Thomas101** [comment]
I have been adding changes into the release page for each version (https://github.com/Thomas101/wmail/releases).

Do you think it would be better to build a changelog as well as this, or maybe direct people to the release page to download so they can see the changes. I did think about doing the latter, but didn't want to put non-techy users off downloading by presenting them with the option to download osx, linux, source code etc.
