### ISSUE TITLE
Request OSX: option to show/hide only certain account unread emails in dock badge 

### ISSUE THREAD

**Issue by lament** [Thomas101/wmail#84]
First of all, amazing job on this Thomas. I've already turned several people on to this at work.

Secondly, I have 2 accounts: personal and work. I'd love to only show my work account unread emails in the OSX dock. I'm frequently between apps and being able to glance at the dock to see that I have only work emails would be awesome.

Is that possible?

Thanks again!

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!

**Comment by lament** [comment]
Thanks Thomas! I will check it out.

**Comment by lament** [comment]
Hi @Thomas101, I don't see an option in the settings to show/hide unread counts for specifica accounts in the OSX dock. Where is that option?
