### ISSUE TITLE
[bug] clicking on "mark as unread" triggers a notification of new mail received

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#87]

**Comment by bertrandmartin01** [comment]
in version 1.2.0
don't remember this behavior in previous versions

**Comment by Thomas101** [comment]
Hey, sorry about this it's a bit of a pain. I've taken a look and I need to rewrite the way I'm handling notifications. I'm not going to have timr to be able to get this together until next week but I'll put a release out when I can. For now you can disable notifications under settings > accounts

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
