### ISSUE TITLE
Request: be able to show which messages are on app badge (unread, unread primary, in inbox)

### ISSUE THREAD

**Issue by Shawnjoseph2001** [Thomas101/wmail#90]

**Comment by itamaro** [comment]
+1

I'd like, per account-avatar, to have the badge show only the number of unread items that are bundled **and shown** in my Inbox, not including bundles that are configured to be shown "only once a day" (an Inbox feature).

**Comment by Thomas101** [comment]
Going to close this off - there may be some updates to the tray icon in the future that will provide more details on unread messages by mailbox but I don't have any plans to add popovers in the account items. @itamaro keep tracking #89 for this
