### ISSUE TITLE
improvement: put sender name + mail subject in notifications

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#91]
as of now notifications for new mails show "New message" + the mail address that received it + the first line of text of the mail

it would be probably useful to have additionally (or in replacement of some stuff) to have the sender name+the subject of the mail and to keep at least the mail address that received it

**Comment by Thomas101** [comment]
I was thinking the same thing earlier! Yeah totally agree

**Comment by aaronwe** [comment]
Yes! I just signed in to suggest the same thing.

Also, "New Message" as the title of the notification toast is redundant. Make the notification title the subject line, and the rest be the sender/message preview.

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
