### ISSUE TITLE
feature: offline access

### ISSUE THREAD

**Issue by bertrandmartin01** [Thomas101/wmail#92]
would be great to have access to our mails through wmail while offline

not sure what could be the best solution for it:
- local storage?
- integrate gmail offline? [https://chrome.google.com/webstore/detail/gmail-offline/ejidjjhkpiempkbhmpbfngldlkglhimk?hl=en]

**Comment by Thomas101** [comment]
Great idea, not sure how feasible it would be. Going to close this and merge items into one thread #105
