### ISSUE TITLE
Receiving dozens of notifications for old emails in Inbox.

### ISSUE THREAD

**Issue by grempe** [Thomas101/wmail#94]
I am receiving notifications for emails that are in some cases months old. I have received possibly 200+ notifications today. I should be seeing a notification come through ONLY if it is a brand new email that just arrived.

**Comment by lid** [comment]
I also saw this for some messages on initial sync - months old messages generating new message notifications (but the pattern of which messages generate notifications is not clear to me).

**Comment by ashwinmt** [comment]
I noticed that I get a notification if I mark an email as unread.

**Comment by Thomas101** [comment]
Hey, sorry about this it's a bit of a pain. I've taken a look and I need to rewrite the way I'm handling notifications. I'm not going to have timr to be able to get this together until next week but I'll put a release out when I can. For now you can disable notifications under settings > accounts

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
