### ISSUE TITLE
Feature request: make download notifications clickable

### ISSUE THREAD

**Issue by deeplypuzzled** [Thomas101/wmail#95]
Some OSX notifications are clickable. E.g. Carbon Copy Cloner notifications open the application when clicked.

Could wmail's "download complete" notifications be made clickable, so that the click opens the downloaded file?

Thanks again for a great application.

**Comment by lid** [comment]
I'd extend this to notifications in general - including New Message notifications, which currently only bring the app to the foreground. It would be great if new message notifications opened the message.

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
