### ISSUE TITLE
wMail Icon not visible when no new email. Looks a bit odd.

### ISSUE THREAD

**Issue by ashwinmt** [Thomas101/wmail#98]
Hi @Thomas101,

Please take a look at the images below:
<img width="205" alt="screen shot 2016-02-12 at 9 37 04 am" src="https://cloud.githubusercontent.com/assets/12843687/12998652/51615e9c-d16c-11e5-98d3-449b2bc8bd62.png">
<br />
<img width="222" alt="screen shot 2016-02-12 at 9 36 54 am" src="https://cloud.githubusercontent.com/assets/12843687/12998651/4dd86ea0-d16c-11e5-89b9-082482b94bdd.png">

In the dark style menubar, if there's no email, the icon doesnt seem visible...

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
