### ISSUE TITLE
Bug: if you accidentally close window, no way to get it back

### ISSUE THREAD

**Issue by tinymachine** [Thomas101/wmail#99]
I think typically for Mac apps hitting <kbd>Command</kbd>+<kbd>0</kbd> or <kbd>Command</kbd>+<kbd>N</kbd> (or an account shortcut, like <kbd>Command</kbd>+<kbd>1</kbd>) would open a new window, but it looks like the only way to get the window back right now (v1.2.0) is by quitting and relaunching.

**Comment by Thomas101** [comment]
Hi, is this regards the main window with your mailboxes or a secondary window (e.g. when you click view entire message)

**Comment by tinymachine** [comment]
The main window.

**Comment by Thomas101** [comment]
I'm not 100% sure what you mean sorry. At the moment if you hit cmd+1 -> cmd+9 it should switch to that mailbox, but always does it in the same window-- a bit like chrome does tabs I guess. Then closing the window normally just hides it on osx into the dock unless you 'hard quit' by right click quitting or using cmd+q etc.

Can you give me some step by step instructions with the expected behaviour? Thanks

**Comment by tinymachine** [comment]
Sure thing -- I think what you're referring to (the window shrinking into the Dock) is minimizing the window (Cmd+M or clicking the middle (yellow) window control button in the upper-left corner of the main window). If you close the main window (Cmd+W or the red button in the upper-left corner), the window closes (i.e. it's not just minimized to the Dock; it disappears entirely, as it should), but to get a new main window to appear, you have to quit and relaunch Wmail.

I think more typical OS X app behavior after closing the main app window is to have a new main window appear when you hit Cmd+N or ⌘1, etc. (See the first-party Calendar app.) (Some other first-party apps, like Contacts and Calculator, just quit when you close the main window. That might make sense for short-use utility apps, but I don't think that's desirable for an important app like an email app.)

I think once the main Wmail window is closed, pressing Cmd+1 (or Cmd+2, etc.) should re-open the window (with the appropriate account showing, of course). Let me know if this is still unclear...

**Comment by Thomas101** [comment]
Okay, I think I understand now. If you close the main window though it still remains in the dock, so you should be able to click on it to bring it up (without restarting the app). I can make it so cmd+n ensures the window is visible as well as switching account.

**Comment by tinymachine** [comment]
That's right -- closing the main window and quitting the app are two distinct events. If I close the main window (which I would usually only do by mistake), the app remains running (indeed it remains in the Dock), but is effectively useless until I quit the app and relaunch since currently there's no other way to get the main window back. In every other app I've used, there's always a way to get the main window back if the app is still running. 

Thanks so much for attending to this!

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!
